### ISSUE TITLE
cordova plugin not found 

### ISSUE THREAD

**Issue by vishal-bluesys** [ionic-team/capacitor#320] opened 2018-03-13 11:54 UTC
![image](https://user-images.githubusercontent.com/24889275/37340054-c9970f24-26e2-11e8-863b-496d28facbe6.png)

Object
index.html:284 native Network.addListener (#15092375)
index.html:284 native Network.getStatus (#15092376)
index.html:65 Native: tried calling FCM.getToken, but the FCM plugin is not installed.
capacitorConsole @ index.html:65
index.html:65 Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm'
capacitorConsole @ index.html:65
index.html:65 Native: tried calling FCM.onNotification, but the FCM plugin is not installed.
capacitorConsole @ index.html:65
index.html:65 Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm'
capacitorConsole @ index.html:65
index.html:65 ERROR Error: Uncaught (in promise): plugin_not_installed
    at c (polyfills.js:3)
    at polyfills.js:3
    at fulfilled (main.js:sourcemap:103)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:sourcemap:4982)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:sourcemap:4973)
capacitorConsole @ index.html:65
index.html:65 ERROR Error: Uncaught (in promise): plugin_not_installed
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:sourcemap:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>

I have installed ionic native wraper then I install this plugin 
As given in the doc 
npm install your-cordova-plugin 
npm install  cordova-plugin-fcm 

npx cap update 
npx cap copy 
then I built apk 

please help 
thanks in advance

**Comment by jcesarmobile** [comment] 2018-03-16 12:25
Closing in favor of https://github.com/ionic-team/capacitor/issues/338 as it has more details.

The problem is the same, if the plugin doesn't have a cordova entry in the package.json it won't find it.

**Closed** 2018-03-16 12:25 UTC
Labels: triage
