### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by sohebcakewalk** [ionic-team/capacitor#7121] opened 2023-12-10 07:55 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 4.8.1
  @capacitor/core: 4.8.1
  @capacitor/ios: 4.8.1
  @capacitor/android: 4.8.1

[success] iOS looking great! 👌
```

### Current Behavior

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000021369e0 h=--& v=--& _UIToolbarContentView:0x10433bd30.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000213fd90 H:|-(0)-[_UIButtonBarStackView:0x10433cf50]   (active, names: '|':_UIToolbarContentView:0x10433bd30 )>",
    "<NSLayoutConstraint:0x60000213fb60 H:[_UIButtonBarStackView:0x10433cf50]-(0)-|   (active, names: '|':_UIToolbarContentView:0x10433bd30 )>",
    "<NSLayoutConstraint:0x600002135f40 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x104407390]   (active, names: '|':_UIButtonBarButton:0x104366750 )>",
    "<NSLayoutConstraint:0x600002134960 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x10440e3e0]   (active, names: '|':_UIButtonBarButton:0x10440e0b0 )>",
    "<NSLayoutConstraint:0x600002135f90 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104407390]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x104366750 )>",
    "<NSLayoutConstraint:0x600002134a00 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x10440e3e0]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x10440e0b0 )>",
    "<NSLayoutConstraint:0x600002134dc0 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x10440fe80'Done']   (active, names: '|':_UIButtonBarButton:0x10440f0a0 )>",
    "<NSLayoutConstraint:0x600002135950 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x10440fe80'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x10440f0a0 )>",
    "<NSLayoutConstraint:0x600002134820 'UISV-canvas-connection' UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x104366750.leading   (active)>",
    "<NSLayoutConstraint:0x600002134b90 'UISV-canvas-connection' UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x10440f0a0.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021345a0 'UISV-spacing' H:[_UIButtonBarButton:0x104366750]-(0)-[UIView:0x10440df20]   (active)>",
    "<NSLayoutConstraint:0x600002136120 'UISV-spacing' H:[UIView:0x10440df20]-(0)-[_UIButtonBarButton:0x10440e0b0]   (active)>",
    "<NSLayoutConstraint:0x600002136170 'UISV-spacing' H:[_UIButtonBarButton:0x10440e0b0]-(0)-[UIView:0x10440ef10]   (active)>",
    "<NSLayoutConstraint:0x6000021361c0 'UISV-spacing' H:[UIView:0x10440ef10]-(0)-[_UIButtonBarButton:0x10440f0a0]   (active)>",
    "<NSLayoutConstraint:0x60000213a620 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x10433cf50 )>",
    "<NSLayoutConstraint:0x60000213a6c0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x10433cf50 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002135f90 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104407390]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x104366750 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

### Other Technical Details

`npm --version` output: 9.8.1

`node --version` output: v18.18.2

`pod --version` output (iOS issues only): 1.8.4

### Additional Context

I have an angular app and added capacitor ios. 
When I build the iOS simulator, it gives me an error. This only comes in iPhone but it is working in iPad view (simulator).

Can you please help me resolve this error?

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000021369e0 h=--& v=--& _UIToolbarContentView:0x10433bd30.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000213fd90 H:|-(0)-[_UIButtonBarStackView:0x10433cf50]   (active, names: '|':_UIToolbarContentView:0x10433bd30 )>",
    "<NSLayoutConstraint:0x60000213fb60 H:[_UIButtonBarStackView:0x10433cf50]-(0)-|   (active, names: '|':_UIToolbarContentView:0x10433bd30 )>",
    "<NSLayoutConstraint:0x600002135f40 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x104407390]   (active, names: '|':_UIButtonBarButton:0x104366750 )>",
    "<NSLayoutConstraint:0x600002134960 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x10440e3e0]   (active, names: '|':_UIButtonBarButton:0x10440e0b0 )>",
    "<NSLayoutConstraint:0x600002135f90 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104407390]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x104366750 )>",
    "<NSLayoutConstraint:0x600002134a00 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x10440e3e0]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x10440e0b0 )>",
    "<NSLayoutConstraint:0x600002134dc0 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x10440fe80'Done']   (active, names: '|':_UIButtonBarButton:0x10440f0a0 )>",
    "<NSLayoutConstraint:0x600002135950 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x10440fe80'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x10440f0a0 )>",
    "<NSLayoutConstraint:0x600002134820 'UISV-canvas-connection' UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x104366750.leading   (active)>",
    "<NSLayoutConstraint:0x600002134b90 'UISV-canvas-connection' UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x10440f0a0.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021345a0 'UISV-spacing' H:[_UIButtonBarButton:0x104366750]-(0)-[UIView:0x10440df20]   (active)>",
    "<NSLayoutConstraint:0x600002136120 'UISV-spacing' H:[UIView:0x10440df20]-(0)-[_UIButtonBarButton:0x10440e0b0]   (active)>",
    "<NSLayoutConstraint:0x600002136170 'UISV-spacing' H:[_UIButtonBarButton:0x10440e0b0]-(0)-[UIView:0x10440ef10]   (active)>",
    "<NSLayoutConstraint:0x6000021361c0 'UISV-spacing' H:[UIView:0x10440ef10]-(0)-[_UIButtonBarButton:0x10440f0a0]   (active)>",
    "<NSLayoutConstraint:0x60000213a620 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x10433cf50 )>",
    "<NSLayoutConstraint:0x60000213a6c0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600003b0d180'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x10433cf50 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002135f90 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x104407390]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x104366750 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by jcesarmobile** [comment] 2023-12-11 10:28
What's the actual problem in your app?
I've seen those errors printed some times, but those are just "warnings" thrown by bad auto layout configurations on Apple side, in example when showing the keyboard, but they are not related to Capacitor, and cause no actual issues in the app inner workings other than the ugly message being shown.

**Comment by sohebcakewalk** [comment] 2023-12-12 08:04
@jcesarmobile - When i run app in iPhone 15 Pro Max simulator, My app loads and on login page when i select any of the input field, i am getting this error and when i keyin Email and Password and hit login button, it seems nothing working.

This same app i tested for Android and published to Google Playstore. 

Android App URL: (https://play.google.com/store/apps/details?id=com.abadi.abadi)

**Comment by jcesarmobile** [comment] 2023-12-12 08:41
Sorry, I can't still understand what your problem is, "nothing working" is not clear enough. The text doesn't appear when you enter the email and password? the login details fail to be submitted to the server? they get submitted but the server returns some error?

Can you provide a sample app that reproduces the issue? (the source code, not the built app)

**Comment by Ionitron** [comment] 2023-12-28 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-12-28 00:05 UTC
Labels: needs reply
