### ISSUE TITLE
bug: registerPlugins  SIGABRT ABORT  crash 

### ISSUE THREAD

**Issue by ccpccp** [ionic-team/capacitor#5524] opened 2022-03-23 06:34 UTC
### Capacitor Version
    - Capacitor (~> 3.4.3)
    - CapacitorApp (~> 1.1.1)
    - CapacitorCordova (~> 3.4.3)
    - CapacitorDevice (~> 1.1.2)

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x2d328 __abort_with_payload + 8
1  libsystem_kernel.dylib         0x2fc34 abort_with_payload_wrapper_internal + 104
2  libsystem_kernel.dylib         0x2fbcc abort_with_payload_wrapper_internal + 30
3  libobjc.A.dylib                0x2d0d4 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 116
4  libobjc.A.dylib                0x2d060 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 30
5  libobjc.A.dylib                0x43a0 class_conformsToProtocol + 772
6  Capacitor                      0xab58 CapacitorBridge.registerPlugins() + 280 (CapacitorBridge.swift:280)
7  Capacitor                      0x1a294 specialized CapacitorBridge.init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 1168 (<compiler-generated>:1168)
8  Capacitor                      0x15e54 CAPBridgeViewController.loadView() + 624 (CapacitorBridge.swift:624)
9  Capacitor                      0x168b0 @objc CAPBridgeViewController.loadView() + 28 (<compiler-generated>:28)
10 UIKitCore                      0x1adec4 -[UIViewController loadViewIfRequired] + 200
11 UIKitCore                      0x181274 -[UIViewController view] + 32
12 BanggoodCapacitor              0xc018 HybridViewController.drawUI() + 61 (HybridViewController.swift:61)
13 BanggoodCapacitor              0xbba4 @objc HybridViewController.viewDidLoad() + 172 (<compiler-generated>:172)
14 UIKitCore                      0x1ab6c4 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 108
```

### Expected Behavior

CapacitorBridge.swift line 280
CapacitorBridge.registerPlugins()

### Code Reproduction
        let webVC = CAPBridgeViewController()
        webVC.view.backgroundColor = UIColor.white
    
        self.addChild(webVC)
        self.view.addSubview(webVC.view)

        webVC.webView?.scrollView.showsVerticalScrollIndicator = false
        webVC.webView?.scrollView.showsHorizontalScrollIndicator = false
        webVC.navigationController?.setNavigationBarHidden(true, animated: false)
        webVC.setStatusBarVisible(false)
        webView = webVC.webView
        
        webVC.bridge?.notificationRouter.pushNotificationHandler = self
        webVC.bridge?.notificationRouter.localNotificationHandler = self;

### Other Technical Details

firebase crashlytics
![image](https://user-images.githubusercontent.com/19773276/159637804-d4b7c045-7140-41db-a7fc-3022e7be49a1.png)

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2022-03-23 09:16
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ccpccp** [comment] 2022-03-24 02:36
![image](https://user-images.githubusercontent.com/19773276/159830646-7b8b49a5-02ba-4263-b13d-be421e6a2d7e.png)

**Comment by ccpccp** [comment] 2022-03-24 02:41
Repeated opening and closing CAPBridgeViewController
![image](https://user-images.githubusercontent.com/19773276/159831250-fec59435-f5f9-4d39-93c5-a55e159c3b42.png)
crash place  in line 277 or line 280

**Comment by ccpccp** [comment] 2022-03-24 02:44
![image](https://user-images.githubusercontent.com/19773276/159831490-5e57238e-7d61-4294-8894-2a257df83b87.png)
Repeated opening and closing  HybridViewController，
HybridViewController addchild  CAPBridgeViewController

**Comment by ccpccp** [comment] 2022-03-24 02:49
Incident Identifier: 805FF3D6-96B8-471D-8E60-FB6694BBD148
Hardware Model:      iPhone12,8
Process:             Factory [2233]
Path:                /private/var/containers/Bundle/Application/AA20DBDB-2408-4139-B2CE-0E63C51C417A/Factory.app/Factory
Identifier:          com.newchic.factory.Mensclo
Version:             1.2.0 (5)
AppStoreTools:       13C90b
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.newchic.factory.Mensclo [897]

Date/Time:           2022-03-10 17:36:39.8749 -0500
Launch Time:         2022-03-10 17:34:46.3827 -0500
OS Version:          iPhone OS 15.3.1 (19D52)
Release Type:        User
Baseband Version:    3.01.02
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: OBJC 1 

Triggered by Thread:  0


Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage


Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001b7a64e44 __terminate_with_payload + 8
1   libsystem_kernel.dylib        	0x00000001b7a665d8 abort_with_payload_wrapper_internal + 136 (terminate_with_reason.c:106)
2   libsystem_kernel.dylib        	0x00000001b7a66550 abort_with_reason + 32 (terminate_with_reason.c:116)
3   libobjc.A.dylib               	0x0000000198cba34c _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 108 (objc-errors.mm:202)
4   libobjc.A.dylib               	0x0000000198cba2e0 _objc_fatal(char const*, ...) + 32 (objc-errors.mm:218)
5   libobjc.A.dylib               	0x0000000198c93db0 class_conformsToProtocol + 640 (objc-runtime-new.mm:564)
6   Capacitor                     	0x0000000105a9ab58 CapacitorBridge.registerPlugins() + 436 (CapacitorBridge.swift:280)
7   Capacitor                     	0x0000000105aaa294 specialized CapacitorBridge.init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 1168 (CapacitorBridge.swift:198)
8   Capacitor                     	0x0000000105aa5e54 specialized CapacitorBridge.init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 28 (<compiler-generated>:184)
9   Capacitor                     	0x0000000105aa5e54 CapacitorBridge.init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 28 (CapacitorBridge.swift:0)
10  Capacitor                     	0x0000000105aa5e54 specialized CapacitorBridge.__allocating_init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 28 (<compiler-generated>:184)
11  Capacitor                     	0x0000000105aa5e54 CapacitorBridge.__allocating_init(with:delegate:cordovaConfiguration:assetHandler:delegationHandler:) + 28 (CAPBridgeViewController.swift:51)
12  Capacitor                     	0x0000000105aa5e54 CAPBridgeViewController.loadView() + 624
13  Capacitor                     	0x0000000105aa68b0 @objc CAPBridgeViewController.loadView() + 28 (<compiler-generated>:0)
14  UIKitCore                     	0x0000000182a14d84 -[UIViewController loadViewIfRequired] + 200 (UIViewController.m:3967)
15  UIKitCore                     	0x00000001829e7bf0 -[UIViewController view] + 32 (UIViewController.m:4035)
16  BanggoodCapacitor             	0x0000000105a64018 HybridViewController.drawUI() + 156 (HybridViewController.swift:61)
17  BanggoodCapacitor             	0x0000000105a63ba4 HybridViewController.viewDidLoad() + 4 (HybridViewController.swift:24)
18  BanggoodCapacitor             	0x0000000105a63ba4 @objc HybridViewController.viewDidLoad() + 172 (<compiler-generated>:21)
19  UIKitCore                     	0x0000000182a12620 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 108 (UIViewController.m:2713)
20  UIKitCore                     	0x0000000182a150d4 -[UIViewController loadViewIfRequired] + 1048 (UIViewController.m:4013)
21  UIKitCore                     	0x00000001829e7bf0 -[UIViewController view] + 32 (UIViewController.m:4035)
22  UIKitCore                     	0x0000000182bdfac8 -[UINavigationController _startCustomTransition:] + 1140 (UINavigationController.m:2063)
23  UIKitCore                     	0x0000000182d3e370 -[UINavigationController _startDeferredTransitionIfNeeded:] + 696 (UINavigationController.m:7519)
24  UIKitCore                     	0x0000000182c133c0 -[UINavigationController __viewWillLayoutSubviews] + 168 (UINavigationController.m:7826)
25  UIKitCore                     	0x0000000182b39994 -[UILayoutContainerView layoutSubviews] + 228 (UILayoutContainerView.m:88)
26  UIKitCore                     	0x00000001829f2474 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2620 (UIView.m:18348)
27  QuartzCore                    	0x0000000184155794 CA::Layer::layout_if_needed(CA::Transaction*) + 536 (CALayer.mm:10038)
28  QuartzCore                    	0x0000000184147fb4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144 (CALayer.mm:2480)
29  QuartzCore                    	0x000000018415c5dc CA::Context::commit_transaction(CA::Transaction*, double, double*) + 524 (CAContextInternal.mm:2586)
30  QuartzCore                    	0x0000000184164ed0 CA::Transaction::commit() + 680 (CATransactionInternal.mm:449)
31  QuartzCore                    	0x000000018414770c CA::Transaction::flush_as_runloop_observer(bool) + 88 (CATransactionInternal.mm:938)
32  CoreFoundation                	0x00000001803fd610 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36 (CFRunLoop.c:1804)
33  CoreFoundation                	0x00000001803cc8f4 __CFRunLoopDoObservers + 572 (CFRunLoop.c:1917)
34  CoreFoundation                	0x00000001803c798c __CFRunLoopRun + 1052 (CFRunLoop.c:2979)
35  CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
36  GraphicsServices              	0x000000019bf7f38c GSEventRunModal + 164 (GSEvent.c:2200)
37  UIKitCore                     	0x0000000182d7e5d0 -[UIApplication _run] + 1100 (UIApplication.m:3493)
38  UIKitCore                     	0x0000000182afcf74 UIApplicationMain + 364 (UIApplication.m:5047)
39  libswiftUIKit.dylib           	0x0000000197cc0fa0 UIApplicationMain(_:_:_:_:) + 104 (UIKit.swift:530)
40  Factory                       	0x0000000104b805c4 specialized static UIApplicationDelegate.main() + 80 (<compiler-generated>:22)
41  Factory                       	0x0000000104b805c4 static AppDelegate.$main() + 92 (ProjectInfoModel.swift:0)
42  Factory                       	0x0000000104b805c4 main + 108
43  dyld                          	0x00000001056e9aa4 start + 520 (dyldMain.cpp:879)

Thread 1:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 2 name:
Thread 2:
0   libsystem_malloc.dylib        	0x000000019215501c nanov2_allocate_from_block + 220 (nanov2_malloc.c:0)
1   libsystem_malloc.dylib        	0x000000019215421c nanov2_allocate + 128 (nanov2_malloc.c:2591)
2   libsystem_malloc.dylib        	0x0000000192154138 nanov2_malloc + 64 (nanov2_malloc.c:1013)
3   libsystem_malloc.dylib        	0x00000001921549c0 nanov2_realloc + 372 (nanov2_malloc.c:1127)
4   libsystem_malloc.dylib        	0x0000000192148748 malloc_zone_realloc + 140 (malloc.c:1705)
5   libsqlite3.dylib              	0x000000019ece80b8 sqlite3MemRealloc + 60 (sqlite3.c:24988)
6   libsqlite3.dylib              	0x000000019ed48958 dbReallocFinish + 136 (sqlite3.c:29530)
7   libsqlite3.dylib              	0x000000019ed28368 sqlite3StrAccumEnlarge + 460 (sqlite3.c:29513)
8   libsqlite3.dylib              	0x000000019ed28478 enlargeAndAppend + 36 (sqlite3.c:30671)
9   libsqlite3.dylib              	0x000000019ed27aa0 sqlite3_str_vappendf + 8164 (sqlite3.c:0)
10  libsqlite3.dylib              	0x000000019ecbe184 sqlite3MPrintf + 92 (sqlite3.c:30833)
11  libsqlite3.dylib              	0x000000019ece5fd4 sqlite3VdbeExec + 60064 (sqlite3.c:94967)
12  libsqlite3.dylib              	0x000000019ecd6594 sqlite3_step + 308 (sqlite3.c:92004)
13  CFNetwork                     	0x0000000180d9f688 -[NSURLStorageURLCacheDB stepSQLStatement:toCompletionWithRetry:] + 40 (NSURLStorageURLCacheDB.mm:1979)
14  CFNetwork                     	0x0000000180cb548c ___ZN12__CFURLCache23CreateAndStoreCacheNodeEP16__CFURLCacheNodePK20_CFCachedURLResponsePK10__CFStringPK13_CFURLRequestPKvbRb_block_invoke + 2356 (NSURLStorageURLCacheDB.mm:1063)
15  libdispatch.dylib             	0x00000001800d6454 _dispatch_block_async_invoke2 + 148 (queue.c:548)
16  libdispatch.dylib             	0x00000001800c7670 _dispatch_client_callout + 20 (object.m:560)
17  libdispatch.dylib             	0x00000001800cedf4 _dispatch_lane_serial_drain + 672 (inline_internal.h:2601)
18  libdispatch.dylib             	0x00000001800cf99c _dispatch_lane_invoke + 444 (queue.c:3937)
19  libdispatch.dylib             	0x00000001800da1b8 _dispatch_workloop_worker_thread + 656 (queue.c:6727)
20  libsystem_pthread.dylib       	0x00000001f0f5b0f4 _pthread_wqthread + 288 (pthread.c:2599)
21  libsystem_pthread.dylib       	0x00000001f0f5ae94 start_wqthread + 8

Thread 3:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001803c3738 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001803c7a2c __CFRunLoopRun + 1212 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000181bf9c84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Foundation                    	0x0000000181c3adb8 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92 (NSRunLoop.m:420)
7   UIKitCore                     	0x0000000182cf774c -[UIEventFetcher threadMain] + 524 (UIEventFetcher.m:1167)
8   Foundation                    	0x0000000181c493fc __NSThread__start__ + 808 (NSThread.m:972)
9   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
10  libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001803c3738 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001803c7a2c __CFRunLoopRun + 1212 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000181bf9c84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Factory                       	0x0000000104fd913c -[WXBridgeManager _runLoopThread] + 256 (WXBridgeManager.m:103)
7   Foundation                    	0x0000000181c493fc __NSThread__start__ + 808 (NSThread.m:972)
8   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
9   libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 8 name:
Thread 8:
0   libsystem_kernel.dylib        	0x00000001b7a3af90 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001f0f62254 _pthread_cond_wait + 1228 (pthread_cond.c:636)
2   libc++.1.dylib                	0x0000000198d3fddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (__threading_support:437)
3   JavaScriptCore                	0x000000018c5b9174 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108 (condition_variable:203)
4   JavaScriptCore                	0x000000018c5bd944 bmalloc::Scavenger::threadRunLoop() + 340 (condition_variable:212)
5   JavaScriptCore                	0x000000018c5bd4e4 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 16 (Scavenger.cpp:295)
6   JavaScriptCore                	0x000000018c5be9a0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scaveng... + 48 (type_traits:3694)
7   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
8   libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001803c3738 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001803c7a2c __CFRunLoopRun + 1212 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000181bf9c84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Factory                       	0x0000000104ebdc10 -[WXComponentManager _runLoopThread] + 256 (WXComponentManager.mm:182)
7   Foundation                    	0x0000000181c493fc __NSThread__start__ + 808 (NSThread.m:972)
8   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
9   libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   FirebaseCrashlytics           	0x0000000105e31140 FIRCLSMachExceptionReadMessage + 56 (FIRCLSMachException.c:194)
3   FirebaseCrashlytics           	0x0000000105e31140 FIRCLSMachExceptionServer + 104 (FIRCLSMachException.c:170)
4   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
5   libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 11:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 13 name:
Thread 13:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001803c3738 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001803c7a2c __CFRunLoopRun + 1212 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   Foundation                    	0x0000000181bf9c84 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
6   Foundation                    	0x0000000181bfa440 -[NSRunLoop(NSRunLoop) run] + 92 (NSRunLoop.m:398)
7   Factory                       	0x000000010503ba90 +[GAI threadMain:] + 64
8   Foundation                    	0x0000000181c493fc __NSThread__start__ + 808 (NSThread.m:972)
9   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
10  libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 14 name:
Thread 14:
0   libsystem_kernel.dylib        	0x00000001b7a3a504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001b7a3ab9c mach_msg + 76 (mach_msg.c:119)
2   CoreFoundation                	0x00000001803c3738 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2646)
3   CoreFoundation                	0x00000001803c7a2c __CFRunLoopRun + 1212 (CFRunLoop.c:3000)
4   CoreFoundation                	0x00000001803db468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
5   CFNetwork                     	0x0000000180e51510 +[__CFN_CoreSchedulingSetRunnable _run:] + 464 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x0000000181c493fc __NSThread__start__ + 808 (NSThread.m:972)
7   libsystem_pthread.dylib       	0x00000001f0f5b9a4 _pthread_start + 148 (pthread.c:891)
8   libsystem_pthread.dylib       	0x00000001f0f5aea0 thread_start + 8

Thread 15:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	0x00000001f0f5ae8c start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000001   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x00000002839a2400   x6: 0x0000000000000280   x7: 0x00000002839a2700
    x8: 0x0000000000000020   x9: 0x00000001d9bf8010  x10: 0x0000000000003f90  x11: 0x0000000000000000
   x12: 0x00000000bee05142  x13: 0x000000003ee05000  x14: 0x000000003ee00000  x15: 0x00006167656c6544
   x16: 0x0000000000000208  x17: 0x00000001dca39530  x18: 0x0000000000000000  x19: 0x0000000000000080
   x20: 0x00000002839a2400  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000001
   x24: 0x0000000000000008  x25: 0x000000012a0893b8  x26: 0x0000000105ae5ec0  x27: 0x000000012a9a6960
   x28: 0x0000000105adff18   fp: 0x000000016b282fb0   lr: 0x00000001b7a665d8
    sp: 0x000000016b282f70   pc: 0x00000001b7a64e44        cpsr: 0x0
   esr: 0x56000080  Address size fault


Binary Images:
0x104b78000 - 0x105233fff Factory arm64  <417ba7f3401b3f37aa181045576921d4> /private/var/containers/Bundle/Application/AA20DBDB-2408-4139-B2CE-0E63C51C417A/Factory.app/Factory
0x1056d0000 - 0x105727fff dyld arm64e  <780553c7d39f322a8cb9f4f6de52610d> /usr/lib/dyld
0x105a58000 - 0x105a67fff BanggoodCapacitor arm64  <d11953b85e073c49b86fcb86ff5ff22d> /private/var/containers/Bundle/Application/AA20DBDB-2408-4139-B2CE-0E63C51C417A/Factory.app/Frameworks/BanggoodCapacitor.framework/BanggoodCapacitor
0x105a90000 - 0x105ad7fff Capacitor arm64  <6005052a7aab301182a8cd8fb6c10231> /private/var/containers/Bundle/Application/AA20DBDB-2408-4139-B2CE-0E63C51C417A/Factory.app/Frameworks/Capacitor.framework/Capacitor
0x105e18000 - 0x105e57fff FirebaseCrashlytics arm64  <63b2637826663e758f868f22105bb47b> /private/var/containers/Bundle/Application/AA20DBDB-2408-4139-B2CE-0E63C51C417A/Factory.app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics
0x1800c3000 - 0x180109fff libdispatch.dylib arm64e  <bd02a62584753fd68dc38aed25d1573b> /usr/lib/system/libdispatch.dylib
0x1803bc000 - 0x18080ffff CoreFoundation arm64e  <e2f84645290531ef8ec73cc19c3cddb3> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x180bd7000 - 0x18109bfff CFNetwork arm64e  <23a465f1e97c36c5a30fcefec059f79f> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x181be1000 - 0x181ee7fff Foundation arm64e  <925a43cdeaf2316193783ed87468301d> /System/Library/Frameworks/Foundation.framework/Foundation
0x182865000 - 0x1840f0fff UIKitCore arm64e  <920a0ee6d2663058814427a27b23ad62> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x184116000 - 0x1843fcfff QuartzCore arm64e  <a2da3a5696bc362fbd55949ab26ad274> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x18b3d8000 - 0x18c6c8fff JavaScriptCore arm64e  <8882e299ecd236a1839b41ee2ca83aa6> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x19213f000 - 0x19215ffff libsystem_malloc.dylib arm64e  <2829a9b635da3a4b8672777bdd140a00> /usr/lib/system/libsystem_malloc.dylib
0x197c90000 - 0x197cfcfff libswiftUIKit.dylib arm64e  <4d3e2acd34663f26a298452d47ba5d9d> /usr/lib/swift/libswiftUIKit.dylib
0x198c90000 - 0x198cc9fff libobjc.A.dylib arm64e  <56a134b6c3d83d91b1fc7bdb75c5903b> /usr/lib/libobjc.A.dylib
0x198d36000 - 0x198d99fff libc++.1.dylib arm64e  <346a1fc1f0b337dbb10209951bb9aa78> /usr/lib/libc++.1.dylib
0x19bf7e000 - 0x19bf86fff GraphicsServices arm64e  <b40e3b1790c73ebcb6bc8c7b605f47a9> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x19ec94000 - 0x19ee26fff libsqlite3.dylib arm64e  <bdddcea91a8f3a4f854a94b2d2e75cff> /usr/lib/libsqlite3.dylib
0x1b7a39000 - 0x1b7a6cfff libsystem_kernel.dylib arm64e  <ff3ee512a0bc3123b983d365a71fb06a> /usr/lib/system/libsystem_kernel.dylib
0x1f0f5a000 - 0x1f0f65fff libsystem_pthread.dylib arm64e  <a17d07cfe86a392387c4921045898a8a> /usr/lib/system/libsystem_pthread.dylib

EOF

**Comment by ccpccp** [comment] 2022-03-24 03:48
public class HybridViewController: UIViewController {
    
    public var isIphoneX : Bool?
    public var app_name: String?
    
    //是否是侧滑返回
    var isSideBack : Bool = false
    public var webView: WKWebView?
    
    public override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = UIColor.white
        drawUI()
    }
    
    public  override func viewWillAppear(_ animated : Bool) {
        self.navigationController?.setNavigationBarHidden(true, animated: false)
        super.viewWillAppear(animated)
        self.navigationController?.interactivePopGestureRecognizer?.delegate = self
    }
    
    public override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        self.navigationController?.interactivePopGestureRecognizer?.delegate =  nil
    }
    
    public override func didMove(toParent toParentViewController: UIViewController?) {
        if parent == nil && isSideBack {
            //是滑动事件且返回了 ---> 侧滑返回
            NotificationCenter.default.post(name: NSNotification.Name("ks_CapSideBackEvent"), object: nil)
        }
    }
    
    func drawUI() {
        var statusBarHeight = CGFloat(0)
        var bottomMargin = CGFloat(0)
        
        //控制安全边距
        if isIphoneX ?? false {
            statusBarHeight = CGFloat(44)
            bottomMargin = CGFloat(34)
        } else {
            statusBarHeight = CGFloat(20)
        }

        let webVC = CAPBridgeViewController()
        webVC.view.backgroundColor = UIColor.white
    
        self.addChild(webVC)
        self.view.addSubview(webVC.view)

        webVC.webView?.scrollView.showsVerticalScrollIndicator = false
        webVC.webView?.scrollView.showsHorizontalScrollIndicator = false
        webVC.navigationController?.setNavigationBarHidden(true, animated: false)
        webVC.setStatusBarVisible(false)
        webView = webVC.webView
        
        webVC.bridge?.notificationRouter.pushNotificationHandler = self
        webVC.bridge?.notificationRouter.localNotificationHandler = self;

        webVC.webView?.snp.makeConstraints({ make in
            make.edges.equalToSuperview().inset(UIEdgeInsets(top: statusBarHeight, left: 0, bottom: bottomMargin, right: 0))
        })
    }
}

**Comment by jcesarmobile** [comment] 2022-03-24 08:22
Please, provide a full app that can be run by the team

**Comment by Ionitron** [comment] 2022-04-09 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-09 00:05 UTC
Labels: needs reply, needs reproduction
