### ISSUE TITLE
bug:  No AndroidManifest.xml generated

### ISSUE THREAD

**Issue by mesqueeb** [ionic-team/capacitor#2905] opened 2020-05-12 02:52 UTC
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.1.0

  @capacitor/core: 2.1.0

  @capacitor/android: 2.1.0

  @capacitor/electron: 2.1.0

  @capacitor/ios: 2.1.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/core 2.1.0

  @capacitor/android 2.1.0

  @capacitor/ios 2.1.0

[error] "AndroidManifest.xml" is missing in: /Users/~~~/.ghq/github.com/~~~~~~/src-capacitor/android/app/src/main
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

No `AndroidManifest.xml` was generated for me.

## Expected Behavior

`AndroidManifest.xml` to be generated

## Other Technical Details

`npm --version` output:
6.14.4
`node --version` output:
v12.16.2
`pod --version` output (iOS issues only):
1.7.5

## Other Information

This was a v1 project, never built android during v1, then upgraded to v2 and built android for the first time.

**Comment by mesqueeb** [comment] 2020-05-12 02:53
How can I manually add the manifest?

just paste this?
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapp"
    android:versionCode="1"
    android:versionName="1.0" >
</manifest>
```

**Comment by mesqueeb** [comment] 2020-05-12 04:26
I was able to add it by deleting the android project folder and re-adding it!

**Comment by jcesarmobile** [comment] 2020-05-12 10:53
closing since you solved it and I can't reproduce

**Closed by jcesarmobile** 2020-05-12 10:53 UTC
