### ISSUE TITLE
bug: toJSON() not implemented on ios

### ISSUE THREAD

**Issue by Adiss** [ionic-team/capacitor#4661] opened 2021-06-02 08:14 UTC
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
iOS

### Current Behavior
Continuously getting '.toJSON() not implemented on ios' errors, but never called them.

#### Edit:
Seems like only the new capacitor v3 plugins generating these errors

![Képernyőfotó 2021-06-02 - 10 11 51](https://user-images.githubusercontent.com/1173134/120447817-4165e780-c38b-11eb-85e0-414ce8b37ce2.png)

**Comment by Ionitron** [comment] 2021-06-02 10:10
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Dave-N-at-Abstract** [comment] 2021-06-03 15:01
I'm seeing the same thing on a project i have updated to  capacitor 3. Plugins seem to function where they are used, but I can see similar being logged during router navigation. I think its before ionViewWillLeave. Not sure what the minimum required code will be, if I get enough time on project i'll have a go at putting something together.

**Comment by Danieltech99** [comment] 2021-06-13 04:27
I am seeing the same issue for SplashScreen (only called in App.tsx) and Camera (called throughout the app). This is triggered for me when I submit a form with react-hook-form and sometimes when I am navigating between tabs.

**Comment by Exocomp** [comment] 2021-06-20 21:17
Capacitor 3.0.0
Angular: 12.0.1
Ionic: 5.6.8

```
Error: Uncaught (in promise): Error: "WebView.toJSON()" is not implemented on ios
Error: Uncaught (in promise): Error: "Camera.toJSON()" is not implemented on ios
Error: Uncaught (in promise): Error: "Filesystem.toJSON()" is not implemented on ios
Error: Uncaught (in promise): Error: "Keyboard.toJSON()" is not implemented on ios 
```

**Comment by jcesarmobile** [comment] 2021-06-21 09:18
closing since nobody has provided a way of reproducing it

**Closed by jcesarmobile** 2021-06-21 09:18 UTC
Labels: needs reproduction, platform: ios
