### ISSUE TITLE
bug: capacitor.config.js in /android/app/src/main/assets is not in .gitignore

### ISSUE THREAD

**Issue by gprossliner** [ionic-team/capacitor#5563] opened 2022-04-13 10:04 UTC
## Bug Report

Hi folks! Thanks for this very nice, handy, slim, and stable tool! I totally appreciate it.
This Issue is based on my comment on https://github.com/ionic-team/capacitor/issues/4626#issuecomment-1091617633.

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
```

### Platform(s)

Dev-Environment on `andorid`, may affect others too.

### Current Behavior
When running `cap sync`, the content of the source file `/capacitor.config.js` (or the exported json serialized value of `/capacitor.config.ts`) is placed in a file named `/android/app/src/main/assets/capacitor.config.json`, which is not ignored by the default `/android/app/.gitignore`.

1. When editing the source file, there is additional git change on the asset file
2. When using a `/capacitor.config.ts` file, and the logic depends on external data (like environment vars), running `cap sync` will create a git change.

##### Note on 2.:
I use a npm script in combination of a `/capacitor.config.ts` file to control Hot Module Reload in Andoid Studio, like:

```json
"scripts" : {
   "android-open-dev": "DEV_SCRIPT=android cap sync android && cap open android && svelte-kit dev",
   "android-open-static": "svelte-kit build && cap sync android && cap open android",
}
``` 

```ts
// /capacitor.config.ts
import { CapacitorConfig } from '@capacitor/cli';

let config: CapacitorConfig = {
  // static config here
};

// dynamic config based on environment vars passed from npm scripts
if (process.env.DEV_SCRIPT === "android") {
  config.server = {
    url: "http://10.0.2.2:3000",      // 10.0.2.2 is localhost for android emulator
    cleartext: true,
  }
}

export default config;
```

If I both, the `android-open-dev` and the `android-open-static` scripts, I always have a git change.

### Expected Behavior

For case 1. there should be no git change, although this would be not that bad, because you are changing something anyway.
For case 2. there should be no get change too. And IMO this is really bad, because you are not editing any source file directly, and have a git change.

### Code Reproduction

See example above, I can also create a demo repository if needed.

### Other Technical Details

In the created `.gitignore` file, only the `public` directory is included:
https://github.com/ionic-team/capacitor/blob/b893a57aaaf3a16e13db9c33037a12f1a5ac92e0/android-template/.gitignore#L96

Questions for a possible PR:
* Should `.gitignore` exclude the parent directory `/app/src/main/assets` instead of only `public`? I only have on additional file `capacitor.plugins.json` in my assets directory, which is a result of `cap sync` too.
* ~~Is there an equivalent on ios outputs which should be excluded too?~~ (yes, see comment)

**Comment by gprossliner** [comment] 2022-04-13 10:27
The `ios` platform create a similar file in `/ios/App/App/capacitor.config.json`

**Comment by jcesarmobile** [comment] 2022-04-18 16:03
duplicate of https://github.com/ionic-team/capacitor/issues/4626

**Closed by jcesarmobile** 2022-04-18 16:03 UTC

**Comment by gprossliner** [comment] 2022-04-19 06:11
Hello @jcesarmobile! I metioned the duplicate in my initial comment. The reason for me to create a new Issue was that the original (where I also commented on), has no kind of response, and is open for > 1Y.

How do you plan to react to this topic?
* If you will fix it (I can make a PR, but it' only a single line in two .gitignore files, so it may not be worth it) please comment so
* If you won't fix it for whatever reason, please close the original issue with a comment.

**Comment by nuestroivan** [comment] 2022-04-24 01:19
i'm having the same issue right now, it's very annoying when i pushed some changes on my project files for both android and ios.. the capacitor.config.js is appearing even it is on .gitignore after fetching my origin
![image](https://user-images.githubusercontent.com/90671186/164951608-42bc26a1-c3a3-4c84-aefb-2edf59f15d48.png)
