### ISSUE TITLE
bug: Refresher component low frame rate

### ISSUE THREAD

**Issue by telpat0298** [ionic-team/capacitor#3654] opened 2020-10-07 14:32 UTC
## Bug Report
I'am using Ionics refresher component inside a ion-content component. I haven’t tested it on iOS yet, but on android (physical device) when pulling down the refresher, the frame rate of the refresher animation drops and the animation gets laggy. When letting it go in order to trigger the refresh, the animation runs smoothly as expected. Also in the browser the whole animation (pulldown and refresh) runs flawlessly. 

**Note**
I've noticed that this issue appears only when the ion-content is not scrollable. When the content element has overflow, it is working as expected.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.2

  @capacitor/core: 2.4.2

  @capacitor/android: 2.4.2

  @capacitor/electron: 2.4.2

  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed


  @capacitor/cli 2.0.1

  @capacitor/core 2.4.2

  @capacitor/android 2.4.2

[success] Android looking great! 👌
```

### Platform(s)

Android

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v13.14.0

### Additional Context

I posted this issue in the ionic forum to see if anyone else has this problem and two persons reported the same issue.
[Refresher component low frame rate](https://forum.ionicframework.com/t/refresher-component-low-frame-rate/197092)

**Comment by liamdebeasi** [comment] 2020-10-07 15:22
Thanks for the issue. This was a regression in Chrome 85 that has since been resolved in Chrome 86. I recommend upgrading your version of Chrome for Android to receive this fix. See https://github.com/ionic-team/ionic-framework/issues/22008#issuecomment-686152162 for more info.

**Closed by liamdebeasi** 2020-10-07 15:22 UTC
Labels: platform: android
