### ISSUE TITLE
bug: checksums changing on pod install since capacitor 3 upgrade

### ISSUE THREAD

**Issue by typeoneerror** [ionic-team/capacitor#5193] opened 2021-11-01 21:00 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/android: 3.2.3
  @capacitor/cli: 3.2.5
  @capacitor/ios: 3.2.4
  @capacitor/core: 3.2.3
```

### Platform(s)

macOS

### Current Behavior

We're unable to get predictable installation results with `npx cap sync ios --deployment`. The CHECKSUMS for specific Capacitor plugins are changing each time.

```
[Edea] ~/Dev/pn/liberator (GS-508) $ npx cap sync ios --deployment
[warn] Using the iOS project root for the public directory is deprecated.
       Please follow the Upgrade Guide to move public inside the iOS target directory:
       https://capacitorjs.com/docs/updating/3-0#move-public-into-the-ios-target-directory
✔ Copying web assets from build to ios/App/public in 695.48ms
✔ Creating capacitor.config.json in ios/App/App in 797.31μp
[info] Found 2 Cordova plugins for ios:
       com-sarriaroman-photoviewer@1.2.5
       cordova-plugin-purchase@10.6.1
✔ copy ios in 760.03ms
✔ Updating iOS plugins in 18.78ms
[info] Found 14 Capacitor plugins for ios:
       @capacitor-community/fcm@2.0.2
       @capacitor/app@1.0.5
       @capacitor/device@1.0.3
       @capacitor/dialog@1.0.3
       @capacitor/keyboard@1.0.3
       @capacitor/network@1.0.3
       @capacitor/push-notifications@1.0.4
       @capacitor/splash-screen@1.1.2
       @capacitor/status-bar@1.0.3
       @capacitor/storage@1.2.0
       @precision-nutrition/device-model@1.0.0
       @precision-nutrition/heap-analytics@1.0.0
       @precision-nutrition/sentry-extensions@1.0.0
       @precision-nutrition/system-utils@1.0.0
[info] Found 2 Cordova plugins for ios:
       com-sarriaroman-photoviewer@1.2.5
       cordova-plugin-purchase@10.6.1
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        Verifying no changes
        [!] There were changes to the lockfile in deployment mode:
        SPEC CHECKSUMS:
        CapacitorApp:
        New Lockfile: 8cd750aa9507b8d2899ac7a65dd6a8bd70aedff0
        Old Lockfile: a3d0e46fd0706c61266ea2d3e65468f9307a3abe
        CapacitorCommunityFcm:
        New Lockfile: 8efa21628cf48c91c507ae1e14651edef8989923
        Old Lockfile: af38ba6452104d1b3c4eef9007d9856b2805a6e8
        CapacitorDevice:
        New Lockfile: 22f63ccd1fb4ba06e7bf263a39d15e92b64d526a
        Old Lockfile: 5679e79e31bfa4552ac53e1535771ba940fb738c
        CapacitorDialog:
        New Lockfile: 2827efc5bb51945fe045e4c21e37023ddefa8089
        Old Lockfile: d3ac1b9972f1e6929e72cd949f9330c70d38ab89
        CapacitorKeyboard:
        New Lockfile: 66caddf249e0e1c437f29167a9d3be5f8e5690e5
        Old Lockfile: 922f77b0ed9987a85fb5622773c0d1972d24ce3f
        CapacitorNetwork:
        New Lockfile: 7900d3382625e255b3940342a93fe0560a6cff93
        Old Lockfile: b641b27149b7d34b82d965a6c8f7c3caf79eea9b
        CapacitorPushNotifications:
        New Lockfile: d06d6267cd165b430ef75d1f3a6d0bb2872099ec
        Old Lockfile: 65cf477d2bace6d1bfd86e1c62fee6a910669222
        CapacitorSplashScreen:
        New Lockfile: 3e71410280e96ea46a7918aa41422d9575476be5
        Old Lockfile: 1c8490ba5fe704a36bc08ce438dc4d435bbf1ec9
        CapacitorStatusBar:
        New Lockfile: b186c8f5a4a12b77c4450e87c9b2720a8bfb5ccc
        Old Lockfile: f7fe678c7c24541f90a9d6ca209e93e8fc25a5e4
        CapacitorStorage:
        New Lockfile: c678af9bf23e730b1c1721fdda807f84378cb708
        Old Lockfile: efb9db39d073545a5dcac176dd2b05c0eabb1e2c
```

Here is our Podfile:

```ruby
platform :ios, '12.0'
use_frameworks!

# source 'https://github.com/PrecisionNutrition/CocoaPodsSpecs.git'
# source 'https://github.com/CocoaPods/Specs.git'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFcm', :path => '../../node_modules/@capacitor-community/fcm'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../node_modules/@capacitor/dialog'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/@capacitor/storage'
  pod 'PrecisionNutritionDeviceModel', :path => '../../plugins/device-model'
  pod 'PrecisionNutritionHeapAnalytics', :path => '../../plugins/heap-analytics'
  pod 'PrecisionNutritionSentryExtensions', :path => '../../plugins/sentry-extensions'
  pod 'PrecisionNutritionSystemUtils', :path => '../../plugins/system-utils'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods

  # NOTE: this is a temporary override until https://github.com/capacitor-community/fcm/pull/68
  #       is merged and released in capacitor-community/fcm.
  pod 'FirebaseCore', '~> 7.11.0'
  pod 'Firebase/Messaging', '~> 7.11.0'

  # Add your Pods here
  #
  # NOTE: ONLY swift-based pods. If you're installing via npm, pods will automatically
  #       be added to the `capacitor_pods` method above.
  pod 'DeviceKit', '~> 4.4.0'
  pod 'Sentry', '~> 6.0.12'
  pod 'TestFairy', '~> 1.29.3', :configurations => ['Debug']
end
```

### Expected Behavior

Checksums should be the same on all machines.

### Code Reproduction

I cannot reproduce this in a small app, unfortunately. I'm opening this hoping someone has an idea of what's happening here. It only seems to update checksums for the Capacitor dependencies.

### Other Technical Details

`npm --version` output: 6.14.6

`node --version` output: v12.18.3

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

Tried `pod cache clean --all`, wiping Pods folder, etc.

**Comment by typeoneerror** [comment] 2021-11-01 23:06
One thing of note...

The [CapacitorApp.podspec.json](https://raw.githubusercontent.com/CocoaPods/Specs/ff588cdba5612f7cf92d0996053547a13c267b7c/Specs/0/7/f/CapacitorApp/1.0.5/CapacitorApp.podspec.json) file and our installed local version have this diff...

```diff
-  "authors": {
-    "name": "Ionic",
-    "email": "hi@ionicframework.com"
-  },
+  "authors": "Ionic <hi@ionicframework.com>",
```

Which would explain the checksum difference... I think. Any idea why they differ?

**Comment by dougestey** [comment] 2021-11-01 23:16
@typeoneerror Dunno. Looking here now. https://github.com/ionic-team/capacitor/blob/c495bed216ddf05450f185d2d3f09b4052b281a8/cli/src/ios/update.ts#L92

**Comment by Ionitron** [comment] 2021-11-02 12:32
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-11-18 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-11-18 00:03 UTC
Labels: needs reply, needs reproduction
