### ISSUE TITLE
Preview is black the first time we open the Camera 

### ISSUE THREAD

**Issue by PaulCailly** [ionic-team/capacitor#5911] opened 2022-09-13 17:56 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/core: 4.0.1
  @capacitor/cli: 4.0.1
  @capacitor/ios: 4.2.0

[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

When we launch Camera module for the first time the we can see the native Camera App UI but the preview screen remains black

We need to close the Camera and request again `Camera.getPhoto()` to have a preview.

### Expected Behavior

Preview should be available the first time we open the Camera

### Code Reproduction

Can be tested with the production app: app.backresto.com (download from AppStore)

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

packages:
```
        "@capacitor/app": "4.0.1",
        "@capacitor/camera": "4.1.1",
        "@capacitor/ios": "4.2.0",
        "@capacitor/push-notifications": "4.1.0",
        "@capacitor/status-bar": "4.0.1",
```

usage:
```
        const photo = await Camera.getPhoto({
            quality: 90,
            width: 900,
            allowEditing: false,
            source: CameraSource.Camera,
            direction: CameraDirection.Rear,
            resultType: CameraResultType.Base64
        });
```

### Additional Context

Sentry is catching this issue:

`Error: User cancelled photos app`

**Comment by Ionitron** [comment] 2022-09-13 20:58
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-29 00:13
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-29 00:13 UTC
Labels: platform: ios, needs reply, needs reproduction
