### ISSUE TITLE
bug: TypeError: Failed to construct 'Response': Response with null body status cannot have body

### ISSUE THREAD

**Issue by speter2** [ionic-team/capacitor#6383] opened 2023-03-10 11:29 UTC
### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/core: 4.7.0
  @capacitor/cli: 4.7.0
  @capacitor/ios: 4.7.0
  @capacitor/android: 4.7.0

[error] Xcode is not installed
```

### Platform(s)

iOS & Android

### Current Behavior

Making a request using the new `CapacitorHttp` client that receives as a response a 204 (with no body) throws an error:
TypeError: Failed to construct 'Response': Response with null body status cannot have body

### Expected Behavior

The request should succeed. Empty body should be accepted.

### Code Reproduction

Not sure what code sample to give... basicly any fetch(url) request fails which receives 204 as a response.

### Other Technical Details

`npm --version` output: 9.5.0

`node --version` output: v18.14.2

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment] 2023-03-10 15:16
duplicate of https://github.com/ionic-team/capacitor/issues/6250

**Closed by jcesarmobile** 2023-03-10 15:16 UTC
Labels: platform: android, platform: ios
