### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by himaniChaine** [ionic-team/capacitor#6212] opened 2023-01-13 12:12 UTC
### Capacitor Version
```
❯ yarn cap doctor    
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

```
yarn cap run ios
```

### Current Behavior
```
➜  mobile-app git:(main) ✗ yarn cap run ios
✔ Copying web assets from dist to ios/App/App/public in 331.14ms
✔ Creating capacitor.config.json in ios/App/App in 1.42ms
⠇ copy ios [info] Inlining sourcemaps
✔ copy ios in 715.95ms
✔ Updating iOS plugins in 19.53ms
[info] Found 5 Capacitor plugins for ios:
       @capacitor/camera@4.1.4
       @capacitor/splash-screen@4.1.2
       @capacitor/status-bar@4.1.1
       @capacitor/toast@4.1.0
       capacitor-plugin-safe-area@1.0.0
✔ Updating iOS native dependencies with pod install in 3.39s
✔ update ios in 3.45s
[error] SyntaxError: Unexpected token E in JSON at position 0
        at JSON.parse (<anonymous>)
        at Object.getPlatformTargets
        (/Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/util/native-run.js:39:26)
        at async Object.runIOS
        (/Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/ios/run.js:13:59)
        at async run
        (/Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/tasks/run.js:74:9)
        at async runCommand
        (/Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/tasks/run.js:61:13)
        at async
        /Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/index.js:123:9
        at async
        /Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/telemetry.js:26:13
        at async Command.<anonymous>
        (/Users/himani/Documents/Github/chaine/.yarn/cache/@capacitor-cli-npm-4.6.1-38f8be1483-082715e2a2.zip/node_modules/@capacitor/cli/dist/util/cli.js:12:13)
```

### Expected Behavior
```
it's should run code in to IOS simlutor
```

### Other Technical Details

`npm --version` output: 3.3.0

`node --version` output: v16.16.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context
```

➜  mobile-app git:(main) ✗ npx native-run ios --list --json

{
	"devices": [],
	"virtualDevices": [
		{
			"platform": "ios",
			"name": "iPad (10th generation)",
			"sdkVersion": "16.2",
			"id": "1C3061DE-D404-4916-970A-E5D41CDFBB49"
		},
		{
			"platform": "ios",
			"name": "iPad Air (5th generation)",
			"sdkVersion": "16.2",
			"id": "FAE66D29-0902-43D0-9BEE-9A163953E6E9"
		},
		{
			"platform": "ios",
			"name": "iPad Pro (11-inch) (4th generation)",
			"sdkVersion": "16.2",
			"id": "07782721-8E96-41BE-98D1-9C6A94E6F2DC"
		},
		{
			"platform": "ios",
			"name": "iPad Pro (12.9-inch) (6th generation)",
			"sdkVersion": "16.2",
			"id": "5B69A556-FE65-46BE-83AE-E9A8F6CCF298"
		},
		{
			"platform": "ios",
			"name": "iPad mini (6th generation)",
			"sdkVersion": "16.2",
			"id": "8EE23C5D-72AF-45EA-A650-2E368B324C39"
		},
		{
			"platform": "ios",
			"name": "iPhone 14",
			"sdkVersion": "16.2",
			"id": "5E5678EB-8B92-40D5-91E3-394B39B8CDB8"
		},
		{
			"platform": "ios",
			"name": "iPhone 14 Plus",
			"sdkVersion": "16.2",
			"id": "6BF393BC-C325-47A1-9C29-33292513A34E"
		},
		{
			"platform": "ios",
			"name": "iPhone 14 Pro",
			"sdkVersion": "16.2",
			"id": "4D1FD894-373D-48D4-B93F-A6231C5480E4"
		},
		{
			"platform": "ios",
			"name": "iPhone 14 Pro Max",
			"sdkVersion": "16.2",
			"id": "9417D95A-EDB9-4FE3-9962-8E4550B9D085"
		},
		{
			"platform": "ios",
			"name": "iPhone SE (3rd generation)",
			"sdkVersion": "16.2",
			"id": "49F22ABC-1261-4D8A-A907-24FF4F43B5B3"
		}
	],
	"errors": []
}
```

**Comment by Ionitron** [comment] 2023-01-17 09:43
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-02 00:05 UTC
Labels: needs reply, needs reproduction
