### ISSUE TITLE
[Android] Can't run Filesystem.readdir()

### ISSUE THREAD

**Issue by Deejay-Ste** [ionic-team/capacitor#1369] opened 2019-03-28 14:06 UTC
Description of the problem:
First of all thanks for the amazing work, Capacitor is way more pleasant to use than Cordova ! I'm trying to rewrite a Ionic 3/Cordova plugin that I need using Ionic 4/Capacitor but I'm struggling to run the `readdir` function of the `Filesystem` plugin on Capacitor Android. It works correctly on iOS but after multiple tries I can't make it work on Android. I always have this error in the Logcat :
```
E/Capacitor: Unable to execute plugin method
    com.getcapacitor.PluginInvocationException: Unable to invoke method readdir on plugin com.getcapacitor.plugin.Filesystem
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:101)
        at com.getcapacitor.Bridge$2.run(Bridge.java:447)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:447) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at org.json.JSONArray.<init>(JSONArray.java:115)
        at com.getcapacitor.JSArray.<init>(JSArray.java:16)
        at com.getcapacitor.JSArray.from(JSArray.java:39)
        at com.getcapacitor.plugin.Filesystem.readdir(Filesystem.java:377)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$2.run(Bridge.java:447) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
Affected platform:
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine:
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version:
1.0.0-beta.19

node version:
10.12.4

npm version:
6.9.0

CocoaPods version:
1.6.0

Steps to reproduce:
Run this code on Capacitor Android
```javascript
try {
      const files = await Filesystem.readdir({
        path: 'cache',
        directory: FilesystemDirectory.Documents
      });

      console.log(files);
}
catch(e) {
      console.error(e);
}
```

**Comment by solojuve1897** [comment] 2019-03-28 18:15
Check this in Filesystem.java-file:

@PluginMethod()
  public void readdir(PluginCall call) {
    String path = call.getString("path");
    String directory = getDirectoryParameter(call);

    File fileObject = getFileObject(path, directory);

    if (fileObject != null && fileObject.exists()) {
      String[] files = fileObject.list();

      JSObject ret = new JSObject();
      ret.put("files", JSArray.from(files));
      call.success(ret);
    } else {
      call.error("Directory does not exist");
    }
  }

The line (377) in question is the following:
ret.put("files", JSArray.from(files));

I'm a C#-developer myself but I suspect the problem is with the attempt to create a JSArray from the String-array. Maybe the JSArray like the JSObject needs to be instantiated first?

**Comment by solojuve1897** [comment] 2019-04-01 11:39
In JSArray.java you'll find the method which is called:

```
public static JSArray from(Object array) {
    try {
      return new JSArray(array);
    } catch(JSONException ex) {}
    return null;
  }
```

The input parameter is of type Object. With my limited Java-knowledge in mind I think that's where the problem lies. The input-parameter should be changed to String[] or - if it exists - an interface which is a common denominator between arrays.

**Comment by jcesarmobile** [comment] 2019-04-03 16:48
It was a permission problem, Documents folder requires permissions and they weren't prompted for read, only for write.
It's been fixed in https://github.com/ionic-team/capacitor/pull/1390

**Closed by jcesarmobile** 2019-04-03 16:48 UTC
