### ISSUE TITLE
bug: Clipboard.read promise unresolved on empty clipboard iOS

### ISSUE THREAD

**Issue by wesleygoldsborough** [ionic-team/capacitor#3702] opened 2020-10-19 23:17 UTC
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 4 Capacitor plugins for ios:
    cordova-plugin-networkinterface (2.0.0)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-sqlite-storage (5.0.0)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
I cannot reproduce this in xCode simulator, only on a physical device. `Clipboard.read()` does not resolve when the clipboard is empty. However, it works fine if the clipboard contains something.

### Expected Behavior
Expect Clipboard.read() promise to resolve normally. 

### Code Reproduction
Brand new Ionic/Capacitor project.
Clear the clipboard with `Clipboard.write({string: ''})`
Attempt to read the empty clipboard and log the clipboard data to the console.
`Clipboard.read().then((data) => { console.log(data) }).catch((err) => { console.log(err) });`
You'll never get the data logged to the console or be able to catch the error

**Comment by jcesarmobile** [comment] 2020-10-20 12:23
I can't reproduce with the data provided, writing an empty string makes read return the empty string.
There could be the case that the plugin don't reject nor resolve if it's really empty, but not sure how to reproduce that.

For Capacitor 3 we are moving plugins out, and @capacitor/clipboard already handles the case of being empty by [rejecting](https://github.com/ionic-team/capacitor-plugins/blob/main/clipboard/ios/Plugin/ClipboardPlugin.swift#L14), so going to close this.

**Closed by jcesarmobile** 2020-10-20 12:23 UTC
Labels: platform: ios

**Comment by wesleygoldsborough** [comment] 2020-10-20 16:00
Ugh. I'm sorry, I just tried again and it's working. Something is awry with this plugin but I can't consistently reproduce it in a consistent pattern. Some series of writing/reading to and from the clipboard on a real iOS device causes the promise either to never resolve or a few times I've even gotten it to throw an Xcode error related to the capacitor plugin. Here's the error.

<img width="1052" alt="clipboard-error" src="https://user-images.githubusercontent.com/19443020/96612511-aebc8080-12b2-11eb-8dd4-f2f0ed28a1aa.png">

**Comment by jcesarmobile** [comment] 2020-10-20 16:07
As I said, for Capacitor 3 we are moving plugins out, and @capacitor/clipboard already handles the case of being empty by rejecting, and also don't force unwrap the string, so that won't be an issue neither.

**Comment by wesleygoldsborough** [comment] 2020-10-20 16:29
Ok thanks! Is @capacitor/clipboard ready? It looks like all the tasks are done here https://github.com/ionic-team/capacitor-plugins/pull/6 but it still shows in progress here https://github.com/ionic-team/capacitor/issues/3227

**Comment by jcesarmobile** [comment] 2020-10-20 16:39
is ready, but will probably fail to build on capacitor 2.x as it also has the Clipboard plugin in core, so can probably only be used with capacitor 3 alpha
