### ISSUE TITLE
bug: in a monorepo capacitor cannot find any plugins if installed in the root package.json

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#5028] opened 2021-09-09 10:30 UTC
## Bug Report

It is currently not possible to use Capacitor in a monorepo properly without adding any plugin to each apps package.json. This is super inefficient and can lead to different versions between apps that share the same core (ofc the compiler would catch some bugs but maybe not all).

I have some ideas to fix this:

1. Since capacitor is a standalone framework I would not like it do depend on other frameworks "workspace" features like Angular or Ionic but what about a new section in the capacitor.config.json that explicitly requires plugins to be included. This would add another benefit by not including plugins that one just installed to test something and forgot do uninstall later.
2. Search through all code for "@capacitor/*" 🤪
3. also search by "peerDependencies" so something like this will work `"peerDependencies": { "@capacitor/app": "*" }`

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2
```

### Platform(s)

All

### Current Behavior

No plugins added to Podfile e.g.

### Expected Behavior

Include them in some way

### Code Reproduction

Create an ionic multi app following this guide: https://openforge.io/mobile-academy/guides/mobile-app-development/how-to-create-a-monorepo-with-ionic-angular-appflow/

### Other Technical Details

`npm --version` output: 6.x

`node --version` output: 14.x

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2021-09-09 10:40
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by muuvmuuv** [comment] 2021-09-09 10:50
Oh the same issue appears to be with cordova plugins that are installed by capacitor..

**Comment by Ionitron** [comment] 2021-09-25 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-09-25 00:02 UTC
Labels: cli, needs reply, needs reproduction

**Comment by distante** [comment] 2022-02-22 09:02
I am trying to sell the idea of using Ionic where I work at, but we use nx monorepos. It makes it hard to sell :/
