### ISSUE TITLE
bug: monorepo (Angular) support

### ISSUE THREAD

**Issue by alexciesielski** [ionic-team/capacitor#4508] opened 2021-04-28 07:15 UTC
### Capacitor Version
Both 2 and 3

### Current Behavior
A separate package.json in the `projects/app/` subfolder needs to be maintained with Capacitor's core and plugin features, lessening the advantages of a single package.json monorepo approach.

### Expected Behavior
Capacitor is able to detect plugins from the root package.json.

### Code Reproduction
- Create a Angular monorepo application, install Capacitor's core features and (at-least) one 3rd party plugin.
- Try to run `ionic capacitor sync` in the root folder. (Error that `package.json` could not be found)
- Add `package.json` under `projects/app` with all of Capacitor's plugins and run `sync` again: works.

**Comment by spicemix** [comment] 2021-09-28 20:35
PLUS ONE.

**Comment by jase88** [comment] 2022-08-13 09:41
Would be helpful for tools like nx

**Comment by WetCouch** [comment] 2023-03-28 09:49
Still happening in v4 with nx, any chance for update? Capacitor seems to not resolve plugins from root package.json

**Comment by WhatsThatItsPat** [comment] 2023-12-16 01:00
Does this really need a reproduction?

**Comment by Ionitron** [comment] 2024-01-01 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-01 00:06 UTC
Labels: needs reply, needs reproduction
