### ISSUE TITLE
bug: Modal page breaks if keyboard open and back button pressed (or swipe back on iOS)

### ISSUE THREAD

**Issue by vadimwe** [ionic-team/capacitor#6263] opened 2023-01-30 17:00 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/ios: 4.6.2
  @capacitor/android: 4.6.2
```

### Platform(s)

iOS, Android

### Current Behavior

This affects only situation when in modal screen exists ion-nav tag with isolated navigation stack (navigation in modal page).
1. Tap on input (keyboard will show)
2. Click back button (with open keyboard)

Result:
Page changed to previous.
**But half of screen stays black** and app works in rest of screen (100% height - keyboard height)

### Expected Behavior

Keyboard should be closed and app screen resized like in ordinary back button click case

### Code Reproduction

Modal with isolated nav stack:
HTML:

```
<ion-nav #isolatedNav></ion-nav>
```

TS:

```
export class IsolatedNavigationStackModalPage implements OnInit, OnDestroy {
  @ViewChild('isolatedNav', { static: true }) isolatedNav!: IonNav;

  @Input() initialPageComponent: any;
  @Input() initialPageComponentProps: any;

  constructor(
    private eventsService: EventsService,
  ) { }

  ngOnInit() {
    this.isolatedNav.setRoot(this.initialPageComponent, {
      isolatedNavProxiedComponentParams: this.initialPageComponentProps
    });
    this.eventsService.subscribe('isolatedNavStack::navigateForward', async (data: {pageComponent: any, pageProps: any, navOptions: any}) => {
      this.isolatedNav.push(data.pageComponent, data.pageProps, data.navOptions);
    });
    this.eventsService.subscribe('isolatedNavStack::navigateBack', async () => {
      if (await this.isolatedNav.canGoBack()) {
        this.isolatedNav.pop();
      }
    });
  }

  ngOnDestroy() {
    this.eventsService.destroy('isolatedNavStack::navigateBack');
  }

}
```

Loaded modal HTML:

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button [disabled]="commonService.isKeyboardVisible"></ion-back-button>
    </ion-buttons>
    <ion-title>Password recover</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div class="ion-padding">
    Please enter your email address and we will send you password recover instructions
  </div>
  <form [formGroup]="passwordForm" (ngSubmit)="handleSubmitButton()">
    <div>
      <ion-list inset="true" class="inset-bg">
        <ion-item>
          <ion-label>
            Email
          </ion-label>
          <ion-input type="email" formControlName="email" placeholder="john.smith@example.org" enterkeyhint="go" (keyup.enter)="handleSubmitButton()" />
        </ion-item>
      </ion-list>
    </div>
    <div class="ion-margin" style="margin-top: 30px;">
      <ion-button type="submit" expand="block" color="primary" shape="round">
        Send instructions
      </ion-button>
    </div>
  </form>
</ion-content>
```

Loaded modal TS:

```
@Component({
  selector: 'app-auth-password-recover',
  templateUrl: './auth-password-recover.page.html',
  styleUrls: ['./auth-password-recover.page.scss'],
})
export class AuthPasswordRecoverPage implements OnInit {
  passwordForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    public commonService: CommonService,
  ) {
    this.passwordForm = this.fb.group({
      email: ['', [Validators.required, Validators.email, Validators.maxLength(255)]]
    });
  }

  ngOnInit() {
    
  }

  ionViewWillEnter() {
    this.commonService.setKeyboardResizeMode(KeyboardResize.Ionic);
  }

  handleSubmitButton() {
    this.commonService.keyboardClose();
    console.log(this.passwordForm.value);
  }

}
```

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v16.18.1

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Tested on Angular & iPhone 14 Pro Max

![IMG_0241](https://user-images.githubusercontent.com/2635452/215543498-290184ed-fb8d-44c5-9a11-6e2b22df08fa.PNG)

![IMG_0243](https://user-images.githubusercontent.com/2635452/215545205-5d8ed8fa-6a9b-4e1b-85ec-3225d20b8770.PNG)

![IMG_0242](https://user-images.githubusercontent.com/2635452/215543566-5c16e7a0-20da-4348-ae07-30a75c210d67.PNG)

**Comment by Ionitron** [comment] 2023-01-30 17:02
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-15 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-15 00:06 UTC
Labels: platform: android, platform: ios, needs reply, needs reproduction
