### ISSUE TITLE
feat: add support on FileSystem to read files as ArrayBuffer

### ISSUE THREAD

**Issue by AleFons** [ionic-team/capacitor#3396] opened 2020-08-07 14:26 UTC
### Description
The Ionic Cordova File Plugin had several ways to read files, including the possibility of reading the file as an ArrayBuffer. The FileSystem plugin doesn't have an equivalent way of doing so, being only capable to read files as binary data. I'd like to request for an implementation to read files as ArrayBuffer.

### Platform(s)
Android, iOS

### Preferred Solution
Add the option to read a file as ArrayBuffer using the readFile method.

### Alternatives
I believe it'd be possible to read a file as a binary and then convert it to arrayBuffer, but it seems very costly performance-wise to do so.

### Additional Context
There is an ongoing issue with the Ionic Cordova File Plugin equivalent to the function requested here, wherein there is a possibility the function loses connection between Angular and Cordova and as such it never resolves. The issue is from 2017 and is still ongoing https://github.com/ionic-team/ionic-native/issues/978.

**Comment by dwieeb** [comment] 2020-08-07 22:58
Duplicate of https://github.com/ionic-team/capacitor/issues/984

**Closed by dwieeb** 2020-08-07 22:58 UTC
Labels: platform: android, platform: ios

**Comment by AleFons** [comment] 2020-08-10 12:31
While the issue referenced talks about dealing with large amounts of data, it doesn't specifically mention anything about ArrayBuffer and the discussion seems to be centered on writing files, not reading them; should I assume then reading as array buffer is also a planned feature for 3.0.0?

**Comment by dwieeb** [comment] 2020-08-10 18:56
#984 is largely a foundational issue I'm using to track the ability to transfer large amounts of binary data over the Capacitor bridge. I assure you that if we add this functionality to FileSystem, it will exist for both reading from and writing to files. While more investigation is needed to confirm it as a feature for 3.0.0, I personally would really like it to be. 

I created https://github.com/ionic-team/capacitor-plugins/issues/10 to track the actual FileSystem API changes. If you have a case as to why we should use ArrayBuffers vs Blobs, feel free to comment in that issue.

Thanks for following up!

**Comment by AleFons** [comment] 2020-08-11 11:30
My specific use case is that I want to use [the aws sdk package](https://www.npmjs.com/package/aws-sdk) to send files to amazon's s3 storage and it specifically requires arrayBuffer.

**Comment by dwieeb** [comment] 2020-08-11 19:13
You will be able to use [`blob.arrayBuffer()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer).
