### ISSUE TITLE
feat: Log iOS low memory warnings

### ISSUE THREAD

**Issue by tristan-morris** [ionic-team/capacitor#6933] opened 2023-09-25 00:37 UTC
### Description
It would be very useful if Capacitor logged [iOS low memory warnings](https://developer.apple.com/documentation/xcode/responding-to-low-memory-warnings) when they are broadcast. Selfishly, I spent quite a bit of time figuring out why WkWebView was restarting--because a webgl process was being terminated as the device had no memory. But I assume this happens fairly frequently and people might not know. I didn't realise so much memory coud have been consumed. While the crash is logged, it is identified as the process terminated rather than being reaped due to low memory (even though my process was the cause of the memory being low). 

### Platform(s)
iOS 

### Preferred Solution
Log memory warnings to console is enough

### Alternatives
Reducing memory is always nice, but knowing it is an issue is more important.

### Additional Context
Mapbox-gl-js on iOS in WkWebView

**Comment by jcesarmobile** [comment] 2023-09-25 16:49
Your problem is most likely the `webViewWebContentProcessDidTerminate` being called, which reloads your app. The memory warnings by themselves won't restart your app.

So I'm closing as duplicate of https://github.com/ionic-team/capacitor/issues/2379

**Closed by jcesarmobile** 2023-09-25 16:49 UTC
Labels: platform: ios
