### ISSUE TITLE
Network.addListener('networkStatusChange') ubg

### ISSUE THREAD

**Issue by UlisesCeca** [ionic-team/capacitor#1625] opened 2019-06-02 13:22 UTC
Description of the problem:

The event `Network.addListener('networkStatusChange'...)` is fired every time the device is unlocked.

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [ X] linux

Other information:

Capacitor version: 1.0.0

node version: 10.16.0

npm version: 6.9.0

**Comment by solojuve1897** [comment] 2019-06-03 09:21
Connected to https://github.com/ionic-team/capacitor/issues/1492

**Comment by jcesarmobile** [comment] 2019-06-03 11:01
It's a duplicate of https://github.com/ionic-team/capacitor/issues/1492

**Closed by jcesarmobile** 2019-06-03 11:01 UTC
