### ISSUE TITLE
bug: The 'Pods-App' target has frameworks with conflicting names

### ISSUE THREAD

**Issue by kieranbarlow** [ionic-team/capacitor#5842] opened 2022-08-08 15:25 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/core: 4.0.1
  @capacitor/cli: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
```

### Platform(s)

IOS

### Current Behavior

When installing a cordova plugin I get a naming conflict when trying to run npx cap sync, I haven't changed anything just installed a cordova plugin following the capacitor npm install cordova-plugin guide. 

### Expected Behavior

Build should succeed

### Code Reproduction

npm install cordova-plugin-brother-label-printer
npx cap sync

`The 'Pods-App' target has frameworks with conflicting names`

### Other Technical Details

`npm --version` output: 6.14.17

`node --version` output: v14.20.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

I raised an issue with a Cordova plugin creator directly, looked into the issue further locally.
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer/issues/51

**Comment by Ionitron** [comment] 2022-08-15 10:45
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-08-31 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-08-31 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction
