### ISSUE TITLE
bug: Black screen when Android System Webview is not up to date on Chromebook

### ISSUE THREAD

**Issue by panstromek** [ionic-team/capacitor#6620] opened 2023-05-29 07:52 UTC
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:       

  @capacitor/cli: 5.0.4    
  @capacitor/core: 5.0.4   
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4    

Installed Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1
  @capacitor/core: 4.7.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)
Chrome OS (Android-like), Lenovo 2v1 Lenovo IdeaPad Flex 3 CB 11M836

### Current Behavior
When the app is started, Splash screen appears, but after that, the whole window is just black. No error message, nothing else happening.

The only pattern I observed is that Android System Webview is not up to date when this happens. After I go to Google Play and update Android System Webview, the issue goes away.

### Expected Behavior
The app should work even when the webview is not up to date, or report some discoverable error (if it's critical)

### Additional Context
I couldn't connect the device to a debugger, it won't pair with my dev machine for some reason, so I don't have access to error logs, console or anything. I'll try some different approach at some point, to get at least some debug info from the machine.

**Comment by Ionitron** [comment] 2023-05-30 08:02
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-15 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-15 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
