### ISSUE TITLE
bug: [iOS] Capacitor Camera API showing blank page (or pop-up) when it should open the photo gallery (photo-picker.viewservice was interrupted)

### ISSUE THREAD

**Issue by marcelo-ansaldi-baltazar** [ionic-team/capacitor#3734] opened 2020-10-27 20:36 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.2     

  @capacitor/core: 2.4.2    

  @capacitor/android: 2.4.2 

  @capacitor/electron: 2.4.2

  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/android 2.2.0

  @capacitor/ios 2.2.0

[error] "laboratorio" is missing in "E:\Proyectos\app-laboratorio-clinico-etcheverry\android\app\src\main\java". Please create a directory structure matching the package id "laboratorio.etcheverry.ripit.cl" within the directory "E:\Proyectos\app-laboratorio-clinico-etcheverry\android\app\src\main\java".
```
### Platform(s)
iOS

### Current Behavior

Ionic 4 + Angular 9 + Capacitor.

I implemented the Capacitor Camera API function getPhoto() like this: 

![image](https://user-images.githubusercontent.com/26723811/97380850-a82b9b80-18a6-11eb-9b8b-1eaaeaa2ce5b.png)
![image](https://user-images.githubusercontent.com/26723811/97380516-fab88800-18a5-11eb-847c-ce033a7d4c28.png)

This works perfect in android and chrome (using ionic serve). 

But in iOS, when i run my app in an xcode simuator, the following happens:

For the camera option **(CameraSource.Camera)**, the simulator throws an alert that says that iOS simulators dont have a camera (i assume this is the outcome i should expect).

For the gallery option **(CameraSource.Photos)**, i get a white screen (or pop-up) in which i can't select any photo, and i get the following error in the xcode terminal: 

![image](https://user-images.githubusercontent.com/26723811/97361121-df398700-187d-11eb-9d42-37471bb6fa39.png)

### Expected Behavior

The simulator should show the gallery when the **(CameraSource.Photos)**, option is selected.

### Code Reproduction

 https://github.com/marcelo-ansaldi-baltazar/issueCapacitatorCameraApi

### Other Technical Details

`npm --version` output: 6.13.8

`node --version` output: 12.19.0

`pod --version` output (iOS issues only): 1.10.0

### Additional Context

Forgot to mention that the Capacitor documentation includes this:

![image](https://user-images.githubusercontent.com/26723811/97362547-f1b4c000-187f-11eb-99d6-18b5a9b67ea9.png)

But i think i have the right thing by default (meaning didn't change anything myself)
![image](https://user-images.githubusercontent.com/26723811/97362796-4a845880-1880-11eb-800a-30ac41bf3fe2.png)

**Comment by jcesarmobile** [comment] 2020-10-28 12:05
I can't reproduce on your sample app
![image](https://user-images.githubusercontent.com/1637892/97433657-26775480-191e-11eb-823a-04577b1dc683.png)

moving to discussions so maybe somebody can give you a hand if faced the same issue

**Closed** 2020-10-28 12:05 UTC
Labels: platform: ios
