### ISSUE TITLE
bug: appendUserAgent not working

### ISSUE THREAD

**Issue by EtiennePASSOT** [ionic-team/capacitor#4886] opened 2021-08-04 09:32 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2

[success] Android looking great! 👌
```
### Platform(s)

- [x] Android

Not tested in iOS

### Current Behavior

I need to change UserAgent from Capacitor Webview. I used in `capacitor.config.ts` appendUserAgent like this:
```
const config: CapacitorConfig = {
  appId: 'com.example.app',
  appName: 'example-mobile',
  webDir: 'dist',
  bundledWebRuntime: false,
  server: {
    url: "http://localhost:3000",
    cleartext: true
  },
  appendUserAgent: 'MyUserAgent',
};
```

I've also tried : 
```
const config: CapacitorConfig = {
  appId: 'com.example.app',
  appName: 'example-mobile',
  webDir: 'dist',
  bundledWebRuntime: false,
  server: {
    url: "http://localhost:3000",
    cleartext: true
  },
  android: {
    appendUserAgent: 'MyUserAgent',
  }
};
```

When i use chrome dev tools (with 'chrome://inspect/#devices')
```
> window.navigator.userAgent
Mozilla/5.0 (Linux; Android 10; COL-L29 Build/HUAWEICOL-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Mobile Safari/537.36
```
### Expected Behavior

```
> window.navigator.userAgent
Mozilla/5.0 (Linux; Android 10; COL-L29 Build/HUAWEICOL-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Mobile Safari/537.36 MyUserAgent
```

### Other Technical Details

`npm --version` output:
6.14.12
`node --version` output:
v12.22.1

Maybe I didn't understand something about UserAgent but I think it's a bug.

Thank you in advance for your help and your answers,
Don't hesitate to answer me if you need more details

**Comment by jcesarmobile** [comment] 2021-08-04 15:24
I've tried and it seems to work fine.
Did you run `npx cap copy`or `npx cap sync` after adding the value?
If you did and still didn't work, please, provide a sample app where it can be reproduced.

**Comment by Ionitron** [comment] 2021-08-20 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-20 00:02 UTC
Labels: platform: android, needs reply
