### ISSUE TITLE
bug: Capacitor Migration - Angular error NG6002 after migration 

### ISSUE THREAD

**Issue by DrDanL** [ionic-team/capacitor#6477] opened 2023-04-09 09:31 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3
```

### Platform(s)
All current builds. 

### Current Behavior
When performing 'ionic build --prod' for the first time seen Capacitor migration package the following errors are returned

```
ERROR in src/app/app-routing.module.ts:29:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
29 export class AppRoutingModule { }

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of ConsentPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of DashboardPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of DebugPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of QRLinkPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of ScreeningPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of SuccessPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of UserPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of WalkthroughPageModule, but itself has errors
28 export class ComponentsModule {}

ERROR in src/app/shell/shell.module.ts:38:14 - error NG6002: Appears in the NgModule.imports of ComponentsModule, but itself has errors
38 export class ShellModule { }

ERROR in src/app/shell/shell.module.ts:38:14 - error NG6003: Appears in the NgModule.exports of ComponentsModule, but itself has errors
38 export class ShellModule { }

ERROR in src/app/tabs/tabs-routing.module.ts:50:14 - error NG6002: Appears in the NgModule.imports of TabsPageModule, but itself has errors
50 export class TabsPageRoutingModule {}

2023-04-09 10:22:25: webpack 5.44.0 compiled in 22129 ms (36866f1a03ab53e41e39)

Error: src/app/app-routing.module.ts:29:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
29 export class AppRoutingModule { }

Error: src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
28 export class ComponentsModule {}

Error: src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of ConsentPageModule, but itself has errors
28 export class ComponentsModule {}

Error: src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of DashboardPageModule, but itself has errors
28 export class ComponentsModule {}

Error: src/app/components/components.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of DebugPageModule, but itself has errors
28 export class ComponentsModule {}
```

### Expected Behavior
It is expected the by running 'ionic build --prod' to produce a build of the app.

**Comment by Ionitron** [comment] 2023-04-10 11:21
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-04-26 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-04-26 00:05 UTC
Labels: needs reply, needs reproduction
