### ISSUE TITLE
App doesn't fill up the whole screen height on iOS

### ISSUE THREAD

**Issue by danielsimon1** [ionic-team/capacitor#646] opened 2018-07-11 08:15 UTC
My capacitor app seems to not fill up the whole screen width on my iPhone 6. The app just stops a few pixels before reaching the bottom of the screen. On the simulator, the issue is not present. Am I the only one having this issue or can someone reproduce?

**Steps to reproduce:**
1. Create an Ionic project (sidemenu template)
2. Add Capacitor
3. Build the app for iOS and run on a real device (iPhone 6 for me)

Below are screenshots, the second one showing the result when I select the `body` element in the Web Inspector. (I added a border to clarify the issue)

<div style="white-space: nowrap">
<img src="https://user-images.githubusercontent.com/18580672/42559026-2fd181b6-84f3-11e8-8cc5-bc18763df41e.PNG" width="40%" style="display: inline; border: 1px solid black">
<img src="https://user-images.githubusercontent.com/18580672/42559030-31ef897a-84f3-11e8-90b7-a2a812817164.PNG" width="40%" style="display: inline; border: 1px solid black" align="right">
</div>

**Comment by jcesarmobile** [comment] 2018-07-11 12:35
what's your ionic version?

**Comment by danielsimon1** [comment] 2018-07-11 13:11
@jcesarmobile Here is the output of `ionic info`

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.10
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 5.6.0 
    OS   : macOS High Sierra

Misc:

    backend : pro

**Comment by mlynch** [comment] 2018-07-11 13:53
Dupe of #337

**Closed by mlynch** 2018-07-11 13:53 UTC
