### ISSUE TITLE
bug: Android crash `NullPointerException: Attempt to invoke virtual method` when clicking phone or email link

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor#6507] opened 2023-04-17 11:29 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/cli: 4.7.3

[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

When the user clicks on a link, which references a phone number or an email address the app crashes.

```
  <a href="tel:12345678">Call: 12345678</a><br><br>
  <a href="mailto:info@example.com">Mail To: info@example.com</a>
```

### Expected Behavior

Well, the app shouldn't crash, and instead start a phone call or open a mail program ;-)

### Code Reproduction

I've created a reproduction repo, which you can find here:

https://github.com/tobiasmuecksch/cap-link-crash-demo

Just clone it, run it an click on one of the links on page 1.

If you prefer to create your own reproduction code, you only need to add the following lines to one of your components:

```
  <a href="tel:12345678">Call: 12345678</a><br><br>
  <a href="mailto:info@example.com">Mail To: info@example.com</a>
```

### Other Technical Details

`npm --version` output:
9.5.0

`node --version` output:
v18.15.0

### Stack Trace

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1294854/232472298-ac52da53-898d-416a-b60d-55300669701b.png">

### Potential Error Source

It looks like this might be the line, where the error occurs, but I'm not sure yet.

<img width="1031" alt="Bildschirmfoto 2023-04-17 um 13 09 29" src="https://user-images.githubusercontent.com/1294854/232472666-c30f0a79-c24d-4fd0-8c44-a7438268c859.png">

**Comment by tobiasmuecksch** [comment] 2023-04-17 11:47
This is **NOT** a duplicate of https://github.com/ionic-team/capacitor/issues/6479
The stack trace is completely different.

**Comment by jcesarmobile** [comment] 2023-04-17 12:18
duplicate of https://github.com/ionic-team/capacitor/issues/6483

**Closed by jcesarmobile** 2023-04-17 12:18 UTC
Labels: platform: android
