### ISSUE TITLE
Error running ionic app in emulator/device. 

### ISSUE THREAD

**Issue by desmasimba** [ionic-team/capacitor#4935] opened 2021-08-17 13:03 UTC
```
2021-08-17 14:57:15.285 7442-7442/com.health.positive_konnections E/ive_konnection: Invalid ID 0x00000000.
2021-08-17 14:57:15.538 7442-7479/com.health.positive_konnections E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.health.positive_konnections/app_webview/variations_seed": /data/user/0/com.health.positive_konnections/app_webview/variations_seed (No such file or directory)
2021-08-17 14:57:15.558 7442-7442/com.health.positive_konnections E/ive_konnection: Invalid ID 0x00000000.
2021-08-17 14:57:15.566 7442-7442/com.health.positive_konnections E/ive_konnection: Invalid ID 0x00000000.
2021-08-17 14:57:16.391 7442-7442/com.health.positive_konnections E/Capacitor: Unable to read file at path public/plugins
2021-08-17 14:57:16.524 7442-7516/com.health.positive_konnections E/chromium: [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
2021-08-17 14:57:17.001 7442-7518/com.health.positive_konnections E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2021-08-17 14:57:17.191 7442-7516/com.health.positive_konnections E/chromium: [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
2021-08-17 14:57:17.351 7442-7518/com.health.positive_konnections E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
2021-08-17 14:57:17.351 7442-7518/com.health.positive_konnections E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
2021-08-17 14:57:17.450 7442-7442/com.health.positive_konnections E/Capacitor/Console: File:  - Line 1 - Msg: Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
2021-08-17 14:57:17.467 7442-7442/com.health.positive_konnections E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.health.positive_konnections, PID: 7442
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=9539, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.health.positive_konnections/com.health.positive_konnections.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.PluginCall.reject(java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.PluginCall.reject(java.lang.String)' on a null object reference
        at com.getcapacitor.Plugin.handleRequestPermissionsResult(Plugin.java:882)
        at com.getcapacitor.Bridge.onRequestPermissionsResult(Bridge.java:856)
        at com.getcapacitor.BridgeActivity.onRequestPermissionsResult(BridgeActivity.java:188)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
        at android.app.Activity.dispatchActivityResult(Activity.java:7458)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

**Comment by desmasimba** [comment] 2021-08-17 13:04
Extra info:

npx cap doctor
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2

Been facing this challenge for the past week to no avail.

**Comment by Ionitron** [comment] 2021-08-17 13:53
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-09-02 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-09-02 00:03 UTC
Labels: needs reply, needs reproduction
