### ISSUE TITLE
bug: capacitor's build gradle script does not get module's build script.

### ISSUE THREAD

**Issue by SalahAdDin** [ionic-team/capacitor#4066] opened 2021-01-14 12:25 UTC
### Capacitor Version

```
❯ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/android 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/core 2.4.5
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 9 Capacitor plugins for ios:
    @capacitor-community/fcm (1.0.8)
    @capacitor-community/firebase-analytics (0.2.0)
    @capacitor-community/firebase-crashlytics (0.3.0)
    @capacitor-community/http (0.2.1)
    @capacitor-community/uxcam (0.0.3)
    @diachedelic/capacitor-background-geolocation (0.3.4)
    capacitor-firebase-auth (2.3.2)
    card.io.cordova.mobilesdk (2.1.0)
    cordova-plugin-inappbrowser (4.1.0)
[success] iOS looking great! 👌
```

### Platform(s)

- [x] Android

### Current Behavior

When the build task is launched, it just takes the main build script as base and from it, **gradle** just take the repositories:
```bash
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.uxcam:uxcam:3.3.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/uxcam/uxcam/3.3.4/uxcam-3.3.4.pom
       - https://jcenter.bintray.com/com/uxcam/uxcam/3.3.4/uxcam-3.3.4.pom
       - file:/Users/luisalaguna/Projects/geliver-ionic-react/android/capacitor-cordova-android-plugins/src/main/libs/uxcam-3.3.4.aar
       - file:/Users/luisalaguna/Projects/geliver-ionic-react/android/capacitor-cordova-android-plugins/src/main/libs/uxcam.aar
       - file:/Users/luisalaguna/Projects/geliver-ionic-react/android/app/libs/uxcam-3.3.4.aar
       - file:/Users/luisalaguna/Projects/geliver-ionic-react/android/app/libs/uxcam.aar
       - https://repo.maven.apache.org/maven2/com/uxcam/uxcam/3.3.4/uxcam-3.3.4.pom
     Required by:
         project :app > project :capacitor-community-uxcam

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
````

### Expected Behavior

It should not be needed to put the required repositories in the main build script file but it should get also repositories from its dependencies(plugins).

### Code Reproduction

plugin's `build.gradle`:
```gradle
repositories {
    jcenter()
    maven {
        url 'https://sdk.uxcam.com/android/'
    }
}
```

### Other Technical Details

`npm --version` output: 7.0.15

`node --version` output: v15.4.0

`pod --version` output (iOS issues only): 1.10.0

**Comment by jcesarmobile** [comment] 2021-01-14 12:31
looks like the problem is on the plugin, but would be good if you could provide a sample app that reproduces the issue

**Comment by SalahAdDin** [comment] 2021-01-14 15:54
@jcesarmobile how could it be a problem of the plugin? that code is included on the plugin and **capacitor** does not get the _url_ from it, we have to add it manually on the application's build script to avoid this problem.

**Comment by jcesarmobile** [comment] 2021-01-14 16:02
because it shouldn't be needed to add anything in your main build.gradle, so probably the plugin is not configuring the dependency correctly

**Comment by SalahAdDin** [comment] 2021-01-14 16:13
@jcesarmobile this is the plugin: https://github.com/SalahAdDin/capacitor-uxcam
we are new doing plugins, so, it is possible we are doing it wrongly.

**Comment by jcesarmobile** [comment] 2021-01-14 17:37
try using `compileOnly 'com.uxcam:uxcam:3.3.4@aar'` instead of `implementation 'com.uxcam:uxcam:3.3.4@aar'`, that way only your plugin compiles the aar and other modules don't need to know about it.

**Comment by SalahAdDin** [comment] 2021-01-15 06:41
@jcesarmobile It seems it did work.

**Comment by jcesarmobile** [comment] 2023-03-06 16:21
closing since no sample app was provided, so it's not possible to reproduce
other plugins are using aar files, so doesn't look like a capacitor bug

if the issue is still present in Capacitor 4, please, create a new issue and provide a sample app that reproduces the issue

**Closed by jcesarmobile** 2023-03-06 16:21 UTC
Labels: platform: android
