### ISSUE TITLE
capacitor android "Unexpected token function" with ionic v4 type==angular

### ISSUE THREAD

**Issue by scipioni** [ionic-team/capacitor#707] opened 2018-08-04 08:28 UTC
Running a simple app (created with wizard) give an error on android platform.

![error](https://user-images.githubusercontent.com/3766283/43674181-c974c4ce-97cf-11e8-82c6-b4797c3e43ae.png)

error
```
SyntaxError: Unexpected token functioncapacitor.handleWindowError @ capacitor-runtime.js:324
capacitor-runtime.js:292 SyntaxError: Unexpected token functioncapacitor.handleError @ capacitor-runtime.js:292
vendor.js:65004 Uncaught SyntaxError: Unexpected token function
```

Tested with simpler startup:
cd /tmp
ionic start myApp tabs --type=angular

cd myApp
npm run build
npm install --save @capacitor/cli @capacitor/core
npm uninstall --save cordova-plugin-splashscreen
npx cap init myApp com.example.myapp
npx cap add android
npx cap copy
... now open android studio on ./android and run app

package.json
```
{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "6.0.9",
    "@angular/core": "6.0.9",
    "@angular/forms": "6.0.9",
    "@angular/http": "6.0.9",
    "@angular/platform-browser": "6.0.9",
    "@angular/platform-browser-dynamic": "6.0.9",
    "@angular/router": "6.0.9",
    "@capacitor/android": "^1.0.0-beta.3",
    "@capacitor/cli": "^1.0.0-beta.3",
    "@capacitor/core": "^1.0.0-beta.3",
    "@ionic-native/core": "5.0.0-beta.14",
    "@ionic-native/splash-screen": "5.0.0-beta.14",
    "@ionic-native/status-bar": "5.0.0-beta.14",
    "@ionic/angular": "4.0.0-beta.0",
    "@ionic/ng-toolkit": "1.0.0",
    "@ionic/schematics-angular": "1.0.1",
    "core-js": "^2.5.3",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.0.8",
    "@angular/compiler": "6.0.9",
    "@angular/compiler-cli": "6.0.9",
    "@angular/language-service": "6.0.9",
    "@angular-devkit/architect": "0.7.0-rc.3",
    "@angular-devkit/build-angular": "0.7.0-rc.3",
    "@angular-devkit/core": "0.7.0-rc.3",
    "@angular-devkit/schematics": "0.7.0-rc.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.5.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2"
  },
  "description": "An Ionic project"
}
```

Environment:
```
> node -v
v8.10.0
> npm list -g --depth=010:04:00 
 ├── ionic@4.0.3
 └── npm@6.3.0
```

**Comment by netsesame2** [comment] 2018-08-10 13:26
Just got the same error!

**Comment by netsesame2** [comment] 2018-08-14 06:59
So....no progress any more?

**Comment by jcesarmobile** [comment] 2018-08-15 11:28
Are you testing on real device or simulator?

**Comment by scipioni** [comment] 2018-08-15 14:30
Android virtual machine

Il mer 15 ago 2018, 13:28 jcesarmobile <notifications@github.com> ha
scritto:

**Comment by netsesame2** [comment] 2018-08-15 15:01
Me too, VM by Genymotion, android 7,6, no lucky.
Running OK on real device.

**Comment by AsbjornRekve** [comment] 2018-08-15 15:15
I am also getting this error - on an actual device.

On a Samsung S7 Edge running Android 8.0.0 (api 26) it works fine, but when i try on a UMIDIGI Z running 7.1.1 (api 25) this same error shows up.

**Comment by jcesarmobile** [comment] 2018-08-15 15:36
This is because of ES6 not being supported in some old browsers, it specially affects simulators (or VMs) because they don't get updates.
It shouldn't really affect real devices if they have the System WebView(Android 5-6) or Chrome (Android 7-8) up to date. So @AsbjornRekve, make sure that device has latest version of Chrome.

Anyway, we are working on getting this fixed

**Comment by jthoms1** [comment] 2018-08-15 15:40
Working on the fix for this.

**Comment by netsesame2** [comment] 2018-08-15 15:44
Good news, expect for the result.

**Comment by jcesarmobile** [comment] 2018-08-15 17:49
[This PR](https://github.com/ionic-team/capacitor/pull/737) removes ES6 from native-bridge.js.

There is still an issue with Ionic/Stencil, that's what @jthoms1 is working on.

Not really a Capacitor issue as it only affects Ionic/Stencil apps, but will keep this open until both of them are fixed/merged.

**Comment by jthoms1** [comment] 2018-08-15 19:45
It appears the issue is with how ionic/core has the package.json entries listed.  Angular + Webpack are choosing the esm+es6 code so there are a whole host of entries that we need to add to account for this.  The following issue was opened to address the issue.

https://github.com/ionic-team/ionic/issues/15191

**Comment by jcesarmobile** [comment] 2018-11-28 00:10
Closing as the pending ionic issue was closed

**Closed by jcesarmobile** 2018-11-28 00:10 UTC
Labels: ionic
