### ISSUE TITLE
bug: add android platform with error "add Error running gradle sync Starting a Gradle Daemon (subsequent builds will be faster)"

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/capacitor#4922] opened 2021-08-13 01:26 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

when add android platform, console with error:
```
✔ Adding native android project in android in 35.34ms
⠸ add Error running gradle sync Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of an undefined build is not supported. Make sure that you are executing Gradle from a folder within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root folder.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Unable to infer default Android SDK settings. This is fine, just run npx cap open android and import and sync gradle manually
✔ Syncing Gradle in 4.24s
✔ add in 4.27s
[success] android platform added!
Follow the Developer Workflow guide to get building:
https://capacitorjs.com/docs/basics/workflow
✔ Copying web assets from www to android/app/src/main/assets/public in 23.50ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 1.24ms
✔ copy android in 37.89ms
✔ Updating Android plugins in 3.59ms
[info] Found 6 Capacitor plugins for android:
       @capacitor/app@1.0.2
       @capacitor/browser@1.0.2
       @capacitor/keyboard@1.0.2
       @capacitor/splash-screen@1.1.0
       @capacitor/status-bar@1.0.2
       capacitor-plugin-safe-area@0.0.1
✔ update android in 49.88ms
```

### Expected Behavior

no errors

### Other Technical Details

`npm --version` output: 7.20.6

`node --version` output: v14.17.3

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2021-08-13 06:36
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-29 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-29 00:02 UTC
Labels: platform: android, needs reply, needs reproduction
