### ISSUE TITLE
"Unable to access camera, user denied permission request"

### ISSUE THREAD

**Issue by mu250234** [ionic-team/capacitor#416] opened 2018-03-31 05:06 UTC
Hi ,

I got above error even I enable permissions in AndroidManifest file as follows:

uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />
    uses-permission android:name="android.permission.CAMERA" />
    uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

here is my code:

// prof pic
  async takePicture() {
    const image = await Plugins.Camera.getPhoto({
      quality: 90,
      allowEditing: true,
      resultType: CameraResultType.Uri,
      source: CameraSource.Camera
    })
    console.log('Got image back', image);
    this.image = this.sanitizer.bypassSecurityTrustResourceUrl(image && (image.webPath));
    console.log("tets");

  }

Please let me know what is the problem

**Comment by mlynch** [comment] 2018-03-31 15:13
I posted in slack, but try uninstalling and reinstalling the app, you should get a permissions prompt. Let me know if you don't.

It's possible you accidentally denied permissions, which you can't re-enable later

**Comment by mu250234** [comment] 2018-03-31 15:31
I tried with uninstall and reinstall app, not worked. and I also checked in my emulator, apps-> myApp-> permissions ,there I can see all camera,storage permissions are granted.

**Comment by mlynch** [comment] 2018-04-03 03:02
Wondering if it's related to this https://issues.apache.org/jira/browse/CB-10120&quot;&gt;CB-10120&lt;

**Comment by jcesarmobile** [comment] 2018-11-29 17:52
Closing as couldn't reproduce and simulators sometimes do strange things. 

Not sure if related, but`android:minSdkVersion` should be 21 instead of 16 and `android:targetSdkVersion` should be 27 instead of 26.
Try updating those values and testing on a real device, and if you can still reproduce, create a new issue and provide a minimal sample project

**Closed by jcesarmobile** 2018-11-29 17:52 UTC
Labels: needs-reply, triage
