### ISSUE TITLE
bug: Remote hosting - Load time/White screen for ~ 30 seconds

### ISSUE THREAD

**Issue by malte94** [ionic-team/capacitor#5745] opened 2022-07-06 06:32 UTC
### Capacitor Version

"@capacitor/android": "^3.6.0",
[info] Found 7 Capacitor plugins for android:
       @capacitor/app@1.1.1
       @capacitor/filesystem@1.1.0
       @capacitor/geolocation@1.3.1
       @capacitor/haptics@1.1.4
       @capacitor/local-notifications@1.1.0
       @capacitor/share@1.1.2
       @capacitor/toast@1.0.8
[info] Found 2 Cordova plugins for android:
       cordova-plugin-file@6.0.2
       cordova-plugin-file-opener2@3.0.5

### Platform(s)
Android

### Current Behavior
When pointing to a remote server, the load time of the app is absurdly high on Android. iOS works without any issues.

The issue is most likely not related to the server, since after various DNS/Redirect testings the server works without any issues.  The web app also loads fine when you call it via the https-URL on all devices on all browsers.

For the first 15 - 30 seconds (the time varies), just nothing seems to be happening.

Screenshot:

![load_time_capg2jxc](https://user-images.githubusercontent.com/89409894/177484144-54742ffd-a4ca-4c5b-a2f0-4ece5bfaaf75.jpeg)

https://abload.de/img/load_time_capg2jxc.jpeg

Video: 

For testing purposes, I removed the whole app and just placed a plain "index.html" with text on the server. Still, it takes forever to show just a plain HTML output. So it is definitely not related to any JS.

https://www.veed.io/view/c59c21a3-e9e2-4441-94d5-e8f36755df95

### Expected Behavior

The Capacitor wrapper must load as quick as calling the hosted web app from any browser.

### Additional information

I also removed the whole /android-Directory and gave it a fresh try with npx cap add android. The issue is still reproducible.

`npm --version` output: 8.10.0

`node --version` output: v16.15.0

```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'id',
  appName: 'name',
  webDir: 'build',
  bundledWebRuntime: false,
  server: {
    url: "https://thesite.com",
    //url: "http://192.168.178.49:3000", --> Loads quickly on android!
    cleartext: true
  },
  plugins: {
    LocalNotifications: {
      iconColor: "#488AFF"
    }
  }
};

export default config;
```

**Comment by Ionitron** [comment] 2022-07-06 08:13
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by malte94** [comment] 2022-07-07 12:05
Thank you @[jcesarmobile](https://github.com/jcesarmobile)

I found a way to reproduce the issue. And to workaround it.

With the following configuration, the load time is vastly.

```
  server: {
    url: "https://yourdomain.com",
    cleartext: true
  },

```
But when using the following notation, the app works fine again.

```
  server: {
    androidScheme: "https",
    url: "yourdomain.com",
    cleartext: true
  },
```

**Comment by Ionitron** [comment] 2022-07-23 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-23 00:06 UTC
Labels: platform: android, needs reply, needs reproduction

**Comment by malte94** [comment] 2022-07-31 19:05
This would probably need to be reopened, since the issue appeared again out of nowhere.
