### ISSUE TITLE
cordova plugins error  AndroidManifest.xml file  how to fix this error 

### ISSUE THREAD

**Issue by hadicreations** [ionic-team/capacitor#439] opened 2018-04-07 00:59 UTC
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.hadicreations.islamic_speach1">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
            android:name="com.hadicreations.islamic_speach1.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
            </intent-filter>

        </activity>
        <activity
          android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
          android:name="com.google.android.gms.ads.AdActivity"
          android:theme="@android:style/Theme.Translucent"/>

      <activity
        android:name="com.keyes.youtube.OpenYouTubePlayerActivity"
        android:screenOrientation="landscape"/>
      <activity
        android:name="com.bunkerpalace.cordova.YouTubeActivity"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
        android:label="@string/activity_name"
        android:launchMode="singleTop"
        android:theme="@android:style/Theme.Black.NoTitleBar"
        android:windowSoftInputMode="adjustResize"/>

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>

      <provider
        android:name="de.appplant.cordova.emailcomposer.Provider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/emailcomposer_provider_paths"/>
      </provider>
      <provider android:name="com.vaenow.appupdate.android.GenericFileProvider"
        android:authorities="${applicationId}.appupdate.provider"
        android:exported="false" android:grantUriPermissions="true">
        <meta-data android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/appupdate_paths"/>
      </provider>

      <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver" android:enabled="true">
        <intent-filter>
          <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH"/>
        </intent-filter>
      </receiver>
      <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver" android:enabled="true" android:exported="true">
        <intent-filter>
          <action android:name="com.android.vending.INSTALL_REFERRER"/>
        </intent-filter>
      </receiver>
      <service android:name="com.google.android.gms.analytics.AnalyticsService" android:enabled="true" android:exported="false"/>
      <service android:name="com.google.android.gms.analytics.CampaignTrackingService" android:enabled="true" android:exported="false"/>

      <amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false" xmlns:amazon="http://schemas.amazon.com/apk/res/android"/>
      <service android:name="com.onesignal.ADMMessageHandler" android:exported="false"/>
      <receiver android:name="com.onesignal.ADMMessageHandler$Receiver" android:permission="com.amazon.device.messaging.permission.SEND">
        <intent-filter>
          <action android:name="com.amazon.device.messaging.intent.REGISTRATION"/>
          <action android:name="com.amazon.device.messaging.intent.RECEIVE"/>
          <category android:name="$PACKAGE_NAME"/>
        </intent-filter>
      </receiver>

    </application>

    

    <uses-permission android:name="android.permission.INTERNET" />
    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

     <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
     <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
      <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
      <uses-permission android:name="com.amazon.device.messaging.permission.RECEIVE"/>
      <uses-permission android:name="$PACKAGE_NAME.permission.RECEIVE_ADM_MESSAGE"/>
       <permission android:name="$PACKAGE_NAME.permission.RECEIVE_ADM_MESSAGE" android:protectionLevel="signature"/>
</manifest>

cordova youtube player activity error , addmobPro activity error  , onsignal push notification error also 
``

Please Check My  AndroidManifest.xml  there have any mistik ?

**Comment by jcesarmobile** [comment] 2018-04-11 10:13
Can you provide more details?
What's the actual error?
How can we reproduce it?

**Comment by jcesarmobile** [comment] 2018-06-04 11:17
Closing because it's incomplete and none of the required information was provided

**Closed by jcesarmobile** 2018-06-04 11:17 UTC
Labels: needs reply

**Comment by KyDenZ** [comment] 2019-06-24 10:22
Hello,

I have the same concern.
I have a build project with ionic and the OneSignal plug-in. During a run with Android Studio on emulator, I have the following error:

error: resource string / activity_name (aka com.company.app:string/activity_name) not found

Thanks

**Comment by jcesarmobile** [comment] 2019-06-24 10:25
create a new issue and provide more information
