### ISSUE TITLE
bug: Screen orientation doesn't work correctly for Ionic with capacitor

### ISSUE THREAD

**Issue by shahramSo** [ionic-team/capacitor#3563] opened 2020-09-15 20:19 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.1
  @capacitor/core: 2.4.1
  @capacitor/android: 2.4.1
  @capacitor/electron: 2.4.1
  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/core 2.4.1
  @capacitor/cli 2.4.1
  @capacitor/android 2.4.1
  @capacitor/electron not installed
```

### Platform(s)

Andoid

### Current Behavior
I used Ionic with capacitor and I also used two Cordova plugin "cordova-plugin-screen-orientation" and "cordova-plugin-x-socialsharing" so my app has 2 views in my template one for portrait and other for landscape. the app and orientation change function works correctly but the views is freezed when orientation changed, so after I tapped on the screen, the view is changed.
this issue that I have tested was on Android, after some working days, I knew the issue comes when the plugin "es6-promise-plugin" is added automatically by capacitor, so when I remove it manually, Capacitor still add it automatically by update command.I think " es6-promise-plugin" is not compatible with some Cordova plugins which is used by Capacitor. for more, if you remove all Cordova plugins by npm uninstall command, the "es6-promise-plugin" is not removed, finally 
I tested with resize change function of angular platform but the result was same. therefore I uninstall all Cordova plugins and I used only resize function of angular platform and my app works correctly if " es6-promise-plugin" has been removed.

### Expected Behavior
Describe what the behavior should be.
I want to change my app view in portrait and landscape when orientation change.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by dwieeb** [comment] 2020-09-15 22:18
There doesn't seem to be a specific bug in this issue. It sounds like you're asking for Screen Orientation APIs as a feature, in which case there's an existing proposal: https://github.com/capacitor-community/proposals/issues/8

**Comment by shahramSo** [comment] 2020-09-16 10:40
As I already explain this is a bug, because by installing Cordova plugins, this issue comes and when I uninstall Cordova plugins , resize function of angular platform works correctly.
I have tested some times and I knew that this issue is related to "es6-promise-plugin".
My app created under the latest Ionic angular 10 with Capacitor.

**Comment by Ionitron** [comment] 2020-09-16 17:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2020-10-17 00:16
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2020-10-17 00:16 UTC
Labels: needs reply, needs reproduction
