### ISSUE TITLE
iOS does not scroll the UI and hiding behind the keyboard, whenever I keyboard shows

### ISSUE THREAD

**Issue by Ibni-Amin** [ionic-team/capacitor#5687] opened 2022-06-15 14:35 UTC
Please if someone work hardly on iOS keyboard to fix the scroll issue to exact height then share it with me thanks in advance

[https://capacitorjs.com/docs/apis/keyboard#setresizemode](url)

**Comment by jcesarmobile** [comment] 2022-06-15 14:39
Closing as the template has not been filled, so the issue is invalid.

But note that Capacitor doesn't automatically focus the view, you should do it yourself using the keyboard events or use a framework such as ionic that handles those things for you

**Closed by jcesarmobile** 2022-06-15 14:39 UTC

**Comment by Ibni-Amin** [comment] 2022-06-15 14:44
> Closing as the template has not been filled, so the issue is invalid.
> 
> But note that Capacitor doesn't automatically focus the view, you should do it yourself using the keyboard events or use a framework such as ionic that handles those things for you

Thanks for your quick reply here. I tried it actually in ionic but all the components are in angular and web tags so this is the reason. I also tried to add some style property to body of app when keyboard is show and bottom etc. but keyboard jut a litle scroll not more.
