### ISSUE TITLE
bug: iOS deeplink works but 'appUrlOpen' event is not firing and 'getLaunchUrl()' returns undefined

### ISSUE THREAD

**Issue by yllaw** [ionic-team/capacitor#5584] opened 2022-04-28 19:56 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS 15.4 simulator 
iOS 15.4.1 Physical Device
iOS 15.3 Physical Device

### Current Behavior

Deep link correctly opens the app instead of the webpage, but the `appUrlOpen` event is not fired. The `getLaunchUrl` function also returns undefined.

### Expected Behavior

The `appUrlOpen` event should fire. The function `getLaunchUrl` should return the URL of the universal link.

### Code Reproduction

```
CapApp.addListener('appUrlOpen', async (event: URLOpenListenerEvent) => {
  console.log(event.url);  // undefined
}); 

CapApp.getLaunchUrl().then( (data) => {
  console.log(data); // undefined
})
```

### Other Technical Details

`npm --version` output: 8.1.2

`node --version` output: v16.13.2

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Custom scheme fires `appUrlOpen` event and `getLaunchUrl()` returns the custom scheme url

Android is working as expected

**Comment by Ionitron** [comment] 2022-04-29 08:34
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-15 00:07
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-15 00:07 UTC
Labels: platform: ios, needs reply, needs reproduction
