### ISSUE TITLE
bug: browserFinished happens with non user close

### ISSUE THREAD

**Issue by Orilow** [ionic-team/capacitor#5728] opened 2022-06-29 12:47 UTC
## Bug Report
I have upgraded capacitor from 2 version to 3. 

After it I have a bug with reopenin Browser window caused with non user close action.
And the documentation said
> Android & iOS only: Listen for the browser finished event. It fires when the Browser **is closed by the user.**

So what means by closed by user? Is js generated close event - by user?

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/ios: 3.5.0
  @capacitor/android: 3.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

android

### Current Behavior

In a part of our app we trying to log user in through external authenticator (using OAuth 2.0)
`await Browser.open({ authUrl, presentationStyle: 'popover' });`
if user close Browser **without** login, we reopen it. So this code worked earlier, but now it reopens again despite of authroization fail or success - anytime.
`Browser.addListener('browserFinished', () => {
        Browser.open({ url, presentationStyle: 'popover' });
      });`
it's interesting that this behavior doesn't repeat in iOS

### Expected Behavior

Browser not reopens if it was not user close action

### Other Technical Details

`npm --version` output: 8.11.0

`node --version` output: v16.15.1

### Additional Context

So the questions are: What exactly is meant by **is closed by user**? Am I using API right due to my idea?

**Comment by Ionitron** [comment] 2023-03-06 16:39
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by szilard-dobai** [comment] 2023-03-10 17:25
We're in the exact same situation 🙃

**Comment by PaulMacinic** [comment] 2023-03-10 17:31
Can confirm we can also reproduce this.

**Comment by Ionitron** [comment] 2023-03-15 18:24
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-31 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-31 00:05 UTC
Labels: platform: android, needs reply, needs reproduction

**Comment by loehnertz** [comment] 2023-04-15 10:17
I have the same exact problem here. The API works as described on iOS but not properly on Android.

However, I think I found why this happens – at least I could fix it in my application:
For me, it disappears if in the `appUrlOpen` listener as the first thing once I detect that the auth login flow called back I invoke `Browser.removeAllListeners()`. Then on Android, it does not trigger anymore for regular browser closing, while on iOS, it still works as expected when calling `Browser.close()` programmatically right after the other call.
