### ISSUE TITLE
bug: Android keyboard hides inputs - no pan to input occurs

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#3661] opened 2020-10-09 13:10 UTC
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 14 Capacitor plugins for ios:
    call-number (1.0.1)
    cordova-open-native-settings (1.5.2)
    cordova-plugin-calendar (5.1.5)
    cordova-plugin-device-motion (2.0.1)
    cordova-plugin-email-composer (0.9.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-nativegeocoder (3.4.1)
    cordova-plugin-x-socialsharing (5.6.8)
    cordova-sms-plugin (1.0.0)
    cordova-support-android-plugin (1.0.2)
    cordova-support-google-services (1.4.1)
    es6-promise-plugin (4.2.2)
    phonegap-nfc (1.2.0)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌

### Platform(s)
Android Only

### Current Behavior
The keyboard will overlap any input.

### Expected Behavior

The keyboard should cause a pan of the screen to the input element that has been made active. 

### Code Reproduction
This happens on any ionic input - tapping it to bring the keyboard up does not pan the screen and instead the input gets hidden. It is also not possible to scroll whilst the keyboard is up
 I have seen that other threads abut the status bar overlay causing it, however i have tired both of the below options with no difference:

```
 StatusBar.setOverlaysWebView({
        overlay:tried both true and false here
      });
```

### Other Technical Details

`npm --version` output:6.14.6

`node --version` output:v14.0.0

`pod --version` output (iOS issues only):1.8.4

### Additional Context
On IOS the panning to input works fine.

**Comment by jcesarmobile** [comment] 2020-10-09 13:27
closing as duplicate of https://github.com/ionic-team/capacitor/issues/3088

**Closed by jcesarmobile** 2020-10-09 13:27 UTC
Labels: platform: android
