### ISSUE TITLE
bug: Application crash due to IllegalStateException 

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [ionic-team/capacitor#5672] opened 2022-06-10 14:32 UTC
## Bug Report

We use this official [plugin](https://github.com/adobe/cordova-acpcore) for adobe analytics but we are seeing many issues on the play store console, this is the only issue in the capacitor project, and the same SDK running properly in the Cordova project. I don't know why? if it is an SDK issue or capacitor because we use the same plugin in the Cordova project and we haven't found such an issue can anyone tell why?

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

```

### Platform(s)
Android only

**Error Log:**
```

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7598)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2177)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8653)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:530)
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:506)
  at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:198)
  at com.adobe.marketing.mobile.V4ToV5Migration.getV4SharedPreferences (V4ToV5Migration.java:548)
  at com.adobe.marketing.mobile.V4ToV5Migration.isMigrationRequired (V4ToV5Migration.java:510)
  at com.adobe.marketing.mobile.V4ToV5Migration.migrate (V4ToV5Migration.java:213)
  at com.adobe.marketing.mobile.MobileCore.setApplication (MobileCore.java:98)
  at com.app.PACKAGE_NAME.AdobeAnalytics.onCreate (AdobeAnalytics.java:21)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7593)
```

**Comment by Ionitron** [comment] 2022-06-10 14:36
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-26 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-26 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
