### ISSUE TITLE
bug: LocalNotification missing identifier

### ISSUE THREAD

**Issue by glIrving** [ionic-team/capacitor#5739] opened 2022-07-04 03:00 UTC
### Capacitor Version
  "dependencies": {
    "@capacitor/android": "^3.5.1",
    "@capacitor/camera": "^1.3.1",
    "@capacitor/cli": "^3.5.1",
    "@capacitor/core": "^3.5.1",
    "@capacitor/ios": "^3.6.0",
    "@capacitor/local-notifications": "^1.1.0",
    "@capacitor/push-notifications": "^1.0.9"
  }

```
 LocalNotification missing identifier
```

### Platform(s)
ios

### Code Reproduction
 pushMessage() {
      // alert("推送通知");
      return new Promise((resolve, reject) => {
        let array = [
          {
            title: "Quasar",
            body: "1This is a test notification",
            id: "1",
            schedule: {
              at: new Date(Date.now() + 100),
            },
          },
          {
            title: "Quasar",
            body: "2This is a test notification",
            id: "2",
            schedule: {
              at: new Date(Date.now() + 100),
            },
          },
        ];
        LocalNotifications.schedule({
          notifications: array,
        })
          .then((res) => {
            console.log("通知成功", res);
            // TODO发送完通知后，更新本地数据库的推送状态
            resolve(res);
          })
          .catch((err) => {
            console.log("通知失败", err);
            reject(err);
          });
      });
    },

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):{"errorMessage":"Notification missing identifier"}

**Comment by Ionitron** [comment] 2022-07-04 08:17
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-07-20 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-20 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction
