### ISSUE TITLE
bug: core http & cookies plugin not working in iOS

### ISSUE THREAD

**Issue by huuhait** [ionic-team/capacitor#6155] opened 2022-12-10 00:28 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1
```

### Platform(s)

ONLY IOS 16.2 IS TESTED

### Current Behavior

I've tested in ios with `document.cookie = 'aa=cc'` or use `CapacitorCookies.setCookie` but after that get cookie in `document.cookie` it's still none and `CapacitorHTTP` is error too (i mean about cookie)

Sorry my bad english

### Other Technical Details

`npm --version` output: 8.19.3

`node --version` output: v19.2.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment] 2022-12-12 09:23
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-28 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-28 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
