### ISSUE TITLE
bug:  keyboard doesn’t work done ios 

### ISSUE THREAD

**Issue by umbode** [ionic-team/capacitor#3549] opened 2020-09-13 20:55 UTC
# Bug Report

**Current behavior:**

https://forum.ionicframework.com/t/the-keyboard-doesnt-work-done-with-inputs/195956

**Expected behavior:**
ion-input right focus on keyboard and binding value on form 

**Steps to reproduce:**
Click on input 

**Related code:**

```
<form [formGroup]="form">
        <ion-grid>
          <ion-row class="ion-background-form-login">
            <ion-col [size]="6">
              <ion-item lines="none" no-padding>
                <!-- <ion-label position="stacked">Username</ion-label> -->
                <ion-input
                  formControlName="first_name"
                  type="text"
                  placeholder="..."
                ></ion-input>
              </ion-item>
            </ion-col>
          </ion-row>
        </ion-grid>
</form>
```
Ionic:

   Ionic CLI                     : 6.9.1 
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.16.2
   npm    : 6.14.8

### GIF

![ezgif-5-de48b7383ef0](https://user-images.githubusercontent.com/71231346/93028389-f8f77580-f613-11ea-9fa4-b08345b41e02.gif)

**Comment by Ionitron** [comment] 2020-09-15 22:43
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2020-10-16 00:17
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2020-10-16 00:17 UTC
Labels: needs reply, needs reproduction
