### ISSUE TITLE
[Feature] web: Camera.getPhoto open file explorer 

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#1973] opened 2019-09-18 07:55 UTC
I'm not sure if the Capacitor-Team is even interest to support a web fallback to test things with `ionic --serve`in the browser but it would be cool if `Camera.getPhoto` opens the file explorer and let me choose a photo from my computer instead of "natively opens the camera". So I can test the implementation in my app before testing it on my device.

**Comment by kayneth** [comment] 2019-09-18 18:26
Hi @muuvmuuv !

I think you might be interested by [this PR about using file input](https://github.com/ionic-team/capacitor/pull/1856). 😄

**Comment by jcesarmobile** [comment] 2020-01-13 16:39
closing as duplicate of https://github.com/ionic-team/capacitor/issues/490

**Closed by jcesarmobile** 2020-01-13 16:39 UTC
