### ISSUE TITLE
feat: Support disabling ALL logs (even Native function calls.)

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/capacitor#4295] opened 2021-03-04 17:23 UTC
### Capacitor Version

```
sharktop:topdecked-unified lincoln$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.6
  @capacitor/core: 3.0.0-beta.6
  @capacitor/android: 3.0.0-beta.6
  @capacitor/ios: 3.0.0-beta.6

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Capacitor 3.x (Native, iOS, Android)

### Current Behavior

It is currently not possible to hide the Capacitor native plugin logs:

![image](https://user-images.githubusercontent.com/362329/110003372-4eb7fb00-7ce4-11eb-82c4-31711c6f21da.png)

### Expected Behavior

This should be controlled by the "hideLogs: true" config setting.

### Code Reproduction

N/A

### Other Technical Details

N/A
### Additional Context

N/A

**Comment by jcesarmobile** [comment] 2021-03-04 17:32
duplicate of https://github.com/ionic-team/capacitor/issues/3723

**Closed by jcesarmobile** 2021-03-04 17:32 UTC
Labels: platform: android, platform: ios
