### ISSUE TITLE
Can't build clean project with gradle

### ISSUE THREAD

**Issue by thesayyn** [ionic-team/capacitor#785] opened 2018-09-01 11:04 UTC
## Environment
OS: **Mac OS Sierra & Windows 10** _(tried with both)_
Capacitor: **1.0.0-beta7**
Platform: **Android**

## Current behavior
Can't build clean project

## Expected behavior
I should be able to build

## Steps to Reproduce
1. Create a **capacitor project**
2. Create a **capacitor plugin**
3. Install the plugin into project
4. Run "**cap add android**"
4. Change directory to android (cd android) at root project
5. Run "gradle assemble" then fail

**Error message**
`**$ gradle assemble**
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :app
google-services.json not found, google-services plugin not applied. Push Notifications won't work
Download https://dl.bintray.com/ionic-team/capacitor/ionic-team/capacitor-android/maven-metadata.xml

> Task :capacitor-android:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :capacitor-android:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-mdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxxhdpi-v4\abc_scrubber_control_to_pressed_mtrl_000.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-mdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-mdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-hdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxxhdpi-v4\abc_scrubber_control_to_pressed_mtrl_005.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\common_google_signin_btn_text_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-hdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-hdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-mdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-mdpi-v4\common_google_signin_btn_text_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-hdpi-v4\common_google_signin_btn_text_light_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_normal_background.9.png: error: file not found.
C:\Users\scope\Documents\capacitor projects\capacitor-inapppurchase-example\node_modules\capacitor-inapppurchase\android\capacitor-inapppurchase\build\intermediates\res\merged\release\drawable-xxhdpi-v4\common_google_signin_btn_text_dark_normal_background.9.png: error: file not found.

> Task :capacitor-inapppurchase:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-inapppurchase:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BU¦LD FAILED in 2m 18s
154 actionable tasks: 154 executed
`

**Comment by jcesarmobile** [comment] 2018-09-01 11:32
Can you provide the plugin you are developing?

**Comment by thesayyn** [comment] 2018-09-01 11:36
It's a plugin generated with cli, I didn't changed anything inside it

**Comment by thesayyn** [comment] 2018-09-01 12:04
there are something i can't understand why capacitor needs google-services in android platform ?

https://github.com/ionic-team/capacitor/blob/master/android-template/build.gradle#L11

**Comment by jcesarmobile** [comment] 2018-09-01 14:00
It needs it for Push notifications. 
You can see this message at the beginning:
> google-services.json not found, google-services plugin not applied. Push Notifications won't work

**Comment by thesayyn** [comment] 2018-09-01 14:05
What if I don't prove it

**Comment by jcesarmobile** [comment] 2018-09-01 14:08
Then it doesn't apply the google-services plugin
https://github.com/ionic-team/capacitor/blob/master/android-template/app/build.gradle#L48

**Comment by thesayyn** [comment] 2018-09-01 14:15
so what is the solution? am i missing something?

**Comment by solojuve1897** [comment] 2018-09-02 07:11
Did you do a build (npm run build) and then "npx cap sync"? Best is to then after all that do "npx cap open android" so that it automatically opens Android Studio in the correct directory.

**Comment by thesayyn** [comment] 2018-09-02 10:56
build succeeded with android studio; but the error still persist on gradle build

**Comment by jcesarmobile** [comment] 2018-09-18 17:46
I was having a different problem, but maybe my solution works for you.

Try changing the `implementation 'ionic-team:capacitor-android:1+'` from the plugin's build.gradle to `implementation project(':capacitor-android')`

**Comment by jcesarmobile** [comment] 2018-10-10 18:50
Going to close this as I was able to build with gradle with the change I mentioned.
My problem was caused by using different versions of capacitor on the plugin and the project as the 1+ doesn't work very well while in alpha/beta, should probably change once we release the final version.

**Closed by jcesarmobile** 2018-10-10 18:50 UTC
