### ISSUE TITLE
bug: "cap add ios" inside a lerna package generates broken Podfile since v4

### ISSUE THREAD

**Issue by mjwvb** [ionic-team/capacitor#6040] opened 2022-10-30 22:06 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0
```

### Current Behavior

When I run `npx cap add ios` in any added lerna package, I run into the following error:

```
[error] 
        [!] Invalid `Podfile` file: cannot load such file --
        (...)/packages/template2/node_modules/@capacitor/ios/scripts/pods_helpers.
        
        #  from (...)/packages/template2/ios/App/Podfile:1
        #  -------------------------------------------
        >  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
        #
        #  -------------------------------------------
```

Since capacitor ^4.0.0 the Podfile has this first line:

`require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'`

However in my lerna monorepo configuration, my capacitor node_modules packages are located further up in the tree. It works when I change the first line to the correct path:

`require_relative '../../../../node_modules/@capacitor/ios/scripts/pods_helpers'`

Important to note that other paths in the Podfile are actually correct. See the fully generated Podfile:

```
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end

```

### Expected Behavior

The first line of the Podfile should point to the correct node_modules folder when inside a Lerna package

### Code Reproduction

```
mkdir test
cd test
npx lerna init
cd packages
npm init @capacitor/app
cd app
npm install @capacitor/ios
npm run build
npx cap add ios
```

Result:

```
➜  app git:(main) ✗ npx cap add ios
✔ Adding native Xcode project in ios in 20.67ms
✔ add in 21.16ms
✔ Copying web assets from dist to ios/App/App/public in 4.69ms
✔ Creating capacitor.config.json in ios/App/App in 263.67μs
✔ copy ios in 10.89ms
✔ Updating iOS plugins in 524.17μs
[info] Found 2 Capacitor plugins for ios:
       @capacitor/camera@4.1.3
       @capacitor/splash-screen@4.1.1
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] 
        [!] Invalid `Podfile` file: cannot load such file --
        (...)/test/packages/app/node_modules/@capacitor/ios/scripts/pods_helpers.
        
        #  from (...)/test/packages/app/ios/App/Podfile:1
        #  -------------------------------------------
        >  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
        #
        #  -------------------------------------------
```

### Other Technical Details

`npm --version` output: 8.12.1

`node --version` output: v14.19.3

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Suggestion to fix:

File: `cli/src/ios/update.ts`
@ async function generatePodFile()

This function changes the Capacitor and CapacitorCordova paths to the correct node_modules folder. I'm not sure what happens in this file, but I'd suggest to make updates to the first line of the Podfile here as well.

**Comment by jcesarmobile** [comment] 2022-10-31 09:29
This is a duplicate of https://github.com/ionic-team/capacitor/issues/5903

As workaround you can manually change the path to adjust it to your needs since the file is not being updated on sync/copy/update commands.

**Closed by jcesarmobile** 2022-10-31 09:29 UTC
