### ISSUE TITLE
[Bug]: Locally stored videos cannot be played back on a real iOS device

### ISSUE THREAD

**Issue by benmarsh** [ionic-team/capacitor#7258] opened 2024-02-15 12:26 UTC
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/ios: 5.7.0

[success] iOS looking great! 👌

### Other API Details

```Shell
iOS 17.3.0

npm 10.2.3
node 21.2.0
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Locally stored video cannot be played back on a real iOS device. 

### Expected Behavior

The video should play!

### Project Reproduction

https://github.com/benmarsh/video-test

### Additional Information

First thing to note is that this does not occur in the iOS Simulator, or locally in a browser during development.

Build and run the above demo app on a real iOS device - mine was on version 17.3.0 at the time of testing.

Steps to reproduce:

1. Download the above repo.
2. Install dependencies.
3. `npm run build`
4. `npx cap sync`
5. Open Xcode and run the app on a real device.

The demo app has two tabs, Tab 1 has the video tag configured like this:

`<video src="assets/flower.mp4" loop muted playsinline autoplay poster="assets/flower.jpg"></video>`

The poster image briefly shows, then the video fails to display.

Tab 2 has a different method where the page reads the video file in then converts it to a dataUrl and attaches it to the video tag. This works - and as such proves the video is playable, but not via the standard src="..." method as on Tab 1.

Appears to be connected to when the capacitor:// protocol is used to access files, as this doesn't occur when running in debug via for example `npx ionic capacitor run ios -l --external --open` - in this instance the video requests are using http:// instead, which doesn't seem to be affected. 

Has been mentioned previously in https://github.com/ionic-team/capacitor/issues/7066 / https://github.com/ionic-team/capacitor/issues/6790 / https://github.com/ionic-team/capacitor/issues/6622 

Attaching Safari to the app and looking at the network requests, we see the following...
<img width="1135" alt="Screenshot 2024-02-15 at 11 26 50" src="https://github.com/ionic-team/capacitor/assets/150741/0adff148-246f-4e96-be0b-8e41c127f0d3">
<img width="1135" alt="Screenshot 2024-02-15 at 11 26 52" src="https://github.com/ionic-team/capacitor/assets/150741/a18718c7-4c63-49e6-90b2-9cd61202c5fe">
<img width="1135" alt="Screenshot 2024-02-15 at 11 26 55" src="https://github.com/ionic-team/capacitor/assets/150741/b7f9331b-ace3-4a51-b308-04d21bef2f35">
<img width="1135" alt="Screenshot 2024-02-15 at 11 26 57" src="https://github.com/ionic-team/capacitor/assets/150741/4d3e112a-9d88-44ef-88b0-b86380321780">
<img width="1135" alt="Screenshot 2024-02-15 at 11 26 59" src="https://github.com/ionic-team/capacitor/assets/150741/201dbf2f-6518-4377-8417-42905cf54323">
<img width="1135" alt="Screenshot 2024-02-15 at 11 27 01" src="https://github.com/ionic-team/capacitor/assets/150741/c1bb94ca-6b52-4a30-96f2-7f34a92c928b">
<img width="1135" alt="Screenshot 2024-02-15 at 11 27 05" src="https://github.com/ionic-team/capacitor/assets/150741/a011ae11-186d-4fb5-b423-95a165948450">
<img width="1135" alt="Screenshot 2024-02-15 at 11 27 06" src="https://github.com/ionic-team/capacitor/assets/150741/c05aaf81-47f4-4ed9-ad71-e064887c8dfe">

Short video of this too:
https://github.com/ionic-team/capacitor/assets/150741/dc25becb-bb3a-4eb8-b68e-2cfbab04c34f

Possibly this is a WebKit thing as we have built apps which have gone to production and are using video tags to show videos, and they worked fine when they were built. I can't put a date on exactly when we noticed this become an issue but perhaps some point over the last 6 months? Hope the above is enough to track down a solution. Thanks.

**Comment by jbgtmartin** [comment] 2024-02-22 09:12
Hi, if this is the same issue as https://github.com/ionic-team/capacitor/issues/7066, it might be fixed since iOS 17.4 beta 3 (see [my comment](https://github.com/ionic-team/capacitor/issues/7066#issuecomment-1959004154) on the other issue). Are you able to check if it works on your device?

**Comment by markemer** [comment] 2024-02-23 16:26
In the past this was an apple bug, and it appears it may be still. Does it work on the latest 17.4 beta?

**Comment by benmarsh** [comment] 2024-02-28 11:47
So just an update on this - I have iOS 17.3.1 installed now on my iPhone 14 and the src="..." based video now plays automatically.

@jbgtmartin I don't have beta versions installed on a real device so can't test against that, but maybe this is now fixed going forwards...

**Comment by jcesarmobile** [comment] 2024-03-15 17:00
This is a know apple bug, they seem to have fixed it on iOS 17.4, but they have fixed it several times already and got broken again.
Closing since it's not a Capacitor bug and it's a duplicate of https://github.com/ionic-team/capacitor/issues/7066

**Closed by jcesarmobile** 2024-03-15 17:00 UTC
Labels: triage
