### ISSUE TITLE
Network plugin is declared working for PWA but does not run in ionic serve

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#591] opened 2018-06-19 10:02 UTC
If we run our app with `ionic serve` and check if the `Network` plugin is available it returns false.

const isNetworkAvailable = Capacitor.isPluginAvailable('Network');

Having a look to Network documentation https://capacitor.ionicframework.com/docs/apis/network/ it seems it is working for **pwa**, **ios**, **android** and **electron**. 
So why we can not use plugins working for **pwa** on `ionic serve` and so also in simple browser app which should be pretty the same thing. Right?
`@ionic-native/network` 4.7 for example is working as expected on all browser environments (not with the same result but it is working, `chrome 65` for example now supports connection.type)

**Comment by jcesarmobile** [comment] 2018-06-19 10:07
Closing as duplicate of #534

**Closed by jcesarmobile** 2018-06-19 10:07 UTC
