### ISSUE TITLE
Bug: Network status change not updating the network connection type

### ISSUE THREAD

**Issue by Abhi0725** [ionic-team/capacitor#3738] opened 2020-10-28 15:42 UTC
## Bug Report

I am using Network plugin to detect when the user switches network from mobile data to Wi-Fi.

```
let handler = Network.addListener('networkStatusChange', (status) => {
  console.log("Network status changed", status);
});
```

In the above code, the connected value of status is updated if I switch on/off internet but the connectionType value doesn't update.

For e.g if I am on mobile data and switch to Wi-Fi it continues showing the connectionType as "4g".

### Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊



Latest Dependencies:

  @capacitor/cli: 2.4.2

  @capacitor/core: 2.4.2

  @capacitor/android: 2.4.2

  @capacitor/electron: 2.4.2

  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/android 2.2.0

  @capacitor/ios 2.4.1

[success] Android looking great! 👌
  Found 24 Capacitor plugins for ios:
    @capacitor-community/sqlite (2.4.1-1)
    com-sarriaroman-photoviewer (1.2.5)
    cordova-clipboard (1.3.0)
    cordova-plugin-android-permissions (1.0.2)
    cordova-plugin-androidx-adapter (1.1.1)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-camera (5.0.0)
    cordova-plugin-email-composer (0.9.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-inappbrowser (4.0.0)
    cordova-plugin-insomnia (4.3.0)
    cordova-plugin-ionic-webview (5.0.0)
    cordova-plugin-local-notification (0.9.0-beta.2)
    cordova-plugin-media-capture (3.0.3)
    cordova-plugin-network-information (2.0.2)
    cordova-plugin-streaming-media (2.3.0)
    cordova-plugin-video-editor (1.1.3)
    cordova-sms-plugin (1.0.0)
    cordova-plugin-device (2.0.2)
    cordova-plugin-ionic-keyboard (2.2.0)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.3)
[success] iOS looking great! 👌
```

### Platform(s)
Android and iOS both.

### Current Behavior

Register the event:

```
let handler = Network.addListener('networkStatusChange', (status) => {
  console.log("Network status changed", status);
});
```

Run the app with mobile data, the connectionType should show as "4g" (3g depending on your network). Then switch to Wi-Fi without killing the app, the network connectionType value remains the same.

### Expected Behavior

The connectionType value should get updated to the current network.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v10.15.3

`pod --version` output (iOS issues only): 1.9.3

### Additional Context

I have tried adding a timeout too (seeing this from ionic cordova's network plugin) but no effect.

**Comment by Ionitron** [comment] 2021-03-12 15:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-04-12 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-04-12 00:06 UTC
Labels: needs reply, needs reproduction, platform: android, platform: ios
