### ISSUE TITLE
bug: Using Capacitor Plugins with WebWorkers for Android app

### ISSUE THREAD

**Issue by fegauthier** [ionic-team/capacitor#6309] opened 2023-02-20 01:30 UTC
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
```

### Platform(s)

Android

### Current Behavior

I'm using the capacitor plugin SQLite and my own capacitor plugin. Everything is working fine. I want to use capacitor plugins in Web Worker but it doesn't work at all. No call is reaching Android Native.

### Expected Behavior

Capacitor plugins should be able to be reached in Web Workers too.

### Code Reproduction

This is my worker code. As I mentioned, this code work outside of a Web Worker.

```
import CategoriesTable from "@/databases/categories.table";
import ConfigTable from "@/databases/config.table";
import { StalkerPortal } from "stalker-portal-capacitor";
import moment from 'moment';
import Promise from 'bluebird';

onmessage = (event) => {
  if(event.data.message === 'start') {
    getCategories(event.data.data);
  }
}

const getCategories = async (data: any) => {
  let theCategories = [];
  //await ConfigTable.deleteByName('LAST_SYNC_CATEGORIES')
  const lastSync = await ConfigTable.findByName('LAST_SYNC_CATEGORIES');
    
    if(!lastSync) {
      await CategoriesTable.truncate();
      const categoriesString: string = (await StalkerPortal.getCategories({ 
        headers: {},
        cookies: { 
          mac: data.mac, 
          timezone: data.timezone
        },
        data: {
          baseURL: data.portal
        }
      })).value;
      theCategories = JSON.parse(categoriesString).js;
      theCategories.unshift(
        {
          id: 'FAVOURITE',
          title: 'Favourite'
        }
      );
      postMessage({ 
        message: 'progress', 
        data: { 
          total: theCategories.length,
          current: 0,
          step: 'FETCHING_CATEGORIES'
        }
      });
      await Promise.each(theCategories, async (category: any, index: number) => {
        await CategoriesTable.insert(category.id, category.title);
        postMessage({ 
          message: 'progress', 
          data: { 
            current: index + 1,
          }
        })
      });
      await ConfigTable.insertOrReplace('LAST_SYNC_CATEGORIES', moment().format('YYYY-MM-DD HH:mm:ss'));
    }
    
    postMessage({ 
      message: 'progress', 
      data: { 
        total: theCategories.length,
        current: 0,
        step: 'PROCESSING_CATEGRORIES'
      }
    });
    theCategories = await CategoriesTable.getAll();
    postMessage({ message: 'complete', data: theCategories });
}

```

### Other Technical Details

`npm --version` output: 9.3.1

`node --version` output: v18.13.0

`pod --version` output (iOS issues only):

### Additional Context

I tried the hack about putting `(<any> self).window = self;` at the top of my worker's file but it doesnt' work.

Thanks

**Comment by Ionitron** [comment] 2023-02-22 18:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by fegauthier** [comment] 2023-02-28 13:25
Hi guys!

This is my own custom plugin.

[StalkerPortalCapacitor.zip](https://github.com/ionic-team/capacitor/files/10850686/StalkerPortalCapacitor.zip)

I currently have a Ionic Framework project that use this plugin and it works perfectly. I need to do a lot of calls to my plugin, so I wanted to let web workers doing this kind of job. So I created a Web Worker script that is using my capacitor plugin. I don't know if Capacitor support Web Worker, but when I call my plugin inside the Web Worker plugin, it's like my plugin is null.

This is my web worker script

```
import CategoriesTable from "@/databases/categories.table";
import ConfigTable from "@/databases/config.table";
import { StalkerPortal } from "stalker-portal-capacitor";
import moment from 'moment';
import Promise from 'bluebird';

onmessage = (event) => {
  if(event.data.message === 'start') {
    getCategories(event.data.data);
  }
}

const getCategories = async (data: any) => {
  let theCategories = [];
  //await ConfigTable.deleteByName('LAST_SYNC_CATEGORIES')
  const lastSync = await ConfigTable.findByName('LAST_SYNC_CATEGORIES');
    
    if(!lastSync) {
      await CategoriesTable.truncate();
      const categoriesString: string = (await StalkerPortal.getCategories({ 
        headers: {},
        cookies: { 
          mac: data.mac, 
          timezone: data.timezone
        },
        data: {
          baseURL: data.portal
        }
      })).value;
      theCategories = JSON.parse(categoriesString).js;
      theCategories.unshift(
        {
          id: 'FAVOURITE',
          title: 'Favourite'
        }
      );
      postMessage({ 
        message: 'progress', 
        data: { 
          total: theCategories.length,
          current: 0,
          step: 'FETCHING_CATEGORIES'
        }
      });
      await Promise.each(theCategories, async (category: any, index: number) => {
        await CategoriesTable.insert(category.id, category.title);
        postMessage({ 
          message: 'progress', 
          data: { 
            current: index + 1,
          }
        })
      });
      await ConfigTable.insertOrReplace('LAST_SYNC_CATEGORIES', moment().format('YYYY-MM-DD HH:mm:ss'));
    }
    
    postMessage({ 
      message: 'progress', 
      data: { 
        total: theCategories.length,
        current: 0,
        step: 'PROCESSING_CATEGRORIES'
      }
    });
    theCategories = await CategoriesTable.getAll();
    postMessage({ message: 'complete', data: theCategories });
}

```

**Comment by fegauthier** [comment] 2023-02-28 16:20
The problem is when I use WebWorkers, the platform detected by the framework is Web and not Android. Is it the normal behaviour ?

**Comment by tachibana-shin** [comment] 2023-03-14 08:08
> The problem is when I use WebWorkers, the platform detected by the framework is Web and not Android. Is it the normal behaviour ?

I had this problem in the past because the capacitor's code didn't inject their apis into the webworker so the only solution was to use the main thread as intermediate sending requests to the main thread and the main thread calling the capacitor.
I use plugin [@fcanvas/communicate](https://www.npmjs.com/package/@fcanvas/communicate) to solve my problem

**Comment by tachibana-shin** [comment] 2023-03-14 08:28
there is no indication that this bug will be of concern as the capacitor pool is gathering for `capacitor@5.x` so those who have problems can use this patch to temporarily fix the problem:

```ts
import type { CopyOptions, CopyResult } from "@capacitor/filesystem"
import { Filesystem } from "@capacitor/filesystem"

function resolve(path: string): string {
  const posix = path.split("/").filter((item) => item !== ".")
  const newPosix: string[] = []

  posix.forEach((item) => {
    if (
      item === ".." &&
      newPosix.length > 0 &&
      newPosix[newPosix.length - 1] !== ".."
    ) {
      newPosix.pop()
    } else {
      newPosix.push(item)
    }
  })

  return newPosix.join("/")
}
function isPathParent(parent: string, children: string): boolean {
  parent = resolve(parent)
  children = resolve(children)
  const pathsA = parent.split("/")
  const pathsB = children.split("/")

  return (
    parent !== children &&
    pathsA.every((value, index) => value === pathsB[index])
  )
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
;(Filesystem as unknown as any)._copy = async function copy(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  this: any,
  options: CopyOptions,
  doRename = false
): Promise<CopyResult> {
  // eslint-disable-next-line functional/no-let
  let { toDirectory } = options
  const { to, from, directory: fromDirectory } = options

  if (!to || !from) {
    throw Error("Both to and from must be provided")
  }

  // If no "to" directory is provided, use the "from" directory
  if (!toDirectory) {
    toDirectory = fromDirectory
  }

  const fromPath = this.getPath(fromDirectory, from)
  const toPath = this.getPath(toDirectory, to)

  // Test that the "to" and "from" locations are different
  if (fromPath === toPath) {
    return {
      uri: toPath,
    }
  }

  if (isPathParent(fromPath, toPath)) {
    throw Error("To path cannot contain the from path")
  }

  // Check the state of the "to" location
  // eslint-disable-next-line functional/no-let
  let toObj
  try {
    toObj = await this.stat({
      path: to,
      directory: toDirectory,
    })
  } catch (e) {
    // To location does not exist, ensure the directory containing "to" location exists and is a directory
    const toPathComponents = to.split("/")
    toPathComponents.pop()
    const toPath = toPathComponents.join("/")

    // Check the containing directory of the "to" location exists
    if (toPathComponents.length > 0) {
      const toParentDirectory = await this.stat({
        path: toPath,
        directory: toDirectory,
      })

      if (toParentDirectory.type !== "directory") {
        throw new Error("Parent directory of the to path is a file")
      }
    }
  }

  // Cannot overwrite a directory
  if (toObj && toObj.type === "directory") {
    throw new Error("Cannot overwrite a directory with a file")
  }

  // Ensure the "from" object exists
  const fromObj = await this.stat({
    path: from,
    directory: fromDirectory,
  })

  // Set the mtime/ctime of the supplied path
  const updateTime = async (path: string, ctime: number, mtime: number) => {
    const fullPath: string = this.getPath(toDirectory, path)
    const entry = await this.dbRequest("get", [fullPath])
    entry.ctime = ctime
    entry.mtime = mtime
    await this.dbRequest("put", [entry])
  }

  const ctime = fromObj.ctime ? fromObj.ctime : Date.now()

  switch (fromObj.type) {
    // The "from" object is a file
    case "file": {
      // Read the file
      const file = await this.readFile({
        path: from,
        directory: fromDirectory,
      })

      // Optionally remove the file
      if (doRename) {
        await this.deleteFile({
          path: from,
          directory: fromDirectory,
        })
      }

      // Write the file to the new location
      const writeResult = await this.writeFile({
        path: to,
        directory: toDirectory,
        data: file.data,
      })

      // Copy the mtime/ctime of a renamed file
      if (doRename) {
        await updateTime(to, ctime, fromObj.mtime)
      }

      // Resolve promise
      return writeResult
    }
    case "directory": {
      if (toObj) {
        throw Error("Cannot move a directory over an existing object")
      }

      try {
        // Create the to directory
        await this.mkdir({
          path: to,
          directory: toDirectory,
          recursive: false,
        })

        // Copy the mtime/ctime of a renamed directory
        if (doRename) {
          await updateTime(to, ctime, fromObj.mtime)
        }
      } catch (e) {
        // ignore
      }

      // Iterate over the contents of the from location
      const contents = (
        await this.readdir({
          path: from,
          directory: fromDirectory,
        })
      ).files

      // eslint-disable-next-line functional/no-loop-statements
      for (const filename of contents) {
        // Move item from the from directory to the to directory
        await this._copy(
          {
            from: `${from}/${filename.name}`,
            to: `${to}/${filename.name}`,
            directory: fromDirectory,
            toDirectory,
          },
          doRename
        )
      }

      // Optionally remove the original from directory
      if (doRename) {
        await this.rmdir({
          path: from,
          directory: fromDirectory,
        })
      }
    }
  }
  return {
    uri: toPath,
  }
}
```

**Comment by jcesarmobile** [comment] 2024-03-21 15:56
Closing since no sample app was provided and the provided plugin is not enough to reproduce.

Capacitor 6 will inject the plugin's javascript into the WebView, so that might have fixed the issue.

If not, please, create a new issue and provide a sample app where the issue can be reproduced.

**Closed by jcesarmobile** 2024-03-21 15:56 UTC
Labels: platform: android, needs reproduction
