### ISSUE TITLE
bug: Uncaught TypeError: alertCtrl.create is not a function

### ISSUE THREAD

**Issue by ManjunathHebballi** [ionic-team/capacitor#3711] opened 2020-10-21 13:19 UTC
### Capacitor Version
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Badari\AppData\Roaming\npm-cache\_npx\10880\node_modules\cap
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Badari\AppData\Roaming\npm-cache\_logs\2020-10-21T13_02_55_493Z-debug.log
Install for [ 'cap@latest' ] failed with code 1

```
in console:
Uncaught TypeError: alertCtrl.create is not a function
    at HTMLElement.<anonymous> (app.js:21)
(anonymous) @ app.js:21
```

**[Index.html](https://github.com/ManjunathHebballi/ionic/blob/main/index.html)**

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project</title>
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"/>
    
</head>
<body>
    <ion-app>
    <ion-header>
        <ion-toolbar color="primary">
            <ion-title>Budget Planner</ion-title>
        </ion-toolbar>
    </ion-header>

<ion-content>
  <ion-grid>
      <ion-row>
          <ion-col size-md="6" offset-md="3">
            <ion-card>
                <ion-card-header>
                    <ion-card-title>New Expense</ion-card-title>
                </ion-card-header>
                <ion-card-content>
                  <ion-item>
                      <ion-label position="floating">Expense Reason</ion-label>
                      <ion-input type="text" id="input-reason"></ion-input>
                  </ion-item>
                  <ion-item>
                      <ion-label position="floating">Expense Amount</ion-label>
                      <ion-input type="number" id="input-amount"></ion-input>
                  </ion-item>
                 <div class="ion-margin-vertical ion-text-right">
                  <ion-button color="danger" fill="outline" id="btn-clear">                    
                    <ion-icon slot="start" name="close-outline"></ion-icon>clear
                  </ion-button>
                  <ion-button id="btn-add"><ion-icon slot="start" name="add-circle-outline" ></ion-icon>Add Expense</ion-button>
                  </div>
                </ion-card-content>
            </ion-card>
          </ion-col>
      </ion-row>
      <ion-row>
          <ion-col>
              <ion-list id="expense-list"></ion-list>
          </ion-col>
      </ion-row>
  </ion-grid>
</ion-content>
<ion-alert-controller></ion-alert-controller>
</ion-app>
<script src="app.js"></script>
</body>
</html>

**app.js**
const reasonInput = document.querySelector('#input-reason');
const amountInput = document.querySelector('#input-amount');
const clearBtn = document.querySelector('#btn-clear');
const addBtn = document.querySelector('#btn-add');
const expenseList = document.querySelector('#expense-list');
const alertCtrl = document.querySelector('ion-alert-controller');
const clear = () =>{
    reasonInput.value='';
    amountInput.value='';
};

addBtn.addEventListener('click',() =>{
const enterdReason = reasonInput.value;
const enterdAmount = amountInput.value;

if(enterdReason.trim().length <=0 ||
enterdAmount <=0 ||
enterdAmount.trim().length <=0){
    alertCtrl
    .create({
        message: 'Please enter the valid details',
        header : 'Invalid Input',
        button : ['okay']
    })
    .then(alertElement =>{
        alertElement.present();
    });
    return;
}
const newItem = document.createElement('ion-item');
newItem.textContent = enterdReason + ' : ₹ ' + enterdAmount;
expenseList.appendChild(newItem);
clear();
});

clearBtn.addEventListener('click',clear);

`npm --version` output:
6.14.8
ionic CLI 5.4.16
 NodeJS : v12.19.0

**Comment by jcesarmobile** [comment] 2020-10-21 15:27
closing as invalid, it's not clear what the problem is, it contains multiple unrelated errors and no context, don't include the required information

**Closed by jcesarmobile** 2020-10-21 15:27 UTC

**Comment by ManjunathHebballi** [comment] 2020-10-22 07:31
in app.js i get error as a type error in alertCtrl.create()
its an object error
