### ISSUE TITLE
bug: android app crashes when Webview Version is "Developer Build"

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/capacitor#6781] opened 2023-08-02 08:32 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/ios: 5.2.2
```

### Platform(s)

- Android

### Current Behavior

The app crashes instantly after starting with the given error

### Expected Behavior

Capacitor should handle unknown WebView versions

### Code Reproduction

Personally I'm unable to reproduce this issue on my testing devices but I added the crash reports from our customers.

```log
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.gratisbroker.android.mobileapp/de.gratisbroker.android.mobileapp.MainActivity}: java.lang.NumberFormatException: For input string: "Developer Build"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
```

```log
Caused by java.lang.NumberFormatException: For input string: "Developer Build"
       at java.lang.Integer.parseInt(Integer.java:617)
       at java.lang.Integer.parseInt(Integer.java:656)
       at com.getcapacitor.Bridge.isMinimumWebViewInstalled(Bridge.java:299)
       at com.capacitorjs.plugins.splashscreen.SplashScreenPlugin.load(SplashScreenPlugin.java:21)
       at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
       at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
       at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
       at com.getcapacitor.Bridge.registerPlugin(Bridge.java:638)
       at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:594)
       at com.getcapacitor.Bridge.<init>(Bridge.java:213)
       at com.getcapacitor.Bridge.<init>()
       at com.getcapacitor.Bridge$Builder.create(Bridge.java:1513)
       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
       at de.gratisbroker.android.mobileapp.MainActivity.onCreate(MainActivity.java:35)
       at android.app.Activity.performCreate(Activity.java:7028)
       at android.app.Activity.performCreate(Activity.java:7019)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2748)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
```

### Other Technical Details

`npm --version` output: 9.8.1

`node --version` output: v18.16.1

`pod --version` output (iOS issues only):

### Additional Context

This issue exists since Capacitor v4: #6144

**Comment by jcesarmobile** [comment] 2023-08-02 08:56
It’s a duplicate of the issue you linked, it’s ok to create duplicates if you didn’t find the other issue or you don’t know, but please, don’t create duplicates of issues you already know that exist.

**Closed by jcesarmobile** 2023-08-02 08:56 UTC
Labels: platform: android
