### ISSUE TITLE
notifyListeners in android not work

### ISSUE THREAD

**Issue by JoyZhou007** [ionic-team/capacitor#2801] opened 2020-04-20 12:08 UTC
In latset capacitor ,i generate a android plugin, i try to use notifyListeners methods to send message to my front page, i listened the event in page, but i did not receive the message

    ngAfterViewInit(): void {
       AwesomePlugin.addListener("AwesomePluginStartEvent", (info: any) => {
        console.log("AwesomePluginStartEvent was fired");
      });
      }

    @Override
    protected void handleOnStart() {
        super.handleOnStart();
        System.out.println("AwesomePlugin----start");
      JSObject ret = new JSObject();
      ret.put("value", "some value");
      notifyListeners("myPluginEvent", ret);
        bridge.triggerWindowJSEvent("AwesomePluginStartEvent", "{ 'AwesomePluginStartKey': 'AwesomePluginStartValue' }");
        initAdapter();
    }

**Comment by jcesarmobile** [comment] 2020-04-20 13:06
Templates are there for a reason, don't delete them.
Also for complex issues like this one, provide a full sample app where it can be reproduced. 
I can't reproduce, so closing.
In your "sample" code you are adding a listener for `AwesomePluginStartEvent`, but you notify `myPluginEvent`

**Closed by jcesarmobile** 2020-04-20 13:06 UTC
