### ISSUE TITLE
bug: pushNotificationReceived not called when app in background 

### ISSUE THREAD

**Issue by spennyf** [ionic-team/capacitor#4145] opened 2021-02-03 01:32 UTC
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/core 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/android 2.4.6
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 8 Capacitor plugins for ios:
    cordova-annotated-plugin-android (1.0.4)
    cordova-plugin-apprate (1.7.1)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-inappbrowser (4.1.0)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-purchases (2.0.0)
    cordova-plugin-x-socialsharing (6.0.3)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌

### Platform(s)

iOS

### Current Behavior
I send a push notification from Firebase via the Java API, when my app is running and in the background (has NOT been killed), the push notification arrives on my device but pushNotificationReceived is not called. In the function I am making an API request to a health check API of mine so I can see if it got called. The function gets called when the app is in the foreground. 

### Expected Behavior
When the push notification arrives and the app is in the background (not killed), pushNotificationReceived should be called and exectued.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v14.15.1

`pod --version` output (iOS issues only): 1.10.1

**Comment by jon4ism** [comment] 2021-05-10 08:14
Hii spennyf, you have any news about this issue?

Thanks in advance!!

**Comment by giddens9527** [comment] 2021-07-05 10:37
Yeah, same issue here. Just want to make sure whether pushNotificationReceived should be called with data when app is in background. As a temp solution, I just refreshed the content when app state switched from background to foreground.

**Comment by mitschmidt** [comment] 2021-09-07 14:27
This would be very helpful to e.g. fetch data in background when a push notification is received, so the data can be displayed to the user immediately when foregrounding the app again.

**Comment by Nemesis19** [comment] 2022-06-20 21:33
I'm trying to use this open issue to signal mi problem.

I'm using capacitor over a VueJS PWA. The listeners as provided in the guide are correctly triggered however the pushNotificationReceived listener returns an empty notification. 
```
await PushNotifications.addListener('pushNotificationReceived', notification => {
                alert('Push received:', JSON.stringify(notification));
            });
```
so this is my code, the alert gets displayed but "notification" is empty. I'm trying to send "data" from the firebase console...the notification gets displayed correctly (for now I'm testing only iOS), but when I open the app the problem comes as described. I'm running out of ideas about where to find the problem. Any help or suggestion is appreciated. Thanks!

**Comment by Ionitron** [comment] 2023-03-06 16:12
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-22 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-22 00:04 UTC
Labels: platform: ios, needs reply, needs reproduction
