### ISSUE TITLE
[Bug]: Download file option not working

### ISSUE THREAD

**Issue by vigneshsf3992** [ionic-team/capacitor#7292] opened 2024-02-27 11:06 UTC
### Capacitor Version

  Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/android: 5.7.0
  @capacitor/cli: 5.7.0
  @capacitor/ios: 5.7.0
  @capacitor/core: 5.7.0

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Download file not working

### Expected Behavior

File needs to be downloaded.

### Project Reproduction

React project

### Additional Information

When i use the below code in react project. It's downloading.
When i click the Download button, the file was not downloading in androidstudio using capacitor. 

```<a href="sample.png" download="file">Download</a>```

**Comment by jcesarmobile** [comment] 2024-02-27 11:58
closing as duplicate of https://github.com/ionic-team/capacitor/issues/5478

You can use Filesystem's downloadFile method for downloading files with more control about were to place the files
https://capacitorjs.com/docs/apis/filesystem#downloadfile

**Closed by jcesarmobile** 2024-02-27 11:58 UTC
Labels: triage

**Comment by vigneshsf3992** [comment] 2024-02-27 12:23
Can you please provide simple react component with the mentioned usage?
