### ISSUE TITLE
bug: MalformedURL Exception on specific  http requests, url received is the actual request object

### ISSUE THREAD

**Issue by ReemBD** [ionic-team/capacitor#6227] opened 2023-01-19 11:06 UTC
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[error] munters is missing in /Users/munters/repos/Rotem-Central-App/rotem-central-app/android/app/src/main/java/com.
        Please create a directory structure matching the Package ID com.munters.trioair within the
        /Users/munters/repos/Rotem-Central-App/rotem-central-app/android/app/src/main/java directory.
```

### Platform(s)
Ios,
Android

### Current Behavior
On a particular scenario in my app. HttpRequest is being fired (via CapacitorHttp Plugin).
The request is being sent with a malformed url. Instead of the url value, the request receives the Request instance itself as the value
![image](https://user-images.githubusercontent.com/63240608/213403330-ca1022d6-da8d-4c43-844a-0dfc13c9f459.png)

### Expected Behavior
Expected Url to equal "https://atlas.microsoft.com/styling/styles/road?styleVersion=2022-08-05&api-version=2.0"

### Other Technical Details

`npm --version` output: 6.14.15 

`node --version` output: 14.18.3
### Code Reproduction
Please see this project i made specifically for the bug reproduction.
Please notice that the project is using a third party which requires a subscription key, so the requests are returning 401, but thats not related to the bug.
https://github.com/ReemBD/capacitor-http-bug-reproduction

### Additional Context
I have enabled capacitorHttp in my capacitor config file, like so - 
` plugins: {
    CapacitorHttp: {
      enabled: true
    }
  }`
It is important the note that when the request is being sent via web, it works just fine.
The problem therefore starts when the CapacitorHttp plugin is in the picture.

As you can see from the attached image, for this request the url is handled not well, and instead of the actual url the whole request is being set as the value and thus I receive "MalformedURL Exception" on android and "Unhandled Promise Rejection: DataCloneError: The object can not be cloned." on ios.

The Http request initiator is **azure-maps-control**, a third party node module that is used in our application, and is not an open source project.
I've thought that if CapacitorHttp plugins would somehow allow to use like a hybrid option, where some chosen requests are sent through javascript http clients, perhaps could allow more flexibility with such cases.

**Comment by Ionitron** [comment] 2023-01-19 11:09
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ReemBD** [comment] 2023-01-19 11:18
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

Hey, I am working on trying to create a demo project, but the setup for reproducing this issue is quite difficult.
If it is possible to meanwhile give it attention as is, perhaps someone ran into this issue already and found a creative solution.

**Comment by Ionitron** [comment] 2023-02-04 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-04 00:05 UTC
Labels: platform: android, platform: ios, needs reply, needs reproduction

**Comment by jcesarmobile** [comment] 2023-03-06 18:43
the bot closed the issue despite a sample app was provided in an edit

but I've tested the sample app and I can't reproduce in Capacitor 4.7.0, so it might have been fixed.

Please, if you still face the issue, create a new issue and provide a sample app where it can be reproduced.
