### ISSUE TITLE
bug: downloadFile recursive not working Android

### ISSUE THREAD

**Issue by AEiosApp** [ionic-team/capacitor#7108] opened 2023-11-30 16:38 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1
```

### Platform(s)
Android

### Current Behavior
Getting Error message in response of **Filesystem.downloadFile** while flag **recursive** is **true**:
```
'Error downloading file: /data/user/0/com.ae.tourin…: open failed: ENOENT (No such file or directory)'}
```

<img width="922" alt="Screenshot 2023-11-30 at 11 34 56 AM" src="https://github.com/ionic-team/capacitor/assets/19554725/d1ebc39f-d760-4bfb-89d1-aa8448e2050c">

### Expected Behavior
When I use **Filesystem.downloadFile** to download file to an existing folder everything works fine.

### Other Technical Details

`npm --version` output: 9.8.1

`node --version` output: 18.18.2

### Additional Context
"@capacitor/filesystem": "^5.1.4"

**Comment by jcesarmobile** [comment] 2023-12-01 17:02
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1835

**Closed by jcesarmobile** 2023-12-01 17:02 UTC
Labels: platform: android, needs reply, needs reproduction
