### ISSUE TITLE
bug: Local Notification shown only after app is shown

### ISSUE THREAD

**Issue by daniell0gda** [ionic-team/capacitor#6207] opened 2023-01-09 21:40 UTC
### Capacitor Version

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/core: 4.0.1

### Platform(s)
Android 10, EMUI 12.0.0 

### Current Behavior
1. Schedule notification (not repeating)
2. Minimize App / Close App
3. Wait for notification deadline
4. Notification is not shown
5. Reopen Application
6. Notification is shown

Here is video of this case ( I am sorry its in Polish but it doesn't matter because she says What I wrote )
https://user-images.githubusercontent.com/8320732/211413437-9328c35b-52de-415c-9dcd-933c6b3ca8ce.mp4

### Expected Behavior
Notification is shown without needing to open application.

### Code Reproduction
I am not sure that this will help because this problem occurs only on this phone

### My workaround

In function **setExactIfPossible** :
I've changed  RTC to RTC_WAKEUP

  
`` 

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && !alarmManager.canScheduleExactAlarms()) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && schedule.allowWhileIdle()) {
                alarmManager.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, trigger, pendingIntent);
            } else {
                alarmManager.set(AlarmManager.RTC_WAKEUP, trigger, pendingIntent);
            }
        } else {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && schedule.allowWhileIdle()) {
                alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, trigger, pendingIntent);
            } else {
                alarmManager.setExact(AlarmManager.RTC_WAKEUP, trigger, pendingIntent);
            }
        }
    }``

Can we do something about it ? Another config option  manipulating it ?

**Comment by Ionitron** [comment] 2023-01-10 09:46
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-26 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-26 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
