### ISSUE TITLE
bug: My StatusBar BLINK , after click Input Text 

### ISSUE THREAD

**Issue by bobwatcherx** [ionic-team/capacitor#5644] opened 2022-05-26 10:20 UTC
why the application i build with capacitor js . experiencing fl
![tolol](https://user-images.githubusercontent.com/52072811/170468423-b8536c09-4c36-4c99-9de3-e02b3db39863.gif)

fickering in the status bar

I've added the statusbar of the capacitor

like this :
import { StatusBar, Style } from '@capacitor/status-bar';
StatusBar.setStyle({ style: Style.Dark });

but it's the same

**Comment by Ionitron** [comment] 2023-03-06 16:44
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-22 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-22 00:04 UTC
Labels: needs reply, needs reproduction
