### ISSUE TITLE
Unable to open Android Studio on Ubuntu

### ISSUE THREAD

**Issue by mburger81** [ionic-team/capacitor#588] opened 2018-06-19 07:48 UTC
If we run simple `npx cap open android` on **K/Ubnutu 18.04** we have this output:
```
npx cap open android
[info] Opening Android project at /home/michi/software/workspace/tmp/ionic/ionic4-capacitor/android
```
But at the end there is opened Dolphin (file explorer) instead of Android Studio.

Having a look from this source code https://github.com/ionic-team/capacitor/blob/master/cli/src/android/open.ts the default configuration value should be `config.linux.androidStudioPath`, these value is not configured in `capacitor.config.json` but this seems to open Dolphin and does not fire and exception running the `linuxError` log. If we configure `linuxAndroidStudioPath` in `capacitor.config,json` the android studio installation is opened.

So I think there should be a bug and also I think this should be documented.

thx a lot

**Comment by jcesarmobile** [comment] 2019-04-12 14:23
I can't reproduce, it was probably fixed with https://github.com/ionic-team/capacitor/pull/778

**Closed by jcesarmobile** 2019-04-12 14:23 UTC
Labels: cli
