### ISSUE TITLE
bug: Basic ionic start myApp tabs --capacitor --type react with electron - shows ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by john-aldridge** [ionic-team/capacitor#2103] opened 2019-10-27 03:34 UTC
# Bug Report

##  - @capacitor/electron": "^1.3.0" / "@capacitor/core": "1.3.0",
I am brand new to ionic and I just tried to create a new ionic app with electron support by running 'ionic start myApp tabs --capacitor --type react' and then I did 'ionic build' and then 'npx cap add electron', 'npx cap copy', and finally 'npx cap open electron' but all I see is a blank screen with the error message that some of the chunked css and js files couldn't be found. Am I doing something wrong?  Thanks!

`npx cap doctor` output:
➜  myApp git:(master) ✗ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/ios not installed

  @capacitor/cli 1.3.0

  @capacitor/core 1.3.0

[fatal] Platform electron is not valid.

## Affected Platform(s)
- [ ] Android
- [ ] iOS
- [x] Electron
- [ ] Web

## Current Behavior
'npx cap open electron' but all I see is a blank screen with the error message that some of the chunked css and js files couldn't be found.
<img width="1604" alt="Screen Shot 2019-10-25 at 5 15 35 PM" src="https://user-images.githubusercontent.com/5142642/67629159-1b37a780-f838-11e9-9b84-6b5a21ee7dc5.png">

## Expected Behavior
I expect to see the sample tabs app.

## Other Technical Details

`npm --version` output: 6.11.3

`node --version` output: v12.8.0

-

**Comment by ShinZ6** [comment] 2019-10-31 15:56
Same thing happening to me

**Comment by Rotho98** [comment] 2019-11-26 21:59
I am getting the same error

**Comment by irishabh96** [comment] 2019-12-04 17:02
Getting the same issue

**Comment by jcesarmobile** [comment] 2020-01-17 11:51
electron apps are served from file protocol, so they need to be built in a different way.
I've made it work by adding `"homepage": "."` in the `package.json` and removing the `<base href="/" />`  in `index.html` or changing it to `<base href="%PUBLIC_URL%/">`

The problem is the same as https://github.com/ionic-team/capacitor/issues/639, closing.

**Closed by jcesarmobile** 2020-01-17 11:51 UTC

**Comment by evalsxonted** [comment] 2020-06-08 14:55
same for me, adding `"homepage": "."` in the `package.json` and removing to `<base href="/"/>` does fix all loading error messages but electron still show nothing but empty screen.
for me it looks like electron could load `index.tsx` file but couldnt load `app.tsx`  since i could display **"HOLA"** in electron app screen by changing this line `ReactDOM.render(<App />, document.getElementById('root'));`
from `index.tsx` to `ReactDOM.render(<div>HOLA</div>, document.getElementById('root'));`
