### ISSUE TITLE
bug: iOS 16 layout is lag and black out happens randomly

### ISSUE THREAD

**Issue by dodomui** [ionic-team/capacitor#5968] opened 2022-10-02 13:25 UTC
### Capacitor Version

```
PASTE OUTPUT HERE
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)

iOS

### Current Behavior

After upgrade to iOS 16, the App layout is lagging and it happens black out on parts of the screen randomly.
It could be solved by waiting and sometime it need to leave and reenter the view only can display the layout properly.

### Expected Behavior

The app is working just fine since Capacitor 2. But after upgrade of iOS 16.0 / 16.0.2, everything went wrong.
It should works as other iOS version or platform. Which no lagging of layout and no black out happens.

### Other Technical Details

`npm --version` output:
8.19.2
`node --version` output:
v18.4.0
`pod --version` output (iOS issues only):
1.11.3

**Comment by Ionitron** [comment] 2022-10-03 08:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-10-19 00:11
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-19 00:11 UTC
Labels: platform: ios, needs reply, needs reproduction
