### ISSUE TITLE
bug: Capacitor 3 iOS splashscreen white flicker

### ISSUE THREAD

**Issue by Exocomp** [ionic-team/capacitor#4702] opened 2021-06-08 19:04 UTC
Use capacitor 3.0.0 with a custom splash screen (use cordova-res, ex: cordova-res ios --skip-config --copy).

Launch the app on the physical device (not simulator), first the custom image is displayed then a brief white flash then the custom image is displayed.

The issue being the white flash which should not be there as it is distracting and bad user experience.

**NOTE**: this issue existed in prior versions and was fixed, see the following for hints on how to fix it:

- https://github.com/ionic-team/capacitor/pull/2933
- https://forum.ionicframework.com/t/background-flickering-on-startup/188364
- https://github.com/ionic-team/capacitor/issues/3601

**Comment by Ionitron** [comment] 2021-06-09 07:34
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-25 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-25 00:02 UTC
Labels: needs reply, needs reproduction
