### ISSUE TITLE
feat: EOL CRLF on windows platform

### ISSUE THREAD

**Issue by kerosin** [ionic-team/capacitor#3402] opened 2020-08-10 08:17 UTC
### Description

After executing `npx cap sync` several files are changed. Some files change their EOF type from CRLF to LF on Windows. This regularly generates unwanted changes to local files.

### Platform(s)

CLI

### Preferred Solution

- set EOL to CRLF (`\r\n`) on Windows machines and default would be LF (`\n`)

### Alternatives

- alternatively make it configurable which EOL is wished (e.g. `capacitor.config.json`) instead of deciding it based on the OS

**Comment by dwieeb** [comment] 2020-09-16 21:55
@kerosin I'm not really seeing this on Windows. Could you provide a code reproduction?

**Comment by Ionitron** [comment] 2020-09-16 21:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2020-10-17 00:16
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2020-10-17 00:16 UTC
Labels: cli, needs attention, needs reply, needs reproduction

**Comment by visant** [comment] 2021-01-08 10:08
Hi,
I have noticed the same issue on a brand new app created from the ionic cli default template.
You need to be under windows, git configured with core.autocrlf=true, and vs code set for CRLF.
After running a ionic cap build, git changes will show few files (config.xml on each platform,  capacitor.config.json) whereas no difference is visible by a human eye.
We can see in vscode in the status bar that the encoding of eol are now LF while all other ones are CRLF.

There are 2 options:
- the eol  used by capacitor file generator scripts is configurable (using by default os default one)
- as a developer, I need to change my git settings and vs code settings to be always in LF  even in windows (which could cause issue if a developer does not set properly any of them or use some editors not set properly as well)

Thank you
