### ISSUE TITLE
bug: ios cookies not applied

### ISSUE THREAD

**Issue by bazuka5801** [ionic-team/capacitor#5293] opened 2021-12-04 01:58 UTC
## Bug Report
Hi!)
I get cookies from the server
![image](https://user-images.githubusercontent.com/11452353/144692607-9357961a-e04c-48ba-ac98-eae921d253b8.png)

They should be automatically set for the next request, but what do we see? - We don't see any.
![image](https://user-images.githubusercontent.com/11452353/144692659-dad3c5b7-041c-4ada-b921-a1404807604c.png)

How we can fix this problem?

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2
  @capacitor/cli: 3.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

```
PASTE OUTPUT HERE
```

### Platform(s)
iOS 15

### Current Behavior
Cookies not applied to the next request

### Expected Behavior
Next request (video stream) should be with cookies

**Comment by thomasvidas** [comment] 2021-12-04 04:21
This is a long standing issue with Capacitor. We're aware of the problem and still not sure the best way to solve this since Capacitor does not have a synchronous communication method to the native layer and the document.cookie API is synchronous. Closing this in favor of [#1373](https://github.com/ionic-team/capacitor/issues/1373). Just because the issue is old doesn't mean we don't think about it! 😄

You could try `@capacitor-community/http` since that has basic cookie support. But your best bet at the moment may be to write your own cookie wrapper.

**Closed** 2021-12-04 04:22 UTC
Labels: platform: ios

**Comment by bazuka5801** [comment] 2021-12-04 14:22
@thomasvidas Hi! Before writing this, I tried a lot of ways, this included:
1) Cordova plugin cors - https://www.npmjs.com/package/cordova-plugin-cors?activeTab=readme
2) AppBoundDomains
3) Server.hostname

But none of this made the video tag, send the request via native or with cookies

**Comment by realityfilter** [comment] 2022-09-01 10:09
Anybody successfully got cookies to work with hostname and AppBoundDomains or other workarounds? We need this to authenticate medias, so we can not use the HTTP plugin.

**Comment by tsenguunchik** [comment] 2022-11-06 20:30
> @thomasvidas Hi! Before writing this, I tried a lot of ways, this included:
> 
> 1. Cordova plugin cors - https://www.npmjs.com/package/cordova-plugin-cors?activeTab=readme
> 2. AppBoundDomains
> 3. Server.hostname
> 
> But none of this made the video tag, send the request via native or with cookies

How did you solve this issue? I think we have basically the exact same problem. For me, i can solve android side but not ios side
