### ISSUE TITLE
bug: Fail at com.getcapacitor.Splash$2.run: android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by davicedraz** [ionic-team/capacitor#4119] opened 2021-01-26 20:24 UTC
## Bug Report

Thank you all for your great work!
I hope you can help me. 

I'm getting this fail my Google Play Console, mostly on SDKs 29, 28 but also on 23 and 24:

```
android.view.WindowManager$BadTokenException: 
  at android.view.ViewRootImpl.setView (ViewRootImpl.java:806)
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:356)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:94)
  at com.getcapacitor.Splash$2.run (Splash.java:276)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6746)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/core 2.2.1
  @capacitor/cli 2.2.1
  @capacitor/ios 2.2.1
  @capacitor/android 2.2.1
  @capacitor/electron not installed
```

### Platform(s)
- Android

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.17.0

**Comment by jcesarmobile** [comment] 2021-01-27 12:16
try updating to latest capacitor, if the problem continues, provide a sample app where it can be reproduced

**Comment by davicedraz** [comment] 2021-01-27 21:09
We were unable to reproduce this error, which seems to happen only in production and only on some devices. As this is not an ANR, I was unable to obtain any more useful logs for analysis or reproducibility.

Thanks for the answer, we will consider updating the capacitor version of our app and hope that this error stops occurring.

**Comment by svssdeva** [comment] 2021-02-09 09:55
`java.lang.IllegalStateException: 
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:443)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:95)
  at com.getcapacitor.Splash$2.run (Splash.java:235)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8154)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)`

**Comment by josluimg** [comment] 2021-10-18 09:10
Me too. Also getting this error. 

Package.json:
`    "@capacitor/android": "~2.4.0",
    "@capacitor/core": "~2.4.0",
    "@capacitor/ios": "~2.4.0",`

Version:
`    "@capacitor/android": "2.4.7",
    "@capacitor/core": "2.4.7",
    "@capacitor/ios": "2.4.7",`

Crashlytics data:
 `Fatal Exception: android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@b6ae9f7 for displayid = 0 is not valid; is your activity running?`
<img width="1161" alt="Captura de pantalla 2021-10-18 a las 11 07 47" src="https://user-images.githubusercontent.com/3416114/137702060-0df90f43-8bf1-426c-af07-8f2f5d6b1b88.png">

Devices fail:

- HUAWEI Y6 2019 - Android 9
- Galaxy Note9 - Android 10
- Huawei P10 - Android 9
- Huawei P20 Pro - Android 10
- Huawe Mate 10 - Android 9
- ...

**Comment by Ionitron** [comment] 2021-11-03 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-11-03 00:03 UTC
Labels: platform: android, needs reply, needs reproduction
