### ISSUE TITLE
iOS dark themed keyboard color is changing while displaying keyboard 

### ISSUE THREAD

**Issue by rodrigo-infomagnus** [ionic-team/capacitor#6152] opened 2022-12-08 07:24 UTC
Hi,

I am using ionic/angular and capacitor for an application and when I am using the dark theme on iOS the keyboard first displays as a lighter tone of grey and it takes a some time to adjust to correct darker grey.  I try to force dark keyboard style both on capacitor-config and app.component.ts but that does nothing to it.

The attached video shows the problem happening.

https://user-images.githubusercontent.com/89427735/206384166-8dd15901-298b-4306-8c2f-a88671294a1d.mp4

Does anyone experienced that before?

Those are the relevant versions from package.json: 
    "@ionic/angular": "^6.0.13",
    "@capacitor-community/barcode-scanner": "^3.0.1",
    "@capacitor/android": "^4.6.1",
    "@capacitor/app": "^4.1.1",
    "@capacitor/app-launcher": "^4.1.0",
    "@capacitor/clipboard": "^4.1.0",
    "@capacitor/core": "^4.6.1",
    "@capacitor/device": "^4.1.0",
    "@capacitor/dialog": "^4.1.0",
    "@capacitor/filesystem": "^4.1.4",
    "@capacitor/haptics": "^4.1.0",
    "@capacitor/ios": "^4.6.1",
    "@capacitor/keyboard": "^4.1.0",
    "@capacitor/push-notifications": "^4.1.2",
    "@capacitor/share": "^4.1.0",
    "@capacitor/splash-screen": "^4.1.2",
    "@capacitor/status-bar": "^4.1.1"

Thanks,

Rodrigo

**Comment by Ionitron** [comment] 2022-12-08 10:36
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-24 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-24 00:05 UTC
Labels: needs reply, needs reproduction
