### ISSUE TITLE
Share Plugin - Local Image Sharing Problem with WhatsApp 

### ISSUE THREAD

**Issue by dhwalin** [ionic-team/capacitor#4090] opened 2021-01-20 10:43 UTC
Once again I am writing this problem. The thing is Sharing on Email is working. But when you try to share on WhatsApp, it says "can't send empty message", if you pass some text, only text is getting pasted in WhatsApp Chat window.

```
const save_image_id = random_id;
const dataURL = dataURLValue;

      Filesystem.writeFile({
        path: save_image_id+".jpg",
        data: dataURL,
        directory: FilesystemDirectory.Cache,
      }).then(function(result){

          Share.share({
            title:'Share',
            text:'',
            url:result.uri,
            dialogTitle:'Share'
          });
```

As per above code, first I am saving image in cache folder, get the path, pass the image file path with no text.

Sharesheet is getting open, on selection on WhatsApp, its get back into App by saying "Can't send empty message"

Now when you try with email, Image is getting attached.

So I guess there is no problem in my code. If anything is there, please let me know.
 
Testing Device:
One UI Core : 2.5
Android Version: 10

* I have not tested with Instagram personally, but my tester said same thing is happen in instagram too.

**Comment by jcesarmobile** [comment] 2021-01-20 13:09
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/156

**Closed by jcesarmobile** 2021-01-20 13:09 UTC
