### ISSUE TITLE
[Android Studio] Errors after Capacitor update in Android Studio

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/capacitor#349] opened 2018-03-16 14:08 UTC
[X] I would to submit a bug or support question

**Current behavior**

I'm not sure if it's a bug or just something I should ignore, but each time I update `capacitor` in my existing test project, build, copy and then open `Android Studio` I face the following errors (first error popup straight after Android Studio open, the other one after automatic build)

> 16.03.18
> 15:02	Unsupported Modules Detected: Compilation is not supported for following modules: assets-capacitor-android-plugins~1, capacitor-android-plugins. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
> 
> 15:02	Unsupported Modules Detected: Compilation is not supported for following modules: assets-capacitor-android-plugins~1, capacitor-android-plugins. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
>
> 15:02	Unregistered VCS root detected
			The directory /Users/me/Documents/projects/lab/capacitor-camera is under Git, but is not registered in the Settings.
			Add root  Configure  Ignore
>
> 15:03	Gradle sync started
> 
> 15:03	Error Loading Project: Cannot load module assets-capacitor-android-plugins Details...
> 
> 15:03	Platform and Plugin Updates: The following components are ready to update: Android Emulator, Google Play services
> 
> 15:03	Project setup started
> 
> 15:03	Gradle sync failed: java.lang.NullPointerException (41s 709ms)

<img width="1359" alt="android_studio_error_after_update" src="https://user-images.githubusercontent.com/16886711/37524957-b77c68ac-292b-11e8-90cb-a83d28adf06a.png">

**Expected behavior**

No error I guess, but like I said, maybe I do something wrong

**Current way to solve this**

To solve this, each time I remove the "platform" 

    rm -r android

and then add it again 

    npx cap add android
    npx cap sync
    npx cap open android

**Steps to reproduce**

    npm remove --save @capacitor/core @capacitor/cli
    npm install --save @capacitor/core @capacitor/cli
    ionic build --prod
    npx cap copy
    npx cap open android

p.s.: all the above steps are successful and produce no errors

**Others informations**

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.6 x86_64

**Comment by jcesarmobile** [comment] 2018-03-16 14:13
Do you have cordova plugins in your project?

**Comment by peterpeterparker** [comment] 2018-03-16 14:16
@jcesarmobile to create the project I did "ionic start ..." answered no to "would you like to add iOS/android" and then as described in the doc, as far as I remember, deleted the splash screen plugin

**Comment by peterpeterparker** [comment] 2018-03-16 14:17
@jcesarmobile to create the project I did "ionic start ..." answered no to "would you like to add iOS/android" and then as described in the doc, as far as I remember, deleted the splash screen plugin

**Comment by jcesarmobile** [comment] 2018-03-16 14:26
what template did you choose?

**Comment by peterpeterparker** [comment] 2018-03-16 14:32
@jcesarmobile menu ("hamburger menu top left")

**Comment by jcesarmobile** [comment] 2018-03-16 15:12
I'm not able to reproduce, but might be related to removing capacitor cli as we write a lot of things there, so after removing it, better run a cap sync or cap update to make sure everything is recreated, specially if you have Cordova or custom plugins.

**Comment by peterpeterparker** [comment] 2018-03-16 16:17
Same same. 

You know what, this problem appears because `Android Studio`, the very first time I open the project (`npx cap open android` after having created a fresh new platform like described above) in it, create a folder `capacitor-android-plugins` with the following `manifests/AndroidManifest.xml` file in it

    <?xml version='1.0' encoding='utf-8'?>
      <manifest package='capacitor.android.plugins' xmlns:android='http://schemas.android.com/apk/res/android'>
    </manifest>

Then, if I close it and open it again, it will try to compile this and complains.

Does that make sense? Do you also have such a folder/file in your project?

<img width="377" alt="android_studio_error_plugin_manifest" src="https://user-images.githubusercontent.com/16886711/37531910-da91e59e-293d-11e8-8ecf-05fd7faad1ad.png">

**Comment by jcesarmobile** [comment] 2018-03-16 16:32
Yeah, I have it and doesn't complain about it

**Comment by peterpeterparker** [comment] 2018-03-17 08:36
Weird....I'll keep an eye on it. I saw that I "need" to update one or two Android libs, maybe it will help

**Comment by JStumpp** [comment] 2018-03-26 14:02
Maybe it is because the android studio files are committed. I had the same issue. After removing them it was not a problem any longer. I modified the default gitignore to reflect this: 
https://github.com/ionic-team/capacitor/pull/378

**Comment by peterpeterparker** [comment] 2018-03-27 04:55
cool @JStumpp I'll will keep an eye on it too

if I can't reproduce it anymore, count on me to close the issue

**Comment by peterpeterparker** [comment] 2018-03-27 19:04
mmmmh I could reproduce the problem after upgrading from alpha25 to alpha31

I tried to remove the git origin (`git remote rm origin`) but they were none to remove

so I did

    npm install --save @capacitor/core @capacitor/cli
    ionic build --prod
    npx cap sync
    npx cap open android

**Comment by ArmorDarks** [comment] 2018-07-26 16:32
I've left the project for about a week, then when returned faced the same set of errors. I even didn't change anything in it!

`npx cap sync` or `npx cap update` didn't make any difference, nor attempts to clear or rebuild project.

**Comment by ArmorDarks** [comment] 2018-07-27 19:48
Removing and adding `android` directory again helped, though, none of the tracked by Git files changed, so I assume it is something to do with files listed in `.gitignore`...

**Comment by ArmorDarks** [comment] 2018-07-30 14:37
Seems to be unrelated to the `android` directory at all, since resetting it to defaults doesn't help. However, resetting `@capacitor` `node_modules` content does help.

I assume Gradle writes in Capacitor `node_modules` something that later leads to this issue.

**Comment by mlynch** [comment] 2019-01-24 17:12
Closing without more info there's not much we can do here. Try invalidating caches and restarting as recommended above. It's just one of those things you get used to when doing Android development as Android Studio makes mistakes sometimes.

**Closed by mlynch** 2019-01-24 17:12 UTC
Labels: platform: android, triage

**Comment by krithikuntukad** [comment] 2019-11-05 08:57
I am still facing the issue

**Comment by SergioSuarezDev** [comment] 2019-11-05 14:37
same here

**Comment by Brayan233** [comment] 2019-11-06 01:48
Same here...

**Comment by Brayan233** [comment] 2019-11-06 02:50
@SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
Hope it will help

**Comment by jnettome** [comment] 2019-11-13 15:27
Ty @Brayan233 , that fixes my build

**Comment by kristianmandrup** [comment] 2019-11-20 15:54
I'm getting: `Unsupported Modules Detected: Compilation is not supported for following modules: capacitor-cordova-android-plugins. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.` which results in the same problem

**Comment by SSuarezBrooktec** [comment] 2019-11-23 15:34
> @SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
> Hope it will help

works like a charm, thx!

**Comment by SergioSuarezDev** [comment] 2019-11-23 15:35
> @SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
> Hope it will help

works like a charm! thx

**Comment by jdcifuentes** [comment] 2019-12-14 03:53
> @SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
> Hope it will help

This worked.

**Comment by jnettome** [comment] 2019-12-14 05:31
There's another way I've found to fix it, File -> Invalidate Caches / Restart -> Invalidate and Restart

**Comment by peterpeterparker** [comment] 2020-02-02 10:24
Faced the issue, again.

Neither "Invalidate Caches / Restart" nor "Sync Project with gradle files" solved the problem, after each restart I still faced the issue.

Add no other choice than delete (`rm -r android`) and add (`npx cap add android`) the android project to clean the project and "solve" it.

**Comment by razmans** [comment] 2020-02-04 07:40
> @SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
> Hope it will help

This works!

**Comment by hichambranis** [comment] 2020-02-26 20:32
i solved this by running the following command : ionic capacitor update android

it works fine !

**Comment by wannadream** [comment] 2020-03-10 16:57
I am still getting this error. Tried all recommended solution.

**Comment by Niiitzer** [comment] 2020-03-26 18:38
None of the recommended solutions worked for me. 
Removing the /android/.idea folder did the job

**Comment by hichambranis** [comment] 2020-03-26 18:41
Try to close android studio, re open it and retry again : ionic capacitor update android

**Comment by Niiitzer** [comment] 2020-03-26 18:43
@hichambranis thanks but that wasn't working on my side, don't know why.
Removing the /android/.idea folder helped me

**Comment by skmohammadi** [comment] 2020-03-27 08:07
Removing the /android/.idea folder helped me :)

**Comment by heniotierra** [comment] 2020-03-29 23:29
> Removing the /android/.idea folder did the job

That did the trick for me!

**Comment by cdCarlos** [comment] 2020-04-07 18:00
> Faced the issue, again.
> 
> Neither "Invalidate Caches / Restart" nor "Sync Project with gradle files" solved the problem, after each restart I still faced the issue.
> 
> Add no other choice than delete (`rm -r android`) and add (`npx cap add android`) the android project to clean it and "solve" the issue.

Same here. I didn't remove `android` but event with the error shown by Android Studio saying that you cannot compile the project, I hit `Build > Build Bundle(s) / APK(s) > Build APK(s)` and it worked (and that's what I wanted)

**Comment by cdCarlos** [comment] 2020-04-07 18:07
> Removing the /android/.idea folder helped me :)

This removes the error

**Comment by florian-sander** [comment] 2020-04-14 17:26
> Removing the /android/.idea folder did the job

Same here. It was the only solution that worked for me. Thanks @Niiitzer !

**Comment by sunil-developer-ios** [comment] 2020-04-29 18:47
> Removing the /android/.idea folder helped me :)

Yes, did the trick. Thanks.

**Comment by lincolnthree** [comment] 2020-05-06 17:45
This just keeps... coming... back. Anyone else keep having this issue over and over again? If so, how did you solve it?

**Comment by coffeymatt** [comment] 2020-05-07 10:20
Yep, just keeps coming back for me, keep having to remove the idea folder

**Comment by coffeymatt** [comment] 2020-05-07 12:44
@mlynch Any chance this could be reopened? It seems simple to reproduce with the latest versions of everything:

1. Clear out and recreate the android project
2. Run it, it works first time (asks to update gradle). Close it.
3. Run npx cap sync android
4. Run npx cap open android, error is back:

Unsupported Modules Detected: Compilation is not supported for following modules: capacitor-cordova-android-plugins, android-capacitor-cordova-android-plugins. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

**Comment by richardkshergold** [comment] 2020-05-21 10:36
I'm getting this error too @mlynch so maybe this should be re-opened.

**Comment by miainchambers** [comment] 2020-05-21 15:57
I'm getting the error too. Trying to run a Vue Ionic app using 'npm run build:android' which just packages the npx stages.

"build:android": "npm run build; npx cap sync android; npx cap open android"

<img width="500" alt="Screenshot 2020-05-21 at 16 56 43" src="https://user-images.githubusercontent.com/16454408/82578244-0e87f180-9b84-11ea-93db-f0711bca4509.png">

**Comment by adelynx** [comment] 2021-03-30 11:53
> @SergioSuarezDev @krithikuntukad , i solved this issue by sync the project ( File -> Sync Project with gradle files)
> Hope it will help

Worked for me. Thanks

**Comment by xgiral-metacodi** [comment] 2021-06-17 14:38
I have another issue, ionic angular capacior:

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> org.gradle.api.artifacts.result.ComponentSelectionReason.getDescription()Ljava/lang/String;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:89)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy16.buildFinished(Unknown Source)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:132)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:61)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner.runClientAction(AbstractClientProvidedBuildActionRunner.java:55)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:47)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:66)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:90)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:59)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:58)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:34)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NoSuchMethodError: org.gradle.api.artifacts.result.ComponentSelectionReason.getDescription()Ljava/lang/String;
