### ISSUE TITLE
bug: viewheight changes when changing inputs with the keyboard open

### ISSUE THREAD

**Issue by drakedeatonuk** [ionic-team/capacitor#6642] opened 2023-04-05 10:00 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When changing between inputs on a screen, if there is a keyboard open, the viewport of the screen will change.

Take the following example:

https://user-images.githubusercontent.com/41165256/230046106-b7c071a3-d423-4802-8440-2f697a4177a1.mov

In this video, when I click in Input 1:
A. The viewport changes to accommodate the height of the keyboard
B. The background color behind the translucent keyboard is clearly white.
C. I can scroll to the bottom of the div (indicated by the red-to-yellow gradient)

Then, when I click on Input 2:
A. The viewport changes again to disregard the height of the keyboard
B. The background color behind the translucent keyboard changes to red/yellow
C. I can no longer scroll to the very bottom of the div, because of point A.

### Expected Behavior

Clicking on different inputs when the keyboard is open should not cause the viewport of the screen to change.

This behaviour is problematic for users as if may mean certain elements on a screen will be hidden behind the keyboard when the user should be able to scroll to them.

### Steps to Reproduce

1. pull the reproduction repo
2. install deps
3. run:
```
npx ng build app         
npx cap sync
npx cap open ios   
```
4. run the app on the simulator via xcode
5. click on the different inputs, pull up the keyboard, and observe the same behaviour seen in the video.

### Code Reproduction URL

https://github.com/drakedeatonuk/ionic-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3
   Ionic Framework               : @ionic/angular 6.2.8
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v19.8.1 (/opt/homebrew/Cellar/node/19.8.1/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

### Additional Information

Generally continuing to love the ionic framework and where this framework is going - thanks for all you guys do :)

**Comment by thetaPC** [comment] 2023-06-08 19:48
I was able to reproduce the bug with native inputs: [repro URL](https://github.com/thetaPC/capacitor-keyboard-form-bug)

I'll attach a video below. My app has a long page with a paragraph element at the very bottom.

1. I focus on the first input
2. The keyboard appears and the page resizes
3. I can scroll all the way down and see the text
4. I then focus on the second input
5. I can't scroll all the way down, making it impossible to see the text

Video:

https://github.com/ionic-team/capacitor/assets/13530427/6e842947-656e-4e32-97c5-2d9bb990aadc

**Comment by jcesarmobile** [comment] 2023-06-09 06:18
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1413
It should be fixed on latest release from yesterday

**Closed by jcesarmobile** 2023-06-09 06:18 UTC
Labels: triage
