### ISSUE TITLE
bug: Android apps using Capacitor fail to build with Android Studio 4.0 and Gradle 6.1.1

### ISSUE THREAD

**Issue by smpeters** [ionic-team/capacitor#3009] opened 2020-05-29 12:54 UTC
There is a known issue with the bintray-release Gradle plugin used in the capacitor-android Gradle file included in Android apps

https://github.com/novoda/bintray-release/issues/298

For now, the workaround is obviously don't update the Android build tools and Gradle plugin.  

Also, bintray-release isn't really needed for app developers.  Can this be removed from the capacitor-app build.gradle and added but commented out in one android-template build.gradle files?  It's not needed for app developers.  Plugin developers could then uncomment it as needed.

**Comment by jcesarmobile** [comment] 2020-05-29 13:03
duplicate of https://github.com/ionic-team/capacitor/issues/3003

**Closed by jcesarmobile** 2020-05-29 13:03 UTC
