### ISSUE TITLE
bug: Camera cannot select picture from Redmi Gallery app

### ISSUE THREAD

**Issue by jirifranc** [ionic-team/capacitor#2060] opened 2019-10-16 14:26 UTC
# Bug Report

## Capacitor Version

`npx cap doctor` output:
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/core 1.2.1
  @capacitor/cli 1.2.1
  @capacitor/android 1.2.1

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Using the Camera plugin on Android Redmi phones, when a picture is selected in the Gallery app, this error is thrown: **Unable to process image**. It doesn't manifest itself with other apps (e.g. File Manager) and also there was no problem with the Cordova plugin which we used before upgrading to Capacitor.

## Expected Behavior

Users are able to use the default Gallery app to select their pictures on Redmi phones.

## Sample Code or Sample Application Repo
This is the config we use:
`const options: CameraOptions = {
      quality: 30,
      resultType: CameraResultType.Uri,
      allowEditing: false,
      source: CameraSource.Photos,
    };
`

## Reproduction Steps
Configure the Camera plugin to return a Uri and use the option to select a picture from gallery instead of taking a new photo.

## Other Technical Details
- Phone: Redmi 6A/Redmi Note 7
- Android version: 8.1/9
- MIUI version: 10.3.6/10.3.6

## Other Information
I suspect the bug concerns other MIUI devices, such as Xiaomi phones. I managed to track down the problem to **saveTemporaryImage** method in Camera.java. **contentUri.getlastPathSegment** tries to select the filename and a copy of the file is created in the **cacheDir**.

However, contentUri from the Gallery app has this format:
content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20191013_191506.jpg

while the other apps return unescaped slashes in the path, e.g.
content://com.mi.android.globalFileexplorer.myprovider/external_files/DCIM/Camera/IMG_20191013_191506.jpg

I created an easy solution for our app (using a random filename) but this is probably a symptom of a more serious issue and I don't know what the proper fix would be. Is it enough to just unescape the path?

**Comment by wanaideed** [comment] 2019-11-05 16:04
I got the same problem with you.

**Comment by alifrontend499** [comment] 2019-11-06 06:54
The same problem I'm facing

**Comment by jirifranc** [comment] 2019-11-06 09:54
As no one from the Capacitor team has replied, I'll at least give you a workaround.

1. Created a file called named `patch-camera.js` in the project root folder with this content:
```javascript
const fs = require("fs");
const f =
  "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java";

fs.readFile(f, "utf8", function(err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(
    "String filename = contentUri.getLastPathSegment()",
    'String filename = "file"'
  );

  fs.writeFile(f, result, "utf8", function(err) {
    if (err) return console.log(err);
  });
});
```
As you can see, this fix is very fragile as it relies on the specific `node_modules` path and Java source code. This ensures that a timestamp is used for the file name instead of the broken name from the Gallery app.

2. Add the `postinstall` script to your `package.json` to patch the Capacitor source code.
```json
 "scripts": {
    "build": "ng build --prod && npx cap sync",
    "postinstall": "node patch-crypto.js && node patch-camera.js"
```
This automatically runs the fix after `npm install` and works perfectly with **@capacitor/android": "^1.2.1"**. We haven't updated to 1.3 yet.

**Comment by jcesarmobile** [comment] 2020-01-16 19:20
do you know if it's possible to install the miui gallery in a not xiaomi device?
I've tried in different apps and they work fine.

**Comment by jirifranc** [comment] 2020-01-21 10:53
I haven't tried to install the APK manually but the app doesn't seem to be available at the Play Store. The problem is this Gallery is the default one for Xiaomi/Redmi users and while the hack is simple, it's not a long-term solution as we have to check the source code with each release to make sure it doesn't break.

We ran into this issue immediately after migrating from Cordova but hoped it would be fixed quickly.

**Comment by lucasrleandro** [comment] 2020-01-22 10:41
Hello, I am facing this same problem with xiaomi. Our business really needs the camera and our customers are complaining. I think I will try this workaround, but is there any prediction of a definitive solution?

**Comment by tato469** [comment] 2020-03-03 09:00
> As no one from the Capacitor team has replied, I'll at least give you a workaround.
> 
> 1. Created a file called named `patch-camera.js` in the project root folder with this content:
> 
> ```js
> const fs = require("fs");
> const f =
>   "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java";
> 
> fs.readFile(f, "utf8", function(err, data) {
>   if (err) {
>     return console.log(err);
>   }
>   var result = data.replace(
>     "String filename = contentUri.getLastPathSegment()",
>     'String filename = "file"'
>   );
> 
>   fs.writeFile(f, result, "utf8", function(err) {
>     if (err) return console.log(err);
>   });
> });
> ```
> 
> As you can see, this fix is very fragile as it relies on the specific `node_modules` path and Java source code. This ensures that a timestamp is used for the file name instead of the broken name from the Gallery app.
> 
> 1. Add the `postinstall` script to your `package.json` to patch the Capacitor source code.
> 
> ```json
>  "scripts": {
>     "build": "ng build --prod && npx cap sync",
>     "postinstall": "node patch-camera.js"
> ```
> 
> This automatically runs the fix after `npm install` and works perfectly with **@capacitor/android": "^1.2.1"**. We haven't updated to 1.3 yet.

This worked for me, hope we could get "not patched" solution soon :)

**Comment by nikosdouvlis** [comment] 2020-05-27 08:07
I can confirm the same issue. Picking an image via the default Xiaomi gallery app results in a "Unable to process image" error. Other gallery apps seem to work, but its a blocker for us since  most people with xiaomi devices use the default gallery app.

The patched version and the old cordova plugin work for now

**Comment by HamoudaAmine** [comment] 2020-07-15 13:51
same issue on Xiaomi gallery

**Comment by shahidmau** [comment] 2020-07-23 11:39
I acknowledge the exactly same issue on my **Xiaomi** phone while selecting photo from the gallery. Here is my adb log.

```
07-23 17:08:25.212 29040 29040 D Capacitor: Sending plugin error: {"save":false,"callbackId":"49711431","pluginId":"Camera","methodName":"getPhoto","success":false,"error":{"message":"Unable to process image"}}
07-23 17:08:25.215 29040 29040 D Capacitor: App restarted
07-23 17:08:25.216 29040 29040 D Capacitor: App started
07-23 17:08:25.218 29040 29040 D Capacitor/App: Firing change: true
```

**Comment by shahidmau** [comment] 2020-07-23 11:43
> As no one from the Capacitor team has replied, I'll at least give you a workaround.
> 
> 1. Created a file called named `patch-camera.js` in the project root folder with this content:
> 
> ```js
> const fs = require("fs");
> const f =
>   "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java";
> 
> fs.readFile(f, "utf8", function(err, data) {
>   if (err) {
>     return console.log(err);
>   }
>   var result = data.replace(
>     "String filename = contentUri.getLastPathSegment()",
>     'String filename = "file"'
>   );
> 
>   fs.writeFile(f, result, "utf8", function(err) {
>     if (err) return console.log(err);
>   });
> });
> ```
> 
> As you can see, this fix is very fragile as it relies on the specific `node_modules` path and Java source code. This ensures that a timestamp is used for the file name instead of the broken name from the Gallery app.
> 
> 1. Add the `postinstall` script to your `package.json` to patch the Capacitor source code.
> 
> ```json
>  "scripts": {
>     "build": "ng build --prod && npx cap sync",
>     "postinstall": "node patch-camera.js"
> ```
> 
> This automatically runs the fix after `npm install` and works perfectly with **@capacitor/android": "^1.2.1"**. We haven't updated to 1.3 yet.

**This fix is working for me, thanks.**

**Comment by ferdiaddawy** [comment] 2020-08-08 05:30
I also have the same problem, when I upload a file from the gallery (the default xiaomi application) i**t doesn't work**, but when I use the default **Google Photos app it works**

Note: the device that I use redmi note 8

**Comment by manel00** [comment] 2020-08-20 14:50
![capacitorcam](https://user-images.githubusercontent.com/8410687/90787610-30208280-e305-11ea-869f-af1690a590be.jpg)
It fixes also this? cannot run cam on my phone when deploy a capacitor ionic app :S

**Comment by aren1989** [comment] 2020-09-03 08:02
same issue on Xiaomi gallery

**Comment by DoveAz** [comment] 2020-09-10 14:44
same issue

**Comment by lucasrleandro** [comment] 2020-10-27 19:40
> As no one from the Capacitor team has replied, I'll at least give you a workaround.
> 
> 1. Created a file called named `patch-camera.js` in the project root folder with this content:
> 
> ```js
> const fs = require("fs");
> const f =
>   "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java";
> 
> fs.readFile(f, "utf8", function(err, data) {
>   if (err) {
>     return console.log(err);
>   }
>   var result = data.replace(
>     "String filename = contentUri.getLastPathSegment()",
>     'String filename = "file"'
>   );
> 
>   fs.writeFile(f, result, "utf8", function(err) {
>     if (err) return console.log(err);
>   });
> });
> ```
> 
> As you can see, this fix is very fragile as it relies on the specific `node_modules` path and Java source code. This ensures that a timestamp is used for the file name instead of the broken name from the Gallery app.
> 
> 1. Add the `postinstall` script to your `package.json` to patch the Capacitor source code.
> 
> ```json
>  "scripts": {
>     "build": "ng build --prod && npx cap sync",
>     "postinstall": "node patch-camera.js"
> ```
> 
> This automatically runs the fix after `npm install` and works perfectly with **@capacitor/android": "^1.2.1"**. We haven't updated to 1.3 yet.

Works!!! Thanks @jirifranc 😄

**Comment by MilotH2** [comment] 2021-03-03 13:55
The patch no longer works for me... "@capacitor/android": "^2.4.6",

**Comment by koczka** [comment] 2021-04-15 08:53
> The patch no longer works for me... "@capacitor/android": "^2.4.6",

Same here

**Comment by jirifranc** [comment] 2021-04-19 17:27
I've updated Capacitor (core, android, and cli) in our app to 2.4.7 and the patch is still working. Please open the file `node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java` and check the line starting with `String filename =` (there is only one).

**Comment by heyitsbalazs** [comment] 2021-05-13 22:14
There are certainly a lot of markets where Xiaomi and Redmi phones are commonplace – so much so in my case, that about 40% of my Android users use one.

I'm really surprised, especially with a PR outstanding, that the Capacitor team isn't merging it, nor commenting on the issue.

**Comment by jcesarmobile** [comment] 2021-05-24 17:40
should be fixed on latest version @capacitor/camera plugin (requires capacitor 3)

if you still face the issue, create a new issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app where it can be reproduced

**Closed by jcesarmobile** 2021-05-24 17:40 UTC
Labels: bug, platform: android, platform: electron, platform: ios, platform: web, priority: low

**Comment by czabaj** [comment] 2021-07-14 07:04
I encountered this issue on an old Samsung Galaxy J3, the problem persisted even after an upgrade to capacitor@3. I downgraded the capacitor back to v2, as I have a problem debug the native code of the plugins in v3, and found out the exception is thrown in code that corrects the orientation of the image.

### Solution

_By disabling rotation with `correctOrientation: false` I resolved my issue._

### Further investigation

I got a

> java.io.FileNotFoundException: /-1/1/content:/media/external/images/media/376/ORIGINAL/NONE/image/jpeg/1205681957 (No such file or directory)

from the `prepareBitmap` function

by digging deeper, it turned out, that the failing code was `imageUri.getPath()`, a quick search revealed a [StackOverflow thread where this comment notes](https://stackoverflow.com/a/36329563)

> The Uri that you are attempting to open is content://document/image:26171. You need to access it with a ContentProvider.

I'm a newbie in Android development, but it seems that the Samsung Gallery does not provide a regular file URI, thus the Camera plugin must use `ContentProvider` to handle the URI.

**Comment by danbunkr** [comment] 2021-07-19 16:21
@czabaj I also confirmed the same issue on a newer galaxy S10. ```correctOrientation: false``` did resolve the issue for me but images are now uploaded the wrong orientation for portrait photos when sending to the server.

**Comment by mattmilan-dev** [comment] 2021-07-30 22:49
We've also had a few users also state that image uploading is not working across the Samsung device list only; Pixels seem to be unaffected by this. Not to repeat what @czabaj has said, but I'm also thinking it's to do with Samsung's photo gallery not returning the URI, although as stated, `correctOrientation: false` does solve the issue but leaves the returned image rotated 90 degrees anticlockwise. This has occurred after our apps migration to capacitor 3 and was not a problem on v2.

**Comment by sozonome** [comment] 2021-07-31 14:20
> We've also had a few users also state that image uploading is not working across the Samsung device list only; Pixels seem to be unaffected by this. Not to repeat what @czabaj has said, but I'm also thinking it's to do with Samsung's photo gallery returning incorrectly, although the specific error i get is `/external/images/media/389: open failed: ENOENT (No such file or directory)`. As stated, `correctOrientation: false` does solve the issue but leaves the returned image rotated 90 degrees anticlockwise. This has occurred after our apps migration to capacitor 3 and was not a problem on v2.
> 
> As a temporary work around, you can turn the lines [here in the plugin (android/capacitor-camera/src/main/java/com.capacitorjs.plugins.camera/ImageUtils)](https://github.com/ionic-team/capacitor-plugins/blob/561fea2f27b54354ddac11ab7aa74b9b3f09084d/camera/android/src/main/java/com/capacitorjs/plugins/camera/ImageUtils.java#L78-L85) to the following:
> 
> ```java
>  if (orientation != 0) {
>       Matrix matrix = new Matrix();
>       matrix.postRotate(orientation);
>       return transform(bitmap, matrix);
>   } else {
> ```
> 
> and rebuilding should allow it to work for now.

Thanks a lot for the workaround @mattmilan-dev! I've been trying the other workaround but this one finally works for me.

Combining with @jirifranc 's workaround, here are the step I use:

1. Create a file called named patch-camera.js in the project root folder with this content:
```js
const fs = require("fs");
const f =
  "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/ImageUtils.java"; // modify this part according to which version of capacitor plugin you are using, this is for new @capacitor/camera plugin

fs.readFile(f, "utf8", function(err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(
    "ExifInterface exif = new ExifInterface(imageUri.getPath());",
    ""
  ).replace(
    "exif.resetOrientation();",
    ""
  ).replace(
    "exif.saveAttributes();",
    ""
  );

  fs.writeFile(f, result, "utf8", function(err) {
    if (err) return console.log(err);
  });
});
```
As you can see, this fix is very fragile as it relies on the specific node_modules path and Java source code.

2. Add the `postinstall` script to your `package.json` to patch the Capacitor source code.
```json
 "scripts": {
    "postinstall": "node patch-camera.js"
```
Each time we do `yarn install` or `npm install`, `postinstall` will modify the camera plugin for us. Or just `yarn postinstall` or `npm run postinstall`

It works with the latest `@capacitor/camera` plugin (v1.0) because I'm using latest @capacitor/core (v3) which now use the separated capacitor plugin for camera

**Comment by jonmbennett** [comment] 2021-07-31 14:35
> We've also had a few users also state that image uploading is not working across the Samsung device list only; Pixels seem to be unaffected by this.

Thanks for your temporary fix. Yesterday I had this issue affect my personal Pixel 3 XL too, though now I am having trouble reproducing it. At the least I can confirm it does seem to happen consistently on Samsung phones.

**Comment by stevebrowndotco** [comment] 2021-08-09 18:53
@jonmbennett On Samsung 21 I get the error: (via logcat in android studio)

```
2021-08-09 19:50:40.705 32410-32410/com.ionicframework.chalk208279 E/Capacitor/Console: File: http://192.168.0.12:8100/vendor.js - Line 46093 - Msg: ERROR Error: Uncaught (in promise): Error: Unable to process image
    Error: Unable to process image
        at Object.cap.fromNative (http://192.168.0.12:8100/:429:32)
        at <anonymous>:1:18
```

This happens when (as a user) I attempt to add an image from the stock gallery.

WORKS with camera

**Comment by Euxiniar** [comment] 2021-08-13 22:02
> ```java
>  if (orientation != 0) {
>       Matrix matrix = new Matrix();
>       matrix.postRotate(orientation);
>       return transform(bitmap, matrix);
>   } else {
> ```

This fix works for me with a Xiaomi. Does anyone knows if the Capacitor team is on it ?

**Comment by mendo96** [comment] 2021-08-13 22:26
> 
> 
> > ```java
> >  if (orientation != 0) {
> >       Matrix matrix = new Matrix();
> >       matrix.postRotate(orientation);
> >       return transform(bitmap, matrix);
> >   } else {
> > ```
> 
> This fix works for me with a Xiaomi. Does anyone knows if the Capacitor team is on it ?

thank you buddy, that did the job !

**Comment by Sanch9s** [comment] 2021-11-23 12:37
After Capacitor upgrade to v2.5.0 mix of workarounds mentioned above helped us with issue on Xiaomi devices.
patch-camera.js file.

`const fs = require("fs");
const f =
  "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java";
const f2 =
  "node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ImageUtils.java";

// Workaround for Capacitor camera issue https://github.com/ionic-team/capacitor/issues/2060
fs.readFile(f, "utf8", function (err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(
    "String filename = contentUri.getLastPathSegment()",
    'String filename = "file"',
  );

  fs.writeFile(f, result, "utf8", function (err) {
    if (err) return console.log(err);
  });
});

// Inspired by https://github.com/ionic-team/capacitor/issues/2060#issuecomment-890225244
fs.readFile(f2, "utf8", function (err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(
    "if (orientation != 0) {\n" +
      "        Matrix matrix = new Matrix();\n" +
      "        matrix.postRotate(orientation);\n" +
      "        exif.resetOrientation();\n" +
      "        return transform(bitmap, matrix);\n" +
      "      } else {",
    " if (orientation != 0) {\n" +
      "      Matrix matrix = new Matrix();\n" +
      "      matrix.postRotate(orientation);\n" +
      "      return transform(bitmap, matrix);\n" +
      "  } else {",
  );

  fs.writeFile(f2, result, "utf8", function (err) {
    if (err) return console.log(err);
  });
});
`
