### ISSUE TITLE
bug: CookieManager flush needed

### ISSUE THREAD

**Issue by RAIbrahim360** [ionic-team/capacitor#6216] opened 2023-01-14 14:10 UTC
## Bug Report

What happened?
After saving a cookie if reopen app, cookies will be removed, but if you stay in the app for about 30 seconds before reopening, cookies won't be removed. it seems there is a 30 second timer on the sync process between WebView and CookieManager. It is known issue. We can solve this by manually flushing the CookieManager. Please add flush method to cookies api or auto flush after every set done.

What did you expect to happen?
When I open the app again the cookies will exist

How to reproduce?
After saving a cookie if reopen app, cookies will be removed, but if staying in app for about 30 second before reopening, cookies will not be removed.

App info output
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - 11.0.0

Important local packages
  quasar - 2.11.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.6.2 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.15.8 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.18.6 -- Babel compiler core.
  webpack - 5.73.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.9.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/cli - 2.5.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 2.5.0 -- Capacitor: cross-platform mobile apps with the web
  @capacitor/ios - 2.5.0 -- Capacitor: cross-platform mobile apps with the web

Quasar App Extensions
  *None installed*

**Comment by Ionitron** [comment] 2023-01-17 09:41
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jcesarmobile** [comment] 2023-01-18 17:40
Yes, any framework is allowed as long as there are instructions about how to run it and you are using latest Capacitor version

**Comment by Ionitron** [comment] 2023-02-03 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-03 00:05 UTC
Labels: needs reply, needs reproduction
