### ISSUE TITLE
iOS Statusbar Whitebar

### ISSUE THREAD

**Issue by AVatch** [ionic-team/capacitor#433] opened 2018-04-04 18:52 UTC
I'm experimenting with the current alpha and seeing how it integrates in an existing ionic project. I am seeing this white bar consistently render on the apps (see below). This does not appear to happen when starting a fresh ionic project. 

I have tried finding similar issues but was unable to so I am posting it here to let you know about it.

<img width="419" alt="screen shot 2018-04-04 at 2 30 10 pm" src="https://user-images.githubusercontent.com/1807958/38326941-0a249ca8-3815-11e8-978a-d6b54567fc54.png">
<img width="413" alt="screen shot 2018-04-04 at 2 31 32 pm" src="https://user-images.githubusercontent.com/1807958/38326942-0a34326c-3815-11e8-987b-17efac350716.png">

**Comment by mlynch** [comment] 2018-04-04 22:56
Duplicate of #337, thanks for reporting we will fix this soon!

**Closed by mlynch** 2018-04-04 22:56 UTC
