### ISSUE TITLE
bug: OAuth Cordova plugin crashes on android due to missing `getEngine` implementation

### ISSUE THREAD

**Issue by HarelM** [ionic-team/capacitor#5811] opened 2022-07-29 18:44 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Affects only android as far as I know

### Current Behavior
When a plugin would like to evaluate a js code and run it in the webview this will crash android app in capacitor.

### Expected Behavior
Cordova plugin should work without crashes, or there should be an equivalent plugin I could use

### Code Reproduction
Basically use a cordova plugin with the following line in android:
`this.webView.getEngine().evaluateJavascript("window.dispatchEvent(new MessageEvent('message', { data: 'data' }));", null);`
This code can be found here:
https://github.com/AyogoHealth/cordova-plugin-oauth/blob/a09b837cefb1f17628eef1d6d8dba88877149383/src/android/OAuthPlugin.java#L124

### Other Technical Details

`npm --version` output: 8.1.2

`node --version` output: v16.13.2

`pod --version` output (iOS issues only): 1.11.3

### Additional Context
I can see the the mock codorva webview implementation returns null when one request the engine in order to evaluate js code.
I guess one could only implement this method at this point in time in order to allow plugins to be able to evaluate js when they run in capacitor environment.
See here:
https://github.com/ionic-team/capacitor/blob/d744cbb1be647c7979d05128b63e6eeb820f464c/android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java#L241

Let me know if this is something that you would like to add to the mock and I might be able to send a PR.

**Comment by jcesarmobile** [comment] 2022-08-01 14:10
This is a duplicate of https://github.com/ionic-team/capacitor/issues/5390
It says `webView.engine` because that particular plugin uses kotlin, but the problem is the same.

As workaround if the plugin is yours or you want to for it, the code can be changed to something like:

```
WebView webViewImpl;
if(this.webView.getEngine() != null){
    webViewImpl = ((WebView) this.webView.getEngine().getView());
}
else {
    webViewImpl = (WebView) this.webView.getView();
}
webViewImpl.evaluateJavascript("window.dispatchEvent(new MessageEvent('message', { data: 'data' }));", null);
```

**Closed by jcesarmobile** 2022-08-01 14:10 UTC
Labels: platform: android
