### ISSUE TITLE
bug: fileTransfer.download error 401 - whitelist with capacitor

### ISSUE THREAD

**Issue by jackdaniel9** [ionic-team/capacitor#5208] opened 2021-11-04 19:13 UTC
## Bug Report
Download file or image with  "fileTransfer.download" = Code 3. Error 401.

### Platform(s)
Ionic 6

### Current Behavior
var url = "https://myimage.com/image.jpg";
fileTransfer.download(url, e.file.dataDirectory + 'member_' + member_id + '.jpg').then((entry) => {
    console.log('download complete: ' + entry.toURL());
}, (error) => {
    console.log('error download');
    console.log(error);
});

=
ERROR 401. CODE 3.

Someone have the same problem ?

**Comment by Ionitron** [comment] 2021-11-05 09:32
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by elvisgraho** [comment] 2021-11-05 14:02
Use https://ionicframework.com/docs/native/http to download files. I would say you can use the [ new http plugin](https://github.com/capacitor-community/http) but it doesn't work for me on android

**Comment by Ionitron** [comment] 2021-11-21 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-11-21 00:03 UTC
Labels: needs reply, needs reproduction
