### ISSUE TITLE
iOS Viewport Size Issue

### ISSUE THREAD

**Issue by philmerrell** [ionic-team/capacitor#843] opened 2018-10-02 15:58 UTC
My apologies if this is a known issue, but there seems to be a viewport sizing issue in iOS. I'm migrating an app from Cordova and thought it was potentially weirdness with that transition, however after creating a new 'tabs' app with the cli I'm still seeing the issue.

I'm using:
- Xcode 10
- iOS 12
- Capacitor 1.0.0-beta.8
- Ionic 4.0.0-beta.12

To recreate I ran:
- `ionic start --type=ionic-angular capTest`
- `npm install --save @capacitor/core @capacitor/cli`
- `npx cap init`
- `npm run build`
- `npx cap add ios`
- `npx cap copy`
- `npx cap open ios`

Although it's difficult to tell in the screenshots below, this vanilla starter results in extra padding at the bottom of the viewport on multiple devices in iOS. These screenshots are from an iPhone 6 and iPhone X.

![simulator screen shot - iphone 6 - 2018-10-02 at 09 46 04](https://user-images.githubusercontent.com/2514268/46360780-64afc600-c629-11e8-84de-d521a57b8b4c.png)
![simulator screen shot - iphone x - 2018-10-02 at 09 32 57](https://user-images.githubusercontent.com/2514268/46360797-6b3e3d80-c629-11e8-87ae-8902706eca9c.png)

**Comment by jcesarmobile** [comment] 2018-10-02 16:09
Yeah, it's a duplicate of https://github.com/ionic-team/capacitor/issues/337

**Closed by jcesarmobile** 2018-10-02 16:09 UTC
