### ISSUE TITLE
bug: Capacitor 3 App plugin getInfo not implemented on web

### ISSUE THREAD

**Issue by J4si3k** [ionic-team/capacitor#4684] opened 2021-06-05 10:19 UTC
## Bug Report
I use getInfo() method and want to migrate from Capacitor 2 to 3 version, but plugin throw an error"
```
index.js?1547:76 Uncaught (in promise) Error: Not implemented on web.
    at AppWeb.unimplemented (index.js?1547:349)
    at AppWeb.getInfo (web.js?a779:17)
    at eval (index.js?1547:171)
```
__getInfo__ method is one of the most important in Capacitor, which works on Capacitor 2nd version and I use it on three platforms (web, android, ios)

### Capacitor Version

```
3.0.0
```

### App Plugin Version
```
1.0.0
```

### Platform(s)

```
web
```

### Code Reproduction
I use capacitor with Nuxt.js, this code starts on app init. So on application start getInfo method below throw _Error: Not implemented on web._. This code works with Capacitor 2.4.7
```js
import { App } from '@capacitor/app'

(async () => {
    let info = await App.getInfo() // error
})() 
```

**Comment by Ionitron** [comment] 2021-06-07 08:20
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-23 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-23 00:02 UTC
Labels: needs reply, needs reproduction

**Comment by jeremymurray** [comment] 2021-08-07 23:19
We also ran into this as part of the Cap2 -> Cap3 upgrade.  I didn't see any mention this interface had a breaking change.  On Cap2, this method worked and returned info on web/electron builds.  On Cap3 it throws an exception.

```
import { App } from '@capacitor/app';
console.log(await App.getInfo());
```

**Comment by jcesarmobile** [comment] 2021-08-09 11:38
In Capacitor 2, App plugin doesn't have a `getInfo()` method. On Capacitor 3 it's not implemented for web, there is no issue here.
You are probably getting confused about Device's `getInfo()` method.

**Comment by J4si3k** [comment] 2021-08-09 12:02
It is obvious that I am using Device in Capacitor 2. I have submitted the reproduction under the new, 3 version.

My working example on Capacitor 2 looks like this:
```js
import { Plugins } from '@capacitor/core'

const { Device } = Plugins;

(async () => {
  const info = await Device.getInfo()
})()
```

**Comment by jcesarmobile** [comment] 2021-08-09 12:31
Have you tried `Device` plugin instead of `App` plugin?

**Comment by jeremymurray** [comment] 2021-08-09 17:40
At least as far as my issue, you were right on it being Device.getInfo before.  One of the devs switched it to App.getInfo as part of the upgrade and had only been testing on mobile.  Sorry for adding on here.

**Comment by J4si3k** [comment] 2021-08-10 11:31
It was just as @jeremymurray wrote above. I followed the documentation and it read about __App__. Now it's okay, and I do it like this:
```js
import { Device } from '@capacitor/device';

(async () => {
    const info = await Device.getInfo() // ... ok
})() 
```
and it works fine under the browser. Thanks for supporting @jeremymurray

**Comment by whitersun** [comment] 2021-11-24 05:19
I have a same error about not implemented when using:
`import { App } from '@capacitor/app' // version 1.0.2`

I am using App.exitApp() inside my *.js file and when click to event button that not working and throw error on Xcode said 
ERROR MESSAGE: { "code": "UNIMPLEMENTED", "errorMessage": "not implemented", "message": "not implemented"}

Even thought I test on my iPhone and get above that error message.

**Comment by jcesarmobile** [comment] 2021-11-24 08:05
exitApp is android only, Apple doesn’t provide a way to exit the app other than crashing it and they don’t like that apps crash.

> Force exit the app. This should only be used in conjunction with the backButton handler for Android to exit the app when navigation is complete.

**Comment by whitersun** [comment] 2021-11-27 05:38
> exitApp is android only, Apple doesn’t provide a way to exit the app other than crashing it and they don’t like that apps crash.
> 
> > Force exit the app. This should only be used in conjunction with the backButton handler for Android to exit the app when navigation is complete.

Thank you so much, Finally I got it now.

**Comment by mjaga** [comment] 2022-06-15 18:48
ran into similar problem, please find below error message.
"customplugin" plugin is not implemented on electron
Error: "customplugin" plugin is not implemented on electron
    at createPluginMethod
