### ISSUE TITLE
[Feature]: Provide an iOS privacy manifest compliant version of the device plugin

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/capacitor#7495] opened 2024-06-03 15:43 UTC
### Description

iOS privacy manifest friendly device plugin

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

It would be great to have a stripped-down version of the device plugin that does not include anything that will require a declaration in the iOS privacy manifest.

Use of the Device plugin currently requires `NSPrivacyAccessedAPICategoryDiskSpace` to be set in the privacy manifest, **even for apps that are not checking disk space for anything**.  So the app is forced to add the key to the privacy manifest because it is using the device plugin, but since the app is not actually using disk space for anything, all of the reasons for using disk space are invalid.

If other properties such as battery life become subject to the privacy manifest in the future, they should be removed from this "privacy-focused" version of the device plugin.

In addition, part of DeviceInfo, like the `name` of the device, could be removed.

**Comment by jcesarmobile** [comment] 2024-06-03 15:45
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/2071

**Closed by jcesarmobile** 2024-06-03 15:45 UTC
Labels: triage
