### ISSUE TITLE
bug: CapacitorHttp - JSONException on Android

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor#6133] opened 2022-11-30 18:23 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Native Android

### Current Behavior

Hello there! 👋

Using the Angular `HttpClient`, which uses `CapacitorHttp` at a lower level, making a request to a particular API endpoint on native Android fails with a `JSONException`.

Native iOS with or without `CapacitorHttp`, Native Android _without_ `CapacitorHttp`, and Web work fine.

I reproduced the issue on an emulator. The AVD Name is `Pixel_3a_API_33_arm64-v8a` which, as you may infer, is based on a Pixel 3a and using Android Tiramisu (API 33; Google APIs) arm64-v8a. I also reproduced it on a Pixel 2 with Android 10 (physical device).

### Expected Behavior

Native Android with `CapacitorHttp` should make a success HTTP request to the API endpoint and not incur a `JSONException`.

Also, if we want `CapacitorHttp` to work the same as XHR/fetch, this would be a difference.

### Code Reproduction

https://github.com/KevinKelchen/capacitor-http-json-exception-issue#steps-to-reproduce

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Thanks so much! 😀

Kevin

**Comment by jcesarmobile** [comment] 2022-11-30 18:28
Thanks for the issue.
In this case it's a duplicate of https://github.com/ionic-team/capacitor/issues/5996, but thanks for the sample app as it's way better than the other one since you use fetch directly while the other one was using firebase SDK calls which made harder to see what was going on, will use it for testing and working on a fix.

**Closed by jcesarmobile** 2022-11-30 18:28 UTC
Labels: platform: android

**Comment by KevinKelchen** [comment] 2022-11-30 18:37
You're welcome! 😀 Glad the sample app can be of service.

I did come across #5996 as a potential dupe but wasn't sure. What I do remember most about it was being amused by the repeated tagging of the company's CEO. 😄

Thanks so much for investigating this so incredibly quickly and for any efforts that go toward a fix, Julio.

Take care,

Kevin
