### ISSUE TITLE
Set safe area color on iOS when using contentInset: automatic

### ISSUE THREAD

**Issue by GeorgeL9** [ionic-team/capacitor#6585] opened 2023-05-11 17:26 UTC
### Discussed in https://github.com/ionic-team/capacitor/discussions/4023

<div type='discussions-op-text'>

<sup>Originally posted by **vacekj** January  6, 2021</sup>
Hi,

thank you for taking the time to look at my question. I am using the `contentInset: automatic` property in capacitor.config.json, and it works correctly, but I was wondering, if there is any way to set the color of the safe area behind the status bar and bottom bar, that is currently white? Example pictures below:

Bottom Navigation bar:
![image](https://user-images.githubusercontent.com/10381200/103777122-b62d3380-5030-11eb-89d2-1eb2f5772f3f.png)

Status Bar:
![image](https://user-images.githubusercontent.com/10381200/103777173-c6451300-5030-11eb-8c60-4d9426f90b22.png)</div>

**Comment by Ionitron** [comment] 2023-05-12 09:13
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-28 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-05-28 00:05 UTC
Labels: needs reply, needs reproduction
