### ISSUE TITLE
IOS 12 Keyboard Scroll Issue

### ISSUE THREAD

**Issue by luke-rogers** [ionic-team/capacitor#832] opened 2018-09-27 18:55 UTC
**Issue**

When using keyboard which causes input to scroll into view (may be through using keyboard arrows) then closing the keyboard, the buttons in my toolbar cannot be clicked. When you press them nothing happens. This issue is consistently reproducible and makes the app unusable.

This issue does not seem to affect my app when running on iOS 11.

Not super sure the cause of this issue, many issues have been raised across other projects, but it is also effecting capacitor apps.
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/176
https://github.com/apache/cordova-ios/issues/417

Solution / Workaround
There isn't one

Version info:
Capacitor: 1.0.0-beta.8
Device: iPhone X iOS 12

**Comment by jcesarmobile** [comment] 2018-09-27 18:57
Duplicate of https://github.com/ionic-team/capacitor/issues/814

**Comment by jcesarmobile** [comment] 2018-09-27 18:58
BTW, workaround it to keep using Xcode 9

**Closed by jcesarmobile** 2018-09-27 18:57 UTC
