### ISSUE TITLE
feat: Support Push notifications for the web via Capacitor - Webpush

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/capacitor#2275] opened 2019-12-21 19:11 UTC
Hi. First of all, amazing work with ionic and capacitor. Made my life so damn easy. Was wondering if the same Pushnotification plugin of capacitor can be extended to web as well. 

Chrome, Firefox supports Web Push - W3C API for push notifications. We can use pwaelements or something similar to fallback to that when using web.

Firefox: https://support.mozilla.org/en-US/kb/push-notifications-firefox
Chrome: https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by jcesarmobile** [comment] 2020-01-14 13:04
closing as duplicate of https://github.com/ionic-team/capacitor/issues/1282

**Closed by jcesarmobile** 2020-01-14 13:04 UTC
