### ISSUE TITLE
bug: cap run fails to work in a yarn 2+ workspace

### ISSUE THREAD

**Issue by daniellacosse** [ionic-team/capacitor#6791] opened 2023-08-04 14:59 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/android: 5.2.2 
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/ios: 5.2.2

[success] iOS looking great! 👌
```

### Platform(s)
Developing on iOS and Android
Running on MacOS, M1 Pro, Ventura 13.5

### Current Behavior
I have my capacitor project within a yarn 2+ PnP workspace. I'm running `yarn workspace <package name> cap run ios` and receiving the following error (PII in path redacted):

```
[error] SyntaxError: Unexpected token E in JSON at position 0
        at JSON.parse (<anonymous>)
        at getPlatformTargets
        (.../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/util/native-run.js:39:26)
        at async runIOS
        (.../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/ios/run.js:13:64)
        at async run
        (.../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/tasks/run.js:74:9)
        at async runCommand
        (.../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/tasks/run.js:61:13)
        at async
        .../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/index.js:125:9
        at async
        .../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/telemetry.js:26:13
        at async Command.<anonymous>
        (.../.yarn/cache/@capacitor-cli-npm-5.2.2-64c700d9bb-d23da7e05d.zip/node_modules/@capacitor/cli/dist/util/cli.js:12:13)
```

A similar thing happens with Android.

### Expected Behavior
There should be a list of targets to load the app on.

### Code Reproduction
I've got a WIP project here: https://github.com/Jigsaw-Code/outline-sdk/tree/outline-connectivity-app/x/outline-connectivity-app

### Other Technical Details
`npm --version` output: I'm using yarn 3.6.1
`node --version` output: 18.16.1
`pod --version` output (iOS issues only): 1.12.1

### Additional Context
I've noticed that we're calling `native-run` with the following: 

```
async function runNativeRun(args, options = {}) {
    const p = (0, node_1.resolveNode)(__dirname, (0, path_1.dirname)('native-run/package'), 'bin/native-run');
    if (!p) {
        (0, errors_1.fatal)(`${colors_1.default.input('native-run')} not found.`);
    }
    return await (0, subprocess_1.runCommand)(p, args, options);
}
```

This doesn't seem like it would play very well with PnP? Not sure.

**Comment by jcesarmobile** [comment] 2023-09-12 17:24
can you provide some steps to reproduce?
You have provided a massive repository with a "non standar" structure and no indications about where the capacitor app, where to run the commands, etc.

**Comment by Ionitron** [comment] 2023-09-28 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-28 00:05 UTC
Labels: platform: android, platform: ios, needs reproduction
