### ISSUE TITLE
Scandit cordova plugin

### ISSUE THREAD

**Issue by melimestiza** [ionic-team/capacitor#4473] opened 2021-04-19 16:05 UTC
There is a way to make this plugin work in capacitor? I get an specific error about 
<img width="1148" alt="Captura de Pantalla 2021-04-16 a la(s) 12 28 13 p  m" src="https://user-images.githubusercontent.com/16583973/115267675-125b2580-a0ff-11eb-872b-2e714ab1f38a.png">
<img width="980" alt="Captura de Pantalla 2021-04-16 a la(s) 12 29 01 p  m" src="https://user-images.githubusercontent.com/16583973/115267691-15eeac80-a0ff-11eb-986c-dbb7d003cc94.png">

Do I have to contact the developer of this pluging or there is a way it can work?

**Comment by Ionitron** [comment] 2021-04-19 17:01
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-05-18 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-05-18 00:04 UTC
Labels: needs reply, needs reproduction
