### ISSUE TITLE
bug:  Capacitor HTTP stuck in iOS emulator, when http get request is called with integer parameters. Works good on android

### ISSUE THREAD

**Issue by abhilashsajeev** [ionic-team/capacitor#6237] opened 2023-01-21 04:45 UTC
## Bug Report
When i do API requests with integer parameters as URL params using capacitor http plugin it gets stuck at emulator. I zoomed in the culprit part of the code

### Capacitor Version

```
Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Current Behavior

 Now it gets stuck at emulator when I use integer URL params. But when I convert then to string the code works. Issue exists only in iOS

### Expected Behavior

The requests should be completed regardless the params is integer or string

### Code Reproduction

[See Code causing bug](https://necistor.sirv.com/Images/ss.png)

### Other Technical Details

`npm --version` output: 8.19.3

`node --version` output: 18.13.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment] 2023-01-23 09:15
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-08 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-08 00:05 UTC
Labels: needs reply, needs reproduction
