### ISSUE TITLE
bug: navURL comparison with bridge.config.serverURL should be case-insensitive

### ISSUE THREAD

**Issue by karlvr** [ionic-team/capacitor#6093] opened 2022-11-17 03:29 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS (at least)

### Current Behavior

If a `config.server.url` is configured using mixed-case it is not correctly identified as being the server URL when deciding on how to handle navigation. This is because the URL is lower-cased by the browser before being sent through, but Capacitor compares it to the configured mixed-case value.

### Expected Behavior

The web request should be seen as to the capacitor server URL and handled in the app.

### Other Technical Details

This can be corrected in `WebViewDelegationHandler.swift` in the `webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void)` function by changing the `let isApplicationNavigation = navURL.absoluteString.starts(with: bridge.config.serverURL.absoluteString)` line to compare  `navURL` and `bridge.config.serverURL` case-insensitively.

**Comment by Ionitron** [comment] 2022-11-17 08:56
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-03 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-03 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
