### ISSUE TITLE
Image Orientation Comes Across Wrong From Gallery on iOS

### ISSUE THREAD

**Issue by Danchat5** [ionic-team/capacitor#6113] opened 2022-11-24 00:04 UTC
Description of the problem: 
When attempting to load an image from the Gallery in an established Angular Ionic app on some iOS devices, the orientation of the image is rotated depending on the way the picture was taken. When taken in portrait mode, it rotates 90 degrees counter-clockwise, and when taken in landscape it rotates 180 degrees cc. This only applies to images selected from the gallery, as when the image is taken (using source: CameraSource.Camera) the oritentation is just fine.

I followed the advice from [this issue](https://github.com/ionic-team/capacitor/issues/1269) that had a very similar problem, adding the CorrectOrientation: true, but this did not change anything. 

Affected platform: 
iOS. Issue can be replicated on iPhone SE and iPhone 14. On iPhone 8, images in landscape mode do not flip 180 degrees, but the portrait oriented photos still rotate 90 degrees counter-clockwise.

Capacitor version: 
4.0.1

**Comment by Ionitron** [comment] 2022-11-28 09:48
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Danchat5** [comment] 2022-12-03 20:48
I cannot replicate the issue on a standalone app, the image is coming in as expected on iOS. This could be a plugin issue, here are my app's dependencies:
```
"@angular/animations": "^14.2.2",
    "@angular/common": "^14.2.2",
    "@angular/compiler": "^14.2.2",
    "@angular/compiler-cli": "^14.2.2",
    "@angular/core": "^14.2.2",
    "@angular/forms": "^14.2.2",
    "@angular/platform-browser": "^14.2.2",
    "@angular/platform-browser-dynamic": "^14.2.2",
    "@angular/router": "^14.2.2",
    "@angular/service-worker": "^14.2.2",
    "@awesome-cordova-plugins/email-composer": "^5.45.0",
    "@awesome-cordova-plugins/globalization": "^5.45.0",
    "@capacitor/android": "^4.2.0",
    "@capacitor/app": "^4.0.1",
    "@capacitor/browser": "^4.0.1",
    "@capacitor/camera": "^4.1.1",
    "@capacitor/core": "^4.2.0",
    "@capacitor/dialog": "^4.0.1",
    "@capacitor/filesystem": "^4.1.1",
    "@capacitor/haptics": "^4.0.1",
    "@capacitor/ios": "^4.2.0",
    "@capacitor/keyboard": "^4.0.1",
    "@capacitor/preferences": "^4.0.1",
    "@capacitor/push-notifications": "^4.1.0",
    "@capacitor/splash-screen": "^4.0.1",
    "@capacitor/status-bar": "^4.0.1",
    "@fortawesome/angular-fontawesome": "^0.11.1",
    "@fortawesome/fontawesome-pro": "~6.2.0",
    "@fortawesome/free-brands-svg-icons": "~6.2.0",
    "@fortawesome/pro-regular-svg-icons": "~6.2.0",
    "@fortawesome/pro-solid-svg-icons": "~6.2.0",
    "@ionic-native/qr-scanner": "^5.36.0",
    "@ionic/angular": "^6.2.7",
    "@ionic/pwa-elements": "^3.1.1",
    "@mineminemine/fcm": "^4.0.3",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@transistorsoft/capacitor-background-fetch": "^1.0.0",
    "angular-gauge": "^4.0.0",
    "arraybuffer-to-string": "^1.0.2",
    "base64-arraybuffer": "^1.0.2",
    "base64-js": "^1.5.1",
    "cordova-plugin-email-composer": "^0.10.1",
    "cordova-plugin-globalization": "^1.11.0",
    "date-fns-tz": "^1.3.7",
    "hammerjs": "^2.0.8",
    "idb": "^7.0.2",
    "lock": "^1.1.0",
    "lodash-es": "^4.17.21",
    "ngx-ui-scroll": "^3.0.1",
    "p-queue": "^7.3.0",
    "p-timeout": "^6.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.6",
    "scope-css": "^1.2.1",
    "shell-escape": "^0.2.0",
    "swiper": "^8.4.2",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.8"
```

**Comment by jcesarmobile** [comment] 2022-12-05 11:21
If you can't reproduce on a standalone app, then it's probably some problem in your app, closing.

**Closed** 2022-12-05 11:21 UTC
Labels: needs reproduction
