### ISSUE TITLE
bug: Filesystem.stat() androind doesn't work

### ISSUE THREAD

**Issue by loremru** [ionic-team/capacitor#6989] opened 2023-10-11 20:21 UTC
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
Android

### Current Behavior

On Android pickVideo returns path:
content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/1000000018/ORIGINAL/NONE/video/mp4/906508663
When i use this path with Filesystem.stat() application crashes
I think i should transform content:// to file://. How can I do it?

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference - 

### Expected Behavior
get stats

### Code Reproduction

-

### Other Technical Details
-
### Additional Context
I think i should transform content:// to file://. How can I do it?

**Comment by jcesarmobile** [comment] 2023-10-16 08:30
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/308

**Closed by jcesarmobile** 2023-10-16 08:30 UTC
Labels: platform: android
