### ISSUE TITLE
Bug when opening keyboard with alert being open

### ISSUE THREAD

**Issue by lassesteffen** [ionic-team/capacitor#1257] opened 2019-02-22 20:18 UTC
**Might be related to #1045**

Description of the problem:
When opening an keyboard with an alert open, the alert moves and an white overlay appears (check image below)

Affected platform
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
Using Vue 2.6.7, @ionic/core 4.0.2

Capacitor version:
    "@capacitor/core": "^1.0.0-beta.17",
    "@capacitor/ios": "^1.0.0-beta.17",

node version: 11.3.0

npm version: 6.8.0

CocoaPods version: 1.5.3

Steps to reproduce:
1. Open an alert
![iosbug](https://user-images.githubusercontent.com/29383763/53268666-04f4ad00-36e7-11e9-83b9-26ac8a1d12ad.jpg)
2. Click on the input field and open the keyboard
3. Look at the result
![iosbug2](https://user-images.githubusercontent.com/29383763/53268668-06be7080-36e7-11e9-8109-23a365e7a802.jpg)

If you need I  can provide you with additional code.

**Comment by jcesarmobile** [comment] 2019-02-26 13:08
yes, please, provide a sample app, I can't reproduce

**Comment by lassesteffen** [comment] 2019-02-26 15:52
https://github.com/lassesteffen/capacitor-ios-alert-bug

Run

npm run build-ios to build and sync for ios

**Comment by jcesarmobile** [comment] 2019-02-26 16:07
I can reproduce on latest beta, but not on master, so closing as fixed

**Closed by jcesarmobile** 2019-02-26 16:07 UTC

**Comment by vjanssens** [comment] 2019-02-27 09:26
How would you go about testing an app against master? I'm having the same issue, but `1.0.0-beta.17` is the latest release on NPM.

**Comment by jcesarmobile** [comment] 2019-02-27 09:29
You can clone the project and change the Podfile to point to your clone folder instead of to node_modules.
