### ISSUE TITLE
[Bug]: capacitor native http interceptor breaking requests (still happening event after the fix #7352)

### ISSUE THREAD

**Issue by jkd2bleu** [ionic-team/capacitor#7585] opened 2024-07-25 15:07 UTC
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/ios: 6.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
npm 10.7.0
node v20.14.0
pod 1.15.2
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

The current behaviour is adding localhost/_capacitor_https_interceptor_ to the url on IOS when CapacitorHttp is enabled and the request is not sent.

### Expected Behavior

The request should be sent to the server

### Project Reproduction

https://github.com/jkd2bleu/ReproduceCapacitorHttpBug

### Additional Information

We can fix the issue by changing a line on ios/Capacitor/Capacitor/WebViewAssetHandler.swift like mentioned by this comment https://github.com/ionic-team/capacitor/issues/7352#issuecomment-2016830766

**Comment by markemer** [comment] 2024-07-25 19:28
The code reproduction doesn't seem to have an iOS cap app in it, will `npx cap add ios` exhibit this problem?

**Comment by jkd2bleu** [comment] 2024-07-26 07:53
Can you please use this code reproduction [https://github.com/jkd2bleu/ReproduceCapacitorHttpBug](https://github.com/jkd2bleu/ReproduceCapacitorHttpBug)

**Comment by markemer** [comment] 2024-07-26 17:35
> Can you please use this code reproduction https://github.com/jkd2bleu/ReproduceCapacitorHttpBug

Cool, thanks for adding it.

**Comment by jcesarmobile** [comment] 2024-07-29 14:52
The url is changed on purpose so it goes through Capacitor's `WebViewAssetHandler`. It's done for all non `POST` requests as it allows better interception of the requests.

In the provided sample app the request goes through and shows `OK`, so looks like it's working.
Can you provide another sample app where the request is not being sent? or better describe what the problem is?

**Comment by jkd2bleu** [comment] 2024-07-29 16:11
@jcesarmobile I know it works fine on simulator, but not on real device (iPhone). Are you trying to reproduce with a real iPhone ?

**Comment by jcesarmobile** [comment] 2024-07-29 16:47
Yes, tested on a real device (iPad) and it's working.

What's your iOS version?

**Comment by jkd2bleu** [comment] 2024-07-29 16:53
iPhone X with iOS 16.7.8

**Comment by jcesarmobile** [comment] 2024-07-29 17:27
could reproduce on a iOS 15 real device and simulator, so looks like it was a bug on iOS and it's fixed on iOS 17, but we should find a workaround that works on all versions

**Comment by jkd2bleu** [comment] 2024-07-30 01:52
As a workaround, maybe for iOS 17 we can use
`urlRequest.url = URL(string: targetUrl.removingPercentEncoding ?? targetUrl)` 

And for previous versions we can use
`urlRequest.url = URL(string: targetUrl)`

in iOS/Capacitor/Capacitor/WebViewAssetHandler.swift

**Comment by raduab** [comment] 2024-08-01 14:14
I can confirm it still doesn't work (iPhone 15 in Simulator and physical device)

**Closed** 2024-08-05 15:14 UTC
Labels: type: bug
