### ISSUE TITLE
[iOS] [OneSignal] Push notifications not shown in notification area when app is in foreground

### ISSUE THREAD

**Issue by ibanjo** [ionic-team/capacitor#1737] opened 2019-07-04 17:08 UTC
Description of the problem:
OneSignal push notifications cannot be shown in notification area on iOS while app is in foreground. In-app alert work correctly, though, and settings provided in `capacitor.config.json` in the `PushNotifications` plugin section are applied correctly, e.g. reproducing a sound, or vibrating when the notification is received.

Affected platform
- [ ] Android
- [X] iOS
- [ ] electron (not tested)
- [ ] web (not tested)

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:
OneSignal interface is provided by OneSignal cordova plugin, which however is not listed in the [incompatibility list](https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins).

Capacitor version:
1.1.0

node version:
10.15.3

npm version:
6.9.0

CocoaPods version:
1.7.1

Steps to reproduce:
- Install OneSignal cordova plugin and its Ionic native interface
- Call `oneSignal.inFocusDisplaying(oneSignal.OSInFocusDisplayOption.Notification)`
- Send a notification through OneSignal

Link to sample project:
[TBA]

**Comment by jcesarmobile** [comment] 2019-07-15 15:48
Sorry, but it's not clear what the problem is, nor what settings are you using in "PushNotifications plugin section".
Would be good if you could provide a sample app.

**Comment by jcesarmobile** [comment] 2019-08-12 13:31
Closing as it's not clear what the problem is and the user didn't respond to the questions.

**Closed by jcesarmobile** 2019-08-12 13:31 UTC
Labels: needs-reply
