### ISSUE TITLE
bug: After use "cordova-plugin-inappbrowser", lost two way binding, only works html to ts, in ts to html not working

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#4552] opened 2021-05-08 00:01 UTC
### Capacitor Version
```
Installed Dependencies:

  @capacitor/android: 3.0.0-rc.2
  @capacitor/cli: 3.0.0-rc.2
  @capacitor/core: 3.0.0-rc.2
  @capacitor/ios: 3.0.0-rc.2
```

### Platform(s)
ios
android

### Current Behavior
After use "cordova-plugin-inappbrowser", lost two way binding, only works html to ts, in ts to html not working 

### Expected Behavior
Two way binding works

### Code Reproduction
```
const target = "_blank";
const browser = this.inAppBrowser.create('http:/ionicframework.com',target);
browser.close();
```
And then in a page two way binding not working.

### Other Technical Details

@ionic/angular@5.6.6

`pod --version` output (iOS issues only): 1.10.0

### Additional Context

2021-05-07 18:30:36.189854-0500 App[28389:418122] [ProcessSuspension] 0x106b29f80 - ProcessAssertion: Failed to acquire RBS Suspended assertion 'WebProcess Suspended Assertion' for process with PID 28438, error: Error Domain=RBSAssertionErrorDomain Code=3 "Target is not running or required target entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"Suspended" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Target is not running or required target entitlement is missing}

2021-05-07 18:31:02.514323-0500 App[28389:418122] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by Ionitron** [comment] 2021-05-27 15:00
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-12 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-12 00:02 UTC
Labels: needs reply, needs reproduction, platform: android, platform: ios
