### ISSUE TITLE
bug: In app browser with face recognition screen resize issue

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#2757] opened 2020-04-13 17:59 UTC
# Bug Report

## Capacitor Version
Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/core 2.0.1

  @capacitor/android 2.0.1

  @capacitor/ios 2.0.1

[success] Android looking great! 👌
  Found 14 Capacitor plugins for ios:
    call-number (1.0.1)
    cordova-plugin-calendar (5.1.5)
    cordova-plugin-email-composer (0.9.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-firebase-analytics (4.2.0)
    cordova-plugin-firebase-dynamiclinks (4.3.0)
    cordova-plugin-nativegeocoder (3.4.0)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-vibration (3.1.1)
    cordova-sms-plugin (1.0.0)
    cordova-support-android-plugin (1.0.2)
    cordova-support-google-services (1.4.0)
    es6-promise-plugin (4.2.2)
    phonegap-plugin-barcodescanner (8.1.0)

## Affected Platform(s)

- [ ] Android
- [x ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When using the in app browser for authentication with Apple, Facebook or google, IOS prompts me for Face recognition when entering credentials on the keyboard. 

Once face recognition is complete, the keyboard disappears. If i then close the browser, the application is squashed at the top with a large black area where the keyboard was positioned. The application does not resize back to normal with the user of face rec.

If I do the same process but before closing the browser, bring up the keyboard and close it again, the application underneath us resized correctly, so it seems this is isolated to the face recognition ONLY when the keyboard is present.

## Expected Behavior
Once the face recognition is completed and the keyboard is removed, the application resizes back to normal.

## Sample Code or Sample Application Repo

`result = await Browser.open({ url, presentationStyle: 'popover' });`

## Reproduction Steps

1. Open any social login within the browser
2. Open the keyboard 
3. Tap the saved account details
4. Face recognition occurs
5. Close the browser
6. Screen has large black space where keyboard should be

## Other Technical Details
- VSC Mac
- Xcode Version 11.3 (11C29)

`npm --version` output: 6.14.4

`node --version` output: v13.5.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by jcesarmobile** [comment] 2020-04-16 15:43
I still can't reproduce, at least on iOS 12 and don't see anything weird on iPadOS, but my iPad doesn't have FaceID.
In case it only happens on popover presentation, should be fixed by https://github.com/ionic-team/capacitor/pull/2784

**Closed by jcesarmobile** 2020-04-16 15:43 UTC
