### ISSUE TITLE
bug: npx cap sync custom cordova plugin doesn't work

### ISSUE THREAD

**Issue by loremru** [ionic-team/capacitor#7162] opened 2023-12-26 20:35 UTC
Why capacitor doesnt sync my custom cordova plugin?
https://www.npmjs.com/package/kipi-browser

It works with real cordova-in-app-browser, but doesn't work with mine? Where is the difference? What is the rule of detection as a cordova plugin?

**Comment by loremru** [comment] 2024-01-12 19:31
@dallastjames any thoughts?

**Comment by jcesarmobile** [comment] 2024-01-15 12:24
You have to provide a sample app so we can reproduce, as the bot requested.

**Comment by Ionitron** [comment] 2024-01-31 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-31 00:05 UTC
Labels: needs reply, needs reproduction
