### ISSUE TITLE
bug: cap build for android does not sign the APK correctly and/or crashes

### ISSUE THREAD

**Issue by kpturner** [ionic-team/capacitor#6909] opened 2023-09-14 21:03 UTC
### Capacitor Version
```

Latest Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/android: 5.4.0
  @capacitor/ios: 5.4.0

Installed Dependencies:

  @capacitor/cli: 5.4.0
  @capacitor/android: 5.4.0
  @capacitor/core: 5.4.0
  @capacitor/ios: 5.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
android 

### Current Behavior
I want to build an APK so that I can install it on an Android (API 33) emulator WITHOUT running it in order to facilitate a deferred deep link test.  

I therefore tried
```
npx cap build --keystorepath ~/.android/debug.keystore --keystorepass android --keystorealias androiddebugkey --keystorealiaspass android   android
```
but when I drag/drop that to the emulator I get
```
'INSTALL_PARSE_FAILED_NO_CERTIFICATES', message='INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package
```

If I try to force it to sign with `apksigner` like this
```
npx cap build --keystorepath ~/.android/debug.keystore --keystorepass android --keystorealias androiddebugkey --keystorealiaspass android --signing-type apksigner  android
```

I get 
```
✖ Signing Release - failed!
[error] Exception in thread "main" com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum
        supported platform version. Use --min-sdk-version to override
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:420)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
        Caused by: com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported Android
        platform version
        at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:1014)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:296)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:232)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:414)
        ... 1 more
        Caused by: com.android.apksig.apk.ApkFormatException: Missing AndroidManifest.xml
        at com.android.apksig.ApkSigner.getAndroidManifestFromApk(ApkSigner.java:970)
        at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:1012)
        ... 4 more
```
There is no `--min-sdk-version` option on the command so I could not work out how to resolve it.

I could not find any documentation about the `---apksigner` option. I only found it by looking through the code. 

### Expected Behavior
I would like to know how to properly build an APK for manual deployment on API 33

### Code Reproduction
N/A

### Other Technical Details

`npm --version` output:  9.5.0

`node --version` output: v18.15.0

### Additional Context
All included above

**Comment by mr-uzair** [comment] 2023-11-08 03:34
Hi
Are you able to fix this problem ?
I'm facing the same problem while generating and signing .aab file through azure pipeline.

**Comment by kpturner** [comment] 2023-11-08 09:24
I didn't find a solution using capacitor so I do t use it to sign the app anymore. I was initially able to use gradle to sign and build and now use fastlane.

**Comment by tiga05** [comment] 2023-11-08 15:59
Hi,
I stumpled across this issue here, because I have created a very similiar one. But in my case I have provided a minimal working example.
@kpturner Could you please try the minimal working example linked in my issue here? https://github.com/ionic-team/capacitor/issues/7054
Do you get the same issue with this example? In my opinion something is very broken/half finished with that command and/or did never work at all. Maybe thats also why "--signing-type apksigner" is not documented.

And is it possible you explain a little more, how you did create a workaround for this? Maybe an example command?

**Comment by mr-uzair** [comment] 2023-11-08 20:06
Hi, 
Thanks guys. 

I was able to fix this issue. 
          - task: AndroidSigning@3
            inputs:
              apkFiles: '$(Build.SourcesDirectory)/android/app/build/outputs/bundle/$(buildConfiguration)/*.aab'
              apksignerKeystoreFile: '$(keystoreFileName)'
              apksignerKeystorePassword: $(keystorePassword)
              apksignerKeystoreAlias:  $(keyAlias)
              apksignerKeyPassword: $(keyPassword)
              apksignerArguments: --out $(Build.SourcesDirectory)/android/app/build/outputs/bundle/$(buildConfiguration)/*.aab --verbose --min-sdk-version 22
              zipalign: true
            displayName: 'Sign the .aab'


I had to add --min-sdk-version 22 attribute in apksignerArguments.

**Comment by kpturner** [comment] 2023-11-08 21:50
> Hi, 
> 
> Thanks guys. 
> 
> 
> 
> I was able to fix this issue. 
> 
>           - task: AndroidSigning@3
> 
>             inputs:
> 
>               apkFiles: '$(Build.SourcesDirectory)/android/app/build/outputs/bundle/$(buildConfiguration)/*.aab'
> 
>               apksignerKeystoreFile: '$(keystoreFileName)'
> 
>               apksignerKeystorePassword: $(keystorePassword)
> 
>               apksignerKeystoreAlias:  $(keyAlias)
> 
>               apksignerKeyPassword: $(keyPassword)
> 
>               apksignerArguments: --out $(Build.SourcesDirectory)/android/app/build/outputs/bundle/$(buildConfiguration)/*.aab --verbose --min-sdk-version 22
> 
>               zipalign: true
> 
>             displayName: 'Sign the .aab'
> 
> 
> 
> 
> 
> I had to add --min-sdk-version 22 attribute in apksignerArguments. 
> 
> 
> 
> 
> 
> 

Not sure how this relates to using "npm cap build"?

**Comment by kpturner** [comment] 2023-11-08 22:16
> Hi, I stumpled across this issue here, because I have created a very similiar one. But in my case I have provided a minimal working example. @kpturner Could you please try the minimal working example linked in my issue here? #7054 Do you get the same issue with this example and your way to build the app? In my opinion something is very broken/half finished with that command and/or did never work at all. Maybe thats also why "--signing-type apksigner" is not documented.
> 
> And is it possible you explain a little more, how you did create a workaround for this? Maybe an example command?

I don't have an example or a workaround for using `cap build`.  I gave up with it and in any case it was not needed.  
As mentioned before, I resorted to signing and building the app using Android Studio.  Then, when I moved on to needing to do it in a CI process, I started using `fastlane` and their built in `gradle` functionality.

**Comment by jcesarmobile** [comment] 2024-01-18 16:30
Closing as I can't reproduce than the reporter moved to something else. The `--min-sdk-version` should not be needed, it should pick the value from the app's `minSdkVersion` automatically.
It can fail to get the correct version if using an unsupported `apksigner` version, there is one for every SDK, so make sure you are using the version that matches your `compileSdkVersion`.

**Closed by jcesarmobile** 2024-01-18 16:30 UTC
Labels: platform: android
