### ISSUE TITLE
bug: Fail to run Android project after migrating to Capacitor 4

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/capacitor#6048] opened 2022-11-02 18:46 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
App fails to launch

### Expected Behavior
App launches successfully

### Other Technical Details
I ran the migration according to https://capacitorjs.com/docs/updating/4-0. Thought that outdated Cordova plugins could be the reason and therefore transitioned all but one to Capacitor plugins, the one remaining is https://github.com/randdusing/cordova-plugin-bluetoothle

`npm --version` output: 8.19.1

`node --version` output: 18.8.0

### Additional Context
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pepperlfuchs.wilsen, PID: 30590
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.pepperlfuchs.wilsen/com.pepperlfuchs.wilsen.MainActivity}: java.lang.InstantiationException: java.lang.Class<com.pepperlfuchs.wilsen.MainActivity> has no zero argument constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3914)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.InstantiationException: java.lang.Class<com.pepperlfuchs.wilsen.MainActivity> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by Ionitron** [comment] 2022-11-02 22:26
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by willgardner9** [comment] 2022-11-03 16:48
I'm also experiencing this issue on my Capacitor project, migrated from Cap 3 to Cap 4 -- exact same error message. I used the CLI migrate command, but will attempt a manual migration later to see if anything changes 👍

**Comment by NunoSav** [comment] 2022-11-03 16:54
Fixed by renaming `android` folder to something else and running `npx cap add android` and then copying missing files from old folder.

**Comment by jcesarmobile** [comment] 2022-11-03 17:04
glad you figured out

willgardner9, can you create a new issue and provide a sample app where your issue can be reproduced? I'm closing this one since NunoSav solved their issue.

**Closed by jcesarmobile** 2022-11-03 17:04 UTC
Labels: platform: android, needs reproduction
