### ISSUE TITLE
bug: getPlatform returning web running on react production build (external url), but not pointing to live reload webpack server

### ISSUE THREAD

**Issue by scottwilson312** [ionic-team/capacitor#4654] opened 2021-06-01 04:10 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/electron: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/android 2.4.7
  @capacitor/core 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌

```

### Platform(s)
Android

### Current Behavior
I am using React and Capacitor. When I set the server to an ngrok pointed at my development react app,`Capacitorg.getPlatform` returns Android, as expected.

If I build my React project and release it to S3, then point server.url to the site `getPlatform()` returns web!

### Expected Behavior
I'd expect getPlatform to return android and for my plugins to work.

**Comment by scottwilson312** [comment] 2021-06-01 04:15
I've noticed this user on stackoverflow has the same issue.

https://stackoverflow.com/questions/66180885/ionic-3-capacitor-android-build-web-not-native#

**Comment by Ionitron** [comment] 2021-06-01 07:58
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by DmitrySkripkin** [comment] 2021-06-01 12:07
I had similar [issue](https://github.com/ionic-team/capacitor/issues/4329)

**Comment by Ionitron** [comment] 2021-06-17 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-17 00:02 UTC
Labels: needs reply, needs reproduction, platform: android
