### ISSUE TITLE
Cannot find module @ionic-native/geolocation

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/capacitor#627] opened 2018-06-30 05:17 UTC
Getting the above error of `Cannot find module @ionic-native/geolocation` even though I'm using capacitor geolocation. This seems to happen after I updated to beta-0. Am not importing `@ionic-native/geolocation` anywhere in the application.

Was looking for a way to reinstall capacitor. I've npx update, npx copy and npx sync.

**Comment by jcesarmobile** [comment] 2018-06-30 11:02
Where do you get that error? we don't use `@ionic-native/geolocation`

**Comment by ix-xerri** [comment] 2018-06-30 21:57
It loads as a runtime error when I try to load localhost on ionic serve. Removed `@ionic-native/geolocation` from my code and deleted `www` folder but still getting the same runtime error.

**Comment by jcesarmobile** [comment] 2018-06-30 22:01
can you share your app?

**Comment by ix-xerri** [comment] 2018-07-01 06:16
No sorry cannot share.

**Comment by ix-xerri** [comment] 2018-07-01 07:13
I am running `npm run build && npx cap copy` and I get:

`ionic-app-script task: "build"
[09:07:17]  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at beginCatchBlock (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:59853:51)
    at transformAndEmitTryStatement (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:59665:21)
    at transformAndEmitStatementWorker (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:59116:28)
    at transformAndEmitStatement (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:59082:13)
    at transformAndEmitStatements (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:59066:17)
    at transformGeneratorFunctionBody (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:58602:13)
    at visitFunctionExpression (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:58532:37)
    at visitGenerator (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:58472:28)
    at visitor (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:58369:24)
    at visitNodes (/Users/matthewxerri/Documents/git/titanwod/node_modules/typescript/lib/typescript.js:49280:48)`

Here is my package.json

`{
  "name": "xxx",
  "author": "Matthew Xerri",
  "homepage": "xxx",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint --bailOnLintError true",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "test": "ng test"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  "dependencies": {
    "@angular/animations": "5.1.0",
    "@angular/common": "5.1.0",
    "@angular/compiler": "5.1.0",
    "@angular/compiler-cli": "5.1.0",
    "@angular/core": "5.1.0",
    "@angular/forms": "5.1.0",
    "@angular/http": "5.1.0",
    "@angular/platform-browser": "5.1.0",
    "@angular/platform-browser-dynamic": "5.1.0",
    "@angular/platform-server": "5.1.0",
    "@capacitor/android": "^1.0.0-beta.0",
    "@capacitor/cli": "^1.0.0-beta.0",
    "@capacitor/core": "^1.0.0-beta.0",
    "@capacitor/ios": "^1.0.0-beta.0",
    "@firebase/webchannel-wrapper": "^0.2.8",
    "@ionic-native/badge": "^4.7.0",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "^4.7.0",
    "@ionic-native/deeplinks": "^4.7.0",
    "@ionic-native/google-analytics": "^4.7.0",
    "@ionic-native/launch-navigator": "^4.7.0",
    "@ionic-native/push": "^4.7.0",
    "@ionic-native/splash-screen": "^4.7.0",
    "@ionic-native/status-bar": "^4.7.0",
    "@types/googlemaps": "3.26.20",
    "angular2-moment": "^1.8.0",
    "angularfire2": "^5.0.0-rc.5-next",
    "cordova-android": "^7.1.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-badge": "^0.8.7",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-google-analytics": "^1.8.3",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.3.1",
    "firebase": "^4.13.1",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-deeplinks": "^1.0.15",
    "ionicons": "3.0.0",
    "promise-polyfill": "6.0.2",
    "rxjs": "^5.5.10",
    "sw-toolbox": "3.6.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@ionic/app-scripts": "^3.1.10",
    "@types/jasmine": "^2.8.6",
    "@types/node": "^7.0.62",
    "codecov": "^2.3.1",
    "husky": "^0.15.0-rc.13",
    "ionic": "3.20.0",
    "jasmine-core": "^2.99.1",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-mocha-reporter": "^2.2.5",
    "karma-remap-istanbul": "^0.6.0",
    "ts-node": "^3.3.0",
    "tslint": "^5.9.1",
    "tslint-eslint-rules": "^4.0.0",
    "typescript": "2.4.2"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "cordova-plugin-network-information",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "xxx",
  "cordova": {
    "platforms": [
      "ios"
    ],
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-whitelist": {},
      "cordova-sqlite-storage": {},
      "ionic-plugin-deeplinks": {
        "URL_SCHEME": "xxx",
        "DEEPLINK_SCHEME": "https",
        "DEEPLINK_HOST": "xxx",
        "ANDROID_PATH_PREFIX": "/",
        "ANDROID_2_PATH_PREFIX": "/",
        "ANDROID_3_PATH_PREFIX": "/",
        "ANDROID_4_PATH_PREFIX": "/",
        "ANDROID_5_PATH_PREFIX": "/",
        "DEEPLINK_2_SCHEME": " ",
        "DEEPLINK_2_HOST": " ",
        "DEEPLINK_3_SCHEME": " ",
        "DEEPLINK_3_HOST": " ",
        "DEEPLINK_4_SCHEME": " ",
        "DEEPLINK_4_HOST": " ",
        "DEEPLINK_5_SCHEME": " ",
        "DEEPLINK_5_HOST": " "
      },
      "cordova-plugin-google-analytics": {},
      "uk.co.workingedge.phonegap.plugin.launchnavigator": {
        "LOCATION_USAGE_DESCRIPTION": "This app requires access to your location for navigation purposes"
      },
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-badge": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": "null",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": "null"
      }
    }
  }
}
`

**Comment by jcesarmobile** [comment] 2018-07-18 10:46
Ok, closing as we couldn't reproduce and you solved it.

**Closed by jcesarmobile** 2018-07-18 10:46 UTC
