### ISSUE TITLE
bug: Camera.getPhoto allowEditing:true failed but should not

### ISSUE THREAD

**Issue by MockingMagician** [ionic-team/capacitor#5617] opened 2022-05-14 15:01 UTC
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/cli: 3.4.3

### Platform(s)
Android for sure

### Current Behavior

In case you set allowEditing to true and the phone is not able to edit the photo, then it returns a failure even though the photo is taken, you can see the photo in the plugin log but the plugin just returns a failure.

### Expected Behavior

 I don't think this should be the case. It should just return the photo

### Code Reproduction

Just normal use case :

const image = await Camera.getPhoto({
        quality: 90,
        allowEditing: true,
        resultType: CameraResultType.Uri,
        webUseInput: true,
        source: CameraSource.Camera
      })

### Other Technical Details

This bug happened on a samsung galaxy s8

`npm --version` output: 8.1.4

`node --version` output: v14.17.1

**Comment by Ionitron** [comment] 2022-05-16 07:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by MockingMagician** [comment] 2022-05-16 14:15
All the code has already been given. It just throw an error, with message 'Unable to edit image' because mobile phone does not have this funtion implemented inside. So has a workaround, I try one time and if fail, record that user phone can not edit taken pictures, as is:

```js
      let retry, image
      do {
        retry = false
        image = await Camera.getPhoto({
              quality: 90,
              allowEditing: store.state.parameters.device.camera.allowEditing,
              resultType: CameraResultType.Uri,
              webUseInput: true,
              source: CameraSource.Camera
            })
            .catch(async (error) => {
              console.log(error.message)

              if (error.message === 'Unable to edit image') {
                console.log('set allowEditing to false')
                store.commit('parameters/CAMERA_ALLOW_EDITING', false)
                retry = true
              } else if (error.message === 'User cancelled photos app') {
                // do nothing
              } else {
                throw error
              }
            })
      } while (retry)
```

**Comment by Ionitron** [comment] 2022-06-01 00:07
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-01 00:07 UTC
Labels: platform: android, needs reply, needs reproduction
