### ISSUE TITLE
bug:   pushNotificationActionPerformed does not work after a long time of inactive state of the application

### ISSUE THREAD

**Issue by ParzivalBV** [ionic-team/capacitor#6324] opened 2023-02-24 12:10 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/ios: 4.4.0
  @capacitor/android: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

ios

### Current Behavior

There are such listeners, they are bound in create and appStateChange, but if the application is long in the background, pushNotificationActionPerformed stops responding to clicks on the notification, the application opens, but the code is not executed

```
 PushNotifications.removeAllListeners();

      PushNotifications.addListener("registration", (token) => {
        localStorage.FCMToken = token.value.toString();

        const db = getDatabase();
        const Value = ref(db, "Users/" + localStorage.userID);
        get(Value).then((value) => {
          var v = value.val();
          if (v.fcmTokens) {
            if (
              v.fcmTokens.find((x) => x == token.value.toString()) == undefined
            )
              v.fcmTokens.push(token.value.toString());
          } else {
            v.fcmTokens = [token.value.toString()];
          }
          set(ref(db, "Users/" + v.id), v);
        });
      });

      PushNotifications.addListener(
        "pushNotificationReceived",
        (notification) => {
          const data = notification.data.data;
          if (data.EventId) {
            const db = getDatabase();
            const DataEvent = ref(db, "Events/" + data.EventId);
            get(DataEvent).then((Event) => {
              localStorage.setItem("animation", true);
              localStorage.setItem("forwardAnimation", true);

              var newEvent = Event.val();
              newEvent.visibileDate = TransformDateForEvent(newEvent);
              localStorage.NewNotificationEvent = JSON.stringify(newEvent);

              router.push({
                name: "EventPage",
                params: { id: Event.val().id },
              });
            });
          }
        }
      );

      PushNotifications.addListener(
        "pushNotificationActionPerformed",
        (notification) => {
          const data = notification.notification.data;
          if (data.EventId) {
            const db = getDatabase();
            const DataEvent = ref(db, "Events/" + data.EventId);
            get(DataEvent).then((Event) => {
              localStorage.setItem("animation", true);
              localStorage.setItem("forwardAnimation", true);

              var newEvent = Event.val();
              newEvent.visibileDate = TransformDateForEvent(newEvent);
              localStorage.NewNotificationEvent = JSON.stringify(newEvent);

              router.push({
                name: "EventPage",
                params: { id: Event.val().id },
              });
            });
          }
        }
      );
    
```

**Comment by Ionitron** [comment] 2023-03-01 17:30
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-17 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-17 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
