### ISSUE TITLE
bug: Capacitor http request failed on native platforms when response body is null (js null value) and Content-Type is application/json

### ISSUE THREAD

**Issue by dimitr0v** [ionic-team/capacitor#6947] opened 2023-09-29 12:26 UTC
### Capacitor Version

```
Installed Dependencies:

  @capacitor/core: 5.4.1
  @capacitor/cli: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1
```

### Platform(s)

Android and iOS

### Current Behavior

When XHR-Patching is enabled on both Android and iOS platforms and the response body of a GET request is **null** (js null value) and the Content-Type is "application/json", an error is thrown in the native-bridge code which causes the request to fail in the application code.

![http-null-response-bug](https://github.com/ionic-team/capacitor/assets/3835487/0b932cd9-f338-496d-bdc4-6847b1205c3c)

### Expected Behavior

The request should complete successfully and the response body should be **null**, as returned from the native code. When the platform is web it behave in exactly that way.

### Code Reproduction

Using Angular v16.1.6 as a front-end framework.
```js
import { HttpClient } from '@angular/common/http';
// ...
constructor(private http: HttpClient){}
// ...
this.http.get('http://domain.com/api/endpoint').subscribe(res => { // <-- "res" should be null
        console.log(res); // <-- never called
      }, error => {
        console.error(error); // <-- but error is thrown
      });
```

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.16.0

### Additional Context

The error occurs in the native-bridge.ts on [that line](https://github.com/ionic-team/capacitor/blob/3934cf64038cf1983e8ca3e6dba601703e510e13/core/native-bridge.ts#L735) when trying to call **.length** on **nativeResponse.data** and its value is **null**.

**Comment by ChevinDev** [comment] 2024-02-27 16:19
I can confirm this also happens with PUT requests.
The response body of the PUT is null
It will then incorrectly trigger the error interceptor for an 'unknown error'

**Comment by Ionitron** [comment] 2024-03-14 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-03-14 00:05 UTC
Labels: platform: android, platform: ios, needs reproduction
