### ISSUE TITLE
bug: Geolocation Throws An Error If Device Location Services Disabled

### ISSUE THREAD

**Issue by 0xRenshaw** [ionic-team/capacitor#5615] opened 2022-05-13 09:11 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0
  @capacitor/core: 3.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
The latest @capacitor/geolocation is installed, 1.3.1

### Platform(s)

- iOS
- **I am unable to confirm or deny if it occurs on Android**

### Current Behavior

- If the device has 'Location Services' disabled within Settings
- And you request requestPermissions() and/or checkPermissions()
- It will throw an error 

### Expected Behavior

- I would expect it to return a PermissionStatus of 'denied'
- I would not expect it to throw an error and have to handle it differently.
- Error message returned is {message: "Location services are not enabled", errorMessage: "Location services are not enabled"}

### Code Reproduction

- Call either methods below while running on a real world iOS device
- It occurs regardless of destructuring the assignment or not
- const { location } = await Geolocation.checkPermissions();
- const { location } = await Geolocation.requestPermissions({ permissions: ['location'] });
OR
- await Geolocation.checkPermissions();
- await Geolocation.requestPermissions();

### Other Technical Details

`npm --version` output: 6.14.16

`node --version` output: v14.19.0

`pod --version` output (iOS issues only): 1.11.2

**Comment by Ionitron** [comment] 2022-05-13 09:29
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by meerns** [comment] 2022-05-15 13:30
Same issue on android

**Comment by meerns** [comment] 2022-05-15 13:31
I have to open the location setting manually and show it to the user to enable it, it won't show the GPS popup 

``catch (error) {
    if (error.message === 'location disabled') {
      return NativeSettings.open({
        optionAndroid: AndroidSettings.Location,
        optionIOS: IOSSettings.LocationServices,
      });
    }
  }``

**Comment by Ionitron** [comment] 2022-05-31 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-31 00:05 UTC
Labels: needs reply, needs reproduction

**Comment by co-dax** [comment] 2022-08-14 14:39
I have the same issue and I user the following plugin to display native location prompt: [https://ionicframework.com/docs/native/location-accuracy/](url)
