### ISSUE TITLE
bug: media playback on ios unsuccessful: Required client entitlement is missing; Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback'

### ISSUE THREAD

**Issue by mxye** [ionic-team/capacitor#4881] opened 2021-08-03 01:00 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/cli: 3.1.2
  @capacitor/ios: 3.1.2

[success] iOS looking great! 👌
```

### Platform(s)

Mac OS Big Sur 11.5.1
Xcode 12.5.1 (latest)

### Current Behavior

With the html "audio" tag, media playback is unsuccessful. The error messages are

```
2021-08-02 20:46:21.893686-0400 App[14957:2208406] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}>
2021-08-02 20:46:21.895638-0400 App[14957:2208406] [ProcessSuspension] 0x109137d20 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 14957, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}

```

To be more specific, I was using the "audio" tag in my React code like this:

```
<audio controls>
            <source src={audios[0]} type="audio/ogg" />
            <source src={audios[0]} type="audio/mpeg" />
</audio>

```

where audios contains urls to the audio blob that was just recorded. 

The project works fine on the web, no issue with the audio playback. But whenever I try to play the audio in the ios app on a simulator, be it ipad or ipod touch, I get the aforementioned error messages. I've isolated the problem to the "audio" tag not being able to do the playback. 

**_Any idea what causes this? I have looked into it for two full days, and tried many different things. No luck._** 

### Expected Behavior

Audio playback works

### Code Reproduction

I think the "audio" tag code given in the previous section is likely sufficient. But if fuller code is needed, the React code in question is here:
```


import React, { Component } from "react";



import { TiMicrophoneOutline } from 'react-icons/ti';
import { BiSquareRounded } from 'react-icons/bi';

import { VoiceRecorder } from 'capacitor-voice-recorder';

const audioType = "audio/mp3";


class Recorder extends Component {
    constructor(props) {
        super(props);
        this.state = {
            time: {},
            seconds: 0,
            recording: false,
            medianotFound: false,
            audios: [],
            audioBlob: null,
        };
        this.timer = 0;
        this.startTimer = this.startTimer.bind(this);
        this.countDown = this.countDown.bind(this);
    }

    handleAudioPause(e) {
        e.preventDefault();
        clearInterval(this.timer);
        this.mediaRecorder.pause();
        this.setState({ pauseRecord: true });
    }

    handleAudioStart(e) {
        e.preventDefault();
        this.startTimer();
        this.mediaRecorder.resume();
        this.setState({ pauseRecord: false });
    }


    startTimer() {
        //if (this.timer === 0 && this.state.seconds > 0) {
        this.timer = setInterval(this.countDown, 1000);
        //}
    }

    countDown() {
        // Remove one second, set state so a re-render happens.
        let seconds = this.state.seconds + 1;
        this.setState({
            time: this.secondsToTime(seconds),
            seconds: seconds
        });
    }

    secondsToTime(secs) {
        let hours = Math.floor(secs / (60 * 60));

        let divisor_for_minutes = secs % (60 * 60);
        let minutes = Math.floor(divisor_for_minutes / 60);

        let divisor_for_seconds = divisor_for_minutes % 60;
        let seconds = Math.ceil(divisor_for_seconds);

        let obj = {
            h: hours,
            m: minutes,
            s: seconds
        };
        return obj;
    }

    async componentDidMount() {



        navigator.getUserMedia =
            navigator.getUserMedia ||
            navigator.webkitGetUserMedia ||
            navigator.mozGetUserMedia ||
            navigator.msGetUserMedia;

        if (navigator.mediaDevices) {
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            if (this.props.mimeTypeToUseWhenRecording) {
                this.mediaRecorder = new MediaRecorder(stream, { mimeType: this.props.mimeTypeToUseWhenRecording });
            } else {
                this.mediaRecorder = new MediaRecorder(stream);
            }
            this.chunks = [];
            this.mediaRecorder.ondataavailable = e => {
                if (e.data && e.data.size > 0) {
                    this.chunks.push(e.data);
                }
            };
        } else {
            this.setState({ medianotFound: true });


            VoiceRecorder.requestAudioRecordingPermission().then((result) => {
                console.log(result.value);
            });

            // will print true / false based on the status of the recording permission
            VoiceRecorder.hasAudioRecordingPermission.then((result) => console.log(result));
        }

    }

    startRecording(e) {
        e.preventDefault();
        // wipe old data chunks
        this.chunks = [];
        // start recorder with 10ms buffer
        this.mediaRecorder.start(10);
        this.startTimer();
        // say that we're recording
        this.setState({ recording: true });
    }

    stopRecording(e) {
        clearInterval(this.timer);
        this.setState({ time: {} });
        e.preventDefault();

        // stop the recorder
        this.mediaRecorder.stop();
        // say that we're not recording
        this.setState({ recording: false, pauseRecord: false, });
        // save the video to memory
        this.saveAudio();

    }

    handleReset(e) {
        if (this.state.recording) {
            this.stopRecording(e);
        }
        this.setState({
            time: {},
            seconds: 0,
            recording: false,
            medianotFound: false,
            audios: [],
            audioBlob: null
        }, () => {

            this.props.handleReset(this.state);
        });

    }

    saveAudio() {
        // convert saved chunks to blob
        const blob = new Blob(this.chunks, { type: audioType });
        // generate video url from blob
        const audioURL = window.URL.createObjectURL(blob);
        // append videoURL to list of saved videos for rendering
        const audios = [audioURL];
        this.setState({ audios, audioBlob: blob });
        this.props.handleAudioStop({
            url: audioURL + '?playsinline=1',
            blob: blob,
            chunks: this.chunks,
            duration: this.state.time
        });
    }



    render() {
        const { recording, audios, time, medianotFound, pauseRecord } = this.state;
        console.log('audios is', audios);
        const { showUIAudio, title, audioURL } = this.props;
        return (
            <div>
                <div>
                    <div>
                        {!this.props.hideHeader ?
                            <div>
                                <h2>{title}</h2>
                                <span>
                                </span>
                            </div> : null}
                        {!medianotFound ? (
                            <div>
                                <div>
                                    <div>
                                        {audioURL !== null && showUIAudio ? (
                                            <audio webkit-playsinline="true" controls>
                                                <source src={audios[0]} type="audio/ogg" />
                                                <source src={audios[0]} type="audio/mpeg" />
                                            </audio>
                                        ) : null}
                                    </div>
                                    <div>
                                        <span style={{ fontSize: "40px" }}>
                                            {time.m !== undefined
                                                ? `${time.m <= 9 ? "0" + time.m : time.m}`
                                                : "00"}
                                        </span>
                                        <span>:</span>
                                        <span style={{ fontSize: "40px" }}>
                                            {time.s !== undefined
                                                ? `${time.s <= 9 ? "0" + time.s : time.s}`
                                                : "00"}
                                        </span>
                                    </div>
                                    {!recording ? (
                                        <p>Press the microphone to record</p>
                                    ) : null}
                                </div>
                                {!recording ? (

                                    <button shape="circle" size="large" onClick={e => this.startRecording(e)} icon={<Icon component={TiMicrophoneOutline} />} />
                                ) : (
                                    <div >


                                        <button danger shape="circle" type="primary" size="large"
                                            onClick={e => this.stopRecording(e)} icon={<Icon component={BiSquareRounded} />} />

                                        <button danger shape="circle" type="primary" size="large"
                                            onClick={
                                                !pauseRecord
                                                    ? e => this.handleAudioPause(e)
                                                    : e => this.handleAudioStart(e)
                                            }
                                            icon={pauseRecord ? <CaretIcon /> : <PauseIcon />} />

                                    </div>
                                )}
                            </div>
                        ) : (
                            <p style={{ color: "#fff", marginTop: 30, fontSize: 25 }}>
                                Seems the site is Non-SSL
                            </p>
                        )}
                    </div>
                </div>
            </div>
        );
    }
}

export default Recorder;

Recorder.defaultProps = {
    hideHeader: false,
    mimeTypeToUseWhenRecording: null
}


```

### Other Technical Details

I use yarn as the package manager:

`yarn --version` output: 1.22.5

`npm --version` output: 6.14.13

`node --version` output: v12.22.3

`pod --version` output (iOS issues only): 1.10.2

**Comment by Ionitron** [comment] 2021-08-03 11:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-19 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-19 00:03 UTC
Labels: needs reply, needs reproduction

**Comment by danielehrhardt** [comment] 2022-04-23 22:02
Same Issue.
