### ISSUE TITLE
bug: Use a custom icon for a marker with @capacitor/google-maps 1.1.0

### ISSUE THREAD

**Issue by GuillaumeGascon** [ionic-team/capacitor#5797] opened 2022-07-27 07:16 UTC
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

### Platform(s)

Android

### Current Behavior

I've seen in the @capacitor/google-maps documentation that a marker can take an iconUrl property. But when i setup this property with one of my icon, the marker still use the default marker icon.

### Expected Behavior

The marker should use the custom icon i set with iconUrl.

### Code Reproduction

Repo to reproduce : 

https://github.com/GuillaumeGascon/reproduce-google-map-bug

Step: 

- clone the repo;
- cd to the new folder;
- npm i;
- npx cap sync;
- add your API key to environment and android manifest;
- ionic serve or ionic capacitor run <platform>;

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: 14.15.5

### Additional Context

I've tried with relative path, with a link, with the path stored in a variable, any other idea ? Or maybe this functionality isn't working for now ?

Have a nice day !

**Comment by Ionitron** [comment] 2022-07-27 07:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by GuillaumeGascon** [comment] 2022-07-27 10:36
I've edited my initial message with a link to a GitHub repository that reproduce the bug.

**Comment by jcesarmobile** [comment] 2022-08-01 11:31
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1085
check my answer there

**Closed by jcesarmobile** 2022-08-01 11:31 UTC
Labels: platform: android, needs reproduction
