### ISSUE TITLE
Android build terminal support

### ISSUE THREAD

**Issue by shindekaps** [ionic-team/capacitor#529] opened 2018-05-09 04:52 UTC
In Cordova we can easily build android without android studio just using the command 

> cordova build android

. But capacitor don't have build utility for terminal. So it will be great if you add the support for command line build process.
Thanks
Kapil Shinde

**Comment by jcesarmobile** [comment] 2018-05-09 10:25
Closing as duplicate of https://github.com/ionic-team/capacitor/issues/324

In the meantime, you can find how to do it by just using gradlew and adb in the comments here
https://github.com/ionic-team/capacitor/issues/96

**Closed by jcesarmobile** 2018-05-09 10:25 UTC
