### ISSUE TITLE
bug: Ionic 5 angular capacitor ios: some components do not work anymore

### ISSUE THREAD

**Issue by yuyu88** [ionic-team/capacitor#6091] opened 2022-11-16 12:03 UTC
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output: 7.20.5

`node --version` output: v14.15.4

`pod --version` output (iOS issues only): 1.10.2

**Comment by Ionitron** [comment] 2022-11-16 12:15
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-02 00:05 UTC
Labels: needs reply, needs reproduction
