### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by andypotato** [ionic-team/capacitor#7522] opened 2024-06-20 04:53 UTC
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.1.0
  @capacitor/ios: 6.1.0
  @capacitor/core: 6.1.0

[success] iOS looking great! 👌

### Other API Details

```Shell
npm --version
10.4.0

node --version
v18.19.0

pod --version
1.12.1
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

Testing on iPad running IOS 17.5.1 yields the following errors:

```
nw_application_id_create_self NECP_CLIENT_ACTION_GET_SIGNED_CLIENT_ID [80: Authentication error]
Failed to resolve host network app id
```

Seems very similar to [this issue with Cordova](https://github.com/apache/cordova-ios/issues/1440) (solution included)

As a result, no network access is possible (eg. to APIs) so this is rather critical.

### Expected Behavior

Network access working normally

### Project Reproduction

n/a

**Comment by BenRacicot** [comment] 2024-06-25 18:27
Getting this after upgrading to `^6` 
See also [apple.com/thread/25564](https://discussions.apple.com/thread/255647899?sortBy=best)

**Comment by qliqdev** [comment] 2024-07-05 18:36
the same in capacitor ios  5.7.6

**Comment by jcesarmobile** [comment] 2024-07-08 11:43
closing since no sample app was provided and I can't reproduce network loss

**Closed by jcesarmobile** 2024-07-08 11:43 UTC
Labels: needs reproduction
