### ISSUE TITLE
bug: App.addListener('appStateChange') Pixel 5 not firing

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/capacitor#5601] opened 2022-05-08 13:47 UTC
### Capacitor Version
3.5.1

### Platform(s)
Android Pixel 5 API 32
You can use the Android Simulator to reproduce. 
![image](https://user-images.githubusercontent.com/19570043/167299099-d0145869-8494-455b-ae12-d9382959165d.png)

### Current Behavior
App.addListener('appStateChange') should fire when the App go into pause. 
On other Android Phones this fires when i press the square on Android or when i move the App up to see all open Apps. 

### Expected Behavior
The Event appStateChange should fire when you move the App up hold 1-2 Seconds to see the open Apps. 

### Code Reproduction
Add App.addListener('appStateChange') check when it fires. 

### Other Technical Details
`npm --version` output:
8
`node --version` output:
16

**Comment by Ionitron** [comment] 2022-05-09 08:13
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-25 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-25 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
