### ISSUE TITLE
[Bug]: Calling plugin methods uses a different instance of the plugin each time?

### ISSUE THREAD

**Issue by Linksku** [ionic-team/capacitor#7232] opened 2024-02-06 10:14 UTC
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[error] Xcode is not installed
[success] Android looking great! 👌

### Other API Details

```Shell
@codetrix-studio/capacitor-google-auth v3.3.6
```

### Platforms Affected

- [ ] iOS
- [ ] Android
- [X] Web

### Current Behavior

When using the GoogleAuth plugin from https://github.com/CodetrixStudio/CapacitorGoogleAuth, calling methods on the same object creates multiple instances of the object. I.e. if I call `GoogleAuth.method1` and log `this` within that method, then call `GoogleAuth.method2` and log `this` within that method, the 2 `this` are different. I don't think this issue is specific to that plugin, it seems like it has to do with Capacitor's usage of a proxy.

![Screenshot 2024-02-06 020715](https://github.com/ionic-team/capacitor/assets/7908179/8a080e7b-7349-4400-845f-32f23929330a)

### Expected Behavior

When calling different methods on the same object, `this` should remain the same.

### Project Reproduction

https://github.com/CodetrixStudio/CapacitorGoogleAuth

### Additional Information

I'm mostly looking for documentation on why Capacitor plugins use a proxy and how it works. If it's expected that Capacitor plugin methods create new object instances each time, could this be documented somewhere?

**Comment by jcesarmobile** [comment] 2024-02-06 11:58
closing as invalid since no reproduction was provided

**Closed by jcesarmobile** 2024-02-06 11:58 UTC
Labels: triage
