### ISSUE TITLE
Failed to use cordova-plugin-camera-preview

### ISSUE THREAD

**Issue by arielhernandezmusa** [ionic-team/capacitor#1732] opened 2019-07-03 20:00 UTC
When tried to used cordova-plugin-camera-preview I get this error

o Native Cordova ->    
CameraPreview   
startCamera   
CameraPreview756259444   
["options": [0, 0, 414, 736, front, 1, 0, 0, 1, 0, 0, 0]]   
2019-07-03 16:53:06.683542-0300 App[9796:1932987] Metal GPU Frame Capture Enabled
2019-07-03 16:53:06.684129-0300 App[9796:1932987] Metal API Validation Enabled
2019-07-03 16:53:06.750515-0300 App[9796:1932987] *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<CameraRenderController: 0x145e1d450> should have parent view controller:(null) but actual parent is:<Capacitor.CAPBridgeViewController: 0x145d0fd30>'

I used it without Ionic, I build a mobile app with React JS and Capacitor

**Comment by bryplano** [comment] 2019-07-03 20:11
@arielhernandezmusa - do you have a sample repo / app that exhibits the error?

**Comment by arielhernandezmusa** [comment] 2019-07-03 22:26
@bryplano , I just pushed my example to this repo

https://github.com/arielhernandezmusa/react-capacitor.git

**Comment by arielhernandezmusa** [comment] 2019-07-03 22:46
In android simulator works fine

**Comment by Bktechmasala** [comment] 2019-07-06 17:14
watch this video to solved all problems capacitor camera plugin https://youtu.be/EPysW31oryk

**Comment by arielhernandezmusa** [comment] 2019-07-06 18:00
@Bktechmasala thanks, but what I need is sometime like this:

![IMG_4067](https://user-images.githubusercontent.com/12831947/60759628-ce1c9500-9ffe-11e9-9a1d-bcfd531b9332.png)

where I can add an overlay to camera

**Comment by jcesarmobile** [comment] 2019-07-16 17:06
the problem is the plugin tries to add the camera view on the webview's superview, but in Capacitor the view structure is slightly different from Cordova and the webview is already the top view, there is no superview, so the plugin won't work on iOS

Closing as incompatible

**Closed by jcesarmobile** 2019-07-16 17:06 UTC

**Comment by MichalKliment** [comment] 2019-08-17 10:36
Hello @jcesarmobile ,
is there any alternative (in the future) how to use camera layer in own component in both platforms, please, or this option will be no longer able to use?

**Comment by arielhernandezmusa** [comment] 2019-08-17 11:29
You can try https://www.npmjs.com/package/capacitor-camera-preview

**Comment by arielhernandezmusa** [comment] 2019-08-17 11:33
That plugin is based con cordova-camera-preview, but updated to use capacitor’s webview

**Comment by craigster1991** [comment] 2020-06-23 15:14
Hello, I'm having this issue with Ionic 5, despite it being listed as "compatible" on the Ionic documentation...
https://ionicframework.com/docs/native/camera-preview

Is there a known fix / something that should be done that's no in the Ionic documentation?

**Comment by GreenRidingHood** [comment] 2020-07-09 12:27
@craigster1991  did you find solution, i am trying to use my @ionic/react capacitor ios app , cordova-plugin-camera-preview, but crushing at xcode.. 
<img width="777" alt="Screen Shot 2020-07-08 at 11 41 51 AM" src="https://user-images.githubusercontent.com/17296724/87040014-a8980d80-c1b5-11ea-8902-a65cc07c822e.png">

**Comment by craigster1991** [comment] 2020-07-17 11:11
> @craigster1991 did you find solution, i am trying to use my @ionic/react capacitor ios app , cordova-plugin-camera-preview, but crushing at xcode..
> <img alt="Screen Shot 2020-07-08 at 11 41 51 AM" width="777" src="https://user-images.githubusercontent.com/17296724/87040014-a8980d80-c1b5-11ea-8902-a65cc07c822e.png">
> 
> *this patch helped me
> #3177

@GreenRidingHood To be honest, I was in a time-locked situation and so had to resort to the standard camera plugin, which utilises the native viewfinder, shutter button etc.

**Comment by mateoc10** [comment] 2020-07-17 19:26
@GreenRidingHood Same thing happens to me. I can't figure out how to make it work

**Comment by bravoivang** [comment] 2021-03-08 15:31
The preview camera plugin is running in other webview. There is no way to render html over the preview. 
There will be a fix for this?
