### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/capacitor#1709] opened 2019-06-25 23:28 UTC
Ability to use the locally installed chromium instance (chrome, or webview)

Most liked issue of electron
https://github.com/electron/electron/issues/673

Solved by Google Carlo
https://github.com/GoogleChromeLabs/carlo

This could be marketed as the ability to have far lower Binary size than native apps!
As native apps or hybrids such as react native or flutter which all have redundant runtimes.

**Comment by jcesarmobile** [comment] 2019-06-25 23:35
Duplicate of https://github.com/ionic-team/capacitor/issues/1622

**Closed by jcesarmobile** 2019-06-25 23:35 UTC
