### ISSUE TITLE
bug: A large number of console.log clogs the device memory

### ISSUE THREAD

**Issue by Eugeni987** [ionic-team/capacitor#6044] opened 2022-11-01 09:26 UTC
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/ios: 4.0.1

### Platform(s)

ios

### Current Behavior

when I use ngxs logger for the state of the stents on the front end, the RAM of the device is clogged. I think it can be reproduced with a large number of console.log(data)

### Expected Behavior

a lot of console.log should not fill up the RAM of the device so much

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

I assume that there is a problem in 'capconsoleplugin' because when commenting on the 'log' method, the memory was not clogged so much

**Comment by Ionitron** [comment] 2022-11-01 13:14
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-17 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-17 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction
