### ISSUE TITLE
[Bug]: duplicate HTTP header Cookie

### ISSUE THREAD

**Issue by ermolaev** [ionic-team/capacitor#7221] opened 2024-01-29 14:31 UTC
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0
  @capacitor/android: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Other API Details

```Shell
node --version
v20.10.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

duplicate HTTP header `Cookie`

### Expected Behavior

single HTTP header `Cookie`

### Project Reproduction

.

### Additional Information

```js
const config: CapacitorConfig = {
  appId: 'com.test.test',
  appName: 'test',
  webDir: 'www',
  server: {
    allowNavigation: ['https://54cf-80-246-81-186.ngrok-free.app'],
    cleartext: true
  }
}
```

![image](https://github.com/ionic-team/capacitor/assets/938305/9fbea701-fc1e-464b-ad64-1462185824f2)

**Comment by ermolaev** [comment] 2024-02-13 16:38
ngrok set cookie in first visit

on next runs app, capacitor will be duplicate cookie header

example app really very simple, but reproduce bug

insted ngrok and static `index.html `you can use http server, but http server, may have its own logic for processing double headers, Rails for example, combines them into one header, but separates them with a comma

```
Cookie: a=1
Cookie: a=1
```
in rails convert to `Cookie: a=1, a=1`

**Comment by jcesarmobile** [comment] 2024-02-13 17:04
I ran ngrok with the command the README said and there are no ngrok cookies, not on the header as your images show, nor on the Cookies of the Application section of Chrome dev tools.

**Comment by ermolaev** [comment] 2024-02-13 17:18
recording video https://disk.yandex.ru/d/cyjJmaS2Kn5RbA

**Comment by jcesarmobile** [comment] 2024-02-13 18:06
I did that, but looks like the cookie is being set on the "you are about to visit xxx" screen, which in my case doesn't appear.
I'm using ngrok 3.6.0 just installed it from homebrew and it's a free account (saying this since the message says you should use a paid acount to get rid of the screen), so not sure why I don't get that screen, but I can't reproduce.

**Comment by ermolaev** [comment] 2024-02-13 18:27
I updated repo https://github.com/ermolaev/cap-cookie-problem/commit/ef281fbbd7c30e09d92cbc55dbff70e3da83d588

press to button `REFRESH` in emulator

cookie `user=John` should sending
![image](https://github.com/ionic-team/capacitor/assets/938305/efe5818a-4d70-4b98-b023-35cb688fb39f)

**Comment by jcesarmobile** [comment] 2024-02-13 18:36
thanks for the update, I could reproduce now

the issue if fixed in Capacitor 6 (it's in RC state) since this was caused by the way the javascript was injected using a native connection and in Capacitor 6 it's injected in a different way, so the issue is not present, but the change can't be backported to Capacitor 5, so your only solution is to move to Capacitor 6 despite it's still RC or wait for the final release in a few weeks

**Closed by jcesarmobile** 2024-02-13 18:36 UTC
Labels: platform: android, needs reproduction

**Comment by ermolaev** [comment] 2024-02-13 18:52
I checked 6.0.0-rc.0, problem is not reproduce 👍

@jcesarmobile can you show the commit that solved this problem, I want to explore it)

**Comment by jcesarmobile** [comment] 2024-02-14 08:57
It was this one https://github.com/ionic-team/capacitor/pull/7199 but because this one was done first https://github.com/ionic-team/capacitor/pull/7135

Capacitor 5 injects javascript by reading the html files and appending the javascript code in the `<head>` tag, and in Capacitor 6 it uses a new API that google added that injects the javascript into the WebView itself, so no file manipulation is needed and solved several issues that were caused by that.
