### ISSUE TITLE
bug: click statusbar can not fire 'statusTap' event on ios platform

### ISSUE THREAD

**Issue by 2018Cool** [ionic-team/capacitor#2452] opened 2020-02-19 08:01 UTC
# Bug Report
click statusbar can not fire 'statusTap' event on ios platform
## Capacitor Version

`npx cap doctor` output:
Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.5.0

  @capacitor/core 1.5.0

  @capacitor/ios 1.5.0

  Found 0 Capacitor plugins for ios:

## Affected Platform(s)

- [x] iOS

## Sample Code or Sample Application Repo

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  constructor() {
    window.addEventListener('statusTap', function () {
      console.log("statusbar tapped");
    });
  }

}

```

**Comment by jcesarmobile** [comment] 2020-02-19 14:18
duplicate of https://github.com/ionic-team/capacitor/issues/2109

**Closed by jcesarmobile** 2020-02-19 14:18 UTC
