### ISSUE TITLE
bug: Filesystem.copy without specifying a source directory results in a crash

### ISSUE THREAD

**Issue by BARNZ** [ionic-team/capacitor#6114] opened 2022-11-24 01:41 UTC
### Capacitor Version

```
npx cap doctor
[warn] The hideLogs configuration option has been deprecated. Please update to use loggingBehavior instead.
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

Android, have not tested if this problem occurs on iOS

### Current Behavior
I have the following file that I want to copy to another directory. Trying to do this causes a crash:

```
const sourcepath = 'content://com.android.externalstorage.documents/document/primary%3ADCIM%2FCamera%2FIMG_20220928_162028.jpg'
const targetFilepath = 'Media/my-photo.jpg'

Filesystem.copy({
    from: sourcepath,
    to: targetFilepath,
    toDirectory: Directory.External
})
```

It seems that `Filesystem.copy` requires the source `directory` parameter to be specified, but none of the options seems to work. Following the instructions here shows that I should be able to omit directory if I have a fullpath: 

https://capacitorjs.com/docs/apis/filesystem#understanding-directories-and-files

> Additionally, the Filesystem API supports using full file:// paths, or reading content:// files on Android. Simply leave out the directory param to use a full file path.

### Expected Behavior
The file should be copied to the target filepath without crashing

### Code Reproduction
See above example

### Other Technical Details
Testing on an actual android device (OnePlus GM1910) on Android 11

`npm --version` output: 8.19.3

`node --version` output: v18.8.0

A workaround I have tried is to use:

```
return Filesystem.writeFile({
    data: (await Filesystem.readFile({ path: sourcepath })).data,
    path: targetFilepath,
    directory: Directory.External
})
```

But this can cause out of memory errors when reading large files in base64

### Crash / Exception Details

```
FATAL EXCEPTION: CapacitorPlugins

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:730)
    at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:125)
    at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:721)
    at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
    at android.os.Handler.handleCallback(Handler.java:938) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:233) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
    at com.capacitorjs.plugins.filesystem.Filesystem.getDirectory(Filesystem.java:186)
    at com.capacitorjs.plugins.filesystem.Filesystem.getFileObject(Filesystem.java:210)
    at com.capacitorjs.plugins.filesystem.Filesystem.copy(Filesystem.java:92)
    at com.capacitorjs.plugins.filesystem.FilesystemPlugin._copy(FilesystemPlugin.java:396)
    at com.capacitorjs.plugins.filesystem.FilesystemPlugin.copy(FilesystemPlugin.java:376)
```

**Comment by Ionitron** [comment] 2022-11-28 09:48
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-14 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-14 00:05 UTC
Labels: platform: android, platform: ios, needs reply, needs reproduction
