### ISSUE TITLE
bug: Method is undefined when uploading multipart/form-data 

### ISSUE THREAD

**Issue by altinselimi** [ionic-team/capacitor#6726] opened 2023-07-13 11:32 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.2.0
  @capacitor/core: 5.2.0
  @capacitor/android: 5.2.0
  @capacitor/ios: 5.2.0

Installed Dependencies:

  @capacitor/cli: 5.2.0
  @capacitor/core: 5.2.0
  @capacitor/android: 5.2.0
  @capacitor/ios: 5.2.0

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main```

### Platform(s)
iOS



### Current Behavior
I am using CapacitorHTTP plugin to make http calls. That automatically works with Axios so I assume the existing code does not need to be changed. Its a simple HTTP POST request that sends a file. But when I check out in Safari inspector, it says that the method is UNDEFINED, and Im guessing its going as GET because then its throwing a 'resource exceeds maximum size' error.



### Expected Behavior
Attachment should be successfully uploaded and there should be no `resource exceeds maximum size` error. Also the method of the request should be POST.


### Code Reproduction
https://github.com/altinselimi/capacitor-repro-bug


### Other Technical Details

`npm --version` output: 9.5.0

`node --version` output: v18.15.0

`pod --version` output (iOS issues only): 1.12.1

### Additional Context
I have tried using both Axios syntax:
`Axios.post({...})` and `Axios({method: 'post' ,...})` but none of them seem to work.

**Comment by altinselimi** [comment] 2023-07-13 12:11
Here is a screenshot:
[Screenshot](https://i.imgur.com/C8LtnxO.png)

**Comment by altinselimi** [comment] 2023-07-14 11:41
This has completely broken all POST requests, which were working fine previously

**Comment by mikelnorth** [comment] 2023-07-14 23:06
Seeing the same thing using `XMLHttpRequest`. Can not send POST requests

```
  const request = new XMLHttpRequest();
    request.open(
      'POST',
      `https://exampleurl`
    );
```

Network shows GET instead of POST

**Comment by 5uper** [comment] 2023-07-17 13:44
Hi @jcesarmobile

i got the same issue since version 5.2.0.

i described shortly how to reproduce it and what is the possible solution. https://github.com/ionic-team/capacitor/pull/6725#issuecomment-1637672179

**Comment by jcesarmobile** [comment] 2023-07-17 16:40
fixed in https://github.com/ionic-team/capacitor/pull/6740

**Closed by jcesarmobile** 2023-07-17 16:40 UTC
Labels: needs reproduction
