### ISSUE TITLE
[Feature]: Error Handling with nonexistent files and @capacitor/filesystem

### ISSUE THREAD

**Issue by ecc521** [ionic-team/capacitor#7515] opened 2024-06-17 00:40 UTC
### Description

A method of determining whether an error was caused by the file not existing. 

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

An enum for the file not found error message, allowing for specific error causes to be checked. As is, the message is different across platforms, and might change in the future (plus hardcoding is bad practice here)

### Alternatives

An exists methods to determine if a file exists (potentially problematic if file created after called but before read)

**Comment by jcesarmobile** [comment] 2024-06-17 09:46
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/326

**Closed by jcesarmobile** 2024-06-17 09:46 UTC
Labels: triage
