### ISSUE TITLE
Camera throws console error after picture (PWA)

### ISSUE THREAD

**Issue by Bforsyth1234** [ionic-team/capacitor#729] opened 2018-08-13 15:12 UTC
I am getting a console error after taking a picture with my chrome browser. Below is a screen shot of the error and a link to my github project. 

![capture](https://user-images.githubusercontent.com/4528782/44040543-94595220-9ee9-11e8-9285-e6531f5b34e0.PNG)

[https://github.com/Bforsyth1234/capacitor-camera-demo](url)

**Comment by jcesarmobile** [comment] 2018-08-17 12:27
I just cloned your project, and ran
npm install
ionic serve

And worked as expected.

What's your OS? Chrome version?

**Comment by mlynch** [comment] 2018-10-05 21:42
Can you try `@ionic/pwa-elements` 1.0.0? https://github.com/ionic-team/capacitor/issues/658#issuecomment-427504179

**Comment by jcesarmobile** [comment] 2019-05-01 12:08
Closing as I can't reproduce with latest pwa-elements, so it's probably fixed.

**Closed by jcesarmobile** 2019-05-01 12:08 UTC
