### ISSUE TITLE
bug: addListener(appUrlOpen) is never triggered on iOS

### ISSUE THREAD

**Issue by RavioliMuyCalor** [ionic-team/capacitor#2929] opened 2020-05-14 16:57 UTC
# Bug Report

## Capacitor Version
`npx cap doctor` output:

Latest Dependencies:

-   @capacitor/cli: 2.1.0

-   @capacitor/core: 2.1.0

-   @capacitor/android: 2.1.0

-   @capacitor/ios: 2.1.0

Installed Dependencies:

-   @capacitor/cli 1.5.1

-   @capacitor/core 1.5.1

-   @capacitor/android 1.5.1

-   @capacitor/ios 1.5.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

With the app open in the background, I open a deeplink that successfully opens the app. However, once the app is running, the listener appUrlOpen is not called and I can't get the url.

If the app is closed and I open a deeplink. The app opens and getLaunchUrl() is called but the result is always empty, no matter what link I used to open it.

## Expected Behavior

If the app is open in the background and I open a deeplink, the listener appUrlOpen is called and allows me to get the url with which the app was open.

If the app is closed and I open a deeplink, getLaunchUrl() is called and gives the url with which the app was open.

## Sample Code or Sample Application Repo

```
          Plugins.App.addListener('appUrlOpen', (urlOpen:any) => {
            // is never called
            this.ngZone.run(() =>{
              console.log('App URL Open', urlOpen);
              this.navigate(urlOpen.url);
            })
```

```
  async getLaunchUrl() {
    await Plugins.App.getLaunchUrl().then( urlOpen => {
      console.log('LAUNCH URL GOT ', urlOpen);        // <- urlOpen is always empty
      this.state.launchUrl = urlOpen.url;
      if(urlOpen.url){
        console.log('Navigating to URL ', urlOpen);
        this.navigate(urlOpen.url);
      }
    });
  }
```

## Reproduction Steps

Open a deeplink on an iOS device on iOS 13.4 with the app running in the background and see if it prints the url.
Same steps but with the app closed.

## Other Technical Details

`npm --version` output: 6.13.4

`node --version` output: v12.16.1

`pod --version` output (iOS issues only): 1.9.0

## Other Information

The feature works perfectly on Android, no problem

On iOS the url is successfully caught natively by the SceneDelegate on an Ipad Pro with iOS 13.4. I can print it in swift. But not by Capacitor. I've spent a few days on it to make sure it wasn't a problem with the iOS deeplink setup but everything seems to be working fine. That's why I'm suspecting Capacitor to mess something up.

I've tried other listeners to make sure it wasn't a global issue and appStateChange works fine, it really is a specific issue with URL related stuff on iOS

Good luck with it guys !

**Comment by jcesarmobile** [comment] 2020-05-14 17:16
can you update to Capacitor 2.1.0 and provide a sample app where it can be reproduced?

**Comment by RavioliMuyCalor** [comment] 2020-05-20 14:31
Hi ! Sorry for the delay. I've tried updating to 2.1.0 but it still behaves the same. 

The only sample I can give you is this simple src folder since every other configuration is domain association and I can't send that. I don't know if there's a way for you to hook it up to a test domain and run the app on a device with iOS 13.

Other than the configurations, the app component itself behaves the same as the one we use on our app. So if this one works for you and displays the launch url correctly I guess the problem would come from something else.

It's pretty annoying to reproduce with all these domain associations, especially with iOS :/

[src.zip](https://github.com/ionic-team/capacitor/files/4657410/src.zip)

**Comment by jcesarmobile** [comment] 2020-05-22 11:45
that's not a valid sample app, you should commit the whole app, including package.json and ios folder

anyway, closing the issue, I can't reproduce on my own app

**Closed by jcesarmobile** 2020-05-22 11:45 UTC
Labels: needs-reply

**Comment by qnlbnsl** [comment] 2020-09-26 21:28
I'm having the same issue, only appStateChange works

**Comment by qnlbnsl** [comment] 2020-09-27 04:05
So I managed to bypass the issue somewhat. 
I manually set the listener by using 
Capacitor.addListener('App', 'appUrlOpen', (data) => {
    //Handle universal links here
    console.log(data.url.split('/__/'));
  });

the following did not work. 
App.addListener('',(data)=>{
  console.log(data)
})

**Comment by LiLeiAndroid** [comment] 2020-11-19 03:25
I still have this problem, have you solve it? It work fine on Android, but no response on ios.

**Comment by stewones** [comment] 2021-03-08 23:19
maybe you all are in need of `getLaunchUrl()`. the `appUrlOpen` only works if the app is already open 🤷‍♂️

https://capacitorjs.com/docs/apis/app#getlaunchurl

**Comment by Flos** [comment] 2021-04-21 22:12
I see that the customeUrl schema callback is triggering the CAPBridge.handleOpenUrl

```
 func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    // Called when the app was launched with a url. Feel free to add additional processing here,
    // but if you want the App API to support tracking app url opens, make sure to keep this call
    print("url = \(url.absoluteString )")
    return CAPBridge.handleOpenUrl(url, options)
  }
```

But nothing happens after the CAPBridge.handleOpenUrl call
```
/**
   * Handle an openUrl action and dispatch a notification.
   */
  public static func handleOpenUrl(_ url: URL, _ options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
    NotificationCenter.default.post(name: Notification.Name(CAPNotifications.URLOpen.name()), object: [
      "url": url,
      "options": options
    ])
    NotificationCenter.default.post(name: NSNotification.Name.CDVPluginHandleOpenURL, object: url)
    CAPBridge.lastUrl = url
    return true
  }
```

**Comment by Flos** [comment] 2021-04-21 22:16
Duplicate of #1875

**Comment by j-jalving** [comment] 2021-05-05 23:44
This issues popped up for me just now after working perfectly before. The fix suggested by @qnlbnsl works, but I am wondering why the documented way (using App.addListener) suddenly isn't working anymore. I did update both iOS (14.5) and xcode (12.5) recently.

**Comment by nakano-shingo** [comment] 2021-05-18 12:33
I'm having the same issue too.
XCode version 12.5 & iOS(14.5)

**Comment by TheNemus** [comment] 2021-08-16 16:03
Me too;
Capacitor 3
iOS 14.5
