### ISSUE TITLE
bug: Cannot give access to fileSystem on android13

### ISSUE THREAD

**Issue by rbalet** [ionic-team/capacitor#5999] opened 2022-10-17 08:09 UTC
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 4.3.0    
  @capacitor/core: 4.3.0   
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

### Platform(s)

Android 13

### Current Behavior

Cannot give access to the Filesystem

![image](https://user-images.githubusercontent.com/44493964/196123406-7c0c271b-1ac1-4e67-8362-7afa03efaf11.png)

### Expected Behavior

Being able to give access to the Filesystem (like on android 13)
![image](https://user-images.githubusercontent.com/44493964/196123492-932acd4f-aa7b-4f05-b34d-3839005655ef.png)

### Code Reproduction

Inside the `AndroidManifest.xml`
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

```typescript
  geFilesystemAccess(): Promise<boolean> {
    return new Promise(async (resolve) => {
      const status = await Filesystem.checkPermissions()
      const state = status.publicStorage

      if (state === 'granted') {
        console.log('granted')
      } else if (state === 'denied') {
        console.log('denied') // <-- It's always denied
      } else {
        Filesystem.requestPermissions()
      }
      return resolve(false)
    })
  }
```
Then 

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v16.17.1

`pod --version` output (iOS issues only):

### Additional Context

For what I see above android 13 we'll need to give a more granular permissions.  

https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

But what I'm trying to read yet are pdf and not Images, photos or videos.

**Comment by Ionitron** [comment] 2022-10-17 08:31
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-02 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-02 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
