### ISSUE TITLE
bug: error: `package android.* does not exist` after Capacitor 4 migration

### ISSUE THREAD

**Issue by robingenz** [ionic-team/capacitor#5824] opened 2022-08-04 11:11 UTC
### Capacitor Version

```
$ npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/ios: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

- Android

### Current Behavior

I am getting the following error message when building the app in Android Studio since migrating to Capacitor 4:

```
> Task :robingenz-capacitor-screen-orientation:generateDebugRFile
/home/runner/work/capacitor-plugin-demo/capacitor-plugin-demo/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java:3: error: package android.graphics does not exist

import android.graphics.Bitmap;
                       ^
> Task :capacitor-android:compileDebugJavaWithJavac
/home/runner/work/capacitor-plugin-demo/capacitor-plugin-demo/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java:4: error: package android.net does not exist
import android.net.Uri;
                  ^
/home/runner/work/capacitor-plugin-demo/capacitor-plugin-demo/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java:5: error: package android.webkit does not exist
import android.webkit.WebResourceError;
                     ^
/home/runner/work/capacitor-plugin-demo/capacitor-plugin-demo/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java:6: error: package android.webkit does not exist
import android.webkit.WebResourceRequest;
                     ^
/home/runner/work/capacitor-plugin-demo/capacitor-plugin-demo/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java:7: error: package android.webkit does not exist
import android.webkit.WebResourceResponse;
                     ^
...
```

See full output [here](https://github.com/robingenz/capacitor-plugin-demo/runs/7670124074?check_suite_focus=true). 

These are my changes: https://github.com/robingenz/capacitor-plugin-demo/pull/762/files

I used `npx cap migrate` for migration.

### Expected Behavior

No build errors.

### Code Reproduction

See https://github.com/robingenz/capacitor-plugin-demo.
If you like I will create a smaller demo app. But maybe you already have an idea.

### Other Technical Details

`npm --version` output: 8.13.2

`node --version` output: v16.13.1

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment] 2022-08-04 11:28
The problem is the migrator didn't change `classpath 'com.android.tools.build:gradle:4.2.0'` to `classpath 'com.android.tools.build:gradle:7.2.1'`.
It's happening because you didn't have `classpath 'com.google.gms:google-services:xxx'`.
If you run migrate again it should fix the problem, but shouldn't fail to change `classpath 'com.android.tools.build:gradle:xxx'` if `classpath 'com.google.gms:google-services:xxx'`. isn't present, will look into that, thanks for the sample app and PR to easily see the changes!

**Comment by robingenz** [comment] 2022-08-04 11:45
Great, that worked! Thank you for your fast reponse!

**Comment by jcesarmobile** [comment] 2022-08-04 11:46
reopening since it's a problem on the migrator that should be fixed

**Closed** 2022-08-04 15:10 UTC
Labels: platform: android
