### ISSUE TITLE
Improve performance of `sync` on iOS

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor#3991] opened 2020-12-23 23:01 UTC
In Capacitor 3, we split out all the plugins into their own iOS frameworks, which means each needs to be compiled separately before the app can be compiled. In an app with ~15 core plugins, `sync` took ~3 seconds in Capacitor 2 and ~10 seconds in Capacitor 3.

ideas:
- https://github.com/leavez/cocoapods-binary
- https://swift.org/package-manager 🤔

**Comment by jcesarmobile** [comment] 2021-01-07 13:19
sync doesn't do any compiling, it just does `pod install`.
The compiling is done the first time you run from Xcode and I think it doesn't recompile if there are no changes in the Pods.

So the increase in time is probably related to sync running `pod install` and having a lot more dependencies.
sync deletes the `Podfile.lock`, that means a full reinstall is done every time.

At the moment we have a `--deployment` param that can be used, it makes the CLI to not delete the `Podfile.lock` and use the files from `Pods` folder, but it's only good if no new dependencies were added.

The deletion of `Podfile.lock` is done because of a CocoaPods bug, might be fixed by now, so we could do some tests.

**Comment by dwieeb** [comment] 2021-01-07 17:47
Thanks! Those are good ideas to try.

Regarding deleting the `Podfile.lock`, we could generate a `capacitor.plugins.json` file for iOS and if the file changes during `sync` we know we need to delete the lock file.

**Comment by sisoje** [comment] 2021-02-02 13:17
sync also does some file preparation for cordova-plugins, right?

my probem is that we can not skip pod install, if we could it would increase the speed and also be runnable on ubuntu

**Comment by dwieeb** [comment] 2021-02-02 17:31
Interesting. I wonder if it makes more sense to do the native project file manipulations during `copy`, which would mean `update` would _just_ be for invoking gradle/CocoaPods. Maybe this would make each command more "pure".

**Comment by jcesarmobile** [comment] 2021-02-02 17:58
**copy** was supposed to only **copy** the assets folder, **update** was supposed to **update** the cordova plugins project and capacitor files.
Of course, updating the cordova-plugins project involves copying some files, so we can argue that it might make more sense on the copy command, but I think changing the behavior at this point won't be good for users because we recommend to run update after installing plugins, including cordova plugins, so if it would require to run copy instead of update they will get confused.

**Comment by dminkovsky** [comment] 2021-06-14 12:30
> sync deletes the Podfile.lock

Isn't this... problematic? I don't have much experience with CocoaPods specifically, so I'm sorry if I'm ignorant about this particular package manager, but in other package managers the purpose of the lock file is to lock dependencies in place, which is critical if you want reproducible builds. Deleting the lock file is like pulling the rug out from under the developer. I didn't know know that CocoaPods had a lock file or that `cap update` deleted it. Now that I know, I will be incredibly weary of running `update`. I mean, unless I'm misunderstanding something, `cap update` is truly dangerous. Just because semantic versioning exists doesn't mean that people use it correctly or don't make mistakes. I see that `Podfile.lock` is included in the default `.gitignore` (why?) so I will remove it from `.gitignore` and commit it. Seems like the only way to maintain sanity. I would really appreciate it if anyone could shed some light on this. Am I missing something? Would truly appreciate some clarity on this subject.

Thanks a lot!

**Comment by jcesarmobile** [comment] 2021-06-14 13:29
Capacitor and its plugins are served from npm, so they are already locked by the `package-lock.json`.

When we started the project, CocoaPods was having problems with local dependencies (such as the plugins or capacitor itself), so we had to delete the `Podfile.lock` to make it work, it might be fixed by CocoaPods by now, but at that moment, the only way of making it work was deleting the `Podfile.lock` before running `pod install`.

But of course, can be a problem if a capacitor plugin has a dependency to a CocoaPods library and declares it with an open range (such as `~>` or `>=`), but there is also the `--deployment` param you can pass to don't delete the `Podfile.lock`. It has CI on mind since the environment is new on every sync, so the mentioned CocoaPods problem doesn't appear.

**Comment by dminkovsky** [comment] 2021-06-14 14:10
Thank you jcesarmobile for that explanation. Yes, my concern stems from a plugin that declares a dependency like:

    <pod name="GoogleUtilities" spec="~> 7.2.2"/>

The result was I had 7.2.2 installed, and then I noticed 7.3.0 was installed sometime later. I'm using this for Google Sign In, and I don't imagine this change broke anything, but who knows... either way, it spooked me. 

Thanks for letting me know about the `--deployment` flag, I will check it out. Maybe it'll work now on non-fresh installs.

**Comment by markemer** [comment] 2023-07-12 19:48
This is just all sorts of out of date.

**Closed by markemer** 2023-07-12 19:48 UTC
Labels: platform: ios, cli, needs investigation, dx, performance
