### ISSUE TITLE
bug: java.lang.IllegalStateException: Either grant() or deny() has been already called.

### ISSUE THREAD

**Issue by Richard-Choooou** [ionic-team/capacitor#6094] opened 2022-11-17 06:36 UTC
## Bug Report
crashed when the browser request camera and geolocation permissions at the same time
```
11-17 12:43:10.948 E/AndroidRuntime(27720): FATAL EXCEPTION: main
11-17 12:43:10.948 E/AndroidRuntime(27720): Process: cn.cateyes.dispatcher, PID: 27720
11-17 12:43:10.948 E/AndroidRuntime(27720): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=982263707, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {cn.cateyes.dispatcher/cn.cateyes.dispatcher.MainActivity}: java.lang.IllegalStateException: Either grant() or deny() has been already called.
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.os.Handler.dispatchMessage(Handler.java:110)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.os.Looper.loop(Looper.java:219)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at java.lang.reflect.Method.invoke(Native Method)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
11-17 12:43:10.948 E/AndroidRuntime(27720): Caused by: java.lang.IllegalStateException: Either grant() or deny() has been already called.
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at org.chromium.android_webview.permission.AwPermissionRequest.c(HwWebview-11.1.5.315.3337:3)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at org.chromium.android_webview.permission.AwPermissionRequest.b(HwWebview-11.1.5.315.3337:1)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at OH.grant(HwWebview-11.1.5.315.3337:8)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.getcapacitor.BridgeWebChromeClient.lambda$onPermissionRequest$2(BridgeWebChromeClient.java:122)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.getcapacitor.BridgeWebChromeClient$$ExternalSyntheticLambda4.onPermissionSelect(Unknown Source:2)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.getcapacitor.BridgeWebChromeClient.lambda$new$0$com-getcapacitor-BridgeWebChromeClient(BridgeWebChromeClient.java:65)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.getcapacitor.BridgeWebChromeClient$$ExternalSyntheticLambda15.onActivityResult(Unknown Source:4)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:737)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:612)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at com.getcapacitor.BridgeActivity.onRequestPermissionsResult(BridgeActivity.java:146)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8695)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.Activity.dispatchActivityResult(Activity.java:8545)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
11-17 12:43:10.948 E/AndroidRuntime(27720): 	... 11 more
```
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/core: 4.4.0

[success] Android looking great! 👌
```

### Platform(s)

android 10

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2022-11-17 08:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-03 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-03 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
