### ISSUE TITLE
cap update android after installing plugin causes Gradle to crash

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#414] opened 2018-03-30 04:23 UTC
For some reason, after installing a Capacitor plugin and running `npx cap update android`, Gradle will throw exceptions when syncing the next time you open your app. Gradle will report having "failed to sync" with no messages, but the log will show exceptions (NPE's) and the like.

The solution is to invalidate caches and restart, but that's annoying af, maybe there's a way to avoid this after the update command?

**Comment by jcesarmobile** [comment] 2018-04-06 16:34
I can't reproduce this.
I've created a plugin and published it on npm and after installing and running `npx cap update android` the app continues working fine. Closing and opening Android Studio doesn't break at. Running works, manually syncing gradle works.

Was you plugin installed from npm? or linked?
In case it was published, can you share the plugin so I can test it?

I've updated Android Studio to 3.1, might it be possible that it was a bug they have fixed it? Can you give Android Studio 3.1 a try?

**Comment by mlynch** [comment] 2018-04-17 14:24
Might be a non-issue with 3.1

**Comment by jcesarmobile** [comment] 2019-04-12 14:38
closing as couldn't reproduce, might have been an Android Studio bug

**Closed by jcesarmobile** 2019-04-12 14:38 UTC
Labels: platform: android, priority: high
