### ISSUE TITLE
Can not access the capacitorjs.com website ?

### ISSUE THREAD

**Issue by davidce** [ionic-team/capacitor#4574] opened 2021-05-17 08:21 UTC
Hi guys, I can not visite the capacitorjs.com website with error of ERR_CONNECTION_RESET in  the Chinese mainland，Is anybody there have the same issues, thanks!

**Comment by AlwaysLoveme** [comment] 2021-05-19 04:43
the same problem

**Comment by jcesarmobile** [comment] 2021-05-20 12:11
not sure if it could be related to https://github.com/ionic-team/capacitor-site/issues/296

anyway, closing since the problem is on the site, you can subscribe to that other issue for updates and if that problem gets resolved maybe yours too

**Closed by jcesarmobile** 2021-05-20 12:11 UTC

**Comment by netsesame2** [comment] 2021-06-23 00:11
Can't visit these days. still in blocklist?

**Comment by eliot-ye** [comment] 2021-09-24 01:53
The same question

**Comment by AlwaysLoveme** [comment] 2021-09-24 03:31
> Can't visit these days. still in blocklist?

open VPN if you are in China
