### ISSUE TITLE
bug: In some cases, 1 file is not selected via input type=file multiple

### ISSUE THREAD

**Issue by lexmav** [ionic-team/capacitor#6305] opened 2023-02-17 13:40 UTC
### Capacitor Version

```
Capacitor Doctor  

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.2
  @capacitor/android: 4.6.3
  @capacitor/core: 4.6.2

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

phone: Galaxy S21 (I tested it on another samsung (I don't remember the version) - the behavior is similar)

`<input type="file" multiple />`

I click "select files", select **gallery or file manager**, select ONE file (image), confirm.

**The file is not selected.**

If you select a file from recent or select several files, it works correctly.

The change event is not triggered. There are no errors in the console

### Expected Behavior

I expect 1 file to be selected

### Other Technical Details

`npm --version` output:
9.4.2

`node --version` output:
v16.19.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2023-02-22 18:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by trplx** [comment] 2023-03-01 09:50
Have the same issue. Any updates?

**Comment by TheHomeGera** [comment] 2023-03-01 10:05
`<input type="file" multiple (change)="handleFiles($event)" >` You can repeat the behavior with this control. When we select 1 file from the Gallery section, the handleFiles event does not fire. When we try to select 2 files from this section, everything works.

**Comment by Ionitron** [comment] 2023-03-03 18:43
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-19 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-19 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
