### ISSUE TITLE
bug: (jarsigner: unable to open jar file) error when using android flavors

### ISSUE THREAD

**Issue by sabereen** [ionic-team/capacitor#6215] opened 2023-01-14 07:04 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

[success] Android looking great! �
```

### Platform(s)

android

### Current Behavior

It is not signed when I use android flavors.
```
× Signing Release - failed!
[error] jarsigner: unable to open jar file:
        C:\Users\MQT\projects\microblog\android\app\build\outputs\apk\release\app-FLAVOR-release-unsigned.apk
```

### Expected Behavior
My APK is in this path:
```
C:\Users\MQT\projects\microblog\android\app\build\outputs\apk\FLAVOR\release\app-FLAVOR-release-unsigned.apk
```

So jarsigner should sign this path instead.

### Code Reproduction
Define android build falvors and build project using a flavor.

### Other Technical Details
`npm --version` output:
yarn 1.22.19

`node --version` output:
v16.15.1

**Comment by Ionitron** [comment] 2023-01-17 09:41
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-02 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
