### ISSUE TITLE
bug: values.xml produces a Android resource linking failed

### ISSUE THREAD

**Issue by CarlosNano** [ionic-team/capacitor#5078] opened 2021-09-28 09:10 UTC
### Capacitor Version
╰─ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.2.4

  @capacitor/core: 3.2.4

  @capacitor/android: 3.2.4

  @capacitor/electron: 3.2.4

  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli 2.0.1

  @capacitor/android 2.4.0

  @capacitor/ios 2.4.0

  @capacitor/core 2.4.0

  @capacitor/electron 2.4.0

### Platform(s)
Android

### Current Behavior

When I build the app in Android studio I get the following error:

![image](https://user-images.githubusercontent.com/72921935/135057886-318573e8-c1b7-4a27-a06b-aa3a6aabb202.png)

This is only happening when I have plugins in the project, if I remove all the plugins the app builds correctly.

To set up the project I've followed the documentation: Updating Capacitor to 2.0 in your app ( https://capacitorjs.com/docs/updating/2-0 )

This is my `variables.gradle`:

```
ext {
  minSdkVersion = 28
  compileSdkVersion = 30
  targetSdkVersion = 30
  androidxAppCompatVersion = '1.1.0'
  androidxCoreVersion =  '1.2.0'
  androidxMaterialVersion =  '1.1.0-rc02'
  androidxBrowserVersion =  '1.2.0'
  androidxLocalbroadcastmanagerVersion =  '1.0.0'
  firebaseMessagingVersion =  '20.1.2'
  playServicesLocationVersion =  '17.0.0'
  junitVersion =  '4.12'
  androidxJunitVersion =  '1.1.1'
  androidxEspressoCoreVersion =  '3.2.0'
  cordovaAndroidVersion =  '7.0.0'
}
```

I'm using the following version of Gradle and the Gradle plugin:

![image](https://user-images.githubusercontent.com/72921935/135058155-df824f02-d527-4bed-96c6-607b1cfa60d0.png)

### Other Technical Details

`npm --version` output: 7.21.1
`node --version` output: v14.17.5

Thanks

**Comment by Ionitron** [comment] 2021-09-28 10:27
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ellamurii** [comment] 2021-09-30 15:47
I'm having the same issue. seems like related to this [discussion](https://stackoverflow.com/questions/69021225/resource-linking-fails-on-lstar)

**Comment by jcesarmobile** [comment] 2021-09-30 16:10
yeah, looks like some plugin is pinning "latest" androidx.core library, which is picking 1.7.0-alpha02 and that causes the issue.
or if using jetifier it's also assigning that as latest

More info: 
https://www.reddit.com/r/Unity3D/comments/ph2596/android_builds_fail_due_to_core170alpha02_release/

A possible solution is to add this the the build.gradle:
```
configurations.all {
  resolutionStrategy {
    force 'androidx.core:core:1.6.0'
    force 'androidx.core:core-ktx:1.6.0'
  }
}
```
using compileSdkVersion/targetSdkVersion 31 is not a good solution as Capacitor doesn't support it yet and it's not even official

**Comment by henrides** [comment] 2021-10-01 19:17
Adding the resolutionStrategy to build.gradle worked for me. Thanks.

**Comment by ellamurii** [comment] 2021-10-02 05:46
Thanks for pointing out that Capacitor does not support the mentioned compileSdkVersion/targetSdkVersion versions @jcesarmobile 

adding the resolutionStrategy on my `android/app/build.gradle` worked for me

**Comment by jcesarmobile** [comment] 2021-10-04 08:18
Closing since the reporter didn’t answer but the workaround worked for other users.

**Closed by jcesarmobile** 2021-10-04 08:18 UTC
Labels: platform: android, needs reproduction

**Comment by jcesarmobile** [comment] 2021-10-04 15:42
We recommend updating capacitor 2 apps to 1.2.0 on the upgrade guide, and capacitor 3 apps to 1.3.2 as those were the latest stable versions when capacitor 2/3 were released.
It's always good to use latest stable as it usually fixes bugs, but they sometimes introduce breaking changes, but the guides will keep recommending the versions we tested when the upgrade was done.
