### ISSUE TITLE
Electron Project Has Incorrect Path

### ISSUE THREAD

**Issue by saniyusuf** [ionic-team/capacitor#1553] opened 2019-05-22 00:10 UTC
When using Capacitor with Electron, the electron build fails. The reason it fails is that, by default, the INDEX.HTML has a <base> element with the value "/" in the header. This looks like the following. 
`  <base href="/" />`

If you change the value of the href to "./", the app will launch correctly. 
A proposed fix will be to have a build time hook that will set this for the Cordova build. 

I am using Capacitor 1.0.0-beta.25 and running a Mac OSX Mojave 10.14.4

**Comment by jcesarmobile** [comment] 2019-05-22 08:50
It's a duplicate of https://github.com/ionic-team/capacitor/issues/639

If using angular, you can do it with `ng build --prod --base-href=./`.

**Closed by jcesarmobile** 2019-05-22 08:50 UTC

**Comment by gnopor** [comment] 2020-05-23 00:39
Note: For launch the app with electron, follow these steps:(forgive my English I am native french speaker)

1. First of all forget about the electron folder, do not touch it.
2. In your react/ionic directory which is your root directory for the app,add the following in your package.json file:    "homepage": "./"

3. Now from your react/ionic directory which is your root directory for the app, navigate to the "public" directory and update your index.html file replacing <base href="/" /> with:    <base href="./" />

4. Now run the following command and that is it... 
    a. ionic build && npx cap copy
    b. npx cap open electron
