### ISSUE TITLE
feat: support of Periodic Background tasks

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#5083] opened 2021-09-29 08:54 UTC
## Feature Request

Hi Capacitor team `when do you plan to support periodic background tasks ? `

![image](https://user-images.githubusercontent.com/25119847/135236197-70ecfa79-0970-4043-9995-b9658fd48e18.png)

Cf https://github.com/ionic-team/capacitor-site/blob/main/pages/docs/v2/apis/background-task/index.md#background-tasks

Thanks a lot for all the amazing work you do here

**Comment by Ionitron** [comment] 2021-09-29 10:55
Issue detected as duplicate of https://github.com/ionic-team/capacitor/issues/3032

**Closed by Ionitron** 2021-09-29 10:55 UTC
