### ISSUE TITLE
Issue when mixing plugins written in objc and swift

### ISSUE THREAD

**Issue by bagbyte** [ionic-team/capacitor#2357] opened 2020-01-21 22:16 UTC
In my Capacitor project (I#m currently using version 1.4.0) I'm using these plugins:

- `@ionic-native/adjust` : `5.19.1`
- `@ionic-native/fingerprint-aio` : `5.19.1`
- `com.adjust.sdk` : `4.18.0`
- `cordova-plugin-fingerprint-aio` : `3.0.1`

I can build the project with XCode without no problem, but when I try to archive it, I get an error on `ios/capacitor-cordova-ios-plugins/sources/Com.adjust.sdk/src/ios/AdjustSdk.framework/Modules/module.modulemap` file:

```
framework module AdjustSdk {
  umbrella header "Adjust.h"

  export *
  module * { export * }
}
```

On line 2: `Umbrella for module 'CordovaPlugins' already covers this directory`
On line 5: `Inferred submodules require a module with an umbrella`

What I've noticed is that while `fingerprint-aio` is a swift project, `adjust` plugin is written in objc, could this be the cause? Do you have any idea how to fix this?

### Note:
The issue has been caused by adding `fingerprint-aio` plugin, before I had no issue, and the project could be built and archived without any problem.

<img width="870" alt="Screenshot 2020-01-21 at 23 18 04" src="https://user-images.githubusercontent.com/792687/72848311-9d533300-3ca4-11ea-9b0e-1939650645e1.png">

[archive.log](https://github.com/ionic-team/capacitor/files/4094032/archive.log)

**Comment by jcesarmobile** [comment] 2020-01-22 10:21
no, it's not because of the mixing, is because of some incompatible plugin

**Comment by jcesarmobile** [comment] 2020-01-28 15:24
The problem is on the `AdjustSdk.framework`, it includes a modulemap that collides with the one CocoaPods generates when Swift classes are present.

https://github.com/adjust/cordova_sdk/blob/master/src/ios/AdjustSdk.framework/Modules/module.modulemap

Closing as incompatible plugin (com.adjust.sdk) only when mixed with swift plugins

**Closed by jcesarmobile** 2020-01-28 15:24 UTC
