### ISSUE TITLE
bug: SyntaxError: Unexpected token D in JSON at position 0

### ISSUE THREAD

**Issue by TNTRedstone** [ionic-team/capacitor#6633] opened 2023-06-05 20:43 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.4
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0

```

### Platform(s)

Android

### Current Behavior

So when I do ```npx cap run android``` it the error after sitting and doing nothing for approximately a minute after it updates android:
```[error] SyntaxError: Unexpected token D in JSON at position 0
        at JSON.parse (<anonymous>)
        at getPlatformTargets
        (D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\util\native-run.js:39:26)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async runAndroid
        (D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\android\run.js:14:64)
        at async run
        (D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\tasks\run.js:77:9)
        at async runCommand
        (D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\tasks\run.js:61:13)
        at async
        D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\index.js:123:9
        at async
        D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\telemetry.js:26:13
        at async Command.<anonymous>
        (D:\Users\cgste\Documents\coding\Chores-saving_plan\Js\my-app\node_modules\@capacitor\cli\dist\util\cli.js:12:13)
```

### Expected Behavior

This error doesn't make any sense and should not exist

**Comment by Ionitron** [comment] 2023-06-06 07:53
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-22 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-22 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
