### ISSUE TITLE
bug: Official plugins 'not implemented for ios'

### ISSUE THREAD

**Issue by MortenGregersen** [ionic-team/capacitor#4330] opened 2021-03-12 12:33 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/ios: 3.0.0-rc.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Running on iOS Simulator 14.4 with Xcode 12.4.

### Current Behavior

When I run our app, upgraded to Capacitor 3.0 I get error saying:
`⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Network" plugin is not implemented on ios`

### Expected Behavior

I expected the plugins to be implemented, as they are official. They are installed with `npm install @capacitor/network`.

### Other Technical Details

`npm --version` output: 6.14.9

`node --version` output: v12.14.0

`pod --version` output (iOS issues only): 1.10.1

### Additional Context

The plugins are provided in a module in our Angular 11 project:
```
import { Network } from '@capacitor/network';

...

{ provide: CAPACITOR_NETWORK_PLUGIN_TOKEN, useFactory: () => Network },
```

Here is the full log:
```
⚡️  Loading app at myapp://example.app...
2021-03-12 11:56:29.740818+0100 MyApp[34096:3689829] WF: === Starting WebFilter logging for process MyApp
2021-03-12 11:56:29.740982+0100 MyApp[34096:3689829] WF: _userSettingsForUser : (null)
2021-03-12 11:56:29.741091+0100 MyApp[34096:3689829] WF: _WebFilterIsActive returning: NO
To Native Cordova ->  Device getDeviceInfo Device1352365340 ["options": []]
To Native Cordova ->  NetworkStatus getConnectionInfo NetworkStatus1352365341 ["options": []]
To Native Cordova ->  File requestAllPaths File1352365342 ["options": []]
⚡️  [log] - MGR1 {"__zone_symbol__state":null,"__zone_symbol__value":[]}
⚡️  [log] - Ionic Native: deviceready event fired after 158 ms
To Native Cordova ->  CDVOrientation screenOrientation INVALID ["options": [1, portrait-primary]]
To Native Cordova ->  CordovaHttpPlugin setServerTrustMode CordovaHttpPlugin1352365343 ["options": [default]]
⚡️  To Native ->  SecureStorage get 114963024
ERROR MESSAGE:  {"message":"Error retrieving from keychain: error item not found","errorMessage":"Error retrieving from keychain: error item not found"}
⚡️  [log] - Angular is running in development mode. Call enableProdMode() to enable production mode.
⚡️  [error] - Unhandled Promise rejection: "LaunchScreen.toJSON()" is not implemented on ios ; Zone: <root> ; Task: Promise.then ; Value: {"code":"UNIMPLEMENTED"} CapacitorException@myapp://example.app/vendor.js:57878:10
myapp://example.app/vendor.js:58367:41
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - Unhandled Promise rejection: "LaunchScreen.then()" is not implemented on ios ; Zone: <root> ; Task: Promise.then ; Value: {"code":"UNIMPLEMENTED"} CapacitorException@myapp://example.app/vendor.js:57878:10
myapp://example.app/vendor.js:58367:41
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "LaunchScreen.hasOwnProperty()" is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
myapp://example.app/vendor.js:58367:41
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "LaunchScreen.pipe()" is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
myapp://example.app/vendor.js:58367:41
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Network" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [log] - Same error as last. Cancelling error logging.
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Network" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Device" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Keyboard" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "App" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR {}
⚡️  [warn] - Icon with name: "logo" already exists
⚡️  [warn] - Icon with name: "maintenance" already exists
⚡️  [warn] - Icon with name: "update-error" already exists
⚡️  [warn] - Icon with name: "pdf" already exists
⚡️  [warn] - Icon with name: "logo" already exists
⚡️  [warn] - Icon with name: "scanner" already exists
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "ApplePayPlugin" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Network" plugin is not implemented on ios
CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
onInvoke@myapp://example.app/vendor.js:133292:31
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
onInvokeTask@myapp://example.app/vendor.js:133280:35
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
promiseReactionJob@[native code]
⚡️  [log] - Ionic Native: deviceready event fired after 671 ms
⚡️  WebView loaded
⚡️  [error] - Unhandled Promise rejection: "App" plugin is not implemented on ios ; Zone: <root> ; Task: Promise.then ; Value: {"code":"UNIMPLEMENTED"} CapacitorException@myapp://example.app/vendor.js:57878:10
createPluginMethod@myapp://example.app/vendor.js:58351:37
myapp://example.app/vendor.js:58360:40
run@myapp://example.app/polyfills.js:148:53
myapp://example.app/polyfills.js:882:43
runTask@myapp://example.app/polyfills.js:192:61
drainMicroTaskQueue@myapp://example.app/polyfills.js:594:46
invokeTask@myapp://example.app/polyfills.js:509:44
timer@myapp://example.app/polyfills.js:2577:38
```

**Comment by Ionitron** [comment] 2021-03-12 12:50
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by MortenGregersen** [comment] 2021-03-15 09:56
I resolved the issue. I found randomly this project (from one of the people at Ionic) which shows that the plugins should be added to the Podfile: https://github.com/mhartington/react-notes/blob/main/ios/App/Podfile

Maybe this should be mentioned in the upgrade guide for Capacitor 3.0?

**Comment by jcesarmobile** [comment] 2021-03-15 11:46
Plugins are added to the Podfile by Capacitor CLI when you run `npx cap update` or `npx cap sync`.

**Comment by MortenGregersen** [comment] 2021-03-15 14:03
It wasn't added on our project. Maybe because we have a more customized Podfile for our (white label) app.

Maybe it should be written out in the log, if it can't be done, or maybe it already does and I missed it?

**Comment by jcesarmobile** [comment] 2021-03-15 14:24
That's why I requested a sample project, so I could reproduce and evaluate.

But since you got it sorted out, I'm closing the issue.

**Closed by jcesarmobile** 2021-03-15 14:24 UTC
Labels: needs reproduction, platform: ios
