### ISSUE TITLE
bug: log vue 3 warn cause error on iOS

### ISSUE THREAD

**Issue by bazuka5801** [ionic-team/capacitor#6545] opened 2023-04-28 15:45 UTC
### Capacitor Version
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

Installed Dependencies:

  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/cli: 4.7.3
  @capacitor/ios: 4.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

```
PASTE OUTPUT HERE
```

### Platform(s)
iOS

### Current Behavior
Suppress original warn from vue combat
![image](https://user-images.githubusercontent.com/11452353/235192848-210e7b1f-e31b-474e-9961-91344bdf73ff.png)
![image](https://user-images.githubusercontent.com/11452353/235193000-82b1cba6-2c74-4267-ab98-176bbb46cc85.png)

### Expected Behavior
Log vue warns normally, without errors

### Other Technical Details
https://v3-migration.vuejs.org/migration-build.html

**Comment by Ionitron** [comment] 2023-05-01 08:56
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-17 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-05-17 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
