### ISSUE TITLE
capacitor-android(google-maps-plugin) String currentPage = webView.getUrl();  return null

### ISSUE THREAD

**Issue by edy-ap** [ionic-team/capacitor#1674] opened 2019-06-17 16:50 UTC
Description of the problem:

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ X] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0
node version:

npm version:
6.9.0
CocoaPods version:

Steps to reproduce:

1.- Run a project
![error-maps-plugin](https://user-images.githubusercontent.com/13421021/59622010-162e5300-90f6-11e9-863b-fd8152826f94.PNG)

Link to sample project:

**Comment by jcesarmobile** [comment] 2019-06-17 16:59
please, provide more details on the steps to reproduce or a sample app

**Comment by edy-ap** [comment] 2019-06-17 17:04
1.- Install capacitor
2.- Add android platform
3.- Add plugin cordova-plugin-googlemaps
4.- Run project
5.- CordovaWebView webView.getUrl(); return null

**Comment by edy-ap** [comment] 2019-06-17 17:29
the error is in  this class MockCordovaWebViewImpl the method return null
![error-maps-plugin](https://user-images.githubusercontent.com/13421021/59624087-7d023b00-90fb-11e9-91aa-9803da5dbf02.PNG)

**Comment by jcesarmobile** [comment] 2019-06-17 18:01
Good catch, but still, it would be good if you could provide a sample app, I've followed the steps you have provided and the getUrl is not getting called, so you must be doing something else. I can't properly fix it if I can't reproduce the error.

**Comment by edy-ap** [comment] 2019-06-17 18:12
thansk for you answer, i am working on a sample app .

the steps is

1.- Install capacitor
2.- Add android platform
3.- Add plugin cordova-plugin-googlemaps
4.-Add a map element.
5.- Add a marker whit icon
6.- Run project
7.- CordovaWebView webView.getUrl(); return null

**Comment by jcesarmobile** [comment] 2019-06-17 18:40
Thanks, with the new steps I could reproduce once I added the marker with a custom icon.

Will be fixed once I merge https://github.com/ionic-team/capacitor/pull/1677

BTW, for making the icons work you'll have to create a new www folder inside the assets folder and put the icons there as cordova searches in www instead of public.

**Closed** 2019-06-17 19:01 UTC

**Comment by edy-ap** [comment] 2019-06-17 19:09
thanks for you help  =)
