### ISSUE TITLE
Problem with Push notifications (Android)

### ISSUE THREAD

**Issue by damianlluch** [ionic-team/capacitor#6253] opened 2023-01-26 02:41 UTC
Hi, I'm following the Capacitor tutorial below to integrate push notifications in an in-app-browser app in Android

https://capacitorjs.com/docs/guides/push-notifications-firebase

In my `home.page.ts` file I have only this content:

```
import { Component } from '@angular/core';
import { InAppBrowser } from '@awesome-cordova-plugins/in-app-browser/ngx';


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
exportar clase HomePage {

  constructor(private iab: InAppBrowser) {}
  browser = this.iab.create('https://www.saem.com.ar/ingreso/?next=/','_blank',{
    hideurlbar: 'yes
    hidenavigationbuttons : 'yes',
    barra de herramientas: 'no',
    clearcache: 'no',
    clearsessioncache: 'no',
    location: 'no'
  });
}
```

In the tutorial it asks for the `home` class to extend the `OnInit` class. So, to my original code, I add that class extension, and add the methods indicated in the tutorial, resulting in the following code:

```import {Component, OnInit} from '@angular/core';
import { InAppBrowser } from '@awesome-cordova-plugins/in-app-browser/ngx';
import {
  ActionPerformed,
  PushNotificationSchema,
  PushNotifications,
  Token,
} from '@capacitor/push-notifications';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {

  constructor(private iab: InAppBrowser) {}
  browser = this.iab.create('https://www.saem.com.ar/ingreso/?next=/','_blank',{
    hideurlbar: 'yes',
    hidenavigationbuttons :	'yes',
    toolbar: 'no',
    clearcache: 'no',
    clearsessioncache: 'no',
    location: 'no'
  });

  ngOnInit() {
    console.log('Initializing HomePage');

    // Request permission to use push notifications
    // iOS will prompt user and return if they granted permission or not
    // Android will just grant without prompting
    PushNotifications.requestPermissions().then(result => {
      if (result.receive === 'granted') {
        // Register with Apple / Google to receive push via APNS/FCM
        PushNotifications.register();
      } else {
        // Show some error
      }
    });

    // On success, we should be able to receive notifications
    PushNotifications.addListener('registration',
      (token: Token) => {
        alert('Push registration success, token: ' + token.value);
      }
    );

    // Some issue with our setup and push will not work
    PushNotifications.addListener('registrationError',
      (error: any) => {
        alert('Error on registration: ' + JSON.stringify(error));
      }
    );

    // Show us the notification payload if the app is open on our device
    PushNotifications.addListener('pushNotificationReceived',
      (notification: PushNotificationSchema) => {
        alert('Push received: ' + JSON.stringify(notification));
      }
    );

    // Method called when tapping on a notification
    PushNotifications.addListener('pushNotificationActionPerformed',
      (notification: ActionPerformed) => {
        alert('Push action performed: ' + JSON.stringify(notification));
      }
    );
    }
}
```

The problem I have is that when I start the app in android studio, it closes automatically. I understand that I'm doing something wrong, but I don't know what.
If someone can tell me.

Thanks!

**Comment by Ionitron** [comment] 2023-01-26 09:13
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-11 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-11 00:05 UTC
Labels: needs reply, needs reproduction
