### ISSUE TITLE
feat: warn if multiple Capacitor modules bundled

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/capacitor#4186] opened 2021-02-09 20:34 UTC
### Description

It's possible for a bundler to include more than one version of Capacitor for various reasons. When dependencies are resolved they find the nearest `node_modules/@capacitor/core`,  which could be different from what the main app is using. The app will "work", but various bugs will show up depending on the order each Capacitor instance registered itself, and which `fromNative()` is called by the native implementation.

### Preferred Solution

Big loud warning to ensure modules are deduped and there's only one bundled Capacitor. This would be similar to how React will error if there's multiple copies of React resulting in the the hooks not working.

### Additional Context

With npm7 and how it was installing peer deps, my main bundle ended up including two versions of Capacitor, and debugging why the events were not firing was very time consuming. Native was correctly calling `fromNative()`, but it wasn't calling the correct callback instances. We can't stop bundlers from including more than one version, but we can detect if a version is already registered.

**Comment by jcesarmobile** [comment] 2024-02-02 12:15
Closing as won't do since the issue has never come up after three years other than the original report, so doesn't look like a common issue.
It might have been caused by some plugin having `@capacitor/core` as a `dependency` instead of `devDependency`, which was not that uncommon 3 years ago, but it's not common anymore.

**Closed by jcesarmobile** 2024-02-02 12:15 UTC
