### ISSUE TITLE
bug: CapacitorBridge.swift expected ',' separator and use of unknown directive '#unavailable'

### ISSUE THREAD

**Issue by angelicaflausino** [ionic-team/capacitor#7091] opened 2023-11-23 14:28 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/core: 4.8.1
  @capacitor/android: 4.8.1
  @capacitor/cli: 4.8.1
  @capacitor/ios: 4.8.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
IOS

### Current Behavior
iOS build fails with the following errors:

- node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift:443:46: error: expected ',' separator
- node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift:443:29: error: use of unknown directive '#unavailable'
- node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift:443:52: error: closure expression is unused
- node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift:443:52: note: did you mean to use a 'do' statement?

### Expected Behavior
It should be possible to build the iOS project without errors in dependencies

### Code Reproduction
Line commands used.

`npx cap add ios`
`npx cap run ios`

**Device selected:** Iphone 13

**Building with Xcode the error is the same**

### Other Technical Details

`npm --version` output: 8.1.0

`node --version` output: v16.13.0

`pod --version` output (iOS issues only): Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
1.10.1

### Additional Context

**Ionic:**

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 12.2.18
   @angular-devkit/schematics    : 12.2.18
   @angular/cli                  : 12.2.18
   @ionic/angular-toolkit        : 3.1.1

**Capacitor:**

   Capacitor CLI   : 4.8.1
   @capacitor/core : 4.8.1

**Cordova:**

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

**Utility:**

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.4

**System:**

   ios-deploy : 1.11.3
   ios-sim    : ios-sim/9.0.0 darwin-x64 node-v16.13.0
   NodeJS     : v16.13.0 (/Users/alessandrofrizzera/.nvm/versions/node/v16.13.0/bin/node)
   npm        : 8.1.0
   OS         : macOS
   Xcode      : Xcode 13.2.1 Build version 13C100

**Comment by jcesarmobile** [comment] 2023-11-27 11:27
Technically Capacitor 4.x is in extended support (meaning, we only do changes requested by paying customers).
The code causing your errors compiled fine on Xcode 13.3.1, but if we broke Xcode 13.0-13.2 support we should probably fix it.

Can you provide a sample app that reproduces the issue?

**Comment by Ionitron** [comment] 2023-12-13 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-12-13 00:05 UTC
Labels: platform: ios, needs reply

**Comment by gklasen** [comment] 2023-12-15 08:41
@angelicaflausino did you resolve this issue? I am currently having the same.
