### ISSUE TITLE
bug: cannot open urls in app ending with ".html"

### ISSUE THREAD

**Issue by Vasek18** [ionic-team/capacitor#4873] opened 2021-07-29 13:33 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/electron: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

Android

### Current Behavior

We use react routing. And we have addresses ending with ".html". But this urls are not handled by separate files but handled with just a route and a component. Problem: we can not open such urls in app
By the way if we create separate file with name, e.g. test.html, we can open /test.html in a app. But if we have just such route and component that approach won't work in a app

### Expected Behavior

We can use routes in react like "*.html" like any other route in a capacitor

### Code Reproduction

```
// works in browser, doesn't work in app
<Switch>
<Route path={ 'test.html' } exact component={ Test }/>
</Switch>
```

### Other Technical Details

`npm --version` output: 7.3.0

`node --version` output: v15.5.1

`pod --version` output (iOS issues only):

Capacitor config:
```
{
  "appId": "com.mapsly.app",
  "appName": "Mapsly",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "build",
  "server": {
    "iosScheme": "https",
    "androidScheme": "https"
  },
  "plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    }
  },
  "cordova": {},
  "linuxAndroidStudioPath": "/home/vasiliy/Programs/android-studio-ide-201.7042882-linux/android-studio/bin/studio.sh"
}
```

**Comment by thomasvidas** [comment] 2021-08-02 05:18
Can you provide a small sample repo? I'm not able to reproduce this issue from your description

**Comment by Ionitron** [comment] 2021-08-02 05:19
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-18 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-18 00:02 UTC
Labels: platform: android, needs reply, needs reproduction
