### ISSUE TITLE
bug: Plugins are not available on Pixel 7 and Pixel 7 pro phones

### ISSUE THREAD

**Issue by skidrow88** [ionic-team/capacitor#6557] opened 2023-05-03 19:24 UTC
## Bug Report

Plugins are not available on Pixel 7 and Pixel 7 pro phones. The method `isPluginAvailable()` returns always `false`.

### Capacitor Version

```

Latest Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

Installed Dependencies:

  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/cli: 4.7.3
  @capacitor/ios: 4.7.3
```

### Platform(s)

Android but only on Pixel 7 and Pixel 7 pro (Android 13 (SDK 33))

### Current Behavior

Users on Pixel 7 and Pixel 7 pro have issues with plugins. For instance `Capacitor.isPluginAvailable('Camera')` return `false`.

### Expected Behavior

`Capacitor.isPluginAvailable('Camera')` must return `true` like other Android phones.

### Code Reproduction

```
if (!Capacitor.isPluginAvailable('Camera') || this.usePicker) {
      this.executeAction('sendPicture');
      await this.checkScanCounter();
      if (this.adsService.getAdsCounter() <= 0){
        await this.presentAlertAds(
          this.translate.instant('message.empty_scan_tank'), 
          this.translate.instant('message.refill_scan')
        );
      }
      else{
        this.filePickerRef.nativeElement.click();
      }
      return;
    }
```

### Other Technical Details

This issue could be linked to this one : https://github.com/ionic-team/ionic-framework/issues/26240

`npm --version` output:
`9.6.4`
`node --version` output:
`v20.0.0`

`npx cap ls` output:
```
[info] Found 19 Capacitor plugins for android:
       @byteowls/capacitor-filesharer@4.0.0
       @capacitor-community/admob@4.2.0
       @capacitor-community/apple-sign-in@4.0.0
       @capacitor-community/facebook-login@4.0.0
       @capacitor/app@4.1.1
       @capacitor/app-launcher@4.1.0
       @capacitor/browser@4.1.1
       @capacitor/camera@4.1.4
       @capacitor/device@4.1.0
       @capacitor/dialog@4.1.0
       @capacitor/filesystem@4.1.4
       @capacitor/network@4.1.0
       @capacitor/preferences@4.0.2
       @capacitor/push-notifications@4.1.2
       @capacitor/share@4.1.1
       @capacitor/splash-screen@4.2.0
       @capacitor/status-bar@4.1.1
       @codetrix-studio/capacitor-google-auth@3.2.2
       capacitor-rate-app@3.0.0
```

**Comment by Ionitron** [comment] 2023-05-04 07:45
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-04 08:09
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-20 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-05-20 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
