### ISSUE TITLE
bug: navigator.mediaDevices.enumerateDevices InputDeviceInfo getCapabilities function return {}

### ISSUE THREAD

**Issue by Richard-Choooou** [ionic-team/capacitor#6090] opened 2022-11-16 08:07 UTC
## Bug Report
![image](https://user-images.githubusercontent.com/23492006/202120891-a49fea98-86a8-4645-84f2-eb985f5f22ca.png)
[https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceInfo/getCapabilities](https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceInfo/getCapabilities)

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/core: 4.4.0

[success] Android looking great! 👌
```

### Platform(s)

android 10

### Current Behavior

getCapabilities function return {}

### Expected Behavior

return MediaTrackCapabilities object 

### Code Reproduction

```js
navigator.mediaDevices.enumerateDevices()
  .then((devices) => {
    devices.forEach((device) => {
      console.log(device.getCapabilities()); // a MediaTrackCapabilities object.
    });
  })
```

### Other Technical Details

`npm --version` output:
8.5.0
`node --version` output:
v16.14.2
`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2022-11-16 10:01
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-02 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
