### ISSUE TITLE
hiding splash screen manually in ios not working

### ISSUE THREAD

**Issue by fssrepository** [ionic-team/capacitor#607] opened 2018-06-24 22:12 UTC
Hiding splash screen manually in ios not working It's timing out... The same typecript code works under android.

Overall feedback on capacitor beta 1.
Anyway, i have made some plugins in my project, as i cannot post any android based plugin. (the ionic plugin builder hasn't been finished yet), but i do think that the capacitor overal seems to be working fine.

I have made a simple native google maps plugin / ml kit / mqtt / reusable iteractive native overlay (used by google map) for android. The development time was around 50 hours within 3 days i think.

**Comment by jcesarmobile** [comment] 2018-08-24 15:00
I've tested and can reproduce on an Ionic 3 app, but the problem is the Ionic 3 app takes ~3 seconds to launch on iOS, as the default splash duration is also 3 seconds sometimes the auto hide is called before the code hide. If you set a bigger duration with `launchShowDuration` configuration option it goes away (I had to go up to 4500 to get rid of the problem).

On an Ionic 4 app I couldn't reproduce as it takes less than 1 second to launch.

Closing as it's not really a plugin issue, but an app launch issue, when the app launch fast enough the hide is correctly executed. If the app is slow better configure the `launchShowDuration` to have a bigger value.

**Closed by jcesarmobile** 2018-08-24 15:00 UTC
