### ISSUE TITLE
feat: include a .gitignore with npx cap plugin:generate

### ISSUE THREAD

**Issue by jjdf01** [ionic-team/capacitor#2215] opened 2019-11-28 13:13 UTC
# Feature Request

## Describe the Feature Request
Include a .gitignore with npx cap plugin:generate.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution
Als provide a .gitignore file when **npx cap plugin:generate**. This would make it easier to know which files not to include for the different patforms. Now you need to be a platform expert to know the files that can be ignored.

**Comment by jcesarmobile** [comment] 2020-01-14 13:50
closing as duplicate of https://github.com/ionic-team/capacitor/issues/1980

**Closed by jcesarmobile** 2020-01-14 13:50 UTC
