### ISSUE TITLE
bug: Fatal error at com.getcapacitor.Bridge.launchIntent(Bridge.java:59)

### ISSUE THREAD

**Issue by qliqdev** [ionic-team/capacitor#6517] opened 2023-04-18 18:16 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/cli: 4.7.3
  @capacitor/ios: 4.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- [x] android

### Current Behavior

App crashes with error

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.getcapacitor.Bridge.launchIntent(Bridge.java:59)
       at com.getcapacitor.BridgeWebViewClient.shouldOverrideUrlLoading(BridgeWebViewClient.java:6)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-556311633:89)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:8096)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

### Expected Behavior

Should just skip if url is not defined

### Other Technical Details

`npm --version` output: `9.2.0`

`node --version` output: `12.22.12`

### Additional Context

This error unfortunately is on top

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/5783161/232867396-1630e007-a184-4af2-8015-3e4984689b57.png">

**Comment by jcesarmobile** [comment] 2023-04-19 07:59
duplicate of https://github.com/ionic-team/capacitor/issues/6483

**Closed by jcesarmobile** 2023-04-19 07:59 UTC
Labels: platform: android
