### ISSUE TITLE
android: xhr GET request aren't working if your server URL is in `allowNavigation` config

### ISSUE THREAD

**Issue by barakd** [ionic-team/capacitor#1573] opened 2019-05-24 17:12 UTC
Description of the problem:
Having your server URL in `allowNavigation`, won't allow you to make simple GET xhr requests on android.
Because capacitor will intercept them as navigation requests.

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

When my API URL is being added to the `allowNavigation` config.
E.G
```
{
  "appId": "app.com",
  "appName": "app",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "dist",
  "server": {
    "allowNavigation": [
        "my-server-url.com",
      ]
  },
  "android": {
    "allowMixedContent": true
  }
}
```

When my app is having a GET endpoint of my server.
Calling it VIA regular browser or IOS returns the proper headers and response.
![image](https://user-images.githubusercontent.com/7824284/58343654-461e6980-7e5c-11e9-9afb-8fcd011102c9.png)
But on android webView, capticator intercepts the request.
![image](https://user-images.githubusercontent.com/7824284/58343710-65b59200-7e5c-11e9-96c9-2b0ede51bd24.png)
note the `served from disk cache`
and `Content-Type:text/html` , `Client-Via:shouldInterceptRequest` headers.
In browsers or IOS the response returns the correct content-type which is `application/json; `
 
Capacitor version:
1.0.0
node version:
v8.11.3
npm version:
6.9.0
CocoaPods version:

Steps to reproduce:
- Have any API with a GET request.
- Add the API url to `allowNavigation` config.
- run  and build andorid project with an XHR request to the server.

I wonder if capacitor could differentiate between XHR requests and navigation requests to address this issue.

**Comment by allaghi** [comment] 2019-05-25 17:37
I am facing same issue @barakd

**Comment by mhjam** [comment] 2019-05-25 20:11
Looks like this is another use case that could be solved by #1488 .

**Comment by jcesarmobile** [comment] 2019-05-26 18:19
Supposedly it should go through the proxy and not to the local server. Can any of you provide a working sample project?

**Comment by mhjam** [comment] 2019-05-27 20:19
@jcesarmobile I might be wrong, but to me it looks like the request does go through the proxy, and that the internal HTTP request that the proxy makes is causing the problems that the OP has.
@barakd @allaghi I wonder why you are adding your API url to allowNavigation at all. It is not common to navigate to a backend API, or is it? Is there anything else hosted there, beside your API?

**Comment by allaghi** [comment] 2019-05-28 06:01
I don't know how, but now it works with me , I removed allowNavigation from the file , but I don't think it was the issue.

**Comment by theunreal** [comment] 2019-06-07 09:20
I have the same issue, removing everything from allow Navigation didn't do the trick for me. any idea?

**Comment by jcesarmobile** [comment] 2019-06-07 09:28
I have requested a sample app where it can be reproduced, but nobody provides it and I can’t reproduce

**Comment by wanying1804** [comment] 2019-06-16 23:53
i have the same issue. is there a solution for this?

**Comment by jcesarmobile** [comment] 2019-06-17 08:21
I have requested a sample project multiple times, but nobody is willing to collaborate, so if I can’t reproduce I won’t be able to fix it

**Comment by jcesarmobile** [comment] 2019-07-24 10:38
Closing as I couldn't reproduce and nobody provided a sample project.

**Closed by jcesarmobile** 2019-07-24 10:38 UTC

**Comment by mikejpeters** [comment] 2019-11-18 18:26
Here is a small sample project where you can reproduce the issue:
https://github.com/boundstate/capacitor-allow-navigation

(Tested on Pixel 2 with Android 10)

##### Steps to reproduce

1. Download & install the project:
    ```bash
    git clone https://github.com/boundstate/capacitor-allow-navigation.git
    cd capacitor-allow-navigation
    npm i
    ```

2. Add Android platform and open in Android Studio:
    ```bash
    npx cap add android
    npx cap open android
    ```

3. Run on your device and the request will fail (you get the alert "Unable to connect")

4. Remove _*.typicode.com_ from `allowNavigation`, then run `npx cap sync` and re-run the project on your device. The request succeeds and you get "Connection successful".

**Comment by jcesarmobile** [comment] 2019-11-18 18:39
thanks for the sample project, but it was already fixed in https://github.com/ionic-team/capacitor/pull/2146
