### ISSUE TITLE
bug: When I add an iOS app, I'm prompted to repeat the definition '_kCDVAssetsLibraryPrefix'

### ISSUE THREAD

**Issue by coderFH** [ionic-team/capacitor#5676] opened 2022-06-13 02:38 UTC
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
### Platform(s)

iOS platforms

### Current Behavior

When I do that in turn 
npm install @capacitor/ios --save 
npx cap add ios 
npx cap sync 
npx cap open ios 
duplicate symbol ‘_kCDVAssetsLibraryPrefix’  An error message is displayed after the ios program is started 
![Xnip2022-06-13_10-35-15](https://user-images.githubusercontent.com/13100401/173269628-0b75eb5a-4b67-45b7-ae13-5451fba37c17.jpg)

**Comment by Ionitron** [comment] 2022-06-13 08:51
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-29 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-29 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
