### ISSUE TITLE
Android notifications sound 

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1646] opened 2019-06-07 10:29 UTC
Description of the problem:
I have followed the code from the push section guide and notifications work fine on IOS and android. 

However on android they dont make a sound or vibration. I am sending them from the firebase dashboard.

Ive checked the phone settings and sound and vibration is on. 

Affected platform
- [x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x ] macOS
- [ ] linux

Other information:

Capacitor version:
Most recent

Tested on 2 android devices.

**Comment by solojuve1897** [comment] 2019-06-08 11:23
Have you looked at this?

https://capacitor.ionicframework.com/docs/apis/push-notifications#push-notifications-appearance-in-foreground

"plugins": {
  "PushNotifications": {
    "presentationOptions": ["badge", "sound", "alert"]
  }
}

**Comment by jcesarmobile** [comment] 2019-07-01 16:38
When sending them from Firebase console, those use notification payload, and when the device receives a notification payload while in background/closed it's are managed by the OS, not by Capacitor.
When in foreground it's managed by Capacitor, but it's not supposed to have sound nor vibrate. 

I've tested and I can't reproduce, make sure in step 5 of the firebase console you enabled sound, it's disabled by default.

But anyway, as it's managed by the OS, it might not work even if you enable it in the push, in my case, one of the devices is always ringing despite sending push with the sound disabled, so I suppose it can also happen the opposite.

**Closed by jcesarmobile** 2019-07-01 16:38 UTC
