### ISSUE TITLE
bug: No documentation on creating a simple capacitor electron plugin

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2191] opened 2019-11-19 13:46 UTC
Im trying to build a local plugin within the capacitor directory, the end goal is to be able to call capacitors webContents.print() method like so

```            
mainWindow.webContents.print({
            printBackground: true,
            color: false,
            marginsType: 2,
            pageSize: "A4",
            landscape: false
            }, (error, data) => {
            if (error) {
                log.error(`Some problem appears ${error}`);
                throw error
            }
        }) 
```

I cant find any information on this at all other than looking at your repo and how it is implemented, which is fine but how do i register this local plugin within capacitor electron so that I can call it from my app when the user clicks print. In my projects electron folder (projectName/electron) I have created a folder which is called capacitor-print, inside it I have the following files:

projectName/electron/capacitor-print/index.ts
```
import { MyPlugin } from './web';
import { registerElectronPlugin } from '@capacitor/electron/dist/esm';
registerElectronPlugin(MyPlugin);
```

and also 

projectName/electron/capacitor-print/web.ts
```
import { WebPlugin } from '@capacitor/core';

export class MyPluginWeb extends WebPlugin {
  constructor() {
    super({
      name: 'MyPlugin',
      platforms: ['electron']
    });
  }
  async echo(options: { value: any }) {
    console.log('ECHO', options);
    return options;
  }
}

// Instantiate the plugin
const MyPlugin: WebPlugin = new MyPluginWeb();

export { MyPlugin };
```

Can you confirm is this correct ? how do I get to use this within the context of the electron app because when clicking on the print button in my app I get the error that this is not registered as a web plugin

Should I be adding something to electrons preload scripts part and if so what ?

```
  mainWindow = new BrowserWindow({
    height: 920,
    width: 700,
    show: false,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
      preload: path.join(__dirname, 'node_modules', '@capacitor', 'electron', 'dist', 'electron-bridge.js')
    }
  }); 
  ```

https://github.com/ionic-team/capacitor/issues/1281

https://github.com/ionic-team/capacitor/issues/1748

**Comment by REPTILEHAUS** [comment] 2019-11-19 16:30
For anyone else that needs to implement a plugin you can circumvent Capacitor entirely and just use Electrons IPC for communicating between Angular and Electrons API

**Comment by digaus** [comment] 2020-01-07 10:25
> Electrons IPC

Do you have an example?

**Comment by jcesarmobile** [comment] 2020-01-13 18:39
closing as duplicate of https://github.com/ionic-team/capacitor/issues/1748

**Closed by jcesarmobile** 2020-01-13 18:39 UTC
