### ISSUE TITLE
bug: Bundle#saveInstanceState for large Call with startActivityForResult

### ISSUE THREAD

**Issue by boldtrn** [ionic-team/capacitor#6211] opened 2023-01-13 10:51 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

```

### Platform(s)
Android

### Current Behavior
When you run `startActivityForResult` with a call that contains a lot of data, the app crashes.

### Expected Behavior
App does not crash.

### Code Reproduction

In `Bridge#saveInstanceState` we call `outState.putString(BUNDLE_PLUGIN_CALL_OPTIONS_SAVED_KEY, call.getData().toString());`

https://github.com/ionic-team/capacitor/blob/0735e89d48e77a1ddca97a48e3851f4a0a3ea2c1/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L1003

This can result in the following exception:
```
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2051296)
W/ActivityStopInfo: Bundle stats:
W/ActivityStopInfo:   capacitorLastPluginCallOptions [size=1022652]
W/ActivityStopInfo:   android:viewHierarchyState [size=1076]
W/ActivityStopInfo:   capacitorLastPluginCallBundle [size=1022684]
W/ActivityStopInfo:     _json [size=1022652]
W/ActivityStopInfo:   androidx.lifecycle.BundlableSavedStateRegistry.key [size=3660]
W/ActivityStopInfo:     android:support:activity-result [size=2544]
W/ActivityStopInfo:       KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=1672]
W/ActivityStopInfo: PersistableBundle stats:
W/ActivityStopInfo:   [null]
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2051296 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2051296 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:540)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4627)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7861) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```

I would like to propose that instead of saving the data to the outState, that we store this somewhere else and only keep a reference to this in the out state.

If this is not possible, I would like to propose that we throw the error when calling `startActivityForResult`. This would make catching and solving this error a lot easier.

Possibly related to #1044

**Comment by Ionitron** [comment] 2023-01-17 09:43
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-17 11:03
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-02 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
