### ISSUE TITLE
bug:  number/string value in http response throw error

### ISSUE THREAD

**Issue by grzegorzCieslik95** [ionic-team/capacitor#6538] opened 2023-04-26 11:30 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
android
### Current Behavior
When my api return number/string from endpoint capacitor plugin like

```
Value 125 of type java.lang.String cannot be converted to JSONArray
```

### Expected Behavior
Should return a simple value

`npm --version` output: 8.11.0

`node --version` output: v16.16.0

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2023-04-26 11:48
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by grzegorzCieslik95** [comment] 2023-04-26 12:53
config

```
const config = {
  appId: 'appId',
  appName: 'name',
  webDir: 'dir',
  bundledWebRuntime: false,
  ios: {
    contentInset: "always",
  },
  android: {
    appId: 'appId',
  },
  plugins: {
    CapacitorHttp: {
      enabled: true
    },
    CapacitorCookies: {
      enabled: true
    },
  },
  ...server,
};
```

request

```
// this request return id as a number
axiosInstance.getNumberId().then(({data}) => data)
```

**Comment by jcesarmobile** [comment] 2023-04-27 09:57
Can you provide a full sample app we can run to reproduce the problem?

**Comment by NorthFred** [comment] 2023-05-07 14:49
I am getting the same on Android. When there is a **number in the back-end response**, following error is shown:

```
Error: Value 1433 of type java.lang.Integer cannot be converted to JSONArray
    at returnResult (VM3:771:32)
    at win.androidBridge.onmessage (VM3:746:21)
```

This happens in both POST and PUT requests, where a successful creation / update returns a number value from the back-end.  For instance, my back-end is handled with a PHP script which returns the numerical index of the created / updated entity on successful operation.

As ugly work-around, I am now catching this error and if it contains the message above, it will resolve the request as if it was successful. But this is not desired.

**Comment by jcesarmobile** [comment] 2023-05-08 08:17
Closing since no sample app was provided, please, if somebody still faces this issue, create a new issue and provide a sample app where the issue can be reproduced.

**Closed by jcesarmobile** 2023-05-08 08:17 UTC
Labels: platform: android, needs reproduction
