### ISSUE TITLE
Ionic capcitor Network error " Request aborted at e.exports (chunk-vendors.85bc3696.js:1)  at XMLHttpRequest.m.onabort (chunk-vendors.85bc3696.js:26)" on android emulator

### ISSUE THREAD

**Issue by alao115** [ionic-team/capacitor#4509] opened 2021-04-28 09:15 UTC
I'm using Ionic/Vue and wheen I run the application in my browser it works well but when I compile and run on an android emulator I get the error below. Please help 

Error: Request aborted
    at e.exports (chunk-vendors.85bc3696.js:1)
    at XMLHttpRequest.m.onabort (chunk-vendors.85bc3696.js:26)

**Comment by Ionitron** [comment] 2021-04-28 09:32
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-05-18 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-05-18 00:04 UTC
Labels: needs reply, needs reproduction
