### ISSUE TITLE
bug: Camera plugin requires users to edit the photo first even though edit is set to disabled

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/capacitor#2210] opened 2019-11-26 11:15 UTC
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0

  @capacitor/core: 1.3.0

  @capacitor/android: 1.3.0

  @capacitor/ios: 1.3.0

Installed Dependencies:

  @capacitor/core 1.3.0

  @capacitor/cli 1.3.0

  @capacitor/android 1.3.0

  @capacitor/ios 1.3.0


[success] Android looking great! 👌
  Found 10 Capacitor plugins for ios:
    com-sarriaroman-photoviewer (1.2.4)
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-advanced-http (2.2.0)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-facebook4 (6.2.0)
    cordova-plugin-file (6.0.2)
    cordova-plugin-market (1.2.0)
    cordova-sqlite-storage (3.4.0)
    es6-promise-plugin (4.2.2)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.4)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Sample Code or Sample Application Repo

```
  
    async sendImageFromCamera() {
        return this.sendImage(CameraSource.Camera)
    }

    async sendImageFromLibrary() {
        return this.sendImage( CameraSource.Photos )
    }  
  
    async sendImage(pictureSourceType: CameraSource ) {
        if (!this.capacitor) {
            if (pictureSourceType === CameraSource.Camera) {
                   let modal: HTMLIonModalElement = await this.modalCtrl.create({
                        component: CameraMsgModal,
                        componentProps: {}
                    });        
                    modal.onDidDismiss().then((imageBase64: any) => {
                        if (imageBase64) {
                            try {
                                 this.sendImageBase64(`data:image/jpeg;base64,${imageBase64.data}`) // provides a jpeg webcam shot rather than png
                            } catch (error) {
                                this.log.error
                            }
                        }
                    });
                    this.log.log('presenting modal...')
                    try {
                        await modal.present();   
                    } catch (error) {
                        this.log.error
                    }                    
            }
            return
        } else {
            const options: CameraOptions = {
                direction: CameraDirection.Rear,
                saveToGallery: false,
                presentationStyle: "fullscreen",
                allowEditing: false,
                correctOrientation: true,
                quality: 60,
                width: 400,
                height: 400,
                resultType: CameraResultType.Base64,
                source: pictureSourceType
            }        
            try {
            const image = await Camera.getPhoto(options);
            const imageUrl = image.base64String 
            if(imageUrl) {
                this.sendImageBase64(`data:image/jpeg;base64,${imageUrl}`)                           
            }
            } catch (error) {
                this.log.error(`Error encountered while user selecting image pre-crop ${error}`)
            }            
        }      
    }
    
```

## Reproduction Steps

Android phone with ionic capacitor app, allow user 2 methods in the controller 1 for taking a new photo and 1 for taking from gallery. User selects either take photo or from gallery and it only sends if they edit the photo they just took in the photos app and add a filter and click save - expected result as was working with the cordova previously is to just select or take a photo and it will send directly to the apps interface.

Issue most prevalent on Android, IOS still asks you to edit the image before sending also but its less of a hassle and feels more native.

## Other Technical Details

`npm --version` output:
6.9.0

`node --version` output:
v10.16.0

**Comment by REPTILEHAUS** [comment] 2019-11-26 16:27
Steps to reproduce (Huawei Nova)

1) Click on camera button in app to take photo or select a photo
2) Camera app launches and I take a picture, confirm with clicking on tick on top right

- the next step happens but it is not desired as allowEditing is set to false

3) "Complete action using" screen that lets me select either "View and edit" or "Photos"

**Comment by jcesarmobile** [comment] 2020-01-15 12:44
I can't reproduce on my devices, can you provide a sample app just in cases something is different from the code you shared here?

Also, would be good to know android version of the device and if only happens in that one (if you tested more)
Since the plugin just launches an Intent to the Camera app, might be possible that the Camera of that device behaves like that.

**Comment by aspoonemore** [comment] 2020-01-25 16:59
I can duplicate this as well on a SAMSUNG-SM-J327A Android 7.0 physical device as well as in the simular on a Pixel 3a running API 29. 

1. Launch camera from function below
2. Take photo
3. After taking photo, the edit screen is shown with no option to save. Click the x and you lose the photo. (screenshot below)
4. Make an edit and you're able to "save copy" and the photo is sent back into the app  (screenshot below)

![Screenshot_20200125-102625](https://user-images.githubusercontent.com/9590227/73124485-9dcc2200-3f61-11ea-8a89-10bab6f9e477.png)
![Screenshot_20200125-102637](https://user-images.githubusercontent.com/9590227/73124486-9dcc2200-3f61-11ea-87a2-94fec58995a6.png)



  async takeAPhoto() {
    try {
      const image = await Camera.getPhoto({
        quality: 100,
        allowEditing: false,
        resultType: CameraResultType.Base64
      });
      // var imageUrl = "data:image/png;base64," + image.base64String;
      var imageUrl = image.base64String;
      this.image  = imageUrl;

      this.openAddPhotoModal(this.image);
    } catch (error) {
      console.error("error opening camera")
      console.error(error);
    }
  }

**Comment by aspoonemore** [comment] 2020-01-25 17:01
Also, this looks to be the same as https://github.com/ionic-team/capacitor/issues/2020

**Comment by jcesarmobile** [comment] 2020-02-19 16:47
closing since the reporter didn't answer.

For the "losing photo if you cancel" bug, that's fixed already.

**Closed by jcesarmobile** 2020-02-19 16:47 UTC
Labels: needs-reply
