### ISSUE TITLE
Error when appending body for POST request when the Content-Type is unusual on iOS

### ISSUE THREAD

**Issue by BigPackie** [ionic-team/capacitor#6168] opened 2022-12-15 12:28 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@capacitor/ios@4.6.1` for the project I'm working on.

Failure to append body for **POST** requests when the Content-Type is unusual when using the native HTTP plugin `import { CapacitorHttp
} from '@capacitor/core';` for iOS

Currently to append the body as json a very narrow pool of Content-type is accepted.  There are many json subtypes usually annotated with `+json` as per http://www.iana.org/assignments/media-types/media-types.xhtml. 

**The condition for appending body as json should be expanded or broadened.**

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift b/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
index 745e116..ef32705 100644
--- a/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
+++ b/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
@@ -97,7 +97,7 @@ public class CapacitorUrlRequest: NSObject, URLSessionTaskDelegate {
         // If data can be parsed directly as a string, return that without processing.
         if let strVal = try? getRequestDataAsString(body) {
             return strVal
-        } else if contentType.contains("application/json") {
+        } else if contentType.contains("application/json") || contentType.contains("json") {
             return try getRequestDataAsJson(body)
         } else if contentType.contains("application/x-www-form-urlencoded") {
             return try getRequestDataAsFormUrlEncoded(body)
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Ionitron** [comment] 2022-12-15 12:59
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-31 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-31 00:05 UTC
Labels: needs reply, needs reproduction
