### ISSUE TITLE
bug: capacitor 2.4.6 Crashed when calling the camera,    android studio Logcat  show "Access denied finding property "ro.vendor.df.effect.conflict" "

### ISSUE THREAD

**Issue by dahaizhiliang** [ionic-team/capacitor#4208] opened 2021-02-15 14:58 UTC
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2021-02-15 15:02
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-03-18 00:15
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-03-18 00:15 UTC
Labels: needs reply, needs reproduction
