### ISSUE TITLE
setstate not working in Android app but working in PWA

### ISSUE THREAD

**Issue by yonghing** [ionic-team/capacitor#1865] opened 2019-08-12 01:10 UTC
Description of the problem:

I have following code is working in PWA, but in Android app string1 does not displayed, any clues ?
or is caused by capacitor camera API issue ?
https://github.com/yonghing/ionic-react-photo/blob/master/src/pages/Tab2.tsx

Affected platform
- [x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.1.1
node version:

npm version:

CocoaPods version:

Steps to reproduce:

I have following code is working in PWA, but in Android app string1 does not displayed, any clues ?
or is caused by capacitor camera API issue ?
https://github.com/yonghing/ionic-react-photo/blob/master/src/pages/Tab2.tsx

Link to sample project:

https://github.com/yonghing/ionic-react-photo

**Comment by jcesarmobile** [comment] 2020-01-13 18:13
the sample project is not accessible and there is no enough information to know what you are doing or what the problem is, so closing.

**Closed by jcesarmobile** 2020-01-13 18:13 UTC
