### ISSUE TITLE
bug: appStateChange trigged when anything native happens ontop of webview.

### ISSUE THREAD

**Issue by joeldhenry** [ionic-team/capacitor#5320] opened 2021-12-15 00:09 UTC
## Bug Report
Any native pop-over such as Image Picker, Permissions alert, inappbrowser etc triggers appStateChange to change isActive to false, and alerts isActive as true once the native element is closed. 

This is different than the documentation which states `Listen for changes in the App’s active state (whether the app is in the foreground or background)`

### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/ios: 3.3.3

```

### Platform(s)
Android,iOS

### Current Behavior
When native alert, app permissions, or image picker is presented above the webview, appStateChange is emitted.

### Expected Behavior
appStateChange should only emit `isActive=false` when the app is pushed into the background such as being closed, or the phone being turned off.

### Code Reproduction
```
        // subscribe to appStateChange

        App.addListener('appStateChange', ({ isActive }) => {
            console.log('isActive', isActive);
        });

        // do something that creates a pop-up
        CapacitorGeoLocation.getCurrentPosition(....);
        Window.cordova.InAppBrowser.open(...);
```

### Additional Context
I am migrating from Cordova to Capacitor where 'resume' and 'pause' events trigger as expected.

**Comment by jcesarmobile** [comment] 2021-12-15 14:04
It's a duplicate of https://github.com/ionic-team/capacitor/issues/4597

There is a feature request to add more states 
https://github.com/ionic-team/capacitor/issues/4035

resume and pause are still fired for Cordova compatibility, so you can still use them

**Closed by jcesarmobile** 2021-12-15 14:04 UTC
Labels: platform: android, platform: ios
