### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rsougata19** [ionic-team/capacitor#5573] opened 2022-04-20 15:19 UTC
### Capacitor Version
"@capacitor/android": "^3.4.3",
    "@capacitor/core": "^3.4.3",

```
PASTE OUTPUT HERE
Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-7.0-all.zip'.

### Platform(s)
using Android Studio in Mac OS Monterey 



### Current Behavior
I have created a angular (v 10.0.1) web application , trying to create android apk using capacitor , but facing above mention issue .







`node --version` output: v16.14.2
'npm --version' output:8.5.0



### Additional Context
package.json

{
  "name": "my-first-android-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    no
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.3.3",
    "@angular/cli": "^10.2.1",
    "@angular/compiler-cli": "~10.0.0",
    "@capacitor/cli": "^3.4.3",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.3.19",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}

**Comment by jcesarmobile** [comment] 2022-04-20 16:41
Is https://services.gradle.org/distributions/gradle-7.0-all.zip reachable to you?
what's your Android Studio version?

**Comment by rsougata19** [comment] 2022-04-20 16:48
i can download the gradle-7.0-all.zip file directly hit the URL from  browse
<img width="642" alt="Screenshot 2022-04-20 at 10 18 22 PM" src="https://user-images.githubusercontent.com/5312461/164282141-e6e36975-a704-4edc-82cf-7936d4d6335a.png">
r

**Comment by rsougata19** [comment] 2022-04-20 16:53
> Is https://services.gradle.org/distributions/gradle-7.0-all.zip reachable to you? what's your Android Studio version?

i can download the gradle -7.0-all.zip file directly hit from browser, 
<img width="642" alt="Screenshot 2022-04-20 at 10 18 22 PM" src="https://user-images.githubusercontent.com/5312461/164282956-af308669-fe7b-4174-9cfc-4d82789a07fd.png">

**Comment by Ionitron** [comment] 2022-08-25 17:39
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-10 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-10 00:06 UTC
Labels: needs reply, needs reproduction
