### ISSUE TITLE
Invalid path for vendored_libraries generated in podspec

### ISSUE THREAD

**Issue by mley** [ionic-team/capacitor#5866] opened 2022-08-17 10:19 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.7.0
  @capacitor/android: 3.7.0
  @capacitor/core: 3.7.0
  @capacitor/ios: 3.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- ios

### Current Behavior

I'm trying to integrate a new version of the zoom plugin from here: https://devforum.zoom.us/t/unable-to-join-meeting-ionic-app/74211 and after fixing some of the stuff the plugin got wrong, Xcode still won't link the app when building the app for a real ios device. The new zoom plugin comes with xcframework instead of only the ios device framework; I'm not sure how that affects capacitor.

So when doing a `ionic cap sync ios` the file ios/capacitor-cordova-ios-plugins/CordovaPlugins.podspec contains following line
```
s.vendored_frameworks = 'sources/Cordova.plugin.zoom/libs/ios/MobileRTC.xcframework'
[...]
s.vendored_libraries = 'sources/Cordova.plugin.zoom/libMobileRTC.xcframework'
```
I'm not sure what to make of that, since the value of s.vendored_libraries is not a valid path within `ios/capacitor-cordova-ios-plugins/`, but the s.vendored_framework is.

Maybe the value for s.vendored_libraries shall contain these "special" values, but since there are no comments or tests regarding [that bit](https://github.com/ionic-team/capacitor/blob/main/cli/src/ios/update.ts#L327), it leaves me a bit puzzled, since als the [podspec specification](https://guides.cocoapods.org/syntax/podspec.html#vendored_libraries) says, the values shall be paths.

### Expected Behavior

Xcode successfully builds the application.

### Code Reproduction

I can't supply code for reproduction, since the new zoom plugin is available by request only.

### Other Technical Details

`npm --version` output:8.12.1

`node --version` output: v14.19.2

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment] 2022-08-17 10:33
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-02 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-02 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
