### ISSUE TITLE
bug: ionic cap run android does not fully respect flavor

### ISSUE THREAD

**Issue by pfleigo** [ionic-team/capacitor#5104] opened 2021-10-07 09:55 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/android: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/cli: 3.2.0
  @capacitor/ios: 3.2.0
```

### Platform(s)
android

### Current Behavior

- in capacitor.config.ts I set the flavor for android like so:
```
const config: CapacitorConfig = {
  android: {
    flavor: 'myFlavorName'
  },
  ...
}
```
- I run `ionic cap run android`
- the flavor is not respected for assembling the project with the correct build variant

### Expected Behavior
- respect the flavor when assembling the project

### Code Reproduction
- any ionic capacitor starter project is fine

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: 14.15.1

### Additional Context
When looking at the capacitor source code, you can see that `ionic cap run android` will always use `assembleDebug` as gradle argument. Instead, it should take into account the flavor name, e.g. assembleMyFlavorNameDebug
Source code: https://github.com/ionic-team/capacitor/blob/05cb8533d4479efd3dc823b18f48699302f462ba/cli/src/android/run.ts#L22

**Comment by Ionitron** [comment] 2021-10-07 10:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-23 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed as completed by Ionitron** 2021-10-23 00:03 UTC
Labels: platform: android, needs reproduction
