### ISSUE TITLE
bug: Black gap when iOS keyboard type changes

### ISSUE THREAD

**Issue by jldlxs** [ionic-team/capacitor#6223] opened 2023-01-17 20:33 UTC
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1
```

### Platform(s)
iOS

### Current Behavior
A black box appears when the keyboard type is changed inside card modal. And a white gap appears when the keyboard type is changed outside card modal.
The problem occurs only with @capacitor/keyboard installed with Ionic.
If removed keyboard plugin the problem is solved BUT the keyboard pushes the entire modal up. Keyboard plugin is needed to use KeyboardResize.Ionic.
So with plugin: black and white gap.
Without plugins KeyboardResize.Ionic resource, the entire app is pushed up when keyboard opens.
Is there a workaround to solve this issue?

### Expected Behavior
Não black/white gap when keyboard shows.

https://user-images.githubusercontent.com/70068285/213006409-55667bf3-2af6-416f-815a-da2b2f1ff401.MP4

**Comment by Ionitron** [comment] 2023-01-18 09:45
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-03 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-03 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
