### ISSUE TITLE
Android: local notification repeat after reboot even if already shown

### ISSUE THREAD

**Issue by MedaiP90** [ionic-team/capacitor#3424] opened 2020-08-15 19:04 UTC
### Capacitor Version
```json
"@capacitor/android": "^2.4.0",
"@capacitor/core": "2.4.0",
```

### Platform(s)
[ x ] Android

### Current Behavior
An already shown notification is rescheduled after the device reboot (without opening it, but closing it instead).

### Expected Behavior
Already shown notifications not rescheduled at device reboot.

### Code Reproduction 
*I'll link the code sample here as soon as possible*

**Steps to reproduce**:
1. schedule a local notification for a day,
2. wait for the notification to show and delete the notification,
3. shutdown the device,
4. power on the device the next day,
5. wait for few seconds for the same notification to show.

### Other Technical Details
`npm --version` output: `6.14.7`
`node --version` output: `v12.18.3`

**Comment by jcesarmobile** [comment] 2020-08-17 13:31
please, can you provide al the requested information from the bug template?

## Bug Report

### Capacitor Version


```
PASTE OUTPUT HERE
```

### Platform(s)




### Current Behavior




### Expected Behavior




### Code Reproduction




### Other Technical Details


`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

**Comment by Ionitron** [comment] 2020-09-17 00:14
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2020-09-17 00:14 UTC
Labels: needs reply
