### ISSUE TITLE
CapacitorHttp Plugin error handling

### ISSUE THREAD

**Issue by FlueschPluesch** [ionic-team/capacitor#6024] opened 2022-10-24 10:26 UTC
### Plugin(s)
CapacitorHttp 

### Capacitor Version
```
@capacitor/core 4.4.0
```

### Platform(s)
iOS

### Current Behavior
iOS app freezes when CapacitorHttp throws an error. try and catch does not help. In my case it happens when I call a domain that does not exist. The console then shows “NSURLErrorDomain” and the app stops there. 

### Expected Behavior
There should be some possibility to handle the errors.

### Code Reproduction
const options = {
  url: 'https://wrongDomainXYZ.com',
  method: 'GET',
  headers: {  'Accept':' */*',
                    'User-Agent':'' },
  params: {},
  responseType: 'text',
  disableRedirects: false
};

let response = {};

try {

     response = await window.Capacitor.Plugins.CapacitorHttp.request(options);
     console.log(response);

 } catch (error) {

     console.log(error);
        
 }

**Comment by jcesarmobile** [comment] 2022-10-25 16:25
Thanks, I've created a sample app from the zip since it contained an app inside the app and the changes were made in the build folder, so they got overridden on npm run build.
https://github.com/jcesarmobile/http-errors

but I could reproduce on iOS

**Comment by archibald-picq** [comment] 2022-10-27 10:06
Same issue here. It has been fixed on the original @capacitor-community/http project : https://github.com/mrahn24/http/commit/da0742fde037e34008a5c86a176a1c33b888bc02

I've submitted a PR https://github.com/ionic-team/capacitor/pull/6033

**Comment by EinfachHans** [comment] 2022-11-22 12:01
Please  check out the PR, the http plugin is unusable like this for us 😕

**Closed** 2023-01-17 14:18 UTC
Labels: platform: ios, type: bug
