### ISSUE TITLE
Strange behaviour with backspace

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#426] opened 2018-04-03 11:19 UTC
Hi.

I have encountered a strange behaviour I was hoping to solve. In the browser ("npm run dev") this problem doesn't occur. Also launching my hosted project on the phone via the browser works without this problem. I have yet to try the iOS-app on an iOS-device. On my Android-device (Samsung Galaxy S8 Note) the following happens in the android-app:

My project is written in Vue.js. I have a search-field produced by the following code:

`<b-form-input v-model="search" type="text" autofocus></b-form-input>`

When typing text to the input I can see in the logcat the following two lines being generated for every key stroke:

```
04-03 12:59:12.386 28595-28595/com.lakemedelsappen.app D/ViewRootImpl@216ffdf[MainActivity]: ViewPostImeInputStage processKey 0
04-03 12:59:12.387 28595-28595/com.lakemedelsappen.app D/ViewRootImpl@216ffdf[MainActivity]: ViewPostImeInputStage processKey 1

```

For this example I have typed two letters. When trying to delete the two inputted letters I need to first press the backspace button on the phone two times before it starts to register the pressing of backspace. In the logcat nothing will show for the first two strokes, only the third stroke will register:

```
04-03 13:04:07.648 28595-28595/com.lakemedelsappen.app D/ViewRootImpl@216ffdf[MainActivity]: ViewPostImeInputStage processKey 0
    ViewPostImeInputStage processKey 1
```

When it finally registers the pressing of backspace you can remove the rest of the inputted text without hesitation. If I had inputted 5 letters, instead of 2 as in this example, I would have had to first press the backspace button 5 times before getting any response.

Any ideas?

Regards,

**Comment by mlynch** [comment] 2018-04-03 15:00
Any chance you can send me your app? Would love to test it and figure out what's going on. max@ionicframework.com

**Comment by solojuve1897** [comment] 2018-04-04 07:06
@mlynch 

I created a brand new Vue.js-project via the Vue Cli. The only thing I added to it was a search-field. I also added Capacitor of course to build the the project as a native app for Android. The same problem occurs. I will send you the complete project.

**Comment by solojuve1897** [comment] 2018-04-04 08:00
Can confirm that it works on iOS. The issue is specific to Android-devices...

**Comment by solojuve1897** [comment] 2018-04-04 14:04
This issue is very specific it seems. Only occurs while using **swiftkey** as keyboard.

**Comment by mlynch** [comment] 2018-04-04 15:29
Can reproduce, can also confirm Cordova doesn't have the same issue so this should be fixable

**Comment by mlynch** [comment] 2018-04-04 17:46
Looks like this is the culprit: https://github.com/ionic-team/capacitor/commit/b6947e0535efc9f5558f11663d01fd90dad9a8cc

**Comment by mlynch** [comment] 2018-04-04 19:04
Closing as wontfix because I can confirm that Cordova doesn't support capturing input, so the tradeoff is either break #371 which flies in the face of standard recommended android practices, or support a bug case in swiftype.

**Closed by mlynch** 2018-04-04 19:04 UTC
Labels: android, high priority
