### ISSUE TITLE
bug: Still crash when minifyEnabled true

### ISSUE THREAD

**Issue by ironbone** [ionic-team/capacitor#5741] opened 2022-07-05 15:22 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] Android looking great!
```

### Platform(s)

Android

### Current Behavior

When creating an android signed APK and when `minifyEnabled` is set `true` the application crash with the error

`Could not find class by class path: com.capacitorjs.plugins.app.AppPlugin`

I know that this is a known issue, but in the documentation here:
`https://capacitorjs.com/docs/v3/android/troubleshooting`
we have:
`As of Capacitor v3.2.3 there are ProGuard rules included in Capacitor that cover the core functionality of Capacitor plugins, permissions, and activity results`
So for me, it should work out of the box.

My `build.gradle` settings:
```
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
``` 

### Other Technical Details

`npm --version` 8.13.1

`node --version` v16.14.2

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment] 2022-07-05 15:24
duplicate of https://github.com/ionic-team/capacitor/issues/5606

**Closed by jcesarmobile** 2022-07-05 15:24 UTC
Labels: platform: android
