### ISSUE TITLE
[Feature]: Add capacitor to SSR enabled Angular project

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/capacitor#7780] opened 2024-11-27 10:07 UTC
### Description

I have SSR enabled angular 18 project when i add capacitor integration it is showing error that index.html not found.

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

There should an option to update `index.html` file name in `capacitor.config.ts` file

Error i am getting:

```
The web assets directory (./dist/app/server) must contain an index.html file.
The web assets directory (./dist/app/browser) must contain an index.html file.
```

app/server generates `index.server.html`
app/browser generates `index.csr.html`

**Comment by jcesarmobile** [comment] 2024-11-27 10:40
closing as duplicate of https://github.com/ionic-team/capacitor/issues/3912

**Closed by jcesarmobile** 2024-11-27 10:40 UTC
Labels: triage

**Comment by Saqib92** [comment] 2024-11-27 11:15
What is the solution for this? is there a way we can add capacitor to Angular SSR project?

**Comment by miguel2211** [comment] 2024-11-28 00:49
I have the same error, did you find a solution?

**Comment by Saqib92** [comment] 2024-11-28 07:44
> I have the same error, did you find a solution?

No. I tried renaming index.html file then run `npx cap sync` and `npx cap build android` but the app is crashing on startup.
