### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView APIs

### ISSUE THREAD

**Issue by marbetschar** [ionic-team/capacitor#1929] opened 2019-09-06 11:41 UTC
Description of the problem:

**Affected platform**
- [ ] Android
- [x] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [ ] Windows
- [x] macOS
- [ ] linux

**Other information**

When the App is archived in Xcode and uploaded to App Store Connect, it does get post-processed by App Store Connect. Once this post-processing is done, I receive an E-Mail with the following complaint:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See [https://developer.apple.com/documentation/uikit/uiwebview](https://developer.apple.com/documentation/uikit/uiwebview) for more information. 

**Capacitor version:** 1.1.1

**node version:** v12.9.1

**npm version:** 6.10.3

**CocoaPods version:** 1.7.5

**Steps to reproduce**

Just create a new app, archive it and upload it to App Store Connect.

**Comment by bryplano** [comment] 2019-09-06 12:09
Have you tried with Capacitor 1.2.0? Latest release removes references to UIWebView. PR was already merged.

https://github.com/ionic-team/capacitor/issues/1912

**Comment by bryplano** [comment] 2019-09-06 18:49
Closing as a dupe of https://github.com/ionic-team/capacitor/issues/1912

**Closed by bryplano** 2019-09-06 18:49 UTC

**Comment by marbetschar** [comment] 2019-09-06 20:44
@bryplano confirmed; new version fixes the issue. Thank you very much for the hint!

**Comment by bryplano** [comment] 2019-09-13 13:28
@rajashekaranugu - those plugins have their own Github repositories. Do a search to see whether or not `UIWebView` is used in either of those plugins and search for existing issues on the appropriate repos. Those may not even be the plugin(s) at fault in your project.

This is the Capacitor repository and the issue has been fixed here.
