### ISSUE TITLE
bug: Ionic Native Firebase X not working with Capacitor

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [ionic-team/capacitor#5223] opened 2021-11-08 21:03 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.3.1
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1
```

### Platform(s)

Android

### Current Behavior

I get the following error while building. It works fine if I replace Capacitor with Cordova 10 and Cordova Android 10:

```
> capacitor run android --no-sync --target emulator-5554
[capacitor] ✖ Running Gradle build - failed!
[capacitor] [error] 
[capacitor]         > Configure project :app
[capacitor]         google-services.json not found, google-services plugin not applied. Push Notifications won't work
[capacitor]         strippedNativeLibsDir is deprecated and no longer used. Please remove it from your build configuration.
[capacitor]         
[capacitor]         > Configure project :capacitor-cordova-android-plugins
[capacitor]         Crashlytics was applied to an android-library project.
[capacitor]         Android-library support is currently an incubating feature.
[capacitor]         Contact us at https://firebase.google.com/support/troubleshooter/contact with any issues.
[capacitor]         
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]         
[capacitor]         * Where:
[capacitor]         Script '/home/dev/ionic-native-firebase-x-demo/node_modules/cordova-plugin-firebasex/src/android/build.gradle' line: 20
[capacitor]         
[capacitor]         * What went wrong:
[capacitor]         A problem occurred evaluating script.
[capacitor]         > Failed to apply plugin class 'com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin'.
[capacitor]         > Applying the Firebase Crashlytics plugin to a library project is unsupported. It should only be applied to the application module of your project to enable automatic upload of obfuscation mapping files for your application.
[capacitor]         
[capacitor]         * Try:
[capacitor]         Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[capacitor]         
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]         
[capacitor]         BUILD FAILED in 6s
[capacitor]         
[capacitor]         Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[capacitor]         Use '--warning-mode all' to show the individual deprecation warnings.
[capacitor]         See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
```

### Expected Behavior
It completes the build process without errors.

### Code Reproduction

Setup a new ionic project:

```bash
ionic start ionic-native-firebase-x-demo
cd ionic-native-firebase-x-demo
ionic capacitor add android
```

Install Firebase X as described in https://ionicframework.com/docs/native/firebase-x:

```bash
npm install cordova-plugin-firebasex
npm install @ionic-native/firebase-x
ionic cap sync
```

Generate a google-services.json file with package name `io.ionic.starter` in https://console.firebase.google.com/ and place it in the project root folder.

Try to run the project in the emulator following the steps from https://ionicframework.com/docs/developing/android#running-with-capacitor:

```bash
ionic capacitor copy android
ionic capacitor run android -l --host=YOUR_IP_ADDRESS
```

See demo at https://github.com/SoftwareAndOutsourcing/ionic-native-firebase-x-demo.

### Other Technical Details

`npm --version` output: 8.1.3
`node --version` output: v16.13.0
`gradle -v` output: tried both 4.4.1 and 7.1.1
`ionic -v` output: 6.18.0

**Comment by Ionitron** [comment] 2021-11-09 15:15
Issue detected as duplicate of https://github.com/ionic-team/capacitor/issues/3376

**Closed by Ionitron** 2021-11-09 15:15 UTC
Labels: platform: android
