### ISSUE TITLE
feat: Allow disable Cordova bridge

### ISSUE THREAD

**Issue by riderx** [ionic-team/capacitor#5522] opened 2022-03-22 15:34 UTC
### Description
All the plugin i use are now in Capacitor and my whole stack is in Capacitor, it could be great to be able to opt-in to disable Cordova bridge in the codebase.
Like with something inside the `capacitor.config.json`

### Platform(s)
IOS and Android

### Preferred Solution
Be able to disable is the solution to me.

### Alternatives
Have a version in npm without cordova like `3.4.3-nocordova` could be even more interesting but seems a bit hard to manage.

**Comment by jcesarmobile** [comment] 2022-04-06 13:07
closing as duplicate of https://github.com/ionic-team/capacitor/issues/2356

**Closed by jcesarmobile** 2022-04-06 13:07 UTC
Labels: platform: android, platform: ios
