### ISSUE TITLE
feat: allow custom Storage KEY_PREFIX

### ISSUE THREAD

**Issue by ehorodyski-ionic** [ionic-team/capacitor#3090] opened 2020-06-11 13:39 UTC
### Description

While working with a member in the community, it was discovered that the `KEY_PREFIX` value in the `Storage` API is hardcoded. 

In their scenario, an existing PWA is being migrated to Capacitor. Existing users have cached data values stored in `localStorage` without a prefix, such as in the key `foo`. When using the Capacitor API - `Storage.get({key: 'foo'})` - the existing data is not returned as the Storage API is searching `localStorage` for `_cap_foo`.

### Platform(s)

* iOS 
* PWA
* Android (?)

### Preferred Solution

An enhanced development experience may be to allow developers to set their own prefix value used by the Storage API, on applicable platforms.

Looking through the [Android source code](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/Storage.java) with minimal knowledge of Android's `SharedPreferences`, I cannot speak to whether letting developers set their own preference name would be beneficial or cause any unintended side-effects.

### Alternatives

A few alternatives are available:
1. Fetch existing values from `localStorage` and "migrate" them using the Storage API.
2. Check the platform, if it's a PWA, run `(Storage as any)['KEY_PREFIX'] = 'my_prefix';`.

**Comment by jcesarmobile** [comment] 2020-06-11 14:03
duplicate of https://github.com/ionic-team/capacitor/issues/873

**Closed by jcesarmobile** 2020-06-11 14:03 UTC
