### ISSUE TITLE
bug: Capacitor 3  app don't fill the entire screen

### ISSUE THREAD

**Issue by alfredosalzillo** [ionic-team/capacitor#4708] opened 2021-06-09 12:54 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/electron: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios 3.0.0
  @capacitor/android 3.0.0
  @capacitor/core 3.0.0
  @capacitor/cli 3.0.0
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 10 Capacitor plugins for ios:
    @capacitor-community/facebook-login (3.0.0)
    @capacitor/app (1.0.0)
    @capacitor/clipboard (1.0.0)
    @capacitor/device (1.0.0)
    @capacitor/share (1.0.0)
    @codetrix-studio/capacitor-google-auth (3.0.1)
    capacitor-apple-login (0.0.7)
    capacitor-google-analytics (1.0.1)
    cordova-plugin-smartlook (1.7.4)
    onesignal-cordova-plugin (2.11.4)
[success] iOS looking great! 👌

```

### Platform(s)

Android

### Current Behavior

After updating to capacitor 3.0 the screen height is smaller (83% of the screen).

### Expected Behavior
The app height should be full screen.

### Other Technical Details

`npm --version` output: 7.0.15

`node --version` output: v15.4.0

`pod --version` output (iOS issues only):

### Additional Context

![screenshot_20210609-145018](https://user-images.githubusercontent.com/13395386/121358001-8ca36b80-c932-11eb-84f3-4726f34d6472.png)

**Comment by Ionitron** [comment] 2021-06-09 13:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by SheppardX** [comment] 2021-06-11 10:25
i have a same issue ... i dont know what todo ... in before we had capacitor 2.4.7 with NO problems, Code doesnt changed of Angular APP then we upgraded to 3.0.1  this issue happens

the red box is the splashscreen behind the top left webView where the wizard is visual ... 
<img width="507" alt="Bildschirmfoto 2021-06-11 um 12 23 04" src="https://user-images.githubusercontent.com/6494427/121672376-044ad500-cab0-11eb-80a2-568d5540b63c.png">

**Comment by alfredosalzillo** [comment] 2021-06-11 12:56
<img width="895" alt="Screenshot 2021-06-11 at 14 54 53" src="https://user-images.githubusercontent.com/13395386/121689590-0f5c3000-cac5-11eb-9c55-cae65894b70d.png">
I have found that the FrameLayout have paddingBottom setted somewhere

**Comment by SheppardX** [comment] 2021-06-11 13:41
i have just CoordinateLayout and WebView nothing else

Am Fr., 11. Juni 2021 um 14:56 Uhr schrieb Alfredo Salzillo <
***@***.***>:

**Comment by SheppardX** [comment] 2021-06-11 13:41
![Uploading Bildschirmfoto 2021-06-11 um 15.40.00.png…]()

**Comment by alfredosalzillo** [comment] 2021-06-14 10:06
The problem only appear when generating an app bundle

**Comment by SheppardX** [comment] 2021-06-14 10:09
no for me it appears if i try run it on my real device via android studio

**Comment by alfredosalzillo** [comment] 2021-06-14 12:06
@SheppardX when you run on the device he create and run an app bundle (by default) using android studio

**Comment by SheppardX** [comment] 2021-06-14 12:11
okay but what could be the problem ? i created android via npx cap add android initially and it looks like that

**Comment by alfredosalzillo** [comment] 2021-06-23 07:19
The problem happens always when the screen is zoommed

**Comment by alfredosalzillo** [comment] 2021-06-23 07:28
Changing `android:theme="@style/AppTheme.NoActionBarLaunch"`  to `android:theme="@style/AppTheme"` in the android manifest fixed for me.

**Comment by jcesarmobile** [comment] 2021-07-16 12:47
Closing since nobody provided a sample app where it could be reproduced.

If it's theme related it could be fixed by https://github.com/ionic-team/capacitor/pull/4841

**Closed by jcesarmobile** 2021-07-16 12:47 UTC
Labels: needs reproduction, platform: android
