### ISSUE TITLE
bug: I'm getting black iFrame screen on iOS

### ISSUE THREAD

**Issue by MustafaEminn** [ionic-team/capacitor#6041] opened 2022-10-31 10:58 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
I'm getting black iFrame screen in application. It's working on Safari. 

### Expected Behavior
Get correct iFrame screen

### Other Technical Details
[ProcessSuspension] 0x126008720 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=62401, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)" UserInfo={NSLocalizedFailureReason=(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement com.apple.multitasking.systemappassertions)}

`npm --version` output: 8.19.2

`node --version` output: 16.17.1

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment] 2022-10-31 11:01
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by MustafaEminn** [comment] 2022-10-31 11:09
Not related to code. Just an iFrame element

**Comment by jcesarmobile** [comment] 2022-10-31 11:27
I've tested on my sample app and I can use iframes without problems, so closing as can't reproduce.
It's probably some configuration problem on the server serving the iframe or some configuration in the app CSP (if it has one) blocking the iframe connection.
Have in mind that Capacitor apps are served from `capacitor://localhost` and some servers don't allow the connection by default, if the site you are putting into the iframe is yours you'll have to configure it's server, if it's not yours then you won't be able to use it.

**Closed by jcesarmobile** 2022-10-31 11:27 UTC
Labels: platform: ios, needs reproduction
