### ISSUE TITLE
bug: CAPBridgeViewController's WkWebView does not respect safe area insets

### ISSUE THREAD

**Issue by emlynmac** [ionic-team/capacitor#2149] opened 2019-11-07 19:31 UTC
# Bug Report

## Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/android not installed
  @capacitor/cli 1.3.0
  @capacitor/ios 1.3.0
  @capacitor/core 1.3.0

  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
The root web view goes underneath the status bar on iPhone X-ratio phones

## Expected Behavior
Status bar should be un-affected.

## Sample Code or Sample Application Repo
Create a basic project, run on iPhone 11 simulator

## Reproduction Steps
Create a basic project, run on iPhone 11 simulator

## Other Technical Details
The WKWebView is the base view for the app and should respect the safe area layout margins.
To make this happen in the current code, you need to set the default view to a UIView and add the WKWebView as a sub-view with the correct auto-layout constraints:
```
 view = UIView()
    view.backgroundColor = .white
    
    if let wv = webView {
      wv.translatesAutoresizingMaskIntoConstraints = false
      view.addSubview(wv)
      NSLayoutConstraint.activate([
        wv.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
          wv.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor),
          wv.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor),
          wv.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
          ])
    }
```

## Other Information
In future versions, it might be good to have this customizable by allowing overriding of the base view controller object. Currently, the CAPBridgeViewController is not an open class so this is not possible.

**Comment by jcesarmobile** [comment] 2020-01-16 11:14
looks like a duplicate of https://github.com/ionic-team/capacitor/issues/1947

**Closed by jcesarmobile** 2020-01-16 11:14 UTC
