### ISSUE TITLE
feat: Transmit raw bytes over the Capacitor<->Native bridge

### ISSUE THREAD

**Issue by ProofOfKeags** [ionic-team/capacitor#3059] opened 2020-06-04 23:14 UTC
# Feature Request

## Describe the Feature Request
Support raw byte transmission over the capacitor<->native bridge. Currently the only data types supported are JSON types. This means that you cannot pass binary data between the main app and various plugins. Currently the best method for doing this requires an expansion of those bytes into utf8 encoded strings. This is wasteful in terms of compute time and space since it will have to be reconverted back to bytes on the typescript side.

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [ ] Web

## Describe Preferred Solution
Add a type that represents a byte vector to both the typescript and native sides. Ideally this will be doing `Blob` or `ArrayBuffer` on the TypeScript side and then Data/ByteString for Swift/Java respectively. I am presently unaware of the internals of how this data transmission is done right now, but these things can be done with existing data formats such as protobuf or flatbuffers already. I would love to hear opinions on the preferred implementation.

## Describe Alternatives
There are probably numerous alternative implementations. As I stated above I am not super familiar with the internals of how data is passed between the TypeScript and Native execution contexts.

## Additional Context
Implementing this will allow developers to interact with plugins without having to mash the data into the JSON model. I see this as tremendously valuable to the ecosystem as there are many use cases that could benefit from it. To provide just one, it would allow the `Content-Type` `application/octet-stream` in the capacitor-http plugin. Any number of TCP network protocols become possible as well by doing this.

**Comment by dwieeb** [comment] 2020-06-04 23:22
Duplicate of https://github.com/ionic-team/capacitor/issues/984

**Closed by dwieeb** 2020-06-04 23:22 UTC

**Comment by dwieeb** [comment] 2020-06-04 23:25
The current iOS and Android bridge implementation does not allow for anything but strings. To support other data types, it would need to be completely rewritten to use a socket or something. There is no timeline for this, but you can see third-party solutions in the issue I linked to.
