### ISSUE TITLE
bug: Cannot call Kotlin suspend functions as @PluginMethod()

### ISSUE THREAD

**Issue by geoffreyrichey** [ionic-team/capacitor#6550] opened 2023-05-01 23:39 UTC
### Capacitor Version

```
 @capacitor/cli: 4.7.3
 @capacitor/android: 4.7.3
 @capacitor/core: 4.7.3
 @capacitor/ios: 4.7.3
```

### Platform(s)

Android

### Current Behavior

Working on a project that needs to call Kotlin 'suspend' functions from the Google Health Connect SDK. When I try to declare a @PluginMethod() with a suspend function I get the following errror:

```
Serious error executing plugin
java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 1
at java.lang.reflect.Method.invoke(Native Method)
at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:767)
at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
``` 

### Expected Behavior

Should be able to call suspend functions from plugin methods

### Code Reproduction

Run **npm init @capacitor/plugin@latest** to create boilerplate 'echo' plugin

Edit Android code by updating to Kotlin and adding suspend to the echo function:

```
package com.myapp.plugin.mytest

import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin

@CapacitorPlugin(
    name = "MyTestPlugin",
)

class GoogleHealthConnect : Plugin() {

    @PluginMethod()
    suspend fun echo(call: PluginCall) {
        val value = call.getString("value")
        val ret = JSObject()
        ret.put("value", value)
        call.resolve(ret)
    }
}
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2023-05-02 08:07
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-18 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-05-18 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
