### ISSUE TITLE
SplashScreen" plugin is not implemented on android 

### ISSUE THREAD

**Issue by Isaacn123** [ionic-team/capacitor#4845] opened 2021-07-18 12:29 UTC
### Capacitor Version

```
vendor.js:61418 ERROR Error: Uncaught (in promise): Error: "SplashScreen" plugin is not implemented on android
Error: "SplashScreen" plugin is not implemented on android
    at CapacitorException.Wrapper (http://localhost/vendor.js:143599:68)
    at CapacitorException._createSuperInternal (http://localhost/vendor.js:143103:24)
    at new CapacitorException (http://localhost/vendor.js:118297:20)
    at createPluginMethod (http://localhost/vendor.js:118458:15)
    at http://localhost/vendor.js:118471:20
    at ZoneDelegate.invoke (http://localhost/polyfills.js:491:160)
    at Object.onInvoke (http://localhost/vendor.js:88594:25)
    at ZoneDelegate.invoke (http://localhost/polyfills.js:491:48)
    at Zone.run (http://localhost/polyfills.js:217:37)
    at http://localhost/polyfills.js:1637:28
    at CapacitorException.Wrapper (http://localhost/vendor.js:143599:68)
    at CapacitorException._createSuperInternal (http://localhost/vendor.js:143103:24)
    at new CapacitorException (http://localhost/vendor.js:118297:20)
    at createPluginMethod (http://localhost/vendor.js:118458:15)
    at http://localhost/vendor.js:118471:20
    at ZoneDelegate.invoke (http://localhost/polyfills.js:491:160)
    at Object.onInvoke (http://localhost/vendor.js:88594:25)
    at ZoneDelegate.invoke (http://localhost/polyfills.js:491:48)
    at Zone.run (http://localhost/polyfills.js:217:37)
    at http://localhost/polyfills.js:1637:28
    at resolvePromise (http://localhost/polyfills.js:1564:21)
    at http://localhost/polyfills.js:1641:11
    at ZoneDelegate.invokeTask (http://localhost/polyfills.js:524:173)
    at Object.onInvokeTask (http://localhost/vendor.js:88582:25)
    at ZoneDelegate.invokeTask (http://localhost/polyfills.js:524:56)
    at Zone.runTask (http://localhost/polyfills.js:274:39)
    at drainMicroTaskQueue (http://localhost/polyfills.js:740:25)
```

### Platform(s)

`Android Platform `

### Current Behavior

 `am not able to Manually hide Capacitor SplashScreen whithout using the Capacitor config file..
have installed Splash Screen on Capacitor 3.1.1 
using this Command :
npm install @capacitor/splash-screen`

### Expected Behavior

`i want to be able to manually hide splashScreen in my app Components.`

### Code Reproduction
`am unable to reproduce this `

### Other Technical Details

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : 3.1.1
   @capacitor/core    : 3.1.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.16.1 (/usr/local/bin/node)
   npm    : 6.14.12
   OS     : macOS Big Sur

**Comment by Ionitron** [comment] 2021-07-20 15:41
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-05 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-05 00:02 UTC
Labels: needs reply, needs reproduction, platform: android
