### ISSUE TITLE
bug: package name convention problem: "Must be in Java package form with no dashes"

### ISSUE THREAD

**Issue by barocsi** [ionic-team/capacitor#4480] opened 2021-04-21 10:04 UTC
So what about with apps that actually have a name with dash but you'd want to migrate them? Should rewrite each time a cap sync is done?

**Comment by jcesarmobile** [comment] 2021-04-21 11:22
the package name and the app name are different things, so I don't understand your problem, can you provide more information?

**Comment by barocsi** [comment] 2021-04-22 06:52
When you do npx cap sync bundle id gets rewritten using capacitor.config.json appid in the Xcode project.

**Comment by jcesarmobile** [comment] 2021-04-22 07:40
Now it’s even more confusing, capacitor doesn’t rewrite the bundle id and in your title you were talking about Java package

**Comment by jcesarmobile** [comment] 2021-04-29 15:47
Closing since the problem is unclear, please, when reporting issue, provide all the information requested by the template and try to provide a sample app or steps to reproduce the issue.

**Closed by jcesarmobile** 2021-04-29 15:47 UTC

**Comment by ondokuzz** [comment] 2021-08-10 19:29
capacitor.config.json: appId: com.mycompany.a-b-c

when i say:
  cd <project>
  rm -rf ios
  ionic capacitor add ios

it says:
[error] Invalid App ID "com.mycompany.a-b-c". Must be in Java package form with no dashes (ex: com.example.app)

i guess the bundle ID in xcode project (App.xcodeproj:PRODUCT_BINDLE_IDENTIFIER) created by ionic/capacitor is taken from capacitor.config.json (i use ionic 5, capacitor 2.4.7).

apple accepts bundle ids with dashes. but capacitor doesn't seem to let this when creating an ios project (at least in 2.4.7)
