### ISSUE TITLE
Local Notifications in Capacitor v3 gives error while running on android

### ISSUE THREAD

**Issue by Priyank010** [ionic-team/capacitor#4764] opened 2021-06-25 13:10 UTC
Capacitor Version 3

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.2

[error] app/src/main/assets directory is missing in android

### Platform(s)
Android, Quasar, Android studio

### Additional Context
The Code works fine on Desktop browser but gives this error while running on android through android studio :

- Uncaught (in promise) Error: "LocalNotifications" plugin is not implemented on android at createPluginMethod

 and if I open the same link (android one) on Desktop browser than It shows this warning : 

- web.js?feca:14 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by Ionitron** [comment] 2021-06-25 13:16
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-07-11 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-07-11 00:02 UTC
Labels: needs reply, needs reproduction, platform: android
