### ISSUE TITLE
bug: "launchAutoHide" is ignoring SplashScreen.hide() call

### ISSUE THREAD

**Issue by josecarlosrx** [ionic-team/capacitor#6200] opened 2022-12-30 02:37 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1
```

### Platform(s)

Android

### Current Behavior

When "launchAutoHide" is false (in capacitor.config.js), SplashScreen is not hidden after hide() call.

### Expected Behavior

SplashScreen.hide() should work.

### Code Reproduction

Just add this to capacitor.config.json:

```
"plugins": {
    "SplashScreen": {
      "launchAutoHide": false
    }
  },
```

It suddenly works when we specifiy a server, like this:

```
 "server": {
    "url": "http://192.168.1.6:5004",
    "cleartext": true
  },
```

But that's not desirable for production.

### Other Technical Details

`npm --version` output: 8.5.0

`node --version` output: 16.14.2

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2023-01-03 20:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-19 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-19 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
