### ISSUE TITLE
Instance state lost when app launched via icon on the home screen

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1171] opened 2019-01-28 13:08 UTC
This happens on my Samsung Galaxy S8 Plus, **but not** on my Huawei P10.

With regards to pressing on recieved Push Notifications this occurs for both phones.

For both phones this doesn't occur if one opens the app through the "recent applications"-view.

What's the expected behaviour? Seems resonable that the instance state is resumed on all of the mentioned occasions if app is already running.

**Comment by jcesarmobile** [comment] 2019-01-28 15:23
I think this is a duplicate of https://github.com/ionic-team/capacitor/issues/971

I see you already saw it as you added a 👍 to it, so, did you change your activity launchMode to singleTask as recommended there?

**Comment by solojuve1897** [comment] 2019-01-28 16:21
I remember this from some time ago when I encountered a similar behaviour while playing around with deep linking. That was some time now and I had completely forgot about it. Will try it out tonight, thanx for the tip! Will get back with a report.

**Comment by jcesarmobile** [comment] 2019-01-28 18:47
Ok, will close this one and keep #971 to decide if we add singleTask as default or we document it's recommended to use this mode when using push and some other plugins that can launch a new instance

**Closed by jcesarmobile** 2019-01-28 18:47 UTC
