### ISSUE TITLE
bug: Camera.getPhoto with source "PHOTO" returns "No image picked" when choosing between multiple gallery apps

### ISSUE THREAD

**Issue by WIStudent** [ionic-team/capacitor#2171] opened 2019-11-13 11:13 UTC
# Bug Report

## Capacitor Version

```
Installed Dependencies:
  @capacitor/cli 1.3.0
  @capacitor/android 1.3.0
  @capacitor/ios 1.3.0
  @capacitor/core 1.3.0
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Error "No image picked" is returned.

## Expected Behavior
The selected image should be returned

## Sample Code or Sample Application Repo
```typescript
Camera.getPhoto({
  source: CameraSource.Photos
});
```

## Reproduction Steps
1. Have multiple gallery apps installed on your device (in my case "Gallery Go by Google Photos" and "Google Photos"
2. Trigger the `getPhoto` call, the OS should now show a dialog asking which app you want to use
3. Choose an app and select a photo
4. getPhoto resolves with the error "No image picked" 

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v12.13.0

Android version: 10
Device: Goole Pixel 3a

## Other Information
I debugged into the Camera plugin, the error is returned because `data` is null in
```java
public void processPickedImage(PluginCall call, Intent data) {
  if (data == null) {
    call.error("No image picked");
    return;
  }
  ...
}
```
So the `data` passed to the `handleOnActivityResult` method, which then calls `processPickedImage,` is null when Android decides to show the app selection dialog. I am not sure if it is even an issue with capacitor or if android itself is the problem here.

**Comment by vmonjetmapp** [comment] 2019-12-30 00:19
Same problem

**Comment by vmonjetmapp** [comment] 2019-12-30 00:21
> Same problem

This plugin does not work

**Comment by jcesarmobile** [comment] 2020-01-16 19:19
It's not related to the prompt, but to the app used to pick the image. Which one did you use?

Also a sample app would be helpful to make sure you are not doing something wrong, I've just tested the "Gallery go by Google Photos" app and works fine on my device.

**Comment by WIStudent** [comment] 2020-01-17 09:23
I just checked again, in my case it didn't matter which app I choose. I tried selecting Google Photos (version 4.34.0.289665577) and Gallery Go (version 1.0.8.287911753 release) using Capacitor 1.4. The app choosing dialog looks on my device (Pixel 3a with Android 10 Build QQ1A.200105.002) like this:
![app chooser](https://user-images.githubusercontent.com/2707930/72598558-4ea64180-3910-11ea-88fb-e5f40e090f7f.png)
(sorry, it's in German)

If Android doesn't show this dialog because one of the apps was set as default, both Google Photos and Gallery Go are working fine.

I added a breakpoint in Android Studio and saw that the data that is passed back to BridgeActivity.java is null when the dialog was shown.
```java
  @Override
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (this.bridge == null) {
      return;
    }
    this.bridge.onActivityResult(requestCode, resultCode, data);
  }
```
This seems to me the earliest earliest entry point where the result is passed back to Capacitor, so my best guess is that it is a fault within android and not Capacitor.

I don't have an app that I can share but the getPhoto method is called with
```javascript
{
  "source": "PHOTOS",
  "quality": 50,
  "saveToGallery": false,
  "correctOrientation": true,
  "resultType": "uri"
}
```

**Comment by WIStudent** [comment] 2020-01-21 11:19
@mrSingh007 I think your issue is a different one. I never used `allowEditing` (its default value is false). Also in my case data is already null on the first `handleOnActivityResult` call.

**Comment by jcesarmobile** [comment] 2020-01-21 14:27
Yeah, that's a different issue and it's already reported https://github.com/ionic-team/capacitor/issues/2020

As for this bug, I've tested the provided code on 5 different devices and even a Pixel 3a emulator and works fine, since there is no sample app to reproduce I'm closing, sorry.

**Closed by jcesarmobile** 2020-01-21 14:27 UTC
Labels: needs-reply

**Comment by sean118** [comment] 2020-03-21 15:44
The issue here seems to be with the chooser, that lets you select the photos / gallery app to be used, when you have not already set a default app.

Once a default app has been set, this issue disappears for me.

Strangely, when you change the openPhotos() method in Capacitor’s Camera.java to explicitly always use a chooser intent as below, the issue is also not present.

So this quick fix might help some of you:

```
  public void openPhotos(final PluginCall call) {
    if (checkPhotosPermissions(call)) {
      Intent intent = new Intent(Intent.ACTION_PICK);
      intent.setType("image/*");
      // startActivityForResult(call, intent, REQUEST_IMAGE_PICK);

      Intent chooser = Intent.createChooser(intent, "Select Image");
      startActivityForResult(call, chooser, REQUEST_IMAGE_PICK);
    }
  }
```

I’m on a Galaxy A7 (2018) running Android 9.

I’d be happy to hear, if anyone by now has found a better solution. Thanks

**Comment by arnotixe** [comment] 2020-05-06 20:40
metoo, running first test after adding Camera, using the exact method in https://capacitor.ionicframework.com/docs/apis/camera/ (on Android)

This is my reliably reproducible error condition, attached logcat shows bad things happen when trying to edit something we don't have permission to edit (but I don't know who's to blame):

✓ First image capture works out fine (choosing Camera) thereafter choosing edit method, and "Save a copy"
✓ Next image captures work too
× Then choosing "Gallery" to source a photo pulls up the gallery, I can choose a photo and… image is url 
× Subsequent attempt to capture with Camera again pulls open the camera, but after capture it "skips edit" and goes straight back to app, does not return a picked image though
✓ SECOND subsequent attempt works fine again: Capture - Edit - Save and returns the picked: edited picture to app

[logcat-capacitor-2171.txt](https://github.com/ionic-team/capacitor/files/4589386/logcat-capacitor-2171.txt)

My workaround will probably be to implement a checkbox or something that takes away editing if users have trouble. Might have something to do with chinese-touched OS(?)

**Comment by chuyporras18** [comment] 2021-03-30 16:28
It works for me with any photo application, except the native one from xiaomi.

**Comment by florianmonfort** [comment] 2021-07-30 08:15
Hi, we have the same issue from Xiaomi editor, it doesn't work.

**Comment by Sanch9s** [comment] 2021-11-22 19:27
> It works for me with any photo application, except the native one from xiaomi.

I'm sorry, do you have solution for Xiaomi devices? For me it's failing on Redmi Note 9 device...

**Comment by riderx** [comment] 2021-12-28 13:47
Same issue in Redmi Note 9 for `pickImages` feature. i have try to force request permission and still the issue
