### ISSUE TITLE
bug: (critical) Blank screen startup (only on device); error of Capacitor libraries

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/capacitor#4190] opened 2021-02-11 16:11 UTC
### Capacitor Version
2.4.6 (for all packages)

This happens when opening the app in a device, and debugging it with Chrome Remote Devices. Nothing can be seen, just a blank screen (while the "ionic serve" app in desktop works perfectly normal):

```
onscript loading complete
capacitor-runtime.js:358 TypeError: fn.bind is not a function
    at newTrustedFunctionForJIT (vendor-es2015.js:10992)
    at JitEvaluator.evaluateCode (vendor-es2015.js:11056)
    at JitEvaluator.evaluateStatements (vendor-es2015.js:11030)
    at CompilerFacadeImpl.jitExpression (vendor-es2015.js:24424)
    at CompilerFacadeImpl.compileNgModule (vendor-es2015.js:24354)
    at Function.get (vendor-es2015.js:115380)
    at getNgModuleDef (vendor-es2015.js:89506)
    at assertNgModuleType (vendor-es2015.js:89685)
    at compileNgModuleFactory__POST_R3__ (vendor-es2015.js:117414)
    at PlatformRef.bootstrapModule (vendor-es2015.js:117661)
capacitor.handleError @ capacitor-runtime.js:358
vendor-es2015.js:10992 Uncaught TypeError: fn.bind is not a function
    at newTrustedFunctionForJIT (vendor-es2015.js:10992)
    at JitEvaluator.evaluateCode (vendor-es2015.js:11056)
    at JitEvaluator.evaluateStatements (vendor-es2015.js:11030)
    at CompilerFacadeImpl.jitExpression (vendor-es2015.js:24424)
    at CompilerFacadeImpl.compileNgModule (vendor-es2015.js:24354)
    at Function.get (vendor-es2015.js:115380)
    at getNgModuleDef (vendor-es2015.js:89506)
    at assertNgModuleType (vendor-es2015.js:89685)
    at compileNgModuleFactory__POST_R3__ (vendor-es2015.js:117414)
    at PlatformRef.bootstrapModule (vendor-es2015.js:117661)
vendor-es2015.js:66530 Ionic Native: deviceready event fired after 57 ms
DevTools failed to load SourceMap: Could not load content for http://localhost/runtime-es2015.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for http://localhost/polyfills-es2015.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for http://localhost/main-es2015.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for http://localhost/vendor-es2015.js.map: Connection error: net::ERR_CONNECTION_REFUSED
```

### Platform(s)
Only tested in Android so far. Doesn't happen in the normal web app when developing with "ionic serve".

### Current Behavior
The app works perfectly as intended when served as a web app, as aforementioned. But it won't start or do anything in an Android device: it just throws that stacktrace that I mentioned above.

### Expected Behavior
App should start as normal in the device.

### Other Technical Details

`npm --version` output: 6.14.11

`node --version` output: 15.7.0

This is my dependency list, do you see anything that could be causing this error?

```
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@capacitor/android": "^2.4.6",
    "@capacitor/core": "^2.4.6",
    "@capacitor/ios": "^2.4.6",
    "@ionic-native/camera": "^5.28.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/crop": "^5.28.0",
    "@ionic-native/file": "^5.28.0",
    "@ionic-native/geolocation": "^5.26.0",
    "@ionic-native/image-picker": "^5.28.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.5.4",
    "@types/googlemaps": "^3.39.7",
    "@types/parse": "^2.12.1",
    "angularx-social-login": "^3.2.2",
    "cordova-android": "^8.1.0",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-telerik-imagepicker": "^2.3.5",
    "jetifier": "^1.6.6",
    "moment": "^2.26.0",
    "parse": "^2.13.0",
    "rxjs": "~6.5.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.4",
    "@angular/cli": "~11.1.4",
    "@angular/compiler": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@angular/language-service": "~11.2.0",
    "@capacitor/cli": "^2.4.6",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  },
```

**Comment by Ionitron** [comment] 2021-02-11 16:26
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Zerokk** [comment] 2021-02-11 16:29
The issue doesn't seem to be related to the code itself, but rather to some Capacitor process that is messing up at app's startup. Check the error code and the description of the error, please.

**Comment by jcesarmobile** [comment] 2021-02-11 17:19
capacitor has a `handleError` function that gets called when a javascript error happens, so it's probably an error in your code. That's why I'm asking for a sample app.

The error points to capacitor-runtime.js because that's the the `handleError` is, but the error is not there.

**Comment by Zerokk** [comment] 2021-02-11 17:25
Hm, interesting. I'll check it out later or tomorrow and post here the results. At least, this gives me a good hint... thank you!

**Comment by ale-on-github** [comment] 2021-02-13 16:24
Hi, I'm facing the same issue with a brand new Ionic project.
To reproduce the problem, just create a new 'blank' project, build and run it on Android Studio with a device simulator:

ionic start (Framework: Angular, Project name: myApp, template: blank)
cd myApp
ionic build
ionic cap add android
ionic cap run android

then in Android Studio press play button and see the described wrong behaviour.
In the Run tab you can see the error:

E/Capacitor/Console: File: capacitor-runtime.js - Line 362 - Msg: TypeError: fn.bind is not a function
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught TypeError: fn.bind is not a function","url":"http://localhost/vendor.js","line":7726,"col":15,"errorObject":"{}"}}
E/Capacitor/Console: File: http://localhost/vendor.js - Line 7726 - Msg: Uncaught TypeError: fn.bind is not a function

Additional info:
OS: macOs Catalina 10.15.5
Node: v14.15.5
Device: Pixel 3 api 30
"dependencies": {
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@capacitor/android": "^2.4.6",
    "@capacitor/core": "^2.4.6",
    "@ionic/angular": "^5.5.4",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.4",
    "@angular/cli": "~11.1.4",
    "@angular/compiler": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@angular/language-service": "~11.2.0",
    "@capacitor/cli": "2.4.6",
    "@ionic/angular-toolkit": "^3.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  },

Everything works fine in web app with 'ionic serve'.
I've seen the same problem with the other ionic templates as well. Only the 'conference' template (built on top of Angular 8) does not reports this issue.


I hope this can be useful to reproduce and analyse the trouble.

Many Thanks!

**Comment by jcesarmobile** [comment] 2021-02-15 16:10
This is a an angular incompatibility with chrome 83, should be fixed on next angular release.

https://github.com/angular/angular/issues/40507

**Closed by jcesarmobile** 2021-02-15 16:10 UTC
Labels: needs reproduction, platform: android, platform: web

**Comment by Zerokk** [comment] 2021-02-15 16:23
Does this affect to Android's default WebView too? Because in my case, I can use my app with "ionic serve" both in Firefox and Chrome (v 88.0).

In case it's an Angular problem, let's hope they can fix it soon! Thanks for the info.

**Comment by jcesarmobile** [comment] 2021-02-15 16:31
Yeah, the WebView uses Chromium internally, so if the WebView is using Chromium 83 you'll face the issue.

The WebView can be updated from Google Play, on Android 5, 6 and 11 you need to update the "Android System WebView" app, on Android 7, 8, 9 and 10 you have to update Chrome, the versions should match.

Android 30 emulator uses Chrome 83, if you are using an image with google services you can update the WebView from Play Store app. If not using a version with google services, then you can't update and the app won't work.

**Comment by Zerokk** [comment] 2021-02-15 16:52
I'm not able to update either Chrome or the Android Web View; I guess we are still waiting for an update from the Angular team, right?

**Comment by guadalavila** [comment] 2021-02-16 01:41
I had the same problem, update chrome and Android System WebView and it was solved!

**Comment by guadalavila** [comment] 2021-02-16 01:44
I had the same problem in android 10 and it was solved updating chrome and Android System WebView.

**Comment by Zerokk** [comment] 2021-02-16 15:20
I have the latest versions of Android Webview and Chrome installed (Android 10, Xiaomi POCOPHONE F2), and I still can't see anything when opening my app.

I guess cases like mine will have to wait until Angular patches this, right...?

**Comment by jcesarmobile** [comment] 2021-02-16 15:44
If the error is the `fn.bind is not a function`, that should only happen on chromium 83. But maybe you are facing a different error now, any javascript error could cause the white screen.

Also, make sure the WebView is really up to date by running something like `alert(navigator.userAgent)`, that should show the whole user agent and that contains the chromium version.

But yeah, if the problem is the `fn.bind is not a function`, you should wait for an angular release, they already fixed the problem, but as of yesterday, was not released yet.

**Comment by mhartington** [comment] 2021-02-16 15:58
Angular expects users to provide their own polyfils for APIs then need. To polyfill `.bind`,  install this

https://github.com/leahciMic/polyfill-function-prototype-bind


```
npm install --save polyfill-function-prototype-bind
```

**Comment by jcesarmobile** [comment] 2021-02-16 17:53
I don't think this is really related to bind not being available but to a bug on chrome 83 (see linked issue). I can run the app on another simulator with chrome 69, bind has been available on Android since Android 4, so the polyfill shouldn't be needed at this point.

**Comment by MELAS007** [comment] 2021-04-12 13:29
Anyone solved this issue?

Please let me know how to solve ?

**Comment by dsalazarRedelcom** [comment] 2022-02-16 07:55
I know this issue is marked as closed, but I'm currently having the exact same problem with ionic 6.18.1. When I create a _blank_ project, package.json and package-lock.json indicate that it uses angular (core, router, common, etc) ~13.0.0. Same e

When I use the _my-first-app_ template instead, it works perfectly inside the device. The only difference regarding angular I found was that said template used angular 12.0.1.
