### ISSUE TITLE
Add Video Capability to Capacitor Camera Plugin

### ISSUE THREAD

**Issue by 5hee75** [ionic-team/capacitor#4900] opened 2021-08-06 17:29 UTC
### Description
It would be highly desirable to have native video capture capability using the Capacitor Camera plugin.  There is currently only the option to take still images, so additional plugins or custom solutions are required.

### Platform(s)
Android
iOS
Web

### Preferred Solution
New `getVideo()` method in the Camera plugin, alongside existing methods.

Example:

```javascript
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';

const videoData = await Camera.getVideo({
    resultType: CameraResultType.Uri,
    source:  CameraSource.Camera or CameraSource.Photos(Videos/Gallery?),
    ...options
});
```

For memory purposes, this may need to be restricted to only use the URI option as a result type.

### Alternatives
Some plugins exist to provide video capture functionality, like `cordova-plugin-media-capture`, but this requires additional dependencies outside of Capacitor and uses a different API.

The `capacitor-camera-preview` plugin also exists for Android video capture, but this is not compatible with iOS.

### Additional Context
I assume there is a good reason the camera plugin hasn't been given video capability up to this point, so maybe I'm barking up the wrong tree.  Still, I think a one-stop-shop solution for both images and video with Capacitor would go a long way to making the framework feel more feature-complete.

**Comment by jcesarmobile** [comment] 2021-08-06 18:48
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/229

**Closed by jcesarmobile** 2021-08-06 18:48 UTC
Labels: platform: android, platform: ios, platform: web

**Comment by josuelmm** [comment] 2022-05-18 17:43
Any update?
