### ISSUE TITLE
feat: set App Version easily (config or package.json) 

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#4161] opened 2021-02-04 21:06 UTC
### Description
Would be really great to define app Version out of the `./platforms` folders before build, and not editing that manually in each ios / android file.
Taking the app version in package.json would be a must.

### Platform(s)
For all platorms

### Preferred Solution
Be able to put it in Capacitor Config or package.json, near `appName` for example

**Comment by jcesarmobile** [comment] 2021-02-04 22:09
Duplicate of https://github.com/ionic-team/capacitor/issues/3943

**Closed by jcesarmobile** 2021-02-04 22:09 UTC
