### ISSUE TITLE
hide scrollview for android

### ISSUE THREAD

**Issue by matamune94** [ionic-team/capacitor#2456] opened 2020-02-20 13:26 UTC
I search google much time but I could not find solution for capacitor. have idea ? like flutter,  default is hide all scrollbar,

**Comment by jcesarmobile** [comment] 2020-02-20 13:37
can you provide a sample app with the scrollbar you want to hide?

**Comment by matamune94** [comment] 2020-02-20 13:45
I use quasar to build by capacitor, just i want hide it.

**Comment by jcesarmobile** [comment] 2020-02-20 14:57
can you provide a sample quasar app where the scrollbar is visible?

**Comment by jcesarmobile** [comment] 2020-03-02 18:11
closing since it's unclear what the problem is and the reporter didn't provide a sample app

**Closed by jcesarmobile** 2020-03-02 18:11 UTC
