### ISSUE TITLE
bug: CapacitorHttp - Request never returns a result on native iOS

### ISSUE THREAD

**Issue by KevinKelchen** [ionic-team/capacitor#6135] opened 2022-12-01 17:54 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Native iOS

### Current Behavior

Hello there! 👋

Using the Angular `HttpClient`, which uses `CapacitorHttp` at a lower level, making a request to a particular URL on native iOS never returns a result. The request to the URL is known to fail, but expected `CapacitorHttp` to return an error result instead of hanging indefinitely.

Native iOS _without_ `CapacitorHttp`, Native Android _with_ `CapacitorHttp`, Native Android _without_ `CapacitorHttp`, and Web work fine.

Reproduced the issue using an iPhone SE (3rd generation) simulator.

### Expected Behavior

Use of `CapacitorHttp` on native iOS should return an error result instead of hanging indefinitely.

Also, if we want `CapacitorHttp` to work the same as XHR/fetch, this would be a difference.

### Code Reproduction

https://github.com/KevinKelchen/capacitor-http-request-no-result-issue#steps-to-reproduce

### Other Technical Details

`npm --version` output: 8.15.0

`node --version` output: v16.17.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

Thanks so much! 😀

Kevin

**Comment by jcesarmobile** [comment] 2022-12-05 18:21
Thanks for the issue, but this is a duplicate of https://github.com/ionic-team/capacitor/issues/6024

**Closed by jcesarmobile** 2022-12-05 18:21 UTC
Labels: platform: ios

**Comment by KevinKelchen** [comment] 2022-12-05 18:44
Oh good. Thank you for looking into it! 😀
