### ISSUE TITLE
feat(iOS): Support initWithSuiteName in Storage plugin

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/capacitor#3223] opened 2020-07-08 09:08 UTC
### Description

In iOS `UserDefaults` one can init it with a `suiteName`. This is needed e.g. when different `Extensions` want to share data between them. Capacitor should support this.

Example: https://github.com/TheCocoaProject/cordova-plugin-nativestorage#ios-specific-features

### Platform(s)

- iOS

### Preferred Solution

Having an `init` function where the optional property `suiteName` can be specified.

**Comment by jcesarmobile** [comment] 2020-07-10 18:05
closing as duplicate of https://github.com/ionic-team/capacitor/issues/2253

**Closed by jcesarmobile** 2020-07-10 18:05 UTC
Labels: platform: ios

**Comment by BorntraegerMarc** [comment] 2020-07-11 09:34
I completely forgot to search through existing issues. Sorry about this! Thanks!
