### ISSUE TITLE
bug: Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")

### ISSUE THREAD

**Issue by BenRacicot** [ionic-team/capacitor#6245] opened 2023-01-23 20:08 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/ios: 4.6.2
  @capacitor/android: 4.6.2

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Current Behavior
The iOS app build as expected but errors in Xcode seem to be new to V14.2.

```
2023-01-23 14:58:24.586868-0500 App[16359:4285321] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-01-23 14:58:24.586920-0500 App[16359:4285321] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
⚡️  Loading app at capacitor://localhost...
⚡️  WebView loaded
2023-01-23 14:58:25.035612-0500 App[16359:4285321] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
...
```

### Expected Behavior
I'm unfamiliar with iOS native development but am expecting the `info.plist` file to be created by Capacitor without any warnings. Or perhaps the team can inform us what we're doing wrong.

Seems like a popular issue: [https://stackoverflow.com/questions/74805019/info-plist-contained-no-uiscene-configuration-dictionary-looking-for-configurat](https://stackoverflow.com/questions/74805019/info-plist-contained-no-uiscene-configuration-dictionary-looking-for-configurat)

### Other Technical Details

`npm --version` output: `8.19.2`

`node --version` output: `v18.12.1` 

`pod --version` output (iOS issues only): `1.11.3`

**Comment by marshall86** [comment] 2023-01-24 08:19
experiencing the same issue..

**Comment by marshall86** [comment] 2023-01-24 08:36
Try to add the following code to your info.plist file

`<key>UIApplicationSceneManifest</key>
    <dict>
        <key>UISceneConfigurations</key>
        <dict/>
    </dict>`

**Comment by Ionitron** [comment] 2023-01-24 09:31
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by BenRacicot** [comment] 2023-01-24 18:22
This is the solution (same link from my issue) [https://stackoverflow.com/a/75130485/1440240](https://stackoverflow.com/a/75130485/1440240)

It is related to plist config.

**Comment by jcesarmobile** [comment] 2023-01-24 18:27
Closing since you figured out for your project and I can't reproduce

**Closed by jcesarmobile** 2023-01-24 18:27 UTC
Labels: needs reproduction
