### ISSUE TITLE
bug: Capacitor Browser stops working on iOS with presentationStyle: fullScreen and SceneDelegate architecture

### ISSUE THREAD

**Issue by carelliguillaume** [ionic-team/capacitor#5969] opened 2022-10-04 12:58 UTC
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/core: 4.3.0

[success] iOS looking great! 👌

### Platform(s)

iOS (tested on versions: 13, 14, 15, 16)

### Current Behavior

When I add the SceneDelegate iOS architecture (needed by Apple CarPlay), Capacitor Browser stops working with presentationStyle: fullScreen. The SFSafariViewController is not showing up in this mode and I get the following error in XCode console : App[1497:15815] Unbalanced calls to begin/end appearance transitions for <Capacitor.TmpViewController: 0x7faa2852fb70>.
When I switch to presentationStyle: popover it’s working as expected.

### Expected Behavior

Capacitor Browser (SFSafariViewController) should work with presentationStyle: fullScreen and SceneDelegate iOS architecture.

### Code Reproduction

https://github.com/carelliguillaume/ionic-capacitor-scenedelegate

This project is an Ionic app (latest stable Ionic and Angular) with 2 tabs.
The first tab is intended to show the problem we have with Capacitor Browser (SFSafariViewController) and SceneDelegate with presentationStyle : fullScreen on iOS. 
When you click on the button « Open Capacitor Browser Fullscreen », Browser will not open and instead XCode will output an error : App[1497:15815] Unbalanced calls to begin/end appearance transitions for <Capacitor.TmpViewController: 0x7faa2852fb70>.
When you click on the button « Capacitor Browser Popover »,  Browser will open as expected.

The second tab is not intended to show a problem but just to ask if SceneDelegate events are implemented in the right way in my sample.
When you add a SceneDelegate, the 2 AppDelegate following events will not be called :
- application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:])
- application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void)

Instead SceneDelegate events replace AppDelegate events with these functions : 
- scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)
- scene(_ scene: UIScene, continue userActivity: NSUserActivity)

I want to know if my Capacitor ApplicationDelegateProxy calls in these functions are correct. ApplicationDelegateProxy is by default called in AppDelegate functions, but when you have a SceneDelegate, it will not be called.

In this tab you just have a « Open Capacitor AppLauncher » button. When you click on it will call an URL Type Deeplink that will trigger the «scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) » SceneDelegate event. 

### Other Technical Details

`npm --version` output: 6.14.15

`node --version` output: v14.17.6

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

iOS Devices used to reproduce the behavior

iPhone X
iPhone 13 Pro

Tested on many Simulators

**Comment by jcesarmobile** [comment] 2022-10-04 13:00
duplicate of https://github.com/ionic-team/capacitor/issues/5951

**Closed by jcesarmobile** 2022-10-04 13:00 UTC
Labels: platform: ios
