### ISSUE TITLE
bug: ionic capacitor keyboard overlaps input field on iOS

### ISSUE THREAD

**Issue by mastercodingbear** [ionic-team/capacitor#4858] opened 2021-07-21 13:29 UTC
### Capacitor Version

```
latest version
```

### Platform(s)

```
iOS 14.4
```
### Current Behavior

I installed `@capacitor/keyboard` and added options in `capacitor.config.json` as an example.
```
"plugins": {
  "Keyboard": {
    "resize": "body",
    "style": "dark"
  }
}
```
But the keyboard is overlapping the input field on iOS 14.4(real device). It works on iOS emulator
![IMG_0499](https://user-images.githubusercontent.com/84164835/126496660-a38eeb3c-9b1c-49e7-9f49-732d48ec0ffe.png)

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2021-07-21 18:32
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-06 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-06 00:03 UTC
Labels: needs reply, needs reproduction
