### ISSUE TITLE
bug: writing large file throws java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by yelhouti** [ionic-team/capacitor#5523] opened 2022-03-23 04:18 UTC
### Capacitor Version

```
3.3.1
```

### Platform(s)
Android

### Current Behavior
When calling a plugin with with a big file as data, the java code throws an OutOfMemoryError.
The Issue seems to come from: https://github.com/ionic-team/capacitor/blob/33e9b342790ddedfb654c589ffde18b101d4cd98/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L587 
Where the toString is called even when logging is disabled.

### Expected Behavior
The call should not fail.

### Code Reproduction
```
await Filesystem.writeFile({path: basePath + file.id + extension, data: file.file, directory: Directory.Data});
```
With a big file (few hundred megabytes)

### Additional Context
There are few ways to fix this:
1. have a way to disabled logging for data field by adding a param to PluginCall
2. overload Logger.verbose... to accept a lambda that only returns string when `shouldLog()`. (the problem will still happen when logging is enabled in special cases)

I'm willing to implement either or both.

**Comment by Ionitron** [comment] 2022-03-23 09:15
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-04-08 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-08 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
