### ISSUE TITLE
bug: Notification is undefined (LocalNotifications API)

### ISSUE THREAD

**Issue by laaksomavrick** [ionic-team/capacitor#2333] opened 2020-01-14 20:17 UTC
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.4.0

  @capacitor/ios 1.4.0

[success] Android looking great! 👌
  Found 22 Capacitor plugins for ios:
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-app-version (0.1.9)
    cordova-plugin-badge (0.8.8)
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-document-viewer (0.9.13)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-opener2 (2.2.1)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-fileopener (1.0.5)
    cordova-plugin-inappbrowser (3.1.0)
    cordova-plugin-ionic (5.4.5)
    cordova-plugin-ionic-keyboard (2.1.3)
    cordova-plugin-ionic-webview (4.0.1)
    cordova-plugin-local-notification (0.9.0-beta.2)
    cordova-plugin-screen-orientation (3.0.2)
    cordova-plugin-splashscreen (5.0.3)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.3)
    es6-promise-plugin (4.2.2)
    uk.co.workingedge.phonegap.plugin.launchnavigator (5.0.4)
[success] iOS looking great! 👌
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

I'm attempting to use the `LocalNotification` capacitor plugin for local notification functionality. It appears as if the library uses the `Notification` web API internally, which isn't supported by mobile safari. I see the following error from my xcode logs, which also produces an error on our in-flight error logging. This error is isolated to iOS only. The error is elicited via calling `Plugin.LocalNotifications.requestPermissions()` after the device is ready.

```
 [error] - Error: Uncaught (in promise): ReferenceError: Can't find variable: Notification
capacitor://localhost/main.191e07acbb760d821c05.js:1:509052
capacitor://localhost/main.191e07acbb760d821c05.js:1:508982
capacitor://localhost/main.191e07acbb760d821c05.js:1:509194
forEach@[native code]
capacitor://localhost/main.191e07acbb760d821c05.js:1:509156
capacitor://localhost/main.191e07acbb760d821c05.js:1:765494
capacitor://localhost/main.191e07acbb760d821c05.js:1:604306
a@capacitor://localhost/main.191e07acbb760d821c05.js:1:603182
onInvoke@capacitor://localhost/main.191e07acbb760d821c05.js:1:92917
capacitor://localhost/polyfills.765b4fe7021029ff9806.js:1:4577
capacitor://localhost/polyfills.765b4fe7021029ff9806.js:1:16038
onInvokeTask@capacitor://localhost/main.191e07acbb760d821c05.js:1:92833
capacitor://localhost/polyfills.765b4fe7021029ff9806.js:1:5244
d@capacitor://localhost/polyfills.765b4fe7021029ff9806.js:1:12326
promiseReactionJob@[native code]
```

The code in question (minified) is the following:

```
LocalNotificationsPluginWeb.prototype.requestPermissions = function () {
        return new Promise(function (resolve, reject) {
            Notification.requestPermission(function (result) {
                if (result === 'denied' || result === 'default') {
                    reject(result);
                    return;
                }
                resolve({
                    results: [result]
                });
            });
        });
    };
```

## Expected Behavior

Calling `requestPermissions` would prompt the user to allow permissions for local notifications.

## Reproduction Steps

Create an ionic app. Import the `LocalNotification` plugin. Call `requestPermissions`. From iOS, observe an error.

**Comment by jcesarmobile** [comment] 2020-01-15 09:18
Duplicate of https://github.com/ionic-team/capacitor/issues/2236

**Closed by jcesarmobile** 2020-01-15 09:18 UTC

**Comment by jcesarmobile** [comment] 2020-01-15 14:33
Didn't notice you are running the app from Xcode, in that case you are using the plugin in a wrong way that uses the web version instead of the native version.
