### ISSUE TITLE
bug: File assets that are downloaded making use of HTTP Range requests fail to download (sometimes)

### ISSUE THREAD

**Issue by llorenspujol** [ionic-team/capacitor#2978] opened 2020-05-25 08:55 UTC
# Bug Report
File assets that are downloaded making use of [HTTP Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) fail to download (sometimes).

## Capacitor Version

`npx cap doctor` output:

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/electron not installed

  @capacitor/cli 2.1.0

  @capacitor/android 2.1.0

  @capacitor/core 2.1.0

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
File assets that are downloaded making use of [HTTP Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) fail to download (sometimes).

In my case this assets are sound assets in .wav format. The issue is that this audios, are sometimes just partially loaded, or even not loaded at all... This bug is only reproducible when running the app with capacitor.

Here are some captures of the errors:

First request:
![image](https://user-images.githubusercontent.com/18361241/82796155-602ac780-9e75-11ea-90e4-fd8709d84076.png)

Second request (fails:
![image](https://user-images.githubusercontent.com/18361241/82796101-45585300-9e75-11ea-9b58-182e65624e4b.png)

## Expected Behavior

I expect that files that are downloaded using HTTP Range Request are fully and correctly downloded.

## Reproduction Steps
Just put some .wav files on the assets folder, and try to reproduce that audio in a capacitor android app. You will see that the downloading sometimes fails.

## Last words
I can't dig any more on the issue for now since I am a new capacitor user:), but if necessary and with some hints or guidance I could dig more into it and help solve this issue.
Thanks!

**Comment by llorenspujol** [comment] 2020-05-25 10:24
This issue could be related: https://github.com/ionic-team/capacitor/issues/1343

**Comment by albertgasset** [comment] 2021-07-23 16:11
I can reproduce this bug too when playing several audio files concurrently. In the Chrome inspector I can see that response headers are mixed up among requests, so one request gets the response range values of another request.

Looking at the code of WebViewLocalServer I suspect of the PathHandler instances: they contain the response headers and are shared among requests, leading to a data race.

**Comment by Ionitron** [comment] 2022-09-26 13:30
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-10-12 00:11
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-12 00:11 UTC
Labels: needs reply, needs reproduction
