### ISSUE TITLE
bug: npx native-run android --list is not working

### ISSUE THREAD

**Issue by Gabriel-des** [ionic-team/capacitor#4673] opened 2021-06-03 14:08 UTC
### Capacitor Version
```
Latest Dependencies:       

  @capacitor/cli: 3.0.0    
  @capacitor/core: 3.0.0   
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0    

Installed Dependencies:    

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0        
  @capacitor/core: 3.0.0       
  @capacitor/android: 3.0.0 
```

### Platform(s)
Android

### Current Behavior
I'm trying to use the capacitor's livereload function in an Android emulator, but to no avail. I tried to get a list of devices on my computer, but none show up. My emulator comes up with `adb devices`, but when I try to use `npx native-run android --list` the console gives me an error and a link:

> `ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.`

The link takes me to the [Ionic Native Wiki](https://github.com/ionic-team/native-run/wiki/Android-Errors), but the error is not even listed on the page.

When I try to use `ionic cap run android` the console asks me to choose the device, but none appears. 

### Expected Behavior
Build an app in emulator.

### Code Reproduction
`npx native-run android --list`

`npm --version` output: 6.14.13

`node --version` output: v14.17.0

**Comment by jcesarmobile** [comment] 2021-06-03 18:18
closing as duplicate of https://github.com/ionic-team/native-run/issues/183

**Closed by jcesarmobile** 2021-06-03 18:18 UTC
Labels: platform: android

**Comment by leonardofmed** [comment] 2021-06-07 12:06
I'm having the same problem. I can see my emulator with `adb devices`, but can't with `ionic capacitor run android  --list` or `npx native-run android --list`.

**Comment by joao91carlosGit** [comment] 2021-06-07 12:56
I'm currently having the same problem when using capacitor run in my lattest personal project: `ionic capacitor run android --list`
