### ISSUE TITLE
bug: The Haptics API works only on Android

### ISSUE THREAD

**Issue by Fansy-lab** [ionic-team/capacitor#4974] opened 2021-08-27 22:50 UTC
### Capacitor Version
Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

[success] iOS looking great! 👌

### Platform(s)
IOS

### Current Behavior
(IONIC+VueJS)
I have simple button that invokes one of these methods listed  [Here](https://capacitorjs.com/docs/v2/apis/haptics) and it all works fine ONLY on my Android device. When tested on IOS, no errors or warnings are thrown while debugging with XCODE.
No vibration/haptic feedback at all.

### Expected Behavior
Should vibrate

`npm --version` output:
6.14.11
`node --version` output:
v14.16.0
`pod --version` output (iOS issues only):
1.10.2

**Comment by Ionitron** [comment] 2021-08-30 08:24
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by vojto** [comment] 2021-09-08 06:55
@Fansy-lab did you run `cap sync`?

**Comment by Ionitron** [comment] 2021-09-24 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-09-24 00:03 UTC
Labels: platform: ios, needs reply, needs reproduction
