### ISSUE TITLE
bug: Visibility, lights and vibration props not working

### ISSUE THREAD

**Issue by azzamasghar1** [ionic-team/capacitor#5061] opened 2021-09-19 01:12 UTC
### Capacitor Version
```
@capacitor/ios not installed
  @capacitor/cli 2.5.0
  @capacitor/core 2.5.0
  @capacitor/android 2.5.0
  @capacitor/electron not installed
```

### Platform(s)
Android

### Current Behavior
Create a Notification Channel using the below code:
```
const notificationChannel: NotificationChannel = {
    id: "main",
    name: "Main Notifications",
    description: "Main Notifications Channel",
    importance: 5,
    visibility: 1,
    lights: true,
    vibration: true,
};
await LocalNotifications.createChannel(notificationChannel);

const channelList = await LocalNotifications.listChannels();
console.log(channelList);
````

In the logs we can see that although value of `importance` has been override but value of either one of `visibility`, `lights` and `vibration` are not and contains their default values. And of course due to  `visibility` notification is not shown on Lock Screen.

![image](https://user-images.githubusercontent.com/55490507/133912337-a2ed28d9-1938-4900-9ccf-86203d35c523.png)

### Expected Behavior
Value of  `visibility` should be changed to the passed value and notification should be shown on the Lock Screen.

### Other Technical Details

`6.13.4` output:

`v10.19.0` output:

### Additional Context
I tried debugging it in `NotificationChannelManager` and it seems that values are being updated correctly in their.

![image](https://user-images.githubusercontent.com/55490507/133912327-ea970c2b-932f-4557-b0a2-70c6e6da891f.png)

**Comment by Ionitron** [comment] 2021-09-20 08:28
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-06 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-10-06 00:03 UTC
Labels: platform: android, needs reply, needs reproduction
