### ISSUE TITLE
[Electron platform] Assets FILE_NOT_FOUND error in ionic capacitor app

### ISSUE THREAD

**Issue by ZhennanWu** [ionic-team/capacitor#1406] opened 2019-04-10 09:26 UTC
Asset files can't be loaded properly in electron apps due to base href issues, even when the base href in angular has already been manually set to "./".

# Demo
The display of a standard ionic template project "tabs": 
![tabs](https://user-images.githubusercontent.com/38578020/55867227-aca13e00-5bb4-11e9-8352-36b34bba2e8c.png)

The logo is broken due to this issue. The electron app can't load assets/shapes.svg

The electron capacitor app is generated by:
```
npx cap add electron
ng build --base-href ./
npx cap copy
```

Capacitor version: 1.0.0-beta19
@ionic/angular version: 4.1.0

# Related Issues
#888 #639 #693 
This issues specifically focus on the assets side of the problem, which can't be solved by angular cli command.

**Comment by jcesarmobile** [comment] 2019-04-10 10:27
Not really sure if this is a Capacitor problem, if you set the base href to `./`, those urls should look like `./assets/`, not `/assets/`

**Comment by ZhennanWu** [comment] 2019-04-10 11:29
There is a workaround for this issue, by refering to "assets/shapes.svg" instead of "/assets/shapes.svg" in Angular modules.

However, it is really error-prone, and somewhat embarrassing to occur in the ionic template project.

**Comment by mlynch** [comment] 2019-05-19 16:46
Duplicate of #639

**Closed by mlynch** 2019-05-19 16:46 UTC
Labels: platform: electron

**Comment by gnopor** [comment] 2020-05-23 00:40
Note: For launch the app with electron, follow these steps:(forgive my English I am native french speaker)

1. First of all forget about the electron folder, do not touch it.
2. In your react/ionic directory which is your root directory for the app,add the following in your package.json file:    "homepage": "./"

3. Now from your react/ionic directory which is your root directory for the app, navigate to the "public" directory and update your index.html file replacing <base href="/" /> with:    <base href="./" />

4. Now run the following command and that is it... 
    a. ionic build && npx cap copy
    b. npx cap open electron
