### ISSUE TITLE
Error with signed/release apk

### ISSUE THREAD

**Issue by stefanhuber** [ionic-team/capacitor#1204] opened 2019-02-07 09:05 UTC
Description of the problem:

I tried to build and sign an apk. The debug apk is working fine, however the signed version creates the following error:

```
10-11 11:30:30.284 10107-10107/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 10107
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/io.ionic.starter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.a.a.g.a(java.lang.String, org.a.a.e, org.a.a.j, org.a.a.h)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.a.a.g.a(java.lang.String, org.a.a.e, org.a.a.j, org.a.a.h)' on a null object reference
        at org.a.a.o.a(Unknown Source)
        at org.a.a.o.e(Unknown Source)
        at org.a.a.o.a(Unknown Source)
        at com.getcapacitor.b.c.a(Unknown Source)
        at com.getcapacitor.c.a(Unknown Source)
        at com.getcapacitor.c.a(Unknown Source)
        at io.ionic.starter.MainActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Affected platform
- [ x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x ] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:

node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by rahadur** [comment] 2019-02-07 09:09
@stefanhuber I had this problem and worked around it by adding

```
lintOptions { 

    checkReleaseBuilds false

}
```
to my build.grade file within the android{ } section.

**Comment by jcesarmobile** [comment] 2019-02-22 15:43
Did you change or set minifyEnabled to true? That could cause similar problems as proguard obfuscation can make Capacitor not work.

If you are not using minifyEnabled, can you provide a sample app? I can't reproduce on a newly created app.

**Comment by jcesarmobile** [comment] 2019-03-20 15:18
Closing as I can't reproduce and the user didn't answer the question I made nor provided a sample project.

**Closed by jcesarmobile** 2019-03-20 15:18 UTC
