### ISSUE TITLE
bug: bundledWebRuntime is broken after upgrading to capacitor 5 (android)

### ISSUE THREAD

**Issue by livesemantics** [ionic-team/capacitor#6755] opened 2023-07-20 14:48 UTC
### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

### Platform(s)
Android

### Current Behavior

After upgrading to capacitor 5, all plugin are `undefined` in the javascript code (e.g. Network , StatusBar, Filesystem ...) 
It was working in capacitor 4.x, and it's working well in ios with capacitor 5.2 - but it's broken in android.

### Code Reproduction

https://github.com/robingenz/capacitor-plugin-demo

capacitor.config.json: set "bundledWebRuntime": true,
add `<script src="capacitor.js"></script>` as first <script> tag to index.html,
add some plugins in js file, e.g:
```
const { App } = Capacitor.Plugins;
const { AppLauncher } = Capacitor.Plugins;
const { CapacitorHttp } = Capacitor.Plugins;
const { Device } = Capacitor.Plugins;
const { Network } = Capacitor.Plugins;
const { Filesystem } = Capacitor.Plugins;
const { StatusBar } = Capacitor.Plugins;
```
...

The Problem: all variables (App , Device, Network,..) are now undefined (only happens in android)

`npm --version` output: (built with Appflow build stack Linux - 2023.04)

`node --version` output: (built with Appflow build stack Linux - 2023.04)

`pod --version` output (iOS issues only):

**Comment by livesemantics** [comment] 2023-07-21 10:41
Please note that also `npx cap sync web` doesn't copy capacitor.js anymore.
Although  bundledWebRuntime is now deprecated and planned to be removed in 6.x, it should still be supported in 5.x.
Please fix.

**Comment by livesemantics** [comment] 2023-07-25 16:52
Note: Capacitor.Plugins object exists inside the js but it's an empty object {}.
I reverted back to 4.x and now it's working again.
Will try to update to 5.x in few months once it's (hopefully) less buggy.

**Comment by livesemantics** [comment] 2023-07-27 15:06
Code Reproduction
https://github.com/robingenz/capacitor-plugin-demo

capacitor.config.json: set "bundledWebRuntime": true,
add <script src="capacitor.js"></script> as first <script> tag to index.html

**Comment by jcesarmobile** [comment] 2023-07-27 18:02
That app fails on npm install step because it uses private packages, so it's not a valid reproduction, can you provide a simpler sample app that doesn't require private packages nor doing additional steps?

**Comment by Ionitron** [comment] 2023-08-12 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-08-12 00:05 UTC
Labels: platform: android, needs reproduction
