### ISSUE TITLE
[Feature]: Allow us to change the App.xcodeproj in nativeXcodeProjDir

### ISSUE THREAD

**Issue by rl-carno** [ionic-team/capacitor#7577] opened 2024-07-23 16:56 UTC
### Description

Renaming App directory breaks capacitor apps

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

If i change the name of App.xcodeproj it seems to break the build command. I am able to get my apps to run but its just slowing down my workflow.

Not sure why, but it's hard coded into nativeXcodeProjDir as that without any ability to override. And from scanning over the capacitor source code, I can't seem to see where there is justification for hard coding this.

I propose pulling the "App.xcodeproj" from external config so it can be configured inside capacitor.config.ts (ios->projectName).

I work across many apps and plugins and having them all open all showing App > App.xcodeproj gets confusing, so being able to rename these would be a great help to me.

**Comment by jcesarmobile** [comment] 2024-07-26 18:03
closing as duplicate of https://github.com/ionic-team/capacitor/issues/5279

**Closed by jcesarmobile** 2024-07-26 18:03 UTC
Labels: triage
