### ISSUE TITLE
feat: Option to show scrollbar.

### ISSUE THREAD

**Issue by twoco** [ionic-team/capacitor#5540] opened 2022-03-26 12:25 UTC
Please add an option to show the scrollbar of the webview. In my case on Android. Show scrollbar like Chrome does on mobile mode.

![demo](https://user-images.githubusercontent.com/53160891/160239278-fe49a639-ec4f-4d3f-9f99-a9f1c45d8bf4.gif)
Recorded on Windows 10 Chrome 99 in Dev Tools > Toggle Device Toolbar > Mobile frame view.

On Android the thin gray scrollbar is hidden. You don't see scrollable elements and don't see the progress. Just add an option to enable the scrollbar.

**Comment by twoco** [comment] 2022-05-13 20:53
It's just about scroll bars like in system browser. It does not need any code reproduction.
But here it is:

```html
<div style="width: 100px; height: 100px; overflow: auto">
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
  <div>Scroll</div>
</div>
```

![scroll](https://user-images.githubusercontent.com/53160891/168387168-e8414190-2129-442d-a1a5-80763ff00b2d.gif)

Scrollbars were introduced in the 70's. https://en.wikipedia.org/wiki/Scrollbar

The browser on Android or iOS displays the scrollbar. Also some apps I tested. But Cordova and Capacitor not. Why?
I noticed that the mobile scrollbars are only visible on scroll. I suggest 3 options:

- Hidden (as now)
- Scroll (only on scroll)
- Always (display always to indicate scrollable content)

**Comment by jcesarmobile** [comment] 2022-05-17 13:36
can you provide a full sample app that we can run instead of just a snippet of code?

**Comment by twoco** [comment] 2022-05-17 19:58
Sorry you can test it with any project. Just run `ionic start` and launch that empty project with some content to overflow to force scroll. But anyway ... here's a demo project: https://github.com/twoco/capacitor-scrollbar-issue

# Browser 
https://user-images.githubusercontent.com/53160891/168898946-c5719572-4f0d-4740-bf97-1a15f81c304a.mp4

# Capacitor 
https://user-images.githubusercontent.com/53160891/168898950-b086eadd-51c2-4aae-b753-afd1bf254393.mp4

**Comment by jcesarmobile** [comment] 2022-05-18 12:30
Looks like a bug on the WebView, the WebView have the scrollbar enabled by default, and works fine when the whole page is scrollable, but the bar doesn't appear when the page is not scrollable but the div is.

You can try reporting to chromium (Select WebView bugs template)
https://bugs.chromium.org/p/chromium/issues/list

**Comment by jcesarmobile** [comment] 2022-05-27 11:11
closing as the issue on the WebView has been confirmed by google team
https://bugs.chromium.org/p/chromium/issues/detail?id=1327047

**Closed by jcesarmobile** 2022-05-27 11:11 UTC
Labels: needs reproduction
