### ISSUE TITLE
bug: firebase v9 not working on iOS

### ISSUE THREAD

**Issue by JSilva6** [ionic-team/capacitor#5531] opened 2022-03-23 21:37 UTC
### Capacitor Version

```
PASTE OUTPUT HERE
```

### Platform(s)

iOS

### Current Behavior

`firebase` v9 refuses to connect on iOS due to the following errors below. On safari, android, chrome, everything else, works fine.

[Error] Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin capacitor://localhost is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://apis.google.com/_/jserror?script=https%3A%2F%2Fapis.google.com%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.pt_BR.JNlq9XF7n9c.O%2Fm%3Dgapi_iframes%2Frt%3Dj%2Fsv%3D1%2Fd%3D1%2Fed%3D1%2Frs%3DAHpOoo_CgjdRKayLAI-SffAgrENAd8_UBA%2Fcb%3Dgapi.loaded_0%3Fle%3Dscs&error=x%60capacitor&line=183 due to access control checks.
[Error] Failed to load resource: Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin capacitor://localhost is not allowed by Access-Control-Allow-Origin. (jserror, line 0)

### Expected Behavior

Shoulda connect normally. Appears that the domain from http://developers.google.com/  appears to be refusing the connection, tho version 8 of `firebase` worked normally.

### Code Reproduction

Just imported all the libraries from `firebase`

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: 12.22.8

`pod --version` output (iOS issues only): 1.10.2

**Comment by jcesarmobile** [comment] 2022-03-23 23:57
That’s a CORS error, should be fixed on the server, there is nothing we can do from Capacitor side.
If it was working fine with version 8 and broke on version 9 you should report the problem to firebase team.

**Closed by jcesarmobile** 2022-03-23 23:57 UTC
Labels: platform: ios

**Comment by 34fame** [comment] 2022-04-12 15:43
Did you figure out anything on this error, @JSilva6?  I'm having the same issue.

**Comment by JSilva6** [comment] 2022-04-27 14:27
> Did you figure out anything on this error, @JSilva6? I'm having the same issue.

For now I went back to v8.

**Comment by pkunszt** [comment] 2022-08-15 19:59
does not sound satisfying. did you try with gsutil cors? https://cloud.google.com/storage/docs/gsutil/commands/cors

**Comment by nilebma** [comment] 2022-08-17 12:31
Hi ! I got the same problem, it was was caused by a bad initialisation of FireAuth in my case.

See how to properly initialise FireAuth here : https://stackoverflow.com/questions/71630326/firebase-authentication-sticks-capacitor-ionic-on-ios
