### ISSUE TITLE
bug: Could not open cp_proj generic class cache

### ISSUE THREAD

**Issue by Artkoch** [ionic-team/capacitor#6298] opened 2023-02-14 16:38 UTC
## Bug Report
```
> capacitor add android
[capacitor] ✔ Adding native android project in android in 22.66ms
[capacitor] ✔ add in 23.03ms
[capacitor] ✔ Copying web assets from build to android/app/src/main/assets/public in 33.71ms
[capacitor] ✔ Creating capacitor.config.json in android/app/src/main/assets in 259.88μs
[capacitor] ✔ copy android in 53.99ms
[capacitor] ✔ Updating Android plugins in 2.96ms
[capacitor] [info] Found 4 Capacitor plugins for android:
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.0
[capacitor]        @capacitor/status-bar@4.1.1
[capacitor] ✔ update android in 27.36ms
[capacitor] Error running gradle sync
[capacitor] > Configure project :app
[capacitor] WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
[capacitor]
[capacitor] FAILURE: Build failed with an exception.
[capacitor]
[capacitor] * What went wrong:
[capacitor] A problem occurred configuring project ':capacitor-android'.
[capacitor] > Could not open cp_proj generic class cache for build file '/Users/compuser/Sites/app/node_modules/@capacitor/android/capacitor/build.gradle' (/Users/compuser/.gradle/caches/7.4.2/scripts/emf4zh005p5c3xq0le7yfltk6).
[capacitor]    > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
[capacitor]
[capacitor] * Try:
[capacitor] > Run with --stacktrace option to get the stack trace.
[capacitor] > Run with --info or --debug option to get more log output.
[capacitor] > Run with --scan to get full insights.
[capacitor]
[capacitor] * Get more help at https://help.gradle.org
[capacitor]
[capacitor] BUILD FAILED in 454ms
[capacitor]
[capacitor] Unable to infer default Android SDK settings. This is fine, just run npx cap open android and import and sync gradle manually
[capacitor] ✔ Syncing Gradle in 1.57s
[capacitor] [success] android platform added!
[capacitor] Follow the Developer Workflow guide to get building:
[capacitor] https://capacitorjs.com/docs/basics/workflow
```

### Capacitor Version
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
android

### Current Behavior
During execution of ```ionic capacitor add android``` command I get and error. 

### Expected Behavior
Expect finishing the execution of ```ionic capacitor add android``` command without any errors

### Other Technical Details

`npm --version` output: 9.3.1

`node --version` output: v18.6.0

`pod --version` output (iOS issues only):

**Comment by Artkoch** [comment] 2023-02-18 07:27
Can someone give an ideas at least?

**Comment by renehauck** [comment] 2023-02-18 13:06
I just have the problem too, after installing `@capacitor/push-notifications` and syncing it through `npx cap sync`

**Comment by Ionitron** [comment] 2023-02-28 16:58
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-16 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-16 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
