### ISSUE TITLE
bug: localNotificationReceived listener not implemented on Android

### ISSUE THREAD

**Issue by dotrub** [ionic-team/capacitor#2777] opened 2020-04-15 20:31 UTC
# Bug Report

## Capacitor Version
`npx cap doctor` output:

  @capacitor/cli 1.5.0
  @capacitor/core 1.5.0
  @capacitor/android 1.5.0
  @capacitor/ios 2.0.0

Though to test this out, I cloned the latest code from Capacitor and searched the files in that repo.

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
There is no implementation of the `localNotificationReceived` event for Android LocalNotifications. This means that adding that listener has no effect on Android devices, when local notifications are fired.

## Expected Behavior
That documentation will match code. If there is a legitimate reason not to implement this, it should be documented ASAP. If this was an oversight, it should be implemented.

## Reproduction Steps

Search the code in the Android implementation of Capacitor for any instances of `localNotificationReceived`. There are none. There is one in the iOS implementation, and there is one for `localNotificationActionPerformed` in both implementations.

**Comment by jcesarmobile** [comment] 2020-04-15 21:17
Duplicate of https://github.com/ionic-team/capacitor/issues/2352

**Closed by jcesarmobile** 2020-04-15 21:17 UTC
