### ISSUE TITLE
bug:  Capacitor v4 share plugin dialogTitle not showing

### ISSUE THREAD

**Issue by philasandempetukana** [ionic-team/capacitor#6466] opened 2023-04-05 06:29 UTC
I’m using “@capacitor/share”: “^4.1.1” in my app and I have the following code in my Vue.js file:

```
import { Share } from '@capacitor/share';

await Share.share({
  title: 'See cool stuff',
  text: 'Really awesome thing you need to see right meow',
  url: 'http://ionicframework.com/',
  dialogTitle: 'Share with buddies',
});
```

However, the dialogTitle value is not showing on the modal, but the text value is showing instead. See screenshot. Is this a bug or do I need to extend the code and do something? And I’d also like to change the default A icon to a custom one.

<img width="284" alt="Screenshot 2023-04-04 at 18 23 50" src="https://user-images.githubusercontent.com/26714898/229998876-983e8e2a-be27-40c9-9a20-4fe7141cbb62.png">

**Comment by Ionitron** [comment] 2023-04-10 11:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-04-26 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-04-26 00:05 UTC
Labels: platform: android, platform: ios, needs reply, needs reproduction
