### ISSUE TITLE
bug: Unable to run/build android app

### ISSUE THREAD

**Issue by Zyles** [ionic-team/capacitor#6992] opened 2023-10-14 12:55 UTC
## Bug Report

Unable to build android app.

### Capacitor Version
```
 Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

[success] Android looking great! 👌
[error] Xcode is not installed

```

### Platform(s)
Android

### Current Behavior
`$ npx cap run android`

### Expected Behavior

Run the emulator or build project.

### Code Reproduction
Fresh blank install.

### Other Technical Details

```
$ npm --version
10.1.0
```

```
$ node --version
v20.7.0
```

```
$ java -version
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)
```

### Additional Context

```
× Running Gradle build - failed!
[error]
        FAILURE: Build failed with an exception.

        * What went wrong:
        A problem occurred configuring root project 'android'.
        > Could not resolve all files for configuration ':classpath'.
        > Could not resolve com.android.tools.build:gradle:8.1.2.
        Required by:
        project :
        > No matching variant of com.android.tools.build:gradle:8.1.2 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.2' but:
        - Variant 'apiElements' capability com.android.tools.build:gradle:8.1.2 declares a library, packaged as a jar, and its dependencies declared externally:
        - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
        - Other compatible attribute:
        - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
        - Variant 'javadocElements' capability com.android.tools.build:gradle:8.1.2 declares a component for use during runtime, and its dependencies declared externally:
        - Incompatible because this component declares documentation and the consumer needed a library
        - Other compatible attributes:
        - Doesn't say anything about its target Java version (required compatibility with Java 8)
        - Doesn't say anything about its elements (required them packaged as a jar)
        - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
        - ...
```

**Comment by LennonReid** [comment] 2023-10-14 13:22
It appears to be a Java version issue. Please install Java version 11 or higher to address this problem.

**Comment by Zyles** [comment] 2023-10-14 13:39
> It appears to be a Java version issue. Please install Java version 11 or higher to address this problem.

I should have the latest java, I just installed it a few hours ago?

**Comment by LennonReid** [comment] 2023-10-14 14:09
This link might help resolve your issue: [How to change Android Studio default Gradle JDK to 11](https://stackoverflow.com/questions/70228745/how-to-change-android-studio-default-gradle-jdk-to-11). It provides guidance on adjusting the JDK version in Android Studio. @Zyles

**Comment by Zyles** [comment] 2023-10-15 10:23
It's already on 17.0.6

**Comment by jcesarmobile** [comment] 2023-10-16 08:29
Your `java -version` output shows 1.8, not 17, capacitor 5 requires java 17 to work.
If you have updated after you created the issue, restart the computer and make sure `java -version` now returns 17.
Double check that you have a `JAVA_HOME` variable created and it points to the java 17 installation.

Closing since this is not a bug but a bad configuration.
If you still have problems you can ask for help on the discussions section
https://github.com/ionic-team/capacitor/discussions

**Closed by jcesarmobile** 2023-10-16 08:29 UTC
Labels: platform: android
