### ISSUE TITLE
bug: FormData not working when CapacitorHttp is enabled

### ISSUE THREAD

**Issue by dennisameling** [ionic-team/capacitor#6645] opened 2023-06-09 21:40 UTC
### Capacitor Version

```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5
  @capacitor/core: 5.0.5

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

iOS and Android

### Current Behavior

When `CapacitorHttp` [is enabled](https://capacitorjs.com/docs/apis/http#example-configuration), it replaces `window.fetch` and `XMLHttpRequest` with native HTTP calls on iOS/Android. This works fine in most cases, except for when passing a `FormData` object to it. Consider the following example code:

```TS
      const formdata = new FormData();
      formdata.append('file', new Blob([f]));

      this.http.post(`${apiHost}/profile`, formdata, {
        headers: {
          'Client': 'Angular'
        }
      })
        .subscribe(res => {
          console.log('Angular HTTP result')
          console.log(res)
          this.angularHttpResponse = res
        }, err => {
          console.log(err)
          this.angularHttpResponse = err
        })
```

Normally, browser APIs automatically add the `Content-Type: multipart/form-data; boundary=----XXXXXX` header when a [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) object is being sent to a server. However, the CapacitorHttp native calls don't do this, causing the requests to fail:

Behavior on web:

<img width="1425" alt="Screenshot 2023-06-09 at 23 29 48" src="https://github.com/ionic-team/capacitor/assets/17739158/abc2cafe-fbe3-44df-8109-328c59c31328">

Behavior on Android:

<img width="200" alt="Screenshot_20230609_232053_frontend" src="https://github.com/ionic-team/capacitor/assets/17739158/6c2b093b-1ce6-4d11-b67d-d48f24f4cf12">

### Expected Behavior

I guess the expected behavior would be that the native Android and iOS handlers add the `multipart/form-data` header, just like browsers do. So something like `Content-Type: multipart/form-data; boundary=----XXXXXX`.

### Code Reproduction

https://github.com/dennisameling/capacitor-http-bug

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.16.0

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

Similar issue: https://github.com/ionic-team/capacitor/issues/6142

**Comment by davidquon** [comment] 2023-07-08 21:46
Looks like this issue also exists on Capacitor Core `4.8.0` as well.  If anyone has any work around suggestions to get file uploading to work it would be greatly appreciated.

**Comment by taylorbront** [comment] 2023-07-15 09:16
i have this problem with capacitor 5.0. there is no `content-type` header and the `FormData` data payload of the request is empty when sent to the server. so file uploading is currently not possible with capacitor?

**Comment by koraxos** [comment] 2023-07-24 07:53
Hello, a fix has been approved for Capacitor 4.8.1 , i'm not sure that it has been merged on the main branch ( capacitor 5 ),

i'm referring to https://github.com/ionic-team/capacitor/commit/3cd7196ec10066a98561e5d1b1166d8c1133f13a

**Comment by jcesarmobile** [comment] 2023-08-16 17:20
Using the XHR/fetch patch is working now on 5.2.3 version.

Using `CapacitorHttp.post` directly won't work because the native bridges can't handle complex data types such as `FormData`. On Android the call is getting through the bridge, but the data is empty. On iOS the data is failing to be cloned before being sent to the bridge.

The type of the data is set to `any`, but it's not really true, should be documented that passing `FormData` or other complex types won't work, they should be serialized as the XHR/fetch patch does.

**Comment by dennisameling** [comment] 2023-08-17 20:30
Can confirm this is working now on Capacitor 5.2.3, both on Android and iOS 🎉 Just to be clear: I'm not using `CapacitorHttp.post` but Angular's HttpClient (which is either `window.fetch` or `XHR` under the hood). I just enabled the `CapacitorHttp` interceptor [as described here](https://capacitorjs.com/docs/apis/http#example-configuration). Thanks! I believe this issue can be closed now, unless you want to keep this open to track documentation updates.

**Comment by jcesarmobile** [comment] 2023-08-18 07:41
yeah, we will keep it open as should be documented what kind of data the `CapacitorHttp.post` can accept or change the types from `any` to something more restrictive.

**Comment by wolframtheta** [comment] 2023-08-25 08:22
Using `CapacitorHttp.post` it's still adding the header wrong. The header is: `Content-Type: application/x-www-form-urlencoded` insted of multipart with the boundary. Any suggestion?

**Comment by wolframtheta** [comment] 2023-08-25 09:17
> I have updated Capacitor to 5.2.3, on Android and iOS, and at least in Androis using `CapacitorHttp.post` it's still adding the header wrong. The header is: `Content-Type: application/x-www-form-urlencoded` insted of multipart with the boundary. Any suggestion?

Why this is marked as Off-topic? I think it has relation with the bug...

**Comment by theGreatRishabh** [comment] 2023-10-09 21:07
Hi @wolframtheta @dennisameling 
I'm in a similar situation. I updated to the latest 5.4.2 when I keep capacitorHttp enabled I'm able to make POST calls properly in Android but not in iOS. 

It seems as if FormData is being sent as empty content-type is correct, the issue is only in iOS, I need to keep capacitorHttp enabled as it has a dependency with other plugins I'm using. I'm also using Angular's HttpClient and not capacitor.post. 

Please let me know what can I add more for the problem to be more comprehensible.

**Closed** 2023-12-08 15:34 UTC
Labels: platform: android, platform: ios, type: bug

**Comment by jongbonga** [comment] 2023-12-10 18:51
I'm getting an error on Android when posting `formData` with `window.fetch`. I have capacitorHttp enabled. 
It is working fine on iOS though but Android throws
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.getcapacitor.plugin.util.CapacitorHttpUrlConnection.writeFormDataRequestBody(CapacitorHttpUrlConnection.java:239)
	at com.getcapacitor.plugin.util.CapacitorHttpUrlConnection.setRequestBody(CapacitorHttpUrlConnection.java:219)
	at com.getcapacitor.plugin.util.HttpRequestHandler.request(HttpRequestHandler.java:414)
	at com.getcapacitor.plugin.CapacitorHttp.lambda$http$0(CapacitorHttp.java:64)
	at com.getcapacitor.plugin.CapacitorHttp.$r8$lambda$nEWv6LUu-usVqu2PfWDWH0J-AgQ(Unknown Source:0)
	at com.getcapacitor.plugin.CapacitorHttp$$ExternalSyntheticLambda0.run(Unknown Source:6)
```
