### ISSUE TITLE
Capacitor Camera on IOS failed

### ISSUE THREAD

**Issue by BechirAhmed** [ionic-team/capacitor#6006] opened 2022-10-19 09:02 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
IOS

### Current Behavior

When pick an image it says You don’t have permission to save the file [filepath] in the folder “com.apple.mobileslideshow.export-request”

### Expected Behavior

I'm just picking an image and uploading it to server as base64

### Code Reproduction

```
async newSelectImage() {
    const image = await NCamera.getPhoto({
        quality: 90,
        allowEditing: false,
        resultType: CameraResultType.Uri,
        source: CameraSource.Prompt // Camera, Photos or Prompt!
    });

    if (image) {
        this.saveImage(image)
    }
  }
  // Create a new file from a capture image
  async saveImage(photo: Photo) {
    const base64Data = await this.readAsBase64(photo);
    this.img = base64Data;
    this.profile = base64Data;
  }

  private async readAsBase64(photo: Photo) {
    if (this.platform.is('hybrid')) {
        const file = await Filesystem.readFile({
            path: photo.path
        });

        return file.data;
    }
    else {
        // Fetch the photo, read as a blob, then convert to base64 format
        const response = await fetch(photo.webPath);
        const blob = await response.blob();

        return await this.convertBlobToBase64(blob) as string;
    }
  }
  // Helper function
  convertBlobToBase64 = (blob: Blob) => new Promise((resolve, reject) => {
    const reader = new FileReader;
    reader.onerror = reject;
    reader.onload = () => {
        resolve(reader.result);
    };
    reader.readAsDataURL(blob);
  });
```

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v18.10.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment] 2022-10-19 09:04
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-12 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-12 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction
