### ISSUE TITLE
bug:  Capacitor plugins version check fails in monorepo

### ISSUE THREAD

**Issue by borgoat** [ionic-team/capacitor#6599] opened 2023-05-17 07:58 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/ios: 5.0.3
```

### Platform(s)

- Android

### Current Behavior

When performing `cap sync` in a monorepo, where Capacitor plugins were hoisted to the root `node_modules`, the migration step introduced in #6569 fails to find the `build.gradle` file of the plugin.

```
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/app/android/build.gradle. Try updating it manually
[warn] @capacitor/app doesn't officially support Capacitor ^5.0.0 yet, doing our best moving it's package to build.gradle so it builds
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/app/android/src/main/AndroidManifest.xml. Try updating it manually
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/app/android/build.gradle. Try updating it manually
[error] Could not read ~/yeekatee/apps/mobile/node_modules/@capacitor/app/android/src/main/AndroidManifest.xml. Check its permissions and if it exists.
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/browser/android/build.gradle. Try updating it manually
[warn] @capacitor/browser doesn't officially support Capacitor ^5.0.0 yet, doing our best moving it's package to build.gradle so it builds
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/browser/android/src/main/AndroidManifest.xml. Try updating it manually
[error] Unable to find ~/yeekatee/apps/mobile/node_modules/@capacitor/browser/android/build.gradle. Try updating it manually
[error] Could not read ~/yeekatee/apps/mobile/node_modules/@capacitor/browser/android/src/main/AndroidManifest.xml. Check its permissions and if it exists.

[redacted: it repeats for all plugins]
```

### Expected Behavior

The migration step still runs, but it searches from the actual plugin path in the node_modules:

`~/yeekatee/apps/mobile/node_modules/@capacitor/browser/android/build.gradle` -> `~/yeekatee/node_modules/@capacitor/browser/android/build.gradle`

### Code Reproduction

In order to reproduce this, you must have a node_modules in a parent directory of your Capacitor app.

### Other Technical Details

In our specific case, this is a Nx monorepo, but one could achieve the same configuration in many different ways.

### Additional Context

#6598 solves this issue.

**Comment by Ionitron** [comment] 2023-05-17 08:37
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by pomSense** [comment] 2023-05-18 05:03
+1. Same issue with a Monorepo

**Comment by Ionitron** [comment] 2023-06-03 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-03 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
