### ISSUE TITLE
feat: customize platform folders in capacitor.config.json

### ISSUE THREAD

**Issue by ehmprah** [ionic-team/capacitor#3498] opened 2020-09-02 12:44 UTC
As described in this comment: https://github.com/ionic-team/capacitor/issues/1084#issuecomment-538650896 I'd like to see an option to set different folders for ios and android in capacitor.config.json.

**Comment by jcesarmobile** [comment] 2020-09-10 11:36
duplicate of https://github.com/ionic-team/capacitor/issues/2294

**Closed by jcesarmobile** 2020-09-10 11:36 UTC
