### ISSUE TITLE
bug: capacitor3 AppPlugin event register appStateChange dont work after removeAllListeners()

### ISSUE THREAD

**Issue by BobTape** [ionic-team/capacitor#5159] opened 2021-10-22 08:25 UTC
### Capacitor Version
Latest Dependencies:       

  @capacitor/cli: 3.2.5    
  @capacitor/core: 3.2.5   
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5    

Installed Dependencies:    

  @capacitor/ios: not installed   
  @capacitor/android: 3.2.5       
  @capacitor/core: 3.2.5
  @capacitor/cli: 3.2.5

### Platform(s)
Android
Reactjs
Typescript

### Current Behavior

When i use AppPlugin: 
After call removeAllListeners is impossible again register "appStateChange" event. On android is event not triggered, bacause look as unregistered.
but "backButton" event work ok.

### Expected Behavior

Both events will work after removeAllListeners and new registering.

### Code Reproduction

`
import { App as CapApp } from "@capacitor/app";

CapApp.removeAllListeners().then(()=>{

  CapApp.addListener('appStateChange', ({ isActive }) => {
    console.log('App state changed. Is active?', isActive);
  });
  
  CapApp.addListener("backButton", (data: any) => {
    console.log('Back button event');
  });  
});
`

### Other Technical Details

`npm --version` output: 6.14.5
`node --version` output: v14.4.0
`pod --version` output (iOS issues only):

**Comment by BobTape** [comment] 2021-11-02 08:59
I think, described lines is enough for reproduction. Thakn you. Bob

**Comment by Ionitron** [comment] 2021-11-02 12:26
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dtrigo** [comment] 2021-11-15 08:41
I am experiencing the same described behaviour, my code is the same as in the description

**Comment by jcesarmobile** [comment] 2021-11-15 09:12
Can you provide a sample app where it can be reproduced?

**Comment by dtrigo** [comment] 2021-11-15 11:17
I have 2 pages:

Login: 

App.addListener("backButton", (data: any) => {
 exitApp()
});

Index:

App.removeAllListeners().then(()=>{

App.addListener('appStateChange', ({ isActive }) => {
console.log('App state changed. Is active?', isActive);
});

App.addListener("backButton", (data: any) => {
console.log('Back button event');
});

})

In this case, appStateChange event is never handled

**Comment by jcesarmobile** [comment] 2021-11-15 11:20
can you put that code together in an app?

**Comment by dtrigo** [comment] 2021-11-15 11:33
I'll try when I get a chance, but probably is going to take some time

**Comment by BobTape** [comment] 2021-11-15 16:38
Same on my side, i try to find some time for better demo, but i think it is replicable on any capacitor 3 demo app. with ours code examples.

**Comment by robingenz** [comment] 2021-11-28 17:49
Looks like the same problem as https://github.com/ionic-team/capacitor-plugins/issues/703.
I put some additional info in my issue.

**Comment by robingenz** [comment] 2021-11-28 20:45
This is the demo app: https://github.com/robingenz/capacitor-plugins-issue-703

**Comment by jcesarmobile** [comment] 2021-12-01 15:35
closing in favor of https://github.com/ionic-team/capacitor-plugins/issues/703 as it's in the plugins repository and includes a test app.

**Closed by jcesarmobile** 2021-12-01 15:35 UTC
Labels: platform: android, needs reproduction
