### ISSUE TITLE
Android livereload not working

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/capacitor#1809] opened 2019-07-26 11:54 UTC
Description of the problem:
`ionic capacitor run android --livereload` launches Android Studio as expected, and it shows up in the emulator when you run in. 

However, when you change the web source, for example `home.page.html`, you can observe that  Angular compiles but the app is not updated in the emulator.

```shell
[ng] ℹ ｢wdm｣: Compiling...
[ng] Date: 2019-07-26T11:41:55.215Z - Hash: f7a5c98bae47fab75e0d - Time: 844ms
[ng] 103 unchanged chunks
[ng] chunk {home-home-module} home-home-module.js, home-home-module.js.map (home-home-module) 4.92 kB  [rendered]
[ng] ℹ ｢wdm｣: Compiled successfully.
```

I verified by opening a browser and going to `http://localhost:8100` that the source has indeed updated, but it is just not reflected in the Android emulator. 

What makes it even stranger is that if I open chrome and inspect (`chrome://inspect/#devices`) and force a reload that way, I can see that the Android emulator reloads, but the changes are not reflected. Maybe some sort of Capacitor webview caching issue?

Here's steps to reproduce:
1. `git clone https://github.com/biesbjerg/capacitor-android-livereload.git`
2. `ionic capacitor run android --livereload`
3. Run in emulator when Android Studio has launched
4. Make a change to web source

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/kim/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
```

**Comment by jcesarmobile** [comment] 2019-07-26 18:47
The problem is that command is setting the server url to localhost, and that makes to load the local assets.

If you run with `ionic capacitor run android -l --address=0.0.0.0` then it will work. 

I think Ionic CLI is going to be updated to add the --address=0.0.0.0 as default when the run is targeted to android. 

Keeping it open because in #1776 we are trying to workaround this problem too, but have in mind that localhost as live reload server url won't work on real devices unless you enable port forwarding in chrome inspector.

**Comment by biesbjerg** [comment] 2019-07-26 20:49
When running with `--address=0.0.0.0` I never get past the splash screen (running in an emulator).

On the other hand when running on iOS I do need to supply `--address=0.0.0.0` or I won't get past the splash screen (also running in an emulator).

Any ideas why I only reach the splash screen on Android emulator?

**Comment by FernetB** [comment] 2019-07-31 15:00
Same here, ionic capacitor run android -l is not working as expected.
 '''
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.1
   OS     : Windows 10
'''

**Comment by lichnow** [comment] 2019-08-15 05:59
@jcesarmobile 
<img width="339" alt="a" src="https://user-images.githubusercontent.com/1695900/63075650-f3d57c00-bf64-11e9-98c1-2e8496516d96.png">

**Comment by jcesarmobile** [comment] 2019-08-15 07:56
That’s a different problem, on Android 9 http connections are blocked by default, you have to disable cleartext traffic

**Comment by jcesarmobile** [comment] 2019-10-18 16:58
Should be fixed by https://github.com/ionic-team/capacitor/pull/2067

**Closed by jcesarmobile** 2019-10-18 16:58 UTC
