### ISSUE TITLE
bug: SyntaxError: Unexpected token 'E', "Error: spawn ENOTDIR" is not valid JSON (Yarn Plug'n'Play)

### ISSUE THREAD

**Issue by bitjson** [ionic-team/capacitor#6139] opened 2022-12-02 07:45 UTC
### Capacitor Version

```
❯ yarn cap doctor    
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.0
  @capacitor/core: 4.6.0
  @capacitor/android: 4.6.0
  @capacitor/ios: 4.6.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

```
❯ yarn cap run ios -l --external      
✔ Copying web assets from build to ios/App/App/public in 31.11ms
✔ Creating capacitor.config.json in ios/App/App in 792.54μs
[info] Inlining sourcemaps
✔ copy ios in 94.23ms
✔ Updating iOS plugins in 6.29ms
[info] Found 4 Capacitor plugins for ios:
       @capacitor/app@4.1.1
       @capacitor/haptics@4.1.0
       @capacitor/keyboard@4.1.0
       @capacitor/status-bar@4.1.0
✔ Updating iOS native dependencies with pod install in 3.25s
✔ update ios in 3.27s
[error] SyntaxError: Unexpected token 'E', "Error: spawn ENOTDIR" is not valid JSON
        at JSON.parse (<anonymous>)
        at Object.getPlatformTargets
        (/[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/util/native-run.js:39:26)
        at async Object.runIOS
        (/[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/ios/run.js:13:59)
        at async run
        (/[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/tasks/run.js:74:9)
        at async runCommand
        (/[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/tasks/run.js:61:13)
        at async
        /[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/index.js:123:9
        at async
        /[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/telemetry.js:26:13
        at async Command.<anonymous>
        (/[...]/.yarn/cache/@capacitor-cli-npm-4.5.0-b394afdec0-4e8a545462.zip/node_modules/@capacitor/cli/dist/util/cli.js:12:13)
```

### Expected Behavior

Expected to be able to run the app on an external device successfully.

### Code Reproduction

```sh
ionic start blank blank --type=react --capacitor
cd blank
yarn set version latest
yarn capacitor add ios
yarn cap run ios -l --external
# or: yarn ionic cap run ios -l --external
```

### Other Technical Details

`yarn --version` output: 3.3.0

`node --version` output: v19.2.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment] 2022-12-05 18:50
Can you provide a sample app?
Those steps to reproduce don't seem correct, `yarn capacitor add ios` should fail as you haven't installed @capacitor/ios and `yarn cap run ios -l --external` is not correct neither, `-l --external` have no effect on capacitor run command, maybe you are using ionic instead of yarn? (i.e. `ionic capacitor add ios`)

Can you run `npx native-run ios --list --json`? looks like it's returning some error instead of the json with the list of the simulator/devices you have.

**Comment by Ionitron** [comment] 2022-12-21 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-21 00:05 UTC
Labels: platform: ios, needs reply
