### ISSUE TITLE
bug: Keyboard resizes webview but css rules are not reevaluated

### ISSUE THREAD

**Issue by kevinsimper** [ionic-team/capacitor#6430] opened 2023-03-23 15:28 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

On iOS is resized when the keyboard is shown 👍 Good

The bug is that CSS rules like 
```
body {
            padding-top: env(safe-area-inset-top);
            padding-right: env(safe-area-inset-right);
            padding-left: env(safe-area-inset-left);
          }
          .fullScreenMinusInsets {
            height: calc(100vh - env(safe-area-inset-top));
            width: calc(100vw  - env(safe-area-inset-left) - env(safe-area-inset-right));
          }
```

Are not reevaluted, so the safe-inset padding is not there anymore after the keyboard is closed.

If you go into Safari developer tools and toggle the CSS rules, the layout becomes correct again

<img width="301" alt="image" src="https://user-images.githubusercontent.com/1126497/227252610-f2be1dd3-058b-435f-be59-e70cb46a0c6b.png">

So initial screen
![image](https://user-images.githubusercontent.com/1126497/227252718-ada808b8-511a-442f-abc0-5dd85ef21692.png)

Keyboard open
![image](https://user-images.githubusercontent.com/1126497/227252802-6b8aa569-ecf7-4a8b-aa5c-097c619c19aa.png)

Safe inset has disappeared (see the darkgreen is at the bottom now)
(On a real device the "Back" is not up in the area that can not be touched/triggered)
![image](https://user-images.githubusercontent.com/1126497/227252898-66f560a0-c114-4dcd-9260-2e4997925585.png)

CSS Rule disabled in Safari:
![image](https://user-images.githubusercontent.com/1126497/227253000-6d52a6f2-2709-413a-b73a-f724e36eef00.png)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1126497/227253031-8bc99157-ed36-49d2-b4d2-f09584cfc845.png">

CSS Rule enabled again in Safari
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1126497/227253115-30f8b594-f505-4b5f-b231-2f573d9d4ff1.png">

It looks correct again! 
![image](https://user-images.githubusercontent.com/1126497/227252718-ada808b8-511a-442f-abc0-5dd85ef21692.png)

**Comment by kevinsimper** [comment] 2023-03-23 15:53
A temporary fix can be to trigger a CSS recalc with JS
`ref.current.style.height = ...`

**Comment by Ionitron** [comment] 2023-04-11 16:28
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-04-27 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-04-27 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
