### ISSUE TITLE
[Bug]: Capacitor HTTP plugin does not set data for fetch with Request

### ISSUE THREAD

**Issue by michaelkhabarov** [ionic-team/capacitor#7371] opened 2024-03-29 01:06 UTC
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

### Other API Details

```Shell
npm --version
10.2.0

node --version
v20.8.0

pod --version
1.14.0
```

### Platforms Affected

- [X] iOS
- [X] Android
- [ ] Web

### Current Behavior

Sending fetch request with `Request` object as a parameter does not set `data` for request. This makes Capacitor HTTP incompatible with popular [ky](https://github.com/sindresorhus/ky) library.

```js
request = new Request("http://192.168.1.11:3000/clients/auth/verification_code", { method: "POST" })
request.headers.set("Content-Type", "application/json")
request.body = JSON.stringify({"phone": "1234567890"}) // <-- this is ignored
await fetch(request)
```

<img width="771" alt="Screenshot 2024-03-29 at 04 03 16" src="https://github.com/ionic-team/capacitor/assets/1417956/b9bef87a-32e6-4b35-8640-7171c92a5bb6">

### Expected Behavior

Expect passing `Request` to `fetch` parameter to send `body` of request object

### Project Reproduction

none, can be reproduced without a repo

**Comment by WurstMitBrot** [comment] 2024-04-10 08:31
I faced a similiar issue. I'm using the Capacitor Http plugin in combination with rtk query.
The plugin config looks like follows:

` plugins: {
    CapacitorHttp: {
      enabled: true,
    },
  },`
  
  When making a post request i get the following error:
  Using fetch:
![image](https://github.com/ionic-team/capacitor/assets/11289701/22f5990b-8922-4935-aded-4e2c72e44ae6)

Using RTK Query:
![image](https://github.com/ionic-team/capacitor/assets/11289701/88df31ec-e0d7-4e46-b849-55df24b6d426)


To reproduce the issue i created the following project:
https://github.com/WurstMitBrot/capacitor-fetch-example

**Comment by jcesarmobile** [comment] 2024-04-10 16:08
WurstMitBrot, since you say it's a similar issue, but might not be the same problem, can you create a separate issue for your problem?

**Comment by WurstMitBrot** [comment] 2024-04-11 08:55
> WurstMitBrot, since you say it's a similar issue, but might not be the same problem, can you create a separate issue for your problem?

Thanks for your answer, created a new issue.

**Comment by Ionitron** [comment] 2024-04-27 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-04-27 00:06 UTC
Labels: needs reply, needs reproduction
