### ISSUE TITLE
bug: core http & cookies plugin not working with img src in iOS

### ISSUE THREAD

**Issue by inpt333** [ionic-team/capacitor#6038] opened 2022-10-28 12:57 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0
```

### Platform(s)

iOS

### Current Behavior

We're trying to download some images in our html from our cloud provider by using the tag img. To do so, we need to request one of our services to get a security token and propagate it in the cookies of the requests to get those images. To retrieve the cookie, we are using the new Capacitor Core Http and Cookies plugins. In Web and Android everything works fine, but in iOS only the requests done directly via the plugin work, but the ones for the images don't propagate the cookie and are rejected by our cloud provider.

We've even tried to force the setting of the cookie directly in our code for both, `document.cookie` and `CapacitorCookies.setCookie`, and even though the value was set properly in both, the requests to the images didn't have it and therefore failed.

We also tried to set in our Info.plist the array `WKAppBoundDomains` with the domain used to download the images, but it didn't work either.

### Expected Behavior

As in Android, the http plugin should automatically set cookies in the cookie manager and those be reused by the webview when trying to use `<img src=... />` in the html code.

### Other Technical Details

`npm --version` output: 8.12.1

`node --version` output: v18.4.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by ItsChaceD** [comment] 2022-11-17 02:36
Can you please test with this branch and see if the problem still occurs (or provide a code reproduction):
https://github.com/ionic-team/capacitor/pull/6086

Run this in the capacitor folder after pulling down the repo:
`cd core`
`npm run build && npm run build:nativebridge`

then change your local project `package.json` to:
```
"@capacitor/android": "file:../capacitor/android",
"@capacitor/core": "file:../capacitor/core",
"@capacitor/ios": "file:../capacitor/ios",
```

and run `npm i && npm run build && npx cap sync`

**Comment by inpt333** [comment] 2022-11-25 13:44
Hi @ItsChaceD , I've also tested with that version and the issue can be still reproduced, the cookies are not being properly set by the WebView of iOS, so the request done by the img tag still fails due to these missing cookies.

Unfortunately, I cannot provide you with the code, but the use case is simple, we're trying to retrieve via img tag a remote image that is protected by signed cookies. To get the cookies, we do a request to our server via the core CapacitorHttp plugin and we use the core CapacitorCookies (also tried directly with document.cookie) to store the returned cookies. In Android and Web the img tag is able to retrieve the image because the cookies are automatically assigned to the request, but in iOS is not happening.

**Comment by huuhait** [comment] 2022-12-10 00:13
i dont think it's fixed in ios
using (v4.6.1)

**Comment by Ionitron** [comment] 2023-03-06 17:37
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-22 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-22 00:04 UTC
Labels: platform: ios, needs reply, needs reproduction
