### ISSUE TITLE
Sending an unlimited number of emails in an Ionic project with Angular ? 

### ISSUE THREAD

**Issue by ionicsiva** [ionic-team/capacitor#6975] opened 2023-10-09 14:08 UTC
I want to implement the ability to send an unlimited number of emails in an Ionic project with Angular, I've tried to send unlimited emails, but they are not being delivered. I've encountered a error in the "FirebaseError: Firebase: Exceeded daily quota for email sign-in. (auth/quota-exceeded), This is the code for sending email functionality. Please review it.

import { Injectable } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/compat/auth';
import firebase from 'firebase/compat/app';

@Injectable({
providedIn: 'root'
})
export class AuthService {

constructor(private fireAuth: AngularFireAuth) {}
public sendAuthEmail(email: string) {
const actionCodeSettings = {
url: 'https://exampleurl.com/',
handleCodeInApp: true
};

return new Promise<any>((resolve, reject) => {
  this.fireAuth.sendSignInLinkToEmail(email, actionCodeSettings)
    .then(() => {
      resolve('Email link sent successfully'); 
    })
    .catch((error) => {
      console.error(error);
      reject('Email link not sent');
    });
});
}

public async enterVerificationCode(email: string, emailLink: string) {
return new Promise((resolve, reject) => {

  if (!firebase.auth().isSignInWithEmailLink(emailLink)) {
    reject('Invalid email link');
    return;
  }

  firebase.auth().signInWithEmailLink(email, emailLink)
    .then((userCredential) => {
      const user = userCredential.user;
      resolve(user);
    })
    .catch((error) => {
      console.error(error);
      reject('Error confirming email link');
    });
});
}
}

#ionic #firebase

**Comment by jcesarmobile** [comment] 2023-10-09 14:26
closing since this is not a bug report but a question, you already created a question in the discussions section
https://github.com/ionic-team/capacitor/discussions/6973

By the error it looks like firebase has a quota and you exceeded it, so you can't send unlimited mails from firebase.

**Closed by jcesarmobile** 2023-10-09 14:26 UTC
Labels: triage
