### ISSUE TITLE
How to detect an incoming call

### ISSUE THREAD

**Issue by 313hemant313** [ionic-team/capacitor#5506] opened 2022-03-15 17:53 UTC
### Discussed in https://github.com/ionic-team/capacitor/discussions/3992

<div type='discussions-op-text'>

<sup>Originally posted by **313hemant313** December 25, 2020</sup>
The Capacitor AppState provides status of app when the app enters and leaves the foreground, But is it possible to detect incoming call ? 

For me the main task in hand is to mute/volume down the audio that is currently playing when a phone call comes.</div>

**Comment by jcesarmobile** [comment] 2022-03-15 17:59
Closing because it's not a bug, just a repost of the question.

**Closed by jcesarmobile** 2022-03-15 17:59 UTC

**Comment by 313hemant313** [comment] 2022-03-18 09:49
Created an android plugin to detect call state ('RINGING' | 'OUTGOING' | 'IDLE' | 'ON_CALL' | 'ON_HOLD').
Feel free to contribute or use.

# capacitor-plugin-incoming-call
Repository: https://github.com/313hemant313/capacitor-plugin-incoming-call
Package: https://www.npmjs.com/package/capacitor-plugin-incoming-call
