### ISSUE TITLE
bug: DeepLinks not redirect back to App

### ISSUE THREAD

**Issue by SheppardX** [ionic-team/capacitor#3255] opened 2020-07-14 13:37 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.2.1

  @capacitor/core: 2.2.1

  @capacitor/android: 2.2.1

  @capacitor/electron: 2.2.1

  @capacitor/ios: 2.2.1

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.2.0

  @capacitor/core 2.2.0

  @capacitor/ios 2.2.0

  @capacitor/android 2.2.0

[success] Android looking great! 👌
  Found 5 Capacitor plugins for ios:
    cordova-plugin-browsertab (0.2.0)
    cordova-plugin-compat (1.2.0)
    cordova-plugin-deeplinks (1.1.1)
    cordova-plugin-inappbrowser (4.0.0)
    ionic-plugin-deeplinks (1.0.20)
[success] iOS looking great! 👌

```

### Platform(s)
IOS

### Current Behavior
We are using cmotion/ionic-keycloak-auth.
Opens Keycloak in BrowserTab for redirecting its Using DeepLinks. 
After Login Success it should close the browser and save the token in the storage.
Android works perfect.
In Ios the DeepLink is not fired, **App.addListener('appUrlOpen' **  gets called.

i have setup all URL Scheme`s if i delete them Safari tells me about unknown URL.

### Expected Behavior
Browser Close after Successfull login

### Code Reproduction
Install cmotion/ionic-keycloak-auth and try to login with IOS 

### Other Technical Details

`npm --version` output: 6.14.6

`node --version` output: v12.11.0

`pod --version` output (iOS issues only): 1.9.3

### Additional Context
I already posted directly in cmotion github but doesnt get an answer
https://github.com/coding-motion/ionic-keycloak/issues/8

**Comment by thoechtl** [comment] 2020-07-24 13:33
We have a similar issue on iOS and Android. On iOS we can reproduce it when using stored passwords. Sometimes after auto-filling the inputs the form is automatically submitted, in this case 'appUrlOpen' is not fired for the redirected deep link. When submitting the form manually, everything works.

**Comment by telpat0298** [comment] 2020-09-18 16:21
I have a similar issue that could be related (on Android, i haven't tested on IOS). I am using keycloak too, but i wrote my own implementation because cmotion/ionic-keycloak-auth seems to be outdated and not maintained anymore. 
I'am using capacitors browser plugin and the issue i currently have is:  When opening the browser while already being logged in, keycloak is redirecting to the specified redirect url but the app doesn't open. Submitting the form manually by clicking on the login button opens the app as expected.

**Comment by telpat0298** [comment] 2020-09-20 11:36
@SheppardX @thoechtl  Are there any news on this issue? Could you solve your problem?

**Comment by SheppardX** [comment] 2020-09-20 14:58
i wa sable to get it work but i needed to change your code, 

i added the appUrlOpen for IOS devices in your service and called the functions and teverything worked fine maybe i could show u the solution and u could adept it or help me to do it correctly

**Comment by telpat0298** [comment] 2020-09-21 10:25
If u still have this issue, i can provide a fully working example using capacitors Browser and (Community)Http Plugins. I haven't tested it yet on iOS but it is working on Android and in theory it should work to on iOS too.

**Comment by thoechtl** [comment] 2020-09-21 10:36
Because deep link event 'appUrlOpen' did not fire in some special cases as described above we now use cordova-plugin-inappbrowser:
- https://github.com/apache/cordova-plugin-inappbrowser/
- https://ionicframework.com/docs/native/in-app-browser

With InAppBrowser you can clear the cache on each session, hide the URL bar, customize colors and more. You could even remove deep links completely: InAppBrowser provides the possibility to read the current URL with the 'loadstop' event, where you can process the Keycloak login redirect URL params. Since using InAppBrowser everything works like expected and setup without deep links is much simpler.

**Comment by telpat0298** [comment] 2020-09-21 11:03
True that, the setup and implementation with cordovas browser is simpler. For now, i still decided to go with capacitors Browser because the whole framework is newer/under heavy development and capacitor gets promoted by ionic in such way that i just can't imagine that they stop here (at least i hope that).

**Comment by thoechtl** [comment] 2020-09-21 11:30
We had the problems when using Capacitor Browser and deep links configured as described here: https://capacitorjs.com/docs/guides/deep-links

I'd love to switch back to Capacitor Browser when it gets more flexible (hide URL bar, ...) and the issue is fixed. The easiest way to reproduce the issue for us was using stored passwords and let them pre-fill by iOS. Not always but in many cases 'appUrlOpen' did not fire. But the issue also affects Android.

**Comment by telpat0298** [comment] 2020-09-21 12:53
Whats your deeplink configuration? I had http as scheme and on Android the deeplink didn't work when being redirected directly because of an already active keycloak session. I changed the scheme to app:// and it started working on redirect too.

**Comment by thoechtl** [comment] 2020-09-21 13:37
We used a universal https:// link. Maybe app:// works, but I can't test in anymore. 
https:// is the recommended scheme for "universal links" on iOS and "app links" on Android, so it should work in any case.

**Comment by telpat0298** [comment] 2020-09-21 13:44
Ok, got it. Hopefully they fix this issue sooner or later

**Comment by KevinToala** [comment] 2020-11-11 07:56
Hi.
I have the same problem. But with aws amplify and hosted cognito ui. In android appUrlOpen listener is working with custom url scheme. But in ios dont work and not close capacitor browser when redirect to universal link on ios. 
is there any solution that not use cordova in app browser plugin ?

**Comment by KevinToala** [comment] 2020-11-12 03:43
I found a temporary solution.

Do not use Browser.open with IOS and replace it with window.open (They are not good experience since the client exits the app and the browser opens, but it solves the problem),
For android if it works correctly Browser.open and redirection to the app once the deeplink is executed

**Comment by ep-mark** [comment] 2021-02-09 01:50
I found I could fix the problem of the appUrlOpen not firing by changing
`App.addListener('appUrlOpen', (data: AppUrlOpen) => {`
to
`Capacitor.Plugins.App.addListener('appUrlOpen', (data: AppUrlOpen) => {`

**Comment by abrahamtara** [comment] 2021-03-16 11:14
I had the same problem with `appUrlOpen` not firing and successfully used the workaround above suggested by @ep-mark 
 -- however I've just updated to Capacitor 3 and the `App.addListener('appUrlOpen', (data: AppUrlOpen) => { ` syntax is now working for me.

**Comment by damngamerz** [comment] 2021-04-27 15:46
This is a valid bug for me in android everything works fine. For iOS same problem:
Once deeplink is clicked the browser doesn't close and goes to the app. Is there a workaround I can use for now?

**Comment by SheppardX** [comment] 2021-04-27 20:51
yes, i have added App.addEventListener('open', () => {}) some like that. i
am not sure, if u want detailed information write me.

Am Di., 27. Apr. 2021 um 17:47 Uhr schrieb Saurav Singh <
***@***.***>:

**Comment by skotturi** [comment] 2021-04-28 04:38
I followed the guide: https://capacitorjs.com/docs/guides/deep-links#ios-configuration

And cannot get deep links working. Here's my app association file:
https://revillager.com/.well-known/apple-app-site-association

Xcode settings:
![image](https://user-images.githubusercontent.com/4960284/116346891-f8c17a00-a79f-11eb-901b-d612503b3d5e.png)

open `https://revillager.com/tabs/home` and nada. Website loads normally. Nothing in Xcode fires. 

Here's my app.component.ts with the recommended and the `open` event listener:
``` 
initializeApp() {
    this.platform.ready().then(() => {
      console.log(
        '[APP] Connected to database: ',
        environment.firebase.projectId
      );
      this.statusBar.styleDefault();
      SplashScreen.hide();
      this.foregroundSvc.init();
      this.analytics.init();

      App.addListener('open', (data: any) => {
        console.log('[DEEP LINK ALT], ', data);
      })
  
      App.addListener('appUrlOpen', (data: any) => {
        this.zone.run(() => {
          console.log('[DEEP LINK] caught: ', data, data.url);
          // Example url: https://revillager.com/tabs/tab2
          // slug = /tabs/tab2
          const slug = data.url.split('.com').pop();
          console.log('[DEEP LINK] slug: ', slug);
          if (slug) {
            this.router.navigateByUrl(slug);
          }
          // If no match, do nothing - let regular routing
          // logic take over
        });
      });
    });
  }
  ```

**Comment by SheppardX** [comment] 2021-04-28 12:48
Hey,

Ah yeah sorry the listener App.addListener('appUrlOpen', (data: any) => {
is the correct one, sorry i didnt know the event anymore. and i checked my
code and it looks the same.
My Browser opening looks like this te

this.browserTab.isAvailable().then(available => {
  if (available) {
    this.browserTab.openUrl(url);
  } else {
    Browser.open({ url });
  }
});

BrowserTab is the cordova-browser-tab package

private browserTab: BrowserTab,

and my fallback is of capacitor

const { Device, App, Browser } = Plugins;

this these are my npm packages

***@***.***/browser-tab"
***@***.***/core"
***@***.***/deeplinks"
***@***.***/in-app-browser"
***@***.***/native-storage"

"cordova-plugin-browsertab"
"cordova-plugin-compat"
"cordova-plugin-deeplinks"
"cordova-plugin-inappbrowser"
"cordova-plugin-ionic-webview"
"cordova-plugin-whitelist"

hope it can help ...

Am Mi., 28. Apr. 2021 um 06:39 Uhr schrieb Sante Kotturi <
***@***.***>:

**Comment by SheppardX** [comment] 2021-04-28 12:49
App.addListener('appUrlOpen', ({ url: fragment }) => {
  const decodeURI = decodeURIComponent(fragment);
  this.zone.run(() => {
....some logic
  });
});


Am Mi., 28. Apr. 2021 um 14:48 Uhr schrieb J S ***@***.***>:

**Comment by damngamerz** [comment] 2021-04-29 07:32
@SheppardX 
Im using this for oauth process.
Yes I im getting the data to the listener for ios so my universal link is setup correctly. but the in-app-browser (safari) is not closing automatically/taking me back to the app.
Is it the same for you?

**Comment by SheppardX** [comment] 2021-04-29 13:36
For me its bot opening Safari thats the Problem,
Its musst open the browsertab or the Browser of capacitor this is a
chromium Browser I think.

With the Code I postet my app is not opening Safari.



Saurav Singh ***@***.***> schrieb am Do., 29. Apr. 2021,
09:33:

**Comment by damngamerz** [comment] 2021-04-29 14:15
Okay I see.
Browser of capacitor uses Safari View Controller btw.
**https://github.com/ionic-team/capacitor-plugins/blob/main/browser/ios/Plugin/Browser.swift#L9**

I just get this opinion that universal links for ios in general has alot of problems. Hmm I would love to solve this and even contribute to the plugin. But atm I have no idea what could be going wrong.

**Comment by theresaknapp** [comment] 2021-05-18 15:03
Hi @SheppardX,
I have the same issue with ios...
Maybe u could show your modifications to get this work at the cmotion/ionic-keycloak-auth plugin?


> 
> 
> i wa sable to get it work but i needed to change your code,
> 
> i added the appUrlOpen for IOS devices in your service and called the functions and teverything worked fine maybe i could show u the solution and u could adept it or help me to do it correctly

**Comment by SheppardX** [comment] 2021-05-18 15:51
> Hi @SheppardX,
> I have the same issue with ios...
> Maybe u could show your modifications to get this work at the cmotion/ionic-keycloak-auth plugin?
> 
> > i wa sable to get it work but i needed to change your code,
> > i added the appUrlOpen for IOS devices in your service and called the functions and teverything worked fine maybe i could show u the solution and u could adept it or help me to do it correctly

yeah hier is from keycloak sevice
```
 private async beginLoginAndGetCode(options: KeycloakLoginOptions): Promise<KeycloakLoginResponse> {
    const { redirectUri, ...optionData } = options;
    const path = `${ this.appPrefix }/${ options.redirectUri }`;
    this.authService.setToken(null);
    (optionData as KeycloakLoginOptions).redirectUri = path;
    const url = this.keycloakInstance.createLoginUrl(optionData);

    this.browserTab.isAvailable().then(available => {
      if (available) {
        this.browserTab.openUrl(url);
      } else {
        Browser.open({ url });  <--- Changed to this from Plugins(capacitor), it caused problems on Redmi phones and ios
      }
    });
    
    return new Promise<KeycloakLoginResponse>((resolve, reject) => {
      const sub = this.deepLinkService
        .params()
        .subscribe(code => {
          resolve({ code, redirectUri: path });
          sub.unsubscribe();
        }, error => {
          reject(error);
          sub.unsubscribe();
        });
    });
  }
```

and in the deeplink service i added 

```
  public init() {
    this.deepLinks
      .route({}).subscribe(
      (match: DeeplinkMatch) => {
        this.extractData(match.$link);
      },
      (nomatch: DeeplinkMatch) => {
        this.extractData(nomatch.$link);
      }
    );
    this.listenToAppUrlOpen(); <-- i added this listener
  }

// this is the reason why it works on ios, the ios 
  public listenToAppUrlOpen() { 
    App.addListener('appUrlOpen', ({ url: fragment }) => {
      const decodeURI = decodeURIComponent(fragment);
      this.zone.run(() => {
        const token = this.authService.getToken();
        const deepLinkingScheme = this.infrastructurConfig?.environment?.deepLinkingScheme || 'SOME SCHEME';
        const extractedRoute = this.deconstructUrl(decodeURI);
        if (!decodeURI.includes(`${ deepLinkingScheme }://app`)) {
          if (token || extractedRoute.path.includes('SOME SPECIAL ROUTE')) {
            ***SOME ROUTING***
          }
        } else {
          this.extractData({ fragment });
        }
      });
    });
  }
```

**Comment by jcesarmobile** [comment] 2021-05-24 17:50
App plugin is now a separate package. 
Going to close since it went off-topic and there is a mix of errors here and I can't reproduce the original one.
If you still face the issue, create a new issue on https://github.com/ionic-team/capacitor-plugins/issues and provide a sample app.

For the "Browser does not close on iOS" issue, that's how iOS works, when a deep link opens your app, it opens it in the current status, so if you had a browser of other window present, it will be there. Capacitor's browser plugin offers a "close" method you can use to close the browser window, other plugins might have similar methods.
Unlike Android where the deep links launch a new intent to your app, which cancels/closes any presented intent such as the browser window.

**Closed by jcesarmobile** 2021-05-24 17:50 UTC
Labels: platform: ios

**Comment by devmanateam** [comment] 2021-10-14 16:15
> I followed the guide: https://capacitorjs.com/docs/guides/deep-links#ios-configuration
> 
> And cannot get deep links working. Here's my app association file: https://revillager.com/.well-known/apple-app-site-association
> 
> Xcode settings: ![image](https://user-images.githubusercontent.com/4960284/116346891-f8c17a00-a79f-11eb-901b-d612503b3d5e.png)
> 
> open `https://revillager.com/tabs/home` and nada. Website loads normally. Nothing in Xcode fires.
> 
> Here's my app.component.ts with the recommended and the `open` event listener:
> 
> ```
> initializeApp() {
>     this.platform.ready().then(() => {
>       console.log(
>         '[APP] Connected to database: ',
>         environment.firebase.projectId
>       );
>       this.statusBar.styleDefault();
>       SplashScreen.hide();
>       this.foregroundSvc.init();
>       this.analytics.init();
> 
>       App.addListener('open', (data: any) => {
>         console.log('[DEEP LINK ALT], ', data);
>       })
>   
>       App.addListener('appUrlOpen', (data: any) => {
>         this.zone.run(() => {
>           console.log('[DEEP LINK] caught: ', data, data.url);
>           // Example url: https://revillager.com/tabs/tab2
>           // slug = /tabs/tab2
>           const slug = data.url.split('.com').pop();
>           console.log('[DEEP LINK] slug: ', slug);
>           if (slug) {
>             this.router.navigateByUrl(slug);
>           }
>           // If no match, do nothing - let regular routing
>           // logic take over
>         });
>       });
>     });
>   }
> ```
> 
> [EDIT] The workaround above worked:
> 
> ```
> import { Plugins, Capacitor } from '@capacitor/core';
> 
> ...
>     Capacitor.Plugins.App.addListener('appUrlOpen', (data: any) => {
>       this.zone.run(() => {
>         console.log('[DEEP LINK] caught: ', data, data.url);
>         // Example url: https://revillager.com/tabs/tab2
>         // slug = /tabs/tab2
>         const slug = data.url.split('.com').pop();
>         console.log('[DEEP LINK] slug: ', slug);
>         if (slug) {
>           this.router.navigateByUrl(slug);
>         }
>         // If no match, do nothing - let regular routing
>         // logic take over
>       });
>     });
> ```
> 
> why does this work?

Hello
Did you solve this?
