### ISSUE TITLE
bug: MapKit JS doesn't work correctly in Capacitor WebKit on Android

### ISSUE THREAD

**Issue by webeditors** [ionic-team/capacitor#3568] opened 2020-09-17 15:15 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.1
  @capacitor/core: 2.4.1
  @capacitor/android: 2.4.1
  @capacitor/electron: 2.4.1
  @capacitor/ios: 2.4.1

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/android 2.4.1
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 13 Capacitor plugins for ios:
    @capacitor-community/admob (1.0.1)
    cordova-androidx-build (1.0.4)
    cordova-plugin-biometric-keychain (0.0.4)
    cordova-plugin-compat (1.2.0)
    cordova-plugin-globalization (1.11.0)
    cordova-plugin-purchase (10.2.0)
    pushy-cordova (1.0.38)
    pushy-cordova-receiver (1.0.0)
    cordova-plugin-calendar (5.1.5)
    cordova-plugin-device (1.1.2)
    cordova-plugin-geolocation (2.2.0)
    cordova-plugin-statusbar (2.1.3)
    cordova-plugin-whitelist (1.2.2)
[success] iOS looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Pinching (zooming) maps in MapKit JS on Android screws up the location and you end up at 0,0 lat,lon. 

### Expected Behavior

MapKit JS maps work find in Chrome on the same Android device, so I don't know whether this is a bug in MapKit JS or the Capacitor implementation of WebKit. I'm posting in the Apple Developer forum also to see if Apple's framework guys have seen this / know of the issue.

### Code Reproduction

MapKit JS is Apple's javascript implementation of Apple Maps. You initialise it with a token:
```
	mapkit.init({
		authorizationCallback: function(done) {
			done([YOUR TOKEN]);
		},
		language: locale
	});
```
Then throw some coordinates and markers at it, not dissimilar to Google Maps JS API.
```
	var myRegion = new mapkit.CoordinateRegion(
		new mapkit.Coordinate(lat, lon),
		new mapkit.CoordinateSpan(0.25, 0.25)
	);
	var map = new mapkit.Map('element');
	map.region = myRegion;
	var myAnnotations = [];
	var myAnnotation = new mapkit.MarkerAnnotation(new mapkit.Coordinate(lat, lon), {
		title: 'marker'
	});
	myAnnotations.push(myAnnotation);
	map.showItems(myAnnotations);
```
The reason I'm keen to go down the MapKit JS route is because of the very generous plan included for Apple developers, and personally I think they look better than Google Maps. Also, the Google Map native plugin is pretty awful and doesn't work on iOS anyway.
### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: v12.18.3

`pod --version` output (iOS issues only):

### Additional Context

Found very little out there on the web about this, but all my test users on Android are experiencing it. I did consider replacing Apple Maps on Android with the native Google Maps using cordova-plugin-googlemaps, but it quickly became clear that option was unusable (slow, jerky scrolling and breaks my design).

**Comment by Ionitron** [comment] 2020-12-02 18:14
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-01-02 00:25
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-01-02 00:25 UTC
Labels: needs reply, needs reproduction, platform: android
