### ISSUE TITLE
bug: [iOS] Crash report: '/usr/lib/swift/CordovaPlugins.framework/CordovaPlugins' (no such file)

### ISSUE THREAD

**Issue by vanessag** [ionic-team/capacitor#5561] opened 2022-04-12 21:51 UTC
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
```

### Platform(s)
iOS

### Current Behavior
Getting crash reports on iOS from App Store. Unable to reproduce the crash myself and it only seems to happen to a subset of users but looking for some help on where I could start to resolve such an issue. Here is the crash log:

```
Incident Identifier: 2DD56F5F-3DC0-4E30-910A-9AC01984279D
Hardware Model:      iPhone11,2
Process:             App [12368]
Path:                /private/var/containers/Bundle/Application/9C5656A5-7BFD-4F90-97A1-D68D333C24E3/App.app/App
AppStoreTools:       13E500
Code Type:           ARM-64 (Native)
Role:                unknown
Parent Process:      launchd [1]

Date/Time:           2022-04-10 11:00:48.5931 -0400
Launch Time:         2022-04-10 11:00:48.4679 -0400
OS Version:          iPhone OS 15.4.1 (19E258)
Release Type:        User
Baseband Version:    4.03.02
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/CordovaPlugins.framework/CordovaPlugins
Referenced from: /private/var/containers/Bundle/Application/9C5656A5-7BFD-4F90-97A1-D68D333C24E3/App.app/App
Reason: tried: '/usr/lib/swift/CordovaPlugins.framework/CordovaPlugins' (no such file), '/usr/lib/swift/CordovaPlugins.framework/CordovaPlugins' (no such file), '/private/var/containers/Bundle/Application/9C5656A5-7BFD-4F90-97A1-D68D333C24E3/App.app/Frameworks/CordovaPlugins.framework/CordovaPlugins' (could not register fairplay decryption, mremap_encrypted() => -1), '/private/var/containers/Bundle/Application/9C5656A5-7BFD-4F90-97A1-D68D333C24E3/App.app/Frameworks/CordovaPlugins.framework/CordovaPlugins' (could not register fairplay decryption, mremap_encrypted() => -1), '/private/var/containers/Bundle/Application/9C5656A5-7BFD-4F90-97A1-D68D333C24E3/App.app/Frameworks/CordovaPlugins.framework/CordovaPlugins' (could not register fairplay decryption, mremap_encrypted() => -1), '/usr/lib/swift/CordovaPlugins.framework/CordovaPlugins
(terminated at launch; ignore backtrace)

Triggered by Thread:  0


Thread 0 Crashed:
0   dyld                          	0x0000000100cb87a0 __abort_with_payload + 8
1   dyld                          	0x0000000100cbe388 abort_with_payload_wrapper_internal + 104 (terminate_with_reason.c:102)
2   dyld                          	0x0000000100cbe3bc abort_with_payload + 16 (terminate_with_reason.c:124)
3   dyld                          	0x0000000100c8e828 dyld4::halt(char const*) + 328 (DyldProcessConfig.cpp:2067)
4   dyld                          	0x0000000100c8b960 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3560 (dyldMain.cpp:0)
5   dyld                          	0x0000000100c89cc4 start + 488 (dyldMain.cpp:864)


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f662ce0   x3: 0x000000000000009f
    x4: 0x000000016f6628e0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x00000000000fb720  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x0000000100cb2e54  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f6628e0  x21: 0x000000000000009f  x22: 0x000000016f662ce0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016f663738  x26: 0x0000000000000001  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016f6628b0   lr: 0x0000000100cbe388
    sp: 0x000000016f662870   pc: 0x0000000100cb87a0        cpsr: 0x0
   esr: 0x56000080  Address size fault


Binary Images:
0x100c70000 - 0x100cc7fff dyld arm64e  <d16b72c0d6193e4892622c10a1d3066f> /usr/lib/dyld

EOF

```

### Expected Behavior
I expect no crash on iOS.

### Code Reproduction
N/A at this time.

### Other Technical Details
`npm --version` output: 8.3.1

`node --version` output: 16.14.0

`pod --version` output (iOS issues only): 1.11.2

### Additional Context
N/A at this time

**Comment by Ionitron** [comment] 2022-04-18 10:00
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-04 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-04 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
