### ISSUE TITLE
bug: [Browser][Android] closes on app minimize

### ISSUE THREAD

**Issue by JosefBredereck** [ionic-team/capacitor#6670] opened 2023-06-23 07:51 UTC
### Capacitor Version

@capacitor/app: 5.0.3
@capacitor/browser: 5.0.3
@capacitor/camera: 5.0.4
@capacitor/core: 5.0.5
@capacitor/filesystem: 5.0.4
@capacitor/keyboard: 5.0.4
@capacitor/preferences: 5.0.4
@capacitor/splashsceen": "5.0.4
@capacitor/android: 5.0.5
@capacitor/assets: 2.0.4
@capacitor/cli: 5.0.5
@capacitor/device: 5.0.4
@capacitor/ios: 5.0.5

### Platform(s)

- Android

### Current Behavior

The browser closes when the app is minimized and reopened via click on app icon.

### Expected Behavior

The browser should stay open so that the user can go to other apps and look for further information if a form requires more data or 2FA from the authenticator app.

### Code Reproduction

```ts
Browser.open({
    url: options.url,
    presentationStyle: 'fullscreen',
});
```

- Open the browser via the `open` function
- minimize the app
- open the app **by clicking on the app icon** in the launcher 
- the browser is not present

**Comment by Ionitron** [comment] 2023-06-23 08:03
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-07-09 00:07
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-07-09 00:07 UTC
Labels: platform: android, needs reply, needs reproduction

**Comment by JosefBredereck** [comment] 2023-07-09 00:08
Reopen. No further details needed
