### ISSUE TITLE
feat: Add configurable app path urls to support reuse of web app in Embedded Capacitor

### ISSUE THREAD

**Issue by carlpoole** [ionic-team/capacitor#4157] opened 2021-02-04 17:08 UTC
### Description
Capacitor currently supports setting the app url to load a web app into the web view (1 web app to 1 web view). This allows multiple different web apps to be bundled in the app and load in different web views the native app.

Capacitor should also allow the developer to set a path to load a section of the provided web app. This would allow multiple different web views in the app to use the same web app assets, and enter into different areas of the same app.

### Platform(s)
Android, iOS

### Preferred Solution
Add a configurable app path url

### Additional Context
https://github.com/ionic-team/capacitor/pull/3405

**Comment by dwieeb** [comment] 2021-02-04 18:22
Duplicate of https://github.com/ionic-team/capacitor/issues/3912

**Closed** 2021-11-17 20:31 UTC
Labels: platform: android, platform: ios, needs investigation, 8
