### ISSUE TITLE
notifyListeners method and plugin event in android plugin  not work

### ISSUE THREAD

**Issue by JoyZhou007** [ionic-team/capacitor#2806] opened 2020-04-21 01:25 UTC
In latest capacitor version ,i generate a android plugin, i try to use notifyListeners method to send message to my front page, i listened the event in page, but i did not receive the message.

    ` public class AwesomePlugin extends Plugin {
       @PluginMethod()
        public void echo(PluginCall call) {
        String value = call.getString("value");
        JSObject ret = new JSObject();
        ret.put("value", value);
        call.success(ret);
        }

    @PluginMethod()
    public void testEvent(PluginCall call) {
        bridge.triggerWindowJSEvent("myCustomEvent", "{ 'dataKey': 'dataValue' }");
        call.success();
    }

    @PluginMethod()
    public void storeContact(PluginCall call) {
        String name = call.getString("yourName", "default name");
        JSObject address = call.getObject("address", new JSObject());
        boolean isAwesome = call.getBoolean("isAwesome", false);

        if (!call.getData().has("id")) {
            call.reject("Must provide an id");
            return;
        }
        call.resolve();
    }

    @Override
    protected void handleOnStart() {
        super.handleOnStart();
        System.out.println("AwesomePlugin----start");
      JSObject ret = new JSObject();
     ret.put("value", "some value");
      notifyListeners("myPluginEvent", ret);
    }
    }`

    `@Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: ['./app.component.scss'],
    })
    export class AppComponent implements AfterViewInit,OnInit {
      title = 'ionic-capacitor-demo';

      constructor() {
        if (Capacitor.isPluginAvailable('NFC')) {
        }
        console.log(
          'AwesomePluginPlugin',
          AwesomePlugin,
          Capacitor.isPluginAvailable('AwesomePlugin')
        );
        AwesomePlugin.echo({ value: 'teet' });
        AwesomePlugin.testEvent();
        AwesomePlugin.storeContact({
          yourName: 'joy',
          address: { province: 'jiangsu' },
          isAwesome: true,
          id: 1
        });
      }
      ngOnInit(): void {
      }
  
      test(){
        AwesomePlugin.echo({ value: 'test' });
      }
  
      ngAfterViewInit(): void {

        AwesomePlugin.addListener("myPluginEvent", (info: any) => {
           console.log("myPluginEvent was fired",info);
        });
        AwesomePlugin.addListener("myCustomEvent", (info: any) => {
          console.log("myCustomEvent was fired pl",info);
        });
        window.addEventListener("myCustomEvent", function(e) {
          console.log("myCustomEvent was fired",e)
        });

      }
    }
`

**Comment by JoyZhou007** [comment] 2020-04-21 01:32
Plugin event can not be triggered

**Comment by jcesarmobile** [comment] 2020-04-21 07:28
Templates are there for a reason, don't delete them.
Also for complex issues like this one, provide a full sample app where it can be reproduced.
I can't reproduce, so closing.

I already told you this yesterday, please, provide a sample app and fill the template when reporting the issues.

**Closed by jcesarmobile** 2020-04-21 07:28 UTC
