### ISSUE TITLE
[Bug]: Custom Native iOS Code Plugin not Registered

### ISSUE THREAD

**Issue by abegehr** [ionic-team/capacitor#7409] opened 2024-04-16 17:17 UTC
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌

### Other API Details

```Shell
npm: 10.5.1
node: 20.9.0
pod: 1.14.3
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

I've followed the docs for adding custom native code to iOS: https://capacitorjs.com/docs/ios/custom-code - however the EchoPlugin is never called. 

### Expected Behavior

I would expect the EchoPlugin to load and be called. This doesn't occur even though I've followed the docs exactly.

### Project Reproduction

https://github.com/abegehr/capacitor-sample/commit/08fc81759bdaebb4e516b4f6fe03eee4e0e9dc9c

### Additional Information

After some digging, I found that plugins are registered in iOS based on the `packageClassList` parameter on the config json: https://github.com/ionic-team/capacitor/blob/5b2ab7c68db4e77b8b2961e927acc5a708ee260f/ios/Capacitor/Capacitor/CapacitorBridge.swift#L9 - however the generated config json has an empty list under `packageClassList`. I tried adding the plugin name under `plugins` on the src config file but no change. Manually adding "EchoPlugin" to `packageClassList` in the generated config json file works however the file is overwritten on the next sync.

**Comment by jcesarmobile** [comment] 2024-04-16 17:25
closing as duplicate of https://github.com/ionic-team/capacitor-docs/issues/275

**Closed by jcesarmobile** 2024-04-16 17:25 UTC
Labels: triage
