### ISSUE TITLE
feat: add Android autocomplete support

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/capacitor#5052] opened 2021-09-14 14:20 UTC
### Description

Autocomplete is not working in Ionic apps with Capacitor (see: https://github.com/ionic-team/ionic-framework/issues/23695). After investigating with the Chromium team in https://bugs.chromium.org/p/chromium/issues/detail?id=1238338, it looks like autocomplete support was removed from the Android webview in favor of developers implementing Android autofill (https://developer.android.com/guide/topics/text/autofill) in their apps.

It would be great if Capacitor could add support for Android autofill otherwise users will not be able to autofill emails, credit cards, etc in Capacitor apps.

### Platform(s)

Android

### Preferred Solution

The preferred solution is for Capacitor to implement Android autofill.

### Alternatives

The alternative is to leave this up to developers to implement on a per-application basis.

**Comment by f1ght4fun** [comment] 2021-11-11 14:42
Is there any information on this topic !?

**Comment by Odonno** [comment] 2022-01-04 16:06
Very intrigued on how this feature would look like. For our use case, not having Password 
Managers working on native Capacitor apps is a bit of a PITA.

**Comment by msadcenko** [comment] 2022-01-05 11:09
Is this feature planned? I would also be very interested in this topic, as we would also like to use the Android Autofill Framework in one of our projects.

**Comment by holygekko** [comment] 2022-01-16 20:47
I'm looking for a solution as well, please advise.

**Comment by telpat0298** [comment] 2022-03-07 12:28
Any news related to this feature?

**Comment by msadcenko** [comment] 2022-03-07 12:38
@liamdebeasi

**Comment by liamdebeasi** [comment] 2022-03-07 13:52
I do not work on the Capacitor team, so I do not have any updates regarding this Capacitor feature. Someone from the Capacitor team will update this thread when they have any news to share.

**Comment by telpat0298** [comment] 2022-07-14 13:49
Still no news?

**Comment by sujeetulli** [comment] 2022-07-18 11:31
Any good news on this issue ?

**Comment by KalyaniVenna81** [comment] 2022-07-18 11:56
Need help on this.

**Comment by viharshitha** [comment] 2022-07-18 11:57
Please help on this issue

**Comment by shanselm-ergon** [comment] 2022-08-10 08:03
Any update?

**Comment by giralte-ionic** [comment] 2022-08-10 17:48
Sorry for the lack of updates here, I lead Ionic's Native Engineering teams and I am digging in. More soon.

**Comment by really-Deep** [comment] 2022-09-06 03:41
Any updates on this?, this is an absolutely required feature for all apps, If there are any workarounds for this please let me know

**Comment by really-Deep** [comment] 2022-09-06 18:14
guys i found a work around for this, you can use @capacitor/browser plugin to open the website version of your app's login/register page inside the app only, the autofill works perfectly inside the inappbrowser, 

1= now all you need to do is to generate a unique token in ionic app and open a url in the inappbrowser with something like auth.yourwebsite.com/login?mobile_app_token=blahblah
2 = then just pass this token to your login/register apis and on backend remember the relation with the blah blah token and the auth token generated on backned after successfull login, meanwhile from your ionic application keep piniging backend for at interval of something like 5 seconds for whether the newly generated unique token is activated or not if yes then just fetch the real auth token using yuor blah blah token (one time usage token) and you are done, the auth flow is complete now you can close the inappbrowser, and continue executing post login code in the ionic app

**Comment by Artkoch** [comment] 2022-11-09 08:52
Any good news on this issue? Does only one know any workarounds?

**Comment by Artkoch** [comment] 2022-11-09 09:02
> liamdebeasi

Did you manage to find a workaround for this issue?

**Comment by really-Deep** [comment] 2022-11-09 14:19
> > liamdebeasi
> 
> Did you manage to find a workaround for this issue?

Use capacitor in app browser package
On your mobile app login screen open capacitor browser window with your website's login page and carry on login & registration their, complete whole process in the browser only and upto the end when auth is either successful or failed, in case of success copy the auth token generated to clipboard and close the window
make sure to listen to event of window closing from your mobile app's login page
once this event of window closing is fired check the contents of your clipboard, if there's a valid auth token inside that it worked, otherwise report as login/register failed. 
This solution works perfectly just make sure to clear the clipboard at the end :)
The credentials popup appears perfectly in the in-app browser tab
have fun!

**Comment by really-Deep** [comment] 2022-11-09 14:22
this whole thing is not even ionic's problem, android removed credentials autofill feature inside webviews, and the whole ionic app is inside a webview, that's why it's not working, but my above workaround gets things done

**Comment by msadcenko** [comment] 2022-11-09 14:45
> > liamdebeasi
> 
> Did you manage to find a workaround for this issue? 

We implemented it with java in the android project according to the google documentation (https://developer.android.com/guide/topics/text/autofill-services)

**Comment by really-Deep** [comment] 2022-11-09 15:07
> > > liamdebeasi
> > 
> > 
> > Did you manage to find a workaround for this issue?
> 
> We implemented it with java in the android project according to the google documentation (https://developer.android.com/guide/topics/text/autofill-services)

i did try that but for some reasons couldn't get it working
can you please share the code? it would be great help

**Comment by Artkoch** [comment] 2022-11-10 13:17
> > > liamdebeasi
> > 
> > 
> > Did you manage to find a workaround for this issue?
> 
> We implemented it with java in the android project according to the google documentation (https://developer.android.com/guide/topics/text/autofill-services)

Very interesting. Could you share snippets of your code? As far as I understand you would have to write a capacitor plugin in order to call java methods from within the app.

**Comment by shanselm-ergon** [comment] 2023-01-24 14:58
Hello there

I don't see the problem in Android or the autofill services. Autofill works fine in a normal WebView, the problem occurs only, if the web app is bundled in a capacitor app. 

I created two projects to demonstrate the problem. 

https://github.com/shanselm-ergon/autofill-android-webview-demo
This is a simple Android app, which shows an HTML file in a WebView. If an autofill service is configured in the Android settings, this form is automatically filled with the information provided by the service (see the README.md in the repo for reproduction). 

https://github.com/shanselm-ergon/autofill-capacitor-demo
This is a simple Capacitor app, which does basically the same as the example above. The embedded  web app is the same  as above. If you start to fill the form, no autofill suggestions are given (see the README.md in the repo for reproduction). 

If the autofill debug options are turned on on the device, a difference in the log outputs can be noted. I don't no why, but the service won't return any autofill data. 

In our case, it is not an option to create our own autofill service, we don't want to build up a new data base, we want to use an existing one. 

Any help would be appreciated, this would really be a nice feature.

**Comment by shanselm-ergon** [comment] 2023-02-22 07:00
Hello @giralte-ionic , any news on this topic?

**Comment by giralte-ionic** [comment] 2023-02-22 13:06
Right now we are folding this into our work on Capacitor 5 given the scope of the fix. We're still finalizing what Capacitor 5 will include and am aiming for a Q2 release.

**Comment by jcesarmobile** [comment] 2023-02-23 17:27
I can confirm that autocomplete doesn't work on Android 8 and newer, still works on Android 5.1-7. Nothing we can do about it since Google has removed it from the WebView.

On Android 8+, autocomplete has been replaced with autofill, but autofill requires a secure context to work.
So, for making autofill work on Android 8+, the apps have to use https and a custom domain, it won't work from `http://localhost`, which is the default url used by Capacitor apps, won't work from `https://localhost` neither as it's not considering localhost secure despite it's using https.

We have updated the Capacitor autofill docs to reflect that information.
https://capacitorjs.com/docs/guides/autofill-credentials

For doing that, the app developers have to add this to their Capacitor config file:

```
"server": {
    "androidScheme": "https",
    "hostname": "my-app.com" // this is an example, use your own hostname value
}
```

Note that changing the scheme and/or hostname will cause web data loss since the web data is tied to the url (localStorage, IndexedDB, etc.)

What giralte-ionic has mentioned about this being included in Capacitor 5 means that new Capacitor 5 apps will use https by default, no other change will be made in Capacitor 5 as what is need is a configuration change on the user apps to be served form a "secure context".

**Closed by jcesarmobile** 2023-02-23 17:27 UTC
Labels: platform: android, type: feature request

**Comment by abennouna** [comment] 2023-02-23 18:49
> We have updated the Capacitor autofill docs to reflect that information. https://capacitorjs.com/docs/guides/autofill-credentials
> 
> For doing that, the app developers have to add this to their Capacitor config file:
> 
> ```
> "server": {
>     "androidScheme": "https",
>     "hostname": "my-app.com" // this is an example, use your own hostname value
> }
> ```

I can confirm that the `"androidScheme": "https"` entry in Capacitor config file solves the issue. I wrongly thought that the `android:scheme` in AndroidManifest.xml was enough.

**Comment by shanselm-ergon** [comment] 2023-03-23 12:21
Thank you for your explanations, I can also confirm, that the suggested settings fix autofill on android. 

@jcesarmobile about the change to `https` as default for the Android scheme, how about iOS? Currently `https` can not be set as `iosScheme`, as described in the docs: https://capacitorjs.com/docs/config . Will this behaviour also change in Capacitor 5, or is only the Android default affected?

**Comment by telpat0298** [comment] 2023-03-23 13:42
@abennouna how did you manage to make it work on android? I did all the configurations as described in the [autofill guide](https://capacitorjs.com/docs/guides/autofill-credentials#set-capacitor-server-hostname). I published the site association file on our domain and i verified that deeplinking is working. I added the necessary config to the android manifest and the capacitor.config files. I also added the html autocomplete attributes and the appAutoFill directive (directive file and attribute) but when i click on the input field, nothing happens and also when i login it doesn't ask me if i want to save something. Are there other configurations that you have done?

**Comment by DanyloKatranGitHub** [comment] 2023-04-13 10:24
@abennouna Hello. I can't make this work on android as well. Can you help me, please?
I did everything by [autofill guide](https://capacitorjs.com/docs/guides/autofill-credentials#set-capacitor-server-hostname).
iOS works just fine but android doesn't.

My next step was to figure this out with the capacitor test app that is mentioned in this same guide:
https://github.com/ionic-enterprise/cs-autofill-credendials

And again. iOS works great. But android doesn't show me any save modals or any suggestions on the login page. Built with APK and installed on an actual device.
How can I make this work on the test app?
