### ISSUE TITLE
bug: white screen after splash screen 

### ISSUE THREAD

**Issue by Balaaj** [ionic-team/capacitor#4003] opened 2020-12-31 09:20 UTC
Bug Report

After Splash screen, white screen pops out before going to actual home screen, I also tried this one new project with other plugin installed but same thinks happened

Capacitor Version: 2.4.5

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/android 2.4.5
  @capacitor/electron not installed

**Comment by Ionitron** [comment] 2020-12-31 20:07
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ghostriderus** [comment] 2021-01-06 03:54
Have the same trouble. App work only at android 10, at all lower versions white screen with different errors.
I guess empty project will have same behavior.

**Comment by ghostriderus** [comment] 2021-01-06 21:14
> needs reproduction
Do you need app source or APK build?

**Comment by dwieeb** [comment] 2021-01-06 23:12
There's steps to follow: https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction

I'm giving this issue minimal attention because "white screen" is possibly the # 1 reported issue, but it's never a bug in Capacitor. More likely, there's a JS error somewhere in your app that's causing the entire app to fail.

**Comment by ghostriderus** [comment] 2021-01-07 21:59
I dunno whats for, this is default template without any custom line of code.
https://github.com/ghostriderus/ionic-bug-test

**Comment by dwieeb** [comment] 2021-01-07 23:00
Works for me on a Pixel 2 emulator using Android 9. Steps:

1. `npm install`
2. `npx cap add android` (because it wasn't added in your template)
3. `npm run build`
4. `npm cap sync android`
5. `npm cap open android`
6. Click run

**Comment by ghostriderus** [comment] 2021-01-08 00:40
> npm cap sync android
npm cap open android

guess you mean np**X**

nothing change
![inspect](https://user-images.githubusercontent.com/76199202/103960373-0b696200-5163-11eb-915c-5f55c9dae7d6.PNG)

**Comment by dwieeb** [comment] 2021-01-08 03:08
> guess you mean npX 

yeah sorry 

Can you give more information about the device you're using?

**Comment by ghostriderus** [comment] 2021-01-08 04:37
Looks like app work only in OS with gapps included and give error if "clean" version.
It's awful if it's true.

**Comment by ghostriderus** [comment] 2021-01-09 23:02
From docs
>  Capacitor requires an Android WebView with Chrome version 50 or later.

window.navigator.userAgent return
`Mozilla/5.0 (Linux; Android 9; Android SDK built for x86_64 Build/PSR1.180720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36
`
I need to install something extra?

**Comment by jcesarmobile** [comment] 2021-02-12 18:11
closing as the sample app was removed and dwieeb couldn't reproduce

**Closed by jcesarmobile** 2021-02-12 18:11 UTC
Labels: needs reproduction

**Comment by dukedhx** [comment] 2021-02-13 03:35
Had the same issue and was able to nail it by upgrading the [Android System Webview to the latest version] https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US)(.

**Comment by Mooiq** [comment] 2021-11-11 13:53
I had the same issue when I created a new react-app to try capacitor, It was white screen and I used npm init @capacitor/app also show me white screen.
