### ISSUE TITLE
bug: Capacitor camera plugin is not working. When Camera get open app is crashing  in android 12

### ISSUE THREAD

**Issue by shipra5676** [ionic-team/capacitor#5637] opened 2022-05-23 17:29 UTC
Ionic:

   Ionic CLI                     : 6.19.1 
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v16.10.0
   npm    : 8.5.5
   OS     : Windows 10

**Comment by Ionitron** [comment] 2022-05-23 17:47
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-08 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-08 00:05 UTC
Labels: needs reply, needs reproduction
