### ISSUE TITLE
Multipart PluginResult in Cordova plugin

### ISSUE THREAD

**Issue by panuhorsmalahti** [ionic-team/capacitor#2297] opened 2020-01-03 07:17 UTC
I'm trying to develop a Cordova plugin (which will be used in a Capacitor app), which uses a multipart PluginResult. However, on the JavaScript side when receiving a multipart PluginResult, I'm only seeing the first PluginResult message. Is this Cordova feature not supported in Capacitor?

Here's the code in Cordova, which is used to construct multipart PluginResults:
https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/PluginResult.java#L87

Here's an example of creating and sending a multipart message in a Cordova plugin:
https://github.com/don/cordova-plugin-ble-central/blob/master/src/android/SequentialCallbackContext.java#L38-L53

The original issue for adding multipart support to Cordova:
https://issues.apache.org/jira/browse/CB-7707

**Comment by jcesarmobile** [comment] 2020-01-15 16:40
do you have a simpler sample plugin that is easier to test than BLE?

Capacitor uses cordova-android internally, so should work, but the problem might be in the javascript side.

**Comment by jcesarmobile** [comment] 2020-04-20 14:19
I've created a simple plugin that uses multipart response and works the same way as on Cordova, so closing as I can't reproduce.

**Closed by jcesarmobile** 2020-04-20 14:19 UTC
