### ISSUE TITLE
bug:  Incompatible plugin Cordova Social share 

### ISSUE THREAD

**Issue by ABOURAYAN2019** [ionic-team/capacitor#5878] opened 2022-08-20 21:48 UTC
## Bug Report

Hello when i was in capacitor 3 all was OK , but When i migrate to Capcacitor 4  my App crash when i try to sahre a pdf file using Social Share , First bug that i its necissary to add this   android:exported="false" to  manifest file of  capacitor-cordova -android-plugins
 when we add this we can compile app and get APK or bundlle but  app crash when we uses function of sharing 

data about my configuration :
--------------------------------
@capacitor/ios: not installed
  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1

 "cordova-plugin-file": "^7.0.0",
    "cordova-plugin-file-opener2": "^3.0.5",
    "cordova-plugin-x-socialsharing": "^6.0.3",
 "@awesome-cordova-plugins/file": "^5.43.0",
    "@awesome-cordova-plugins/file-opener": "^5.44.0",
    "@awesome-cordova-plugins/social-sharing": "^5.44.0",

-->

```
PASTE OUTPUT HERE
```

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment] 2022-08-22 08:46
The problem is not that the plugin is not compatible with capacitor 4, the problem is that the plugin is not compatible with targeting SDK 32, it won’t work on latest cordova-android neither.
The plugin has several pull requests fixing the issue, but none has been merged.

**Closed by jcesarmobile** 2022-08-22 08:46 UTC
