### ISSUE TITLE
ionic 7 Capacitor 5 white black screen  only first time when launch on iphone not ipad  

### ISSUE THREAD

**Issue by Ibni-Amin** [ionic-team/capacitor#7034] opened 2023-10-28 23:25 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1
```

### Platform(s)

I tested it on iphone and ipad, its working fine on ipad butt not working fine on iphone real device and  simulator

### Current Behavior
I fresh installed and configured the ionic app with tabs selection. I added splash screen resources for ios installed the capacitor splash screen latest. while I launch the app on real and simulator iphone any devices, it show me white or black screen for the first time. when I kill the app and reopen it. it just feel very fast but not take time. 

### Expected Behavior
I want it doesn't show the black or white scrreen on the very first launch.

### Code Reproduction
Just install the fresh app of ionic and configured the default capacitor splash plugin with their icons and splash png. my all versions are latest

### Other Technical Details

sample app: https://github.com/Ibni-Amin/sample-app

`npm --version` output: 10.2.0

`node --version` output: v21.1.0

`pod --version` output (iOS issues only): Ignoring ffi-1.15.3 because its extensions are not built. Try: gem pristine ffi --version 1.15.3
1.11.2

### Additional Context

I test it in my deveploment project using 'cordova-res' but for debuging purpose I also tested it in ionic sample tabs app.

**Comment by LennonReid** [comment] 2023-10-29 16:16
Hello @Ibni-Amin, I recommend giving this [sample project](https://github.com/ionic-team/ionic-conference-app) a try on your iPhone. After testing it, you can compare it to your own project to identify any differences. I hope this proves helpful.

**Comment by LennonReid** [comment] 2023-10-30 12:45
You might find a solution to this problem by following the steps described in [this guide](https://www.mickpatterson.com.auremove-the-white-screen-before-the-splash-screen-in-a-flutter-app/). In my view, it seems to be a native app issue rather than a capacitor issue. I hope this helps.

**Comment by LennonReid** [comment] 2023-10-30 13:28
I've rectified my typo. @Ibni-Amin

**Comment by Ibni-Amin** [comment] 2023-10-30 13:39
> I've rectified my typo. @Ibni-Amin

Still I didn't open it  @LennonReid

**Comment by LennonReid** [comment] 2023-10-30 14:18
It's unusual, but I can easily access it at this URL: https://www.mickpatterson.com.au/blog/remove-the-white-screen-before-the-splash-screen-in-a-flutter-app

**Comment by jcesarmobile** [comment] 2023-10-30 14:44
This is a duplicate of https://github.com/ionic-team/capacitor/issues/3589

But it's not really a Capacitor bug, the problem is you are using very big splash images and some devices have problems with them.
You are using the same image for the 1x, 2x and 3x, but those should have different sizes, 3x should be 3 times the size of 1x and 2x should be two times. And I'm not telling you to make 2x and 3x bigger, but to make the 2x and 1x smaller.

cordova-res is deprecated and replaced by `@capacitor/assets`, if `@capacitor/assets` also generates 3 images with the same size, report an issue on https://github.com/ionic-team/capacitor-assets/issues

**Closed by jcesarmobile** 2023-10-30 14:44 UTC
Labels: needs reproduction

**Comment by Ibni-Amin** [comment] 2023-10-31 05:15
> It's unusual, but I can easily access it at this URL: https://www.mickpatterson.com.au/blog/remove-the-white-screen-before-the-splash-screen-in-a-flutter-app

Thanks now it opened @LennonReid

**Comment by Ibni-Amin** [comment] 2023-10-31 05:16
> This is a duplicate of #3589
> 
> But it's not really a Capacitor bug, the problem is you are using very big splash images and some devices have problems with them. You are using the same image for the 1x, 2x and 3x, but those should have different sizes, 3x should be 3 times the size of 1x and 2x should be two times. And I'm not telling you to make 2x and 3x bigger, but to make the 2x and 1x smaller.
> 
> cordova-res is deprecated and replaced by `@capacitor/assets`, if `@capacitor/assets` also generates 3 images with the same size, report an issue on https://github.com/ionic-team/capacitor-assets/issues

Thanks for telling about @capacitor/assets. Right now I am going to implement it
