### ISSUE TITLE
Make "unhandledRejection SplashScreen does not have web implementation." a warning or even disabled

### ISSUE THREAD

**Issue by bitflower** [ionic-team/capacitor#670] opened 2018-07-23 06:30 UTC
Adding `capacitor` to my plain StencilJS app and only using the splashscreen gives me this in the `npm run build` task of Stencil:

```terminal
19:56.7]  @stencil/core v0.10.7 🚐
[19:56.8]  build, app, prod mode, started ...
[19:57.0]  transpile started ...
[20:00.1]  transpile finished in 3.10 s
[20:00.1]  module map started ...
[20:00.1]  generate styles started ...
preferring built-in module 'events' over local alternative at '/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at '/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at '/Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-ui/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[20:11.4]  module map finished in 11.29 s
[20:11.4]  generate styles finished in 11.28 s
[20:11.4]  generate bundles started ...
[20:19.4]  generate bundles finished in 8.01 s
[20:19.4]  generate app files started ...
[20:21.4]  generate app files finished in 2.04 s
[20:21.5]  prerendering started ...
[20:21.5]  prerender, started: / ...

[ ERROR ]  unhandledRejection SplashScreen does not have web
           implementation.

[20:22.2]  prerender, finished: / in 695 ms
[20:22.2]  prerendered urls: 1 in 700 ms
[20:22.2]  generate service worker started ...
[20:22.4]  generate service worker finished in 247 ms

[20:22.4]  build finished in 25.64
```

This is irritating as I know that the splashscreen is a native thing.

Can we weaken this to `WARN` or even disable the alert at all?

Opinions?

**Comment by bitflower** [comment] 2018-07-23 07:06
Also shows in browser like this:

<img width="524" alt="bildschirmfoto 2018-07-23 um 09 06 10" src="https://user-images.githubusercontent.com/6666636/43062018-bef3dad4-8e57-11e8-8b1f-cf291296c95a.png">

**Comment by jcesarmobile** [comment] 2018-08-03 16:11
I can't reproduce the error when running `npm run build`, but in any case, that should be a stencil problem as it's the one that builds.

About the uncaught promise, you should run it like this:
```
try {
    await SplashScreen.hide();
  } catch(error) {
    console.error(error);
  }
```
The catch should show the error now.

There was a problem with SplashScreen plugin not returning the promises, but was fixed in latest release
https://github.com/ionic-team/capacitor/pull/652

**Closed by jcesarmobile** 2018-08-03 16:11 UTC

**Comment by bitflower** [comment] 2018-08-03 19:35
Thanks, works
