### ISSUE TITLE
bug: status-bar stay black on Android 13

### ISSUE THREAD

**Issue by rbalet** [ionic-team/capacitor#5920] opened 2022-09-15 10:01 UTC
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 4.2.0    
  @capacitor/core: 4.2.0   
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0    

Installed Dependencies:    

  @capacitor/cli: 4.2.0    
  @capacitor/core: 4.2.0   
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0    

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Platform(s)

Pixel 4a - Android 13

### Current Behavior

The status bar stay black

![image](https://user-images.githubusercontent.com/44493964/190373445-ac2f832c-1d2b-42a9-832c-07b13483b90d.png)

### Expected Behavior

Having a light gray transparent  background 

![image](https://user-images.githubusercontent.com/44493964/190373756-e9971293-71a7-458f-9a40-1000d9784d65.png)

### Code Reproduction

Inside `app.component.ts`
```typescript
    await StatusBar.setStyle({ style: Style.Dark })

    if (Capacitor.getPlatform() === 'android') {
      await StatusBar.setOverlaysWebView({ overlay: true })
      await StatusBar.setBackgroundColor({ color: '#0000004d' })
    }
```

### Other Technical Details

`npm --version` output: 8.19.0

`node --version` output: 14.18.1

`pod --version` output (iOS issues only):

**Comment by Ionitron** [comment] 2022-09-15 10:07
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-10-01 00:11
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-01 00:11 UTC
Labels: platform: android, needs reply, needs reproduction
