### ISSUE TITLE
Device token is invalid in hex form

### ISSUE THREAD

**Issue by pedramp20** [ionic-team/capacitor#4442] opened 2021-04-07 00:56 UTC
I am trying to implement push notification WITHOUT firebase using AWS Pinpoint. Everything works perfectly on Android. However, on iOS, the returned device token in registration listener seems to be an FCM token.

```
    PushNotifications.addListener('registration',
      (token: PushNotificationToken) => {
        alert('Push registration success, token: ' + token.value);
      }
    );
```

When, I use the above token to send and APNS push from serverside using pinpoint. I get the following error:

```
{
    "MessageResponse": {
        "ApplicationId": "ca74a9f1f38b404bbf1bcxxxxxxxxx",
        "RequestId": "e40b4f5b-ff14-4fa5-b55a-48fxxxxxxxx",
        "Result": {
            "frLnRmyb5Ez1urKLMtPg7q:APA91bEnw_LjZehJpZqwqh55wspWhBUqXgUOpU1jcyMrxSyAr2YrJZM0FZQLb_jekB5qBPba_P9KZBu3wxMtRwAhhcVQe3JSDTTpvqGldFSWj2H67vyvxXXxxxXXxxxXXXxxXXX": {
                "DeliveryStatus": "PERMANENT_FAILURE",
                "StatusCode": 410,
                "StatusMessage": "{\"errorMessage\":\"Unregistered or expired token\",\"channelType\":\"APNS\",\"pushProviderStatusCode\":\"0\",\"pushProviderError\":\"Device token is invalid in hex form\",\"pushProviderResponse\":\"hexBinary needs to be even-length: frLnRmyb5Ez1urKLMtPg7q:APA91bEnw_LjZehJpZqwqh55wspWhBUqXgUOpU1jcyMrxSyAr2YrJZM0FZQLb_jekB5qBPba_P9KZBu3wxMtRwAhhcVQe3JSDTTpvqGldFSWj2H67vyvxXXxxxXXxxxXXXxxXXX\"}"
            }
        }
    }
}
```
I appreciate any help

**Comment by jcesarmobile** [comment] 2021-04-07 08:09
Can you provide a sample app? 
capacitor uses APNS on iOS, so unless you have installed some fcm plugin or custom code that might be interfering, getting fcm token is impossible

**Comment by Ionitron** [comment] 2021-04-07 08:09
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-05-08 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-05-08 00:01 UTC
Labels: needs reply, needs reproduction
