### ISSUE TITLE
[Bug]: @capacitor/google-maps "Error calling method create on plugin CapacitorGoogleMaps: No method found." on iOS

### ISSUE THREAD

**Issue by frederikheld** [ionic-team/capacitor#7503] opened 2024-06-05 23:41 UTC
### Capacitor Version

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

### Other API Details

```Shell
% npm --version
10.5.0
% node --version
v20.11.0
% pod --version
1.15.2
```

I'm using `@capacitor/google-maps@6.0.0-rc.0` because the `@latest` version won't install without `--legacy-peer-deps`.

EDIT: I tried it with `@latest` which is `5.4.1` and got the same issue.

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

When running the app from Xcode on a physical iPhone or in the emultator, I get the following error:

```
⚡️  To Native ->  CapacitorGoogleMaps create 6519669
⚡️  Error calling method create on plugin CapacitorGoogleMaps: No method found.
⚡️  Ensure plugin method exists and uses @objc in its declaration, and has been defined
```

The `<capacitor-google-map>` element stays empty.

The same setup works well on Android.

### Expected Behavior

No error, map renders

### Project Reproduction

//

**Comment by frederikheld** [comment] 2024-06-06 00:27
I was able to pin the error down to the `await GoogleMap.create({ })` function. All lines after that function won't be executed.

**Comment by shipley-dcc** [comment] 2024-06-15 10:24
Here is a sample app that reproduces the issue on Android: [Maps Sample App](https://github.com/shipley-dcc/maps-sample)

`ionic serve` and run it in a browser. Works no problem.
`ionic capacitor run android --open` builds fine, but when I run it on my Android phone I get an error during start-up of the app:

```
NativePlugin com.capacitorjs.plugins.googlemaps.CapacitorGoogleMapsPlugin failed to load com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible
at com.getcapacitor.PluginHandle.load(PluginHandle.java:107)
at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
at com.getcapacitor.Bridge.registerPlugin(Bridge.java:684)
at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:640)
at com.getcapacitor.Bridge.<init>(Bridge.java:221)
at com.getcapacitor.Bridge.<init>(Unknown Source:0)
at com.getcapacitor.Bridge$Builder.create(Bridge.java:1559)
at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:48)
at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:42)
at android.app.Activity.performCreate(Activity.java:8305)
at android.app.Activity.performCreate(Activity.java:8284)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7932)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by jcesarmobile** [comment] 2024-06-17 15:44
This issue is about iOS, if you are having an issue on Android then it's a different problem, please, create a new issue on https://github.com/ionic-team/capacitor-google-maps/issues

**Comment by frederikheld** [comment] 2024-06-18 22:45
Thanks for the reply. I moved away from Google Maps to an OSM based solution. After trying 3 different GM-based approaches I learned that Google is just too incompetent to create a performant solution. I had to do the whole native stuff only because the JS SDK doesn't perform well with many markers added. The OSM SDK just renders them with less issues than anything I encountered with Google Maps. Sometimes I wonder how Google is still such a big company because so often they don't care to deliver decent SDKs :-(

Where do you see my API key?

**Comment by jcesarmobile** [comment] 2024-06-19 08:29
There was a comment from an user having a different problem on Android and they provided a sample app with their API key on it, my comment was addressed to them, but they have removed the comment from here.

You must have seen it since you added a reaction to it before it was deleted.

They have reported the issue on https://github.com/ionic-team/capacitor-google-maps/issues, but then they closed it because they found out they were putting the API key in the wrong place.

Since you have moved away from Google Maps I guess you won't be providing a sample app for the issue, so I'm going to close.
If you are still interested in providing a sample app, please, create a new issue with the sample app in the google maps plugin repository
https://github.com/ionic-team/capacitor-google-maps/issues

**Closed by jcesarmobile** 2024-06-19 08:29 UTC
Labels: needs reproduction

**Comment by juanpe1103** [comment] 2024-06-24 21:19
Hello! I have the same problem. Can you give me your solution please?
Thanks
@frederikheld

**Comment by frederikheld** [comment] 2024-06-24 21:44
My solution was to move away from every plugin that is related to Google Maps. Not only do the plugins have a lot of bugs, the underlying Google SDK is shit. Google does not seem to care for performance.

I moved to MapTiler and the beauty of this solution is that the Web SDK is performant enough to work on Android/iOS WebView. So I don't need to fiddle around with solutions that put native elements behind my WebView, each with it's own bugs and quirks. This saves me a lot of headache because now I can implement the app once and it actually works everywhere.

**Comment by juanpe1103** [comment] 2024-06-24 21:47
Thanks a lot for the response! I already finish my app so this is a not a solution for me.
Nice to meet you!

**Comment by frederikheld** [comment] 2024-06-24 21:49
Fingers crossed that you get it working ;-) It took me several weeks to find a proper maps solution but rendering several hundred pins on a map is the major feature of my app, so I had to find something that works. It's still difficult, but r/n the bottleneck is not the map but the data handling behind it, which is a huge improvement :-D Nice to meet you too :-)

**Comment by juanpe1103** [comment] 2024-06-24 22:05
I wish u luck!
