### ISSUE TITLE
bug: unextended-module-overlay.yaml generated as invalid file

### ISSUE THREAD

**Issue by craftedsystems** [ionic-team/capacitor#5202] opened 2021-11-03 17:09 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

Installed Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

* iOS

### Current Behavior

* generated `unextended-module-overlay.yaml` file is a JSON with a missing `,` — not a YAML as its extension

```yaml
{
  'version': 0,
  'case-sensitive': 'false',
  'roots': [{
    'type': 'directory',
    'name': "/Users/[removed-path]/ios/DerivedData/77BA122C-41F0-457D-B22A-AC25BF19B52D/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework/Modules"
    'contents': [{
      'type': 'file',
      'name': "module.modulemap",
      'external-contents': "/Users/[removed-path]/ios/DerivedData/77BA122C-41F0-457D-B22A-AC25BF19B52D/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Capacitor.build/unextended-module.modulemap",
    }]
  }]
}
```

### Expected Behavior

* should be a valid YAML (or a valid JSON with correct extension)

**Comment by Ionitron** [comment] 2021-11-03 17:16
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-11-19 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-11-19 00:03 UTC
Labels: platform: ios, needs reply, needs reproduction
