### ISSUE TITLE
[Feature]: native camera resolution, rotation and max size settings

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#7401] opened 2024-04-15 09:38 UTC
### Description

Natively include settings to 

- directly have non rotated pictures without javascript manipulation
- don't upload pictures of 200Mo on recent phones, making app crash
- being able to set a max size of pictures taken with capacitor camera

### Platforms

- [X] iOS
- [X] Android
- [X] Web

### Request or proposed solution

When some users use he capacitor camera, the browser sometimes crashes due to very high resolution (due to modern phones cameras).
We are now handling the pictures compression / resize with javascript, but browser hardly manipulate pictures of 200Mo in a mobile webview, causing app crashes.

### Alternatives

Javascript alternatives are not good, because mobile web browsers most of the time don't have enough RAM to handle this kind of pictures.

**Comment by jcesarmobile** [comment] 2024-04-15 12:23
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/2080

Would be better to copy all the information in that issue since the information there is empty and could be closed because of that.

BTW, the camera plugin has `correctOrientation` option to have non rotated pictures that works on Android and iOS.
Also has `width` and `height` options for the pixel size, I guess you mean file size, would be good if you add that information to the ticket.

**Closed by jcesarmobile** 2024-04-15 12:23 UTC
Labels: triage

**Comment by Aarbel** [comment] 2024-04-15 17:56
Thanks @jcesarmobile, modifications added on the ticket ✅
