### ISSUE TITLE
[Bug]: Capacitor is not injected on loaded URLs specified in allowNavigation on android when webview supports the document start script feature

### ISSUE THREAD

**Issue by matthiasschwarz** [ionic-team/capacitor#7467] opened 2024-05-16 16:00 UTC
### Capacitor Version

6.0.0

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Capacitor is not injected into the html file, so android plugins don't work.

### Expected Behavior

Although allowNavigation shouldn't be used in production i would expect that these websites loaded into the webview to be able to access android plugins.

### Project Reproduction

Not necessary - is obvious looking at the source code

### Additional Information

Issue related to: #7440 and #7454

Commit that causes the issue: f5446d8fcf4d43476c35c1ad669c43458ccfc6b8

Possible fix: https://github.com/ionic-team/capacitor/issues/7454#issuecomment-2101339879

**Comment by jcesarmobile** [comment] 2024-05-20 07:59
closing as duplicate of https://github.com/ionic-team/capacitor/issues/7454

**Closed by jcesarmobile** 2024-05-20 07:59 UTC
Labels: triage
