### ISSUE TITLE
Unable to debug typescript code in Android

### ISSUE THREAD

**Issue by antcasq** [ionic-team/capacitor#715] opened 2018-08-09 11:22 UTC
I've created a project with Ionic 4, added Capacitor to it and run the app in Android Studio. Them using Chrome "chrome://inspect/#devices" I tried to debug the app but only the transpiled javascript code is available. I cannot see my typescript code an put breakpoints in it...

```
Ionic:
   ionic (Ionic CLI)          : 4.0.5 (/home/xpto/sw/nodejs/versions/node-v8.11.3-linux-x64/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Capacitor:
![no-typescript](https://user-images.githubusercontent.com/5212564/43895819-78085878-9bce-11e8-85dd-e72596395ba3.png)

   capacitor (Capacitor CLI) : 1.0.0-beta.4
   @capacitor/core           : 1.0.0-beta.4

System:
   NodeJS : v8.11.3 (/home/xpto/sw/nodejs/versions/node-v8.11.3-linux-x64/bin/node)
   npm    : 5.6.0
   OS     : Linux 4.15
```
I don't know if it's an Ionic or a Capacitor bug, so if I've creating it in the wrong project just let me know and I will create it in the other one :)

Thanks

**Comment by jcesarmobile** [comment] 2018-08-17 11:06
I've been able to debug it by using `ionic serve --source-map` command and then configuring capacitor to load the served url like this

```
"server": {
    "url": "http://192.168.1.128:8100/"
}
```

Doing that the source maps were available and I could see the typescript files and could set breakpoints.

When doing `npx cap copy` I suppose the source maps don't work as they are copied to a different location and the app loads the copied files and not the original ones, while when serving them, they are the original files in the original location.

Anyway, this is not a real Capacitor issue, going to close the issue. 

We can continue with the conversation on the forum entry you created, so if people find better ways or in case some VS extension appears that helps debugging it can be tracked there. 
https://forum.getcapacitor.com/t/debug-android-app/89

**Closed by jcesarmobile** 2018-08-17 11:06 UTC

**Comment by ryaa** [comment] 2018-12-19 11:55
> When doing `npx cap copy` I suppose the source maps don't work as they are copied to a different location and the app loads the copied files and not the original ones, while when serving them, they are the original files in the original location.

The problem is that when you're remote debugging on an android device, Chrome debugger cannot access the source map file on the device. This is a known limitation.

The solution/fix is to include the source map inline. Prior to ionic 4 this was possible by setting the appropriate config to make the webpack to add the source maps inline (see https://stackoverflow.com/questions/41413082/ionic-2-application-running-on-the-android-device-cant-be-debugged/41414355#41414355)

However, since ionic cli v4 uses angular cli for building this option is not available since angular cli does not support this.
There are two options here (in addition to configuring capacitor to load the sources from the external url as mentioned above):
1) make the build with --eval-source-map param
To do so i change scripts in package.json to have the below
```
"build": "ng build --eval-source-map"
```
and then run **npm run build**. However this still has one limitation. The angular cli will build the source maps using eval param (see https://webpack.js.org/configuration/devtool/) which might not be what you are looking for. For more details please see https://github.com/angular/angular-cli/issues/12434
2) To see the true original ts file while debugging on Android I patched angular cli source code (i have @angular/cli version 7.0.0) to use inline-source-maps webpack option. To do so I changed one line in **node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js** file
```
sourcemaps = 'eval';
```
to
```
sourcemaps = 'inline-source-map';
```
After that running **npm run build** did the trick.

> Anyway, this is not a real Capacitor issue, going to close the issue.

Yes. This is not a capacitor issue.

> We can continue with the conversation on the forum entry you created, so if people find better ways or in case some VS extension appears that helps debugging it can be tracked there.
> https://forum.getcapacitor.com/t/debug-android-app/89

I added my findings there as well.

**Comment by ryaa** [comment] 2019-01-30 04:40
Would it be possible to support customizing cordova build, to enable debugging on Android devices, by building it in to the ionic schematics which can be found here: https://github.com/ionic-team/angular-toolkit/blob/master/builders/cordova-build/index.ts

More details can be found here https://github.com/angular/angular-cli/issues/13543#issuecomment-458663189

**Comment by ryaa** [comment] 2019-02-06 06:54
To whom it may concern, here is the approach I implemented to enable debugging with source maps support on Android devices

* install ngx-build-plus by running `npx ng add ngx-build-plus`   
This will install the required npm package and update angular.json as required
For more details please see https://github.com/manfredsteyer/ngx-build-plus
* create new file `build-customization-plugin.js` in the project root directory and add the below content in this file   
```
var merge = require('webpack-merge');

exports.default = {
    config: function (cfg) {
        const strategy = merge.strategy({
            'devtool': 'replace',
        });

        return strategy(cfg, {
            devtool: 'inline-source-map'
        });
    }
}
```   
* run `ng build --eval-source-map --plugin ~build-customization-plugin.js` from the root directory to build the project with source maps to debug on Android devices   

This is a better approach then changing angular/cli source :)

**Comment by yogeshpatil143** [comment] 2019-05-03 07:05
Just add below code in package.json file. 

 "config": {
    "ionic_bundler": "webpack",
    "ionic_source_map_type": "#inline-source-map"
  }

It's working 100% fine.

**Comment by alxpsr** [comment] 2019-10-08 06:32
> It's working 100% fine.
not working for me :(

**Comment by alxpsr** [comment] 2019-10-08 08:42
Workaround for me:

```
/* 
For enable TypeScript in Chrome with remoteDevices, you should edit webpackConfig.
- set devtool to inline-source-map
- set isEval to true

I use this patch before cordova build and after

my package.json script section:

"scripts": {
    "build:android": "npm run patch:android-sourcemap:rollup && ionic cordova build android && npm run patch:android-sourcemap:revert",
    "patch:android-sourcemap:rollup": "node ./utils/android-source-map.patch.js",
    "patch:android-sourcemap:revert": "node ./utils/android-source-map.patch.js true"
  }
*/

//== android-source-map.patch.js
const fs = require('fs');
const PATH_TO_WEBPACK_CONFIG = '../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js';

fs.readFile(PATH_TO_WEBPACK_CONFIG, 'utf8', function (err, data) {
    const cliArgs = process && process.argv ? process.argv.slice(2) : [];
    
    const isRevert = cliArgs[0] || false;
    const operationType = isRevert ? 'REVERT' : 'ROLLUP';

    let targetText = { eval: null, devtool: null };
    let replacedText = { eval: null, devtool: null };
    
    if (err) {
        return console.log(err);
    }
    
    console.log('\x1b[33m%s\x1b[0m', `SOURCE-MAP-PATCH START TYPE::${operationType}`);

    if (isRevert) {
        targetText.devtool = /devtool: "inline-source-map"/;
        targetText.eval = /isEval = true/;
        replacedText.eval = 'isEval = false'
        replacedText.devtool = "devtool: isEval ? 'eval' : false"
    } else {
        targetText.devtool = /devtool: isEval \? 'eval' : false/;
        targetText.eval = /isEval = false/;
        replacedText.eval = 'isEval = true';
        replacedText.devtool = 'devtool: "inline-source-map"';
    }

    var result = data.replace(targetText.eval, replacedText.eval);
    result = result.replace(targetText.devtool, replacedText.devtool);

    fs.writeFile(PATH_TO_WEBPACK_CONFIG, result, 'utf8', function (err) {
        if (err) return console.log(err);
        console.log('\x1b[33m%s\x1b[0m', `SOURCE-MAP-PATCH TYPE::${operationType} SUCCESS`);
    });
});

```
