### ISSUE TITLE
Crashes on some devices during Google Play test

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#747] opened 2018-08-17 15:32 UTC
## Version

1.0.0-beta.4

## Issue

Crashes during Google Play test on the following device right after the splashscreen

![image](https://user-images.githubusercontent.com/4460311/44274828-df747b80-a24b-11e8-9dde-e79981526f46.png)

```
FATAL EXCEPTION: ControllerMessenger
Process: app.zelenka, PID: 17313
java.lang.IllegalArgumentException: Real screen element corresponding to shadow element ElementDescription{className=android.webkit.WebView, resourceName=app.zelenka:id/webview, contentDescription=Web View, componentType=WEBVIEW, inputType=NONE, isWebViewElement=false} not found.
	at com.google.android.apps.mtaas.crawler.obfuscated.ai.x.a(PatternCompiler.java:22)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.transformAction(RemotePlatform.java:73)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:21)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:84)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lionelkermesse** [comment] 2018-08-24 00:28
Hello please did you found the issue of this bugs. I have the same bug and don't know how to tackle

**Comment by jcesarmobile** [comment] 2018-08-24 06:09
Hard to know with so little information

**Comment by lionelkermesse** [comment] 2018-08-24 08:01
Here is my bug report:
Fatal Exception: java.lang.IllegalArgumentException
Real screen element corresponding to shadow element ElementDescription{className=android.support.v7.widget.AppCompatTextView, resourceName=com.singhymnals:id/hymn_view, contentDescription=, componentType=TEXT_VIEW, inputType=NONE, isWebViewElement=false} not found

Any idea?

**Comment by T-travis** [comment] 2018-08-24 20:44
Same issue here.

Issue: java.lang.IllegalArgumentException: Real screen element corresponding to shadow element ElementDescription{className=android.support.v7.widget.AppCompatTextView, resourceName=com.semble_calculator:id/textView, contentDescription=, componentType=TEXT_VIEW, inputType=NONE, isWebViewElement=false} not found.
FATAL EXCEPTION: ControllerMessenger
Process: com.semble_calculator, PID: 13062
java.lang.IllegalArgumentException: Real screen element corresponding to shadow element ElementDescription{className=android.support.v7.widget.AppCompatTextView, resourceName=com.semble_calculator:id/textView, contentDescription=, componentType=TEXT_VIEW, inputType=NONE, isWebViewElement=false} not found.
	at com.google.android.apps.mtaas.crawler.obfuscated.ai.x.a(PatternCompiler.java:22)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.transformAction(RemotePlatform.java:76)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:21)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

any ideas on a fix or what is causing this?

**Comment by bermudaparty** [comment] 2018-08-24 22:31
I got here from google. Am having the exact same issue on an app that is not related to this project here. Seems indeed to be a Google Play issue.

I released an update today. When I saw that it was causing this error, I re-released the previous apk (with new version code) to halt the "faulty" update. Lo and behold this time arround the pre release test found crashes on almost all test devices, even though it is exactly the same version as I had previously released without issue.

**Comment by T-travis** [comment] 2018-08-24 23:33
@bermudaparty  thanks!  I re-released the apk with a new version code and no more error.

**Comment by ArmorDarks** [comment] 2018-08-25 08:13
I have a feeling that it is an issue with Google Play crawler.

A few days ago we released a built without any changes, with Capactior beta.6, and suddenly there were no more crashes:

![image](https://user-images.githubusercontent.com/4460311/44616413-d5f4a000-a857-11e8-9cb7-c39a6585284f.png)

I will continue monitoring issue.

**Comment by anonym24** [comment] 2018-08-25 11:31
I don't use any framework for android app developing (capactior, reactjs, xamarin,..), just java android developer here
I uploaded APK already 3 times and still test fails for all devices with this annoying error

**Comment by anonym24** [comment] 2018-08-25 16:02
those Indian developers in Google really messed up with Google Console product

I can't even change my Google Console interface language anymore

I set only English on https://myaccount.google.com/language

But Google Console is still in Russian 

Before https://myaccount.google.com/language was working for Google Console (you set one some language it effects all Google Products - sites)

But now it's not working

![screenshot_3](https://user-images.githubusercontent.com/8851301/44620228-47a10e00-a899-11e8-9852-59deb4c7b277.png)

**Comment by anonym24** [comment] 2018-08-25 20:42
https://issuetracker.google.com/issues/113164874

**Comment by snijsure** [comment] 2018-08-27 18:17
Wow @anonym24 that is classic comment `those Indian developers in Google really did something wrong with Google Console product` what have got against `Indian Developers`, huh?

**Comment by anonym24** [comment] 2018-08-27 18:52
@snijsure just a joke, don't take it seriously :) (it's not just me, many people jokes about it)

**Comment by kensodemann** [comment] 2018-08-27 18:59
@anonym24 - joke or not, it violates the CoC. Please refrain from making such comments here in the future, even as a joke. 

https://github.com/ionic-team/capacitor/blob/master/CODE_OF_CONDUCT.md

I have updated your comment to remove the offending phrase. Please review to make sure the constructive portions of your comment are still intact and preserve the intended meaning.

**Comment by jcesarmobile** [comment] 2018-09-06 19:29
Closing as it looks like it was some problem on Google Play as people not using Capacitor also faced the same problem with the same error messages.

**Closed by jcesarmobile** 2018-09-06 19:29 UTC

**Comment by QumberAbbas** [comment] 2019-02-01 12:19
A am facing this issue

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handleTakeScreenshot(RemotePlatform.java:53)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$500(RemotePlatform.java:89)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:12)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by DURK** [comment] 2020-03-31 06:51
@QumberAbbas I have the same issue, both on Pixel devices. I've watched the video of Google's "monkey test", and the error occurs right after taking a photo and returning to the app:
![image](https://user-images.githubusercontent.com/605056/77995468-1f5a7a80-732c-11ea-86ec-0a66c86b236a.png)

I'm using Capacitor 2.0.0-beta1.

So far, I've not been able to reproduce this issue on an emulator in Android Studio, or an actual device.
