### ISSUE TITLE
[Feature]:  Capacitor Video Recorder

### ISSUE THREAD

**Issue by Bauss9** [ionic-team/capacitor#7333] opened 2024-03-12 15:46 UTC
### Description

I would love if capacitor did a plugin for video recording

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

There are no solid capacitor video recording plugins, as a matter of fact there are basically none.

I managed to build a working plugin with Swift and connected it to Capacitor, I can open it through my ionic app on ios and record the video and preview it as well. I only ran into issues when trying to pass the data from the swift cap plugin to my inoic app, my knowledge is limited here and I tried everything I just couldnt get the file there. If someone were willing to help me with this we can publish this plugin, it's a very solid one for recording videos.

**Comment by jcesarmobile** [comment] 2024-03-12 15:49
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/229

**Closed by jcesarmobile** 2024-03-12 15:49 UTC
Labels: triage
