### ISSUE TITLE
bug: HTML5 video element refuses to play on all devices after update although it works on native Safari and Chrome

### ISSUE THREAD

**Issue by simaxme** [ionic-team/capacitor#6622] opened 2023-05-29 12:20 UTC
### Capacitor Version
💊   Capacitor Doctor  💊 

```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
- iOS / iPadOS

### Current Behavior
HTML5 Video-Element from assets folder or blob url refuses to play.

### Expected Behavior
HTML5 Video-Element should play normally 

### Code Reproduction

```html
      <video [muted]="true"
             loop="loop"
             muted
             playsinline
             [attr.webkit-playsinline]="'webkit-playsinline'"
             [controls]="false"
             #video
             src="{{content}}"
      ></video>
```
Here, every possible attribute is used for making the video play automatically and in a loop. This does completely work in the Safari and Chrome browser. 

### Other Technical Details

This issue is only happening due to using a local url or blob url. In the given example, content does refer to the simple string "/assets/quickstart/example.mp4". The safari dev-tools show that the video is being loaded in different chunks:
![image](https://github.com/ionic-team/capacitor/assets/59118411/c15ca2b4-c3b8-42a6-99d7-90fe7535e0b5)

In chrome dev-tools simply many errors are sent while trying to load the mp4:
![image](https://github.com/ionic-team/capacitor/assets/59118411/ac675a80-fabe-4d79-89f6-01b4e7cf3bea)

Here, two of the video elements are loaded in chunks, but neither of them does play. When manually activating the controls and pressing the play button, the timeline on the button is very bugged and always extends the duration of the video. 
![IMG_4C0CB494F4DA-1](https://github.com/ionic-team/capacitor/assets/59118411/67bd0f49-d937-424e-a201-8006a107e088)

One interesting fact: Videos do play in this way as soon as they refer to a complete existing HTTP-URL from an other server. It looks like it has to do something with the `capacitor://` url.

Local addresses are working normally when using images. Only video tags are not loading.

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

This did happen at first after updating to Capacitor v5 from v4. It seems some mechanics changed here.

At least when using the local urls, it has to do something with the range requests: https://github.com/ionic-team/capacitor/issues/1343

Hope someone can help me 😓

**Comment by JaHollTV** [comment] 2023-05-29 13:44
Hey there,
i have same problem with a simmilar usecase. Only with iOS

**Comment by simaxme** [comment] 2023-05-29 14:33
Hello, i have to give one small update: Android now works by using a workaround
- i was able to manually fetch the video and provide the video tag with a reference to the corresponding blob. This did work perfectly. 
- I found this solution from the issue: https://github.com/ionic-team/capacitor/pull/5956

iOS still does not work with this solution. Although i have preloaded the video, safari keeps trying to load the blob in small parts:
![image](https://github.com/ionic-team/capacitor/assets/59118411/ce0cfbad-cacd-45a0-ae2a-f565f2d82f05)

**Comment by simaxme** [comment] 2023-05-29 14:59
Next comment: I also got it working in iOS and iPadOS:

While createObjectURL() causes Safari trying to load the video in chunks, dataURLs are not causing this weird issue and are working perfectly when using videos. The only downside on this part is the data limitation of around 2Mb. 

In our application this is not important as the videos reach a maximum of 3sec playtime.

Although for me this issue is fixed, i will keep it open as these described things are complete workaround that will not work in any case.

**Comment by Ionitron** [comment] 2023-05-30 08:03
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jansgescheit** [comment] 2023-06-05 08:22
I am running in similar failure. 

```bash 
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/core: 4.8.0
  @capacitor/cli: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/android: 4.8.0

[success] iOS looking great! 👌
```

In my case i download the Videos with `fetch` and create with `URL.createObjectURL` a object url. This works fine on a desktop browser. But i discovered problems on iOS.

The create Object URL's are prefixt with `blob:capacitor://localhost/` the HTMLVideo Player shows a blank Video

if i remove `capacitor://` to `blob:localhost/6310f486-da40-423d-95b9-c96253a00555` and the video plays as expected.

**Comment by Miguelmcanabal** [comment] 2023-06-08 16:19
Im managing the same issue on Capacitor 5 in a 10th gen iPad with iOS 16.4.


```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4
  @capacitor/android: 5.0.4

``` 

I cannot reproduce videos from Angular assets, video player fails and it crashes the iPad gallery! After trying to play a video, if i try to open a video in iOS gallery, it wont play either. Its a weird behaviour to be honest.

**Comment by digaus** [comment] 2023-06-22 09:54
Same issue here. Workaround is to use the Filesystem and Uri but thats not a great solution.

I could provide a demo project if needed?

**Comment by jansgescheit** [comment] 2023-06-22 09:56
> Same issue here. Workaround is to use the Filesystem and Uri but thats not a great solution.
> 
> I could provide a demo project if needed?

I had also tried that way, but that had not worked either. Would be nice if you could share a few lines of code.

**Comment by Ionitron** [comment] 2023-06-26 14:29
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-07-12 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-07-12 00:06 UTC
Labels: needs reply, needs reproduction

**Comment by simaxme** [comment] 2023-07-12 07:05
Wow, you have the best bot ever . This Issue is real and needs to be adressed!

**Comment by jansgescheit** [comment] 2023-07-12 07:12
> Wow, you have the best bot ever . This Issue is real and needs to be adressed!

I thought so too

**Comment by simaxme** [comment] 2023-07-12 10:45
If there is no response in this week, i will open a new issue with the same problem. The problem is obvious and needs to be adressed. It would be nice if someone could respond to avoid this unnecessary work.
