### ISSUE TITLE
ArgumentError - Illformed requirement `"$IOS_FIREBASE_ANALYTICS_VERSION"` for ios Capacitor ionic 5 

### ISSUE THREAD

**Issue by madhusudhanv255** [ionic-team/capacitor#3517] opened 2020-09-07 08:24 UTC
### Capacitor Version

```

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/android 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/electron not installed
```

### Platform(s)

Ios

### Current Behavior

After updating the pods 
Step 1: update the pods
Step 2: ionic build this command works
Step 3: npx cap sync ios shows the error

### Other Technical Details

`npm --version` output: 6.4.1

`node --version` output: 10.13.0

`pod --version` output (iOS issues only):1.10.0.beta.2

### Additional Context

ArgumentError - Illformed requirement `"$IOS_FIREBASE_ANALYTICS_VERSION"`
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/dependency.rb:101:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification/consumer.rb:223:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification/consumer.rb:223:in `block in dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification/consumer.rb:222:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification/consumer.rb:222:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification/consumer.rb:222:in `dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification.rb:403:in `block in dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification.rb:402:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/specification.rb:402:in `dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/validator.rb:44:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `validator_for_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/abstract_external_source.rb:186:in `validate_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `store_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:967:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by XtreZz** [comment] 2020-09-07 09:34
I got the same problem, had to revert the plugin to 2.3.0

**Comment by madhusudhanv255** [comment] 2020-09-07 10:42
It did not work

**Comment by laituanmanh32** [comment] 2020-09-08 04:45
+1 . I got same error after update npm package (delete package-lock.json then reinstall)

**Comment by madhusudhanv255** [comment] 2020-09-08 07:06
Thanks but mine worked with npm i capacitor-firebase-analytics after removing the firebase analytics

**Comment by dwieeb** [comment] 2020-09-08 15:34
Use the new Capacitor Community Firebase Analytics plugin: https://github.com/capacitor-community/firebase-analytics

**Comment by jcesarmobile** [comment] 2020-09-08 16:10
Just because there is a capacitor plugin doesn't mean this shouldn't be fixed.
The problem is the CLI is not replacing the IOS_FIREBASE_ANALYTICS_VERSION variable with the default value and causing pod install to fail. This can affect other plugins that might not have an alternative Capacitor plugin

**Comment by laituanmanh32** [comment] 2020-09-09 03:30
This workaround works for me.
edit and change `s.dependency 'Firebase/Analytics', '$IOS_FIREBASE_ANALYTICS_VERSION'` to `s.dependency 'Firebase/Analytics', '6.31.0'` in file `ios/capacitor-cordovar-ios-plugins/CordovaPluginsStatic.podspec`. then call `pod install` in `ios/App`.
![Screen Shot 2020-09-09 at 10 30 00](https://user-images.githubusercontent.com/11975819/92551115-6b203100-f287-11ea-9482-511f8c18ae76.png)

**Comment by jcesarmobile** [comment] 2020-09-11 10:20
closing since the linked PR was merged and the fix was released in 2.4.1

**Closed by jcesarmobile** 2020-09-11 10:20 UTC
Labels: platform: ios

**Comment by haikyuu** [comment] 2020-10-23 16:37
Note that you need to update `@capacitor/cli` to `2.4.1`.

Thanks @jcesarmobile

**Comment by pixolopr** [comment] 2021-05-17 21:24
Pods are not accepting Versions in that form.

**Solution that worked for me:**

`edit vi ./node_modules/cordova-plugin-firebase-analytics/plugin.xml`

Replace pod name with
`<pod name="Firebase/Analytics" spec="~> 7.0.0" />`
