### ISSUE TITLE
Share Plugin - Capacitor Core 2.4.3

### ISSUE THREAD

**Issue by dhwalin** [ionic-team/capacitor#3868] opened 2020-11-26 08:19 UTC
Code to Share:
```
import { Plugins } from '@capacitor/core';
const { Share } = Plugins;


Share.share({
            title:'Share',
            text:'',
            url:result.uri,
            dialogTitle:'Share'
          })

// result.uri is local image url saved in cache folder.
```
After updating to Capacitor Core 2.4.3, Only text is passing in "url", not image. In url if I pass remote url, it is getting shared. If I pass local image url, it goes blank. Console Below.

```
/Capacitor/Filesystem: File '/data/user/0/com.dhwalin.bjpframes/cache/khykaez1.jpg' saved!
D/OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x7af6748480
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 70545263, pluginId: Share, methodName: share
V/Capacitor: callback: 70545263, pluginId: Share, methodName: share, methodData: {"title":"Share","text":"","url":"file:\/\/\/data\/user\/0\/com.dhwalin.bjpframes\/cache\/khykaez1.jpg","dialogTitle":"Share"}
D/Capacitor: App paused
D/ViewRootImpl@840390f[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@5ea42a[MainActivity]
    getNavigationBarColor() -855310
I/Capacitor/Console: File: http://192.168.1.148:3000/static/js/main.chunk.js - Line 3196 - Msg: ShareResult [object Object]
W/System: A resource failed to call close. 
```

Please guide if something wrong. Please update if something buggy.

**Comment by jcesarmobile** [comment] 2020-11-26 17:44
Can you provide a sample app?

**Comment by dhwalin** [comment] 2020-11-27 03:54
Guess what. Tested in Android Version 5.0.1 , 9 & 10.

Only Version 10 giving this error, I meant not sending the image. Rest is working fine.

**Comment by jcesarmobile** [comment] 2020-11-30 14:31
I still can't reproduce, even on Android 10, can you provide a sample app?

**Comment by efunneko** [comment] 2020-12-23 14:40
I am still investigating this on my side, but I have seen a similar issue on iOS where the local file is not shared. For me, sharing appears to work fine when sending email or a text message, but when I try to share to Slack I don't get the image. I didn't see any error. Other apps on my phone can successfully share images to Slack, so I know that can work.

**Comment by jcesarmobile** [comment] 2020-12-23 14:44
there is another issue open for that iOS problem https://github.com/ionic-team/capacitor-plugins/issues/156

closing this one since I can't reproduce and the reporter didn't provide the requested information

**Closed** 2020-12-23 14:44 UTC

**Comment by dhwalin** [comment] 2021-01-20 06:03
I could not provide requested information because I did not have enough sources. 

I came to know that on Sharing Image URL on WhatsApp it says "Cannot send empty message"

but If I select Gmail then image or video is getting attached and working perfectly.
