### ISSUE TITLE
Status Bar reappearing after calling hide() function

### ISSUE THREAD

**Issue by RobotBroer** [ionic-team/capacitor#1887] opened 2019-08-20 16:46 UTC
Description of the problem:
Status Bar reappears after calling hide() function on platform.ready(). The status bar reappears after selecting an input field for example. Expected behaviour is that the status bar will remain hidden until the Show() function is called. 

Affected platform
- [ X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ X] macOS
- [ ] linux

Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/Users/work/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.801.1
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.1.0
   @capacitor/core           : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/Library/Android/sdk)
   NodeJS            : v11.7.0 (/usr/local/Cellar/node/11.7.0/bin/node)
   npm               : 6.10.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by jcesarmobile** [comment] 2019-08-23 16:23
Not sure what do you mean by "selecting an input field", but I can't reproduce by focusing on an ion-input field.
Can you provide more information or a sample app if possible?

**Comment by RobotBroer** [comment] 2019-08-24 12:24
Hi, 

I have started a basic Ionic Capacitor app to illustrate. In this case the status bar does not even hide initially and only when pulling down on the info bar does the status bar hide. 

Afterwards when selecting the input the keyboard and status bar will appear, and after closing the keyboard the status bar won't return to a hidden state. 

https://github.com/RobotBroer/Ionic-Capacitor-StatusBar

Emulator: Nexus 5X API 25

<img width="311" alt="Status Bar Is Hidden" src="https://user-images.githubusercontent.com/44133396/63637240-ae0e6700-c67a-11e9-8b0e-6c8e91c21664.png">

<img width="309" alt="Input is selected" src="https://user-images.githubusercontent.com/44133396/63637241-ae0e6700-c67a-11e9-8d98-b352eac72d36.png">

<img width="304" alt="Status bar is now visable" src="https://user-images.githubusercontent.com/44133396/63637242-aea6fd80-c67a-11e9-9631-5f527388ce60.png">

**Comment by lincolnthree** [comment] 2019-08-29 13:16
For what it's worth, I am also experiencing this behavior on Android 9 on a Pixel 2 XL with any app I deploy. Sometimes the status bar does not hide at all. Sometimes it hides a few seconds to minutes after calling .hide(), sometimes it reappears.

**Comment by jcesarmobile** [comment] 2020-01-21 15:19
I've been able to reproduce in a few devices with your sample app

**Comment by lincolnthree** [comment] 2020-01-21 15:37
I seem to be able to reproduce this the most simply by swiping up to "activate" the Android controls at the bottom of the screen.

**Comment by GabDug** [comment] 2021-02-24 12:35
Does anybody have a workaround for this issue? Thanks!

**Comment by lincolnthree** [comment] 2021-02-25 16:13
Set an interval that hides the status bar every few seconds. It's really not ideal and bad for CPU, but seems to be the only "official" workaround: https://github.com/ionic-team/capacitor-plugins/issues/79

**Comment by jcesarmobile** [comment] 2021-05-25 15:24
since status-bar is now a separate plugin, closing in favor of https://github.com/ionic-team/capacitor-plugins/issues/79

**Closed by jcesarmobile** 2021-05-25 15:24 UTC
Labels: bug, platform: android
