### ISSUE TITLE
Classnotfound Exception occurs while migrating cordova to capacitor

### ISSUE THREAD

**Issue by tamsel12** [ionic-team/capacitor#4854] opened 2021-07-20 16:41 UTC
I have used the latest capacitor version 3 only. I have followed the steps given in the document 
**Platform : Android** 
**Crash Log**
2021-07-20 22:09:26.884 12097-12097/app.youareaceo.mobile D/Capacitor: Starting BridgeActivity
2021-07-20 22:09:26.904 12097-12097/app.youareaceo.mobile W/System.err: java.lang.ClassNotFoundException: com.instabug.cordova.plugin.IBGPlugin
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.Class.classForName(Native Method)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.Class.forName(Class.java:453)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.Class.forName(Class.java:378)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at org.apache.cordova.PluginManager.init(PluginManager.java:86)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:58)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at com.getcapacitor.Bridge$Builder.create(Bridge.java:1262)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:73)
2021-07-20 22:09:26.905 12097-12097/app.youareaceo.mobile W/System.err:     at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:111)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.Activity.performStart(Activity.java:7348)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3145)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.os.Looper.loop(Looper.java:214)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7078)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
2021-07-20 22:09:26.906 12097-12097/app.youareaceo.mobile W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2021-07-20 22:09:26.907 12097-12097/app.youareaceo.mobile W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.cordova.plugin.IBGPlugin" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/app.youareaceo.mobile-QwQnGg9RAfu70RqCu_wRTg==/base.apk"],nativeLibraryDirectories=[/data/app/app.youareaceo.mobile-QwQnGg9RAfu70RqCu_wRTg==/lib/arm64, /data/app/app.youareaceo.mobile-QwQnGg9RAfu70RqCu_wRTg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2021-07-20 22:09:26.907 12097-12097/app.youareaceo.mobile W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2021-07-20 22:09:26.907 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2021-07-20 22:09:26.907 12097-12097/app.youareaceo.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2021-07-20 22:09:26.907 12097-12097/app.youareaceo.mobile W/System.err: 	... 25 more
2021-07-20 22:09:26.908 12097-12097/app.youareaceo.mobile I/System.out: Error adding plugin com.instabug.cordova.plugin.IBGPlugin.
2021-07-20 22:09:26.908 12097-12097/app.youareaceo.mobile D/AndroidRuntime: Shutting down VM

2021-07-20 22:09:26.910 12097-12097/app.youareaceo.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.youareaceo.mobile, PID: 12097
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:58)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1262)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:73)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:111)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
        at android.app.Activity.performStart(Activity.java:7348)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3145)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2021-07-20 22:09:27.934 12097-12177/app.youareaceo.mobile W/GraphRequest: Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls. Visit https://developers.facebook.com/docs/android/getting-started#client-token to learn how to implement this change.
2021-07-20 22:09:27.949 12097-12177/app.youareaceo.mobile I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-07-20 22:09:27.950 12097-12177/app.youareaceo.mobile I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-07-20 22:09:28.478 12097-12179/app.youareaceo.mobile W/uareaceo.mobil: Unknown chunk type '200'.

**Comment by Ionitron** [comment] 2021-07-20 17:34
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-05 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-05 00:02 UTC
Labels: needs reply, needs reproduction
