### ISSUE TITLE
bug: Invalid `Podfile` file: cannot load such file (using Yarn Plug'n'Play)

### ISSUE THREAD

**Issue by bitjson** [ionic-team/capacitor#6138] opened 2022-12-02 07:34 UTC
### Capacitor Version

```
❯ yarn cap doctor    
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.0
  @capacitor/core: 4.6.0
  @capacitor/android: 4.6.0
  @capacitor/ios: 4.6.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

```
❯ yarn capacitor add ios
✔ Adding native Xcode project in ios in 17.36ms
✔ add in 17.60ms
✔ Copying web assets from build to ios/App/App/public in 22.55ms
✔ Creating capacitor.config.json in ios/App/App in 317.42μs
✔ copy ios in 75.66ms
✔ Updating iOS plugins in 6.75ms
[info] Found 4 Capacitor plugins for ios:
       @capacitor/app@4.1.1
       @capacitor/haptics@4.1.0
       @capacitor/keyboard@4.1.0
       @capacitor/status-bar@4.1.0
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] 
        [!] Invalid `Podfile` file: cannot load such file --
        [...]/node_modules/@capacitor/ios/scripts/pods_helpers.
        
        #  from [...]/ios/App/Podfile:1
        #  -------------------------------------------
        >  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
        #
        #  -------------------------------------------
```

The issue is that `./ios/App/Podfile` includes the line:

`require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'`

But yarn PNP doesn't include `node_modules`.

### Expected Behavior

Not sure what the best solution is, but in my case, changing the line:

`require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'`

to:

`require_relative '../../.yarn/unplugged/@capacitor-ios-virtual-35271fc2f7/node_modules/@capacitor/ios/scripts/pods_helpers'`

works. (Though I expect the `@capacitor-ios-virtual-35271fc2f7` must be changed after each update?)

### Code Reproduction

```
ionic start blank blank --type=react --capacitor
cd blank
yarn set version latest
yarn capacitor add ios
```

### Other Technical Details

`yarn --version` output: 3.3.0

`node --version` output: v19.2.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by jcesarmobile** [comment] 2022-12-05 10:43
closing as duplicate of https://github.com/ionic-team/capacitor/issues/5903

**Closed by jcesarmobile** 2022-12-05 10:43 UTC
Labels: platform: ios
