### ISSUE TITLE
bug: Android 13, Push notification not working.

### ISSUE THREAD

**Issue by sujeet-matchps** [ionic-team/capacitor#6259] opened 2023-01-27 11:10 UTC
As Android 13 has introduced new permission,
For reference find the below link.
https://yggr.medium.com/exploring-android-13-notification-runtime-permission-6e198bb5ae3b

Current behavior.
If we don't add any permissions in the manifest file, Then the Push notification setting will be disabled.

**Comment by jcesarmobile** [comment] 2023-01-27 11:31
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1135

**Closed by jcesarmobile** 2023-01-27 11:31 UTC
Labels: triage
