### ISSUE TITLE
bug: minifyEnabled true in build.gradle on Capacitor 4 causes App Crash

### ISSUE THREAD

**Issue by jordodev** [ionic-team/capacitor#6189] opened 2022-12-23 04:08 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```
### Platform(s)

Android

### Current Behavior

When Building a Signed App (APK or Bundle) **Release** version using the following settings in `build.gradle`, and attempting to start on an Android device, the App crashes and/or shows white screen.

```
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
### Expected Behavior

The default `proguard-rules.pro` should be updated to include `-keep` rules pertaining to Capacitor v4, and thus allow the **Release** version to deploy to an Android device without crashing.

### Other Technical Details

`npm --version` output: 9.1.2

`node --version` output: v16.16.0

`pod --version` output (iOS issues only):

### Additional Context

Have tried setting `proguard-rules.pro` file to various suggestions in following links, to no avail.

[https://github.com/ionic-team/capacitor/blob/main/android/capacitor/proguard-rules.pro](url)
[https://github.com/ionic-team/capacitor/issues/739](url)

Noticed the comments only refer to capacitor v2 and v3. What should the `-keep` rules be for a Capacitor 4 App?

Thanks

**Comment by Ionitron** [comment] 2023-01-03 20:14
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-19 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-19 00:05 UTC
Labels: platform: android, needs reply, needs reproduction
