### ISSUE TITLE
bug: Persistent Cookie Storage Issue in iOS App

### ISSUE THREAD

**Issue by Nasmar** [ionic-team/capacitor#6715] opened 2023-07-06 09:30 UTC
### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 5.1.1    
  @capacitor/core: 5.1.1   
  @capacitor/android: 5.1.1
  @capacitor/ios: 5.1.1    

Installed Dependencies:    

  @capacitor/cli: 5.0.4    
  @capacitor/core: 5.0.4   
  @capacitor/ios: 5.0.4    
  @capacitor/android: 5.0.4
```

### Platform(s)

iOS

### Current Behavior

We cannot achieve persistent storage of HttpOnly cookies in our iOS app using CapacitorCookies and CapacitorHttp plugins.

Our app successfully retains cookies and functions as intended under normal usage. However, when the app is terminated and restarted, it fails to remember the cookies, resulting in users being prompted to log in again. 

Note that our Android app functions correctly, retaining the cookies as intended.

We are utilizing the native Capacitor Http module to make API calls.

### Expected Behavior

When shutting the iOS app down, we expect that the app can retain the http only cookie to use our cookie authentication

### Code Reproduction

```
import { CapacitorHttp, type HttpResponse } from '@capacitor/core';
const options = {
        url: url,
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        data: JSON.stringify(postdata),
        options: {
          webFetchExtra: {
            credentials: "include",
          },
        }
      };

const response: HttpResponse = await CapacitorHttp.post(options);
const resultAsJson = await JSON.parse(JSON.stringify(response)).data
```

capacitor.config.ts:
```
  appId: 'com.XXXX.app',
  appName: 'XXXX',
  webDir: 'dist',
  plugins: {
    CapacitorHttp: {
      enabled: true // This provides native http service support via patching fetch and XMLHttpRequest
    },
    CapacitorCookies: {
      enabled: true
    }
  }
```

Info.plist:
```
	<key>WKAppBoundDomains</key>
	<array>
        <string>XXXX.XXXX.XX</string>
	<string>XXXX.XXXX.XX/api/</string>
	<string>https://XXXX.XXXX.XX/</string>
        <string>https://XXXX.XXXX.XX/api/</string>
	</array>
```

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: 20.3.0

`pod --version` output (iOS issues only): 1.12.1

**Comment by markemer** [comment] 2023-07-12 18:50
Can you upload a sample project that we can use to test?

**Comment by generator85** [comment] 2023-07-25 23:01
I seem to be having the same issue

**Comment by jcesarmobile** [comment] 2023-07-31 12:53
closing due to the lack of reproduction

**Closed by jcesarmobile** 2023-07-31 12:53 UTC
Labels: platform: ios, needs reproduction

**Comment by Nasmar** [comment] 2023-08-08 12:44
I will make a sample project on it. Should i repost or is it fine here?

**Comment by robmarshall** [comment] 2023-08-15 20:18
I am also having this issue.

**Comment by Nasmar** [comment] 2023-08-18 13:09
@robmarshall look here for the solution [https://github.com/ionic-team/capacitor/issues/6809]
