### ISSUE TITLE
bug: Capacitor Google Maps Plugin - Map not showing on Android devices

### ISSUE THREAD

**Issue by JanVilimek** [ionic-team/capacitor#5888] opened 2022-08-29 23:09 UTC
### Capacitor Version

```
  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/core: 4.1.0
```

### Platform(s)

Android (physical and virtual)

### Current Behavior

When app is installed on the devices (real and virtual), Map is not showing. 
_(Yes I have transparent backgrounds)_ - android debug console shows error (copied on the bottom)

In webview (localhost), it is displaying correctly and works like charm, problem is appearing only when I try it on real/virtual device.

**GoogleCertificatesRslt: not allowed.** 
I am not sure if it is problem with ionic, or google services.
I have also found this: https://issuetracker.google.com/issues/228091313

### Expected Behavior

Map displaying correctly on android devices and without error in debug console.

### Code Reproduction

Just create new app, with the capacitor-google-maps-plugin and try to deploy to your physical/virtual device. 
REACT+capacitor

app->page->content->maps

### Other Technical Details

`npm --version` output: 8.12.1

`node --version` output: v16.17.0

`pod --version` output (iOS issues only):

### Additional Context

Log from android debug console: 
```
W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 7
I/SnapshotHandler: Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#, using defaults.
W/MobStoreFlagStore: Unable to update local snapshot for com.google.android.libraries.consentverifier#, may result in stale flags.
    java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=...
    at ahv.s(:com.google.android.gms.dynamite_mapsdynamite@222615084@22.26.15 (150700-0):3)
        at ahv.get(:com.google.android.gms.dynamite_mapsdynamite@222615084@22.26.15 (150700-0):2)
        at ajf.g(:com.google.android.gms.dynamite_mapsdynamite@222615084@22.26.15 (150700-0):2)
        at xx.d(:com.google.android.gms.dynamite_mapsdynamite@222615084@22.26.15 (150700-0):1)
        at xz.run(:com.google.android.gms.dynamite_mapsdynamite@222615084@22.26.15 (150700-0):0)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Important part:
```
GoogleCertificatesRslt: not allowed: pkg=..., sha256=[], etc.
```

**Comment by Ionitron** [comment] 2022-09-01 16:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-17 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-17 00:06 UTC
Labels: platform: android, needs reply, needs reproduction
