### ISSUE TITLE
FileReader API not firing

### ISSUE THREAD

**Issue by ronwondaal** [ionic-team/capacitor#1564] opened 2019-05-23 19:59 UTC
Description of the problem:
In my project I'm trying to read and convert a Blob downloaded from the dropbox api to a text string. When building my project using Cordova, the FileReader fires onload and onprogress events. When building using Capacitor, filereader does not fire any events at all.

Affected platform
- [ ] Android
- [x ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ x] macOS
- [ ] linux

Other information:
As suggested in other bug reports, I tried wrapping the FileReader in 
```
platform.ready().then(_ => {
/// perform file reading 
})
```
and in 
```
zone.run(() => {
/// perform file reading
})
```
None helped. Cordova has no issues reading the file.

When I use
```
var text = await (new Response(response.fileBlob)).text();
```
to read the file blob, it does work.

Capacitor version: 1.0.0-beta.24

**Comment by jcesarmobile** [comment] 2019-05-23 20:20
Can you provide a sample project?

**Comment by ronwondaal** [comment] 2019-05-23 20:40
Okay, so in the sample project it works. Guess the problem lies somewhere in the use of dropbox combined with promises and the filereader. I shall investigate further and when I find something I'll let you know!

**Comment by ronwondaal** [comment] 2019-05-23 22:42
@jcesarmobile, apparently the problem is in the cordova-plugin-file plugin.
https://github.com/ronwondaal/capacitorFileReaderTest

**Comment by jcesarmobile** [comment] 2019-05-24 00:06
But on the plugin itself or only when using it with Capacitor?

**Comment by ronwondaal** [comment] 2019-05-24 06:46
When using it with capacitor it prevents FileRead from firing events.

**Comment by jcesarmobile** [comment] 2019-05-24 15:05
Looks like some problem with zone.js, but not sure why it only affects Capacitor and not Cordova

If I log the FileReader object I get this results:

Capacitor with Ionic `{"__zone_symbol__originalInstance":{"_readyState":1,"_error":null,"_result":null,"_progress":0,"_localURL":"","_realReader":{}}}`

Cordova with Ionic `{"_readyState":1,"_error":null,"_result":null,"_progress":0,"_localURL":"","_realReader":{"__zone_symbol__originalInstance":{}}}`

Capacitor without framework `{"_readyState":1,"_error":null,"_result":null,"_progress":0,"_localURL":"","_realReader":{}}`

Cordova without framework `{"_readyState":1,"_error":null,"_result":null,"_progress":0,"_localURL":"","_realReader":{}}`

The `onload` is being added to the `FileReader` object, but the problem is, when using Capacitor with zone.js, the `FileReader` object is put inside the `"__zone_symbol__originalInstance"` object and the `onload`is set to the object containing the `"__zone_symbol__originalInstance"` and not on the real `FileReader`.

If we take zone.js (angular/ionic) out of the equation it works fine.

**Comment by jcesarmobile** [comment] 2019-05-24 16:16
Found this ionic-native issue https://github.com/ionic-team/ionic-native/issues/505

Now I know why this isn't an issue on Cordova, `polyfills.js` is loaded there before `cordova.js`, but in Capacitor `cordova.js` is injected into the webview before `polyfills.js`.
I've tried injecting `polyfills.js` too but that doesn't seem to work.

**Comment by ronwondaal** [comment] 2019-05-24 20:03
Yeah, I took a look at the angular zone.js file, and it seems the have done some bug fixes regarding cordova. The also have zone.js patch for cordova here: https://github.com/angular/zone.js/blob/master/dist/zone-patch-cordova.js
But I'm not that skilled a programmer to be able to figure out what they are doing to patch the stuff :(

**Comment by digaus** [comment] 2019-08-01 23:18
@jcesarmobile 
Is someone looking for a fix? Currently also running into this issue while switching from cordova to capacitor...

**Comment by dansterrett** [comment] 2019-09-18 16:00
> Found this ionic-native issue [ionic-team/ionic-native#505](https://github.com/ionic-team/ionic-native/issues/505)
> 
> Now I know why this isn't an issue on Cordova, `polyfills.js` is loaded there before `cordova.js`, but in Capacitor `cordova.js` is injected into the webview before `polyfills.js`.
> I've tried injecting `polyfills.js` too but that doesn't seem to work.

@jcesarmobile, thanks for the tip. Loading `polyfills.js` before `cordova.js` fixed the issue for me.

**Comment by tripodsgames** [comment] 2019-10-04 02:22
You can try this.

```
export function getFileReader(): FileReader {
    const fileReader = new FileReader();
    const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
    return zoneOriginalInstance || fileReader;
}
...
let newInstance = getFileReader();
```

**Comment by neerajsaxena0711** [comment] 2019-11-27 11:43
I can confirm @tripodsgames 's solution is working for me.

**Comment by tgangso** [comment] 2019-12-11 23:48
Thank you for the workaround @tripodsgames saved me.

Maybe time for an official fix?

**Comment by lampham2505** [comment] 2019-12-20 09:31
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

This solution's working for me too, but after using it, I can see that the UI's loading slowly than before(it's now display the text "back" then change to the icon). Does anyone else get that bad peformance or just me?

**Comment by supinder-cf** [comment] 2020-01-09 09:02
@tripodsgames 's solution worked like charm. Thank you so much.

**Comment by jcesarmobile** [comment] 2020-01-09 11:23
closing since this is a zone.js bug related to changing cordova-plugin-file's `FileReader`.
If you are affected by this, use the workaround proposed by tripodsgames

**Closed by jcesarmobile** 2020-01-09 11:23 UTC

**Comment by casper5822** [comment] 2020-05-04 15:22
I have this problem with Ionic V4 and capacitor without the cordova-plugin-file, use just a FileReader object and the problem is still present. 

If you use the hack, it works but there is a very bad performance, i made tests in a galaxy s7 edge.

I'm using the last zone.js version.

I understood that this problem was patched below, is it right?

The cordova filereader was patched as the zone.js you can see here:
https://github.com/angular/zone.js/issues/868

Also in cordova.js there was a patch, here: 

https://github.com/angular/zone.js/pull/879


Is there any other solution? 

Best regards.

**Comment by SamTomashi** [comment] 2020-05-25 00:58
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

I have been hitting my head for almost a week now over this issue using Ionic 6, and finally this solution came to the rescue.

**Comment by mauryaak15** [comment] 2020-06-13 16:00
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

You saved my life bro, thanks a ton

**Comment by robingenz** [comment] 2020-06-15 16:03
I've found another solution.
Import `zone.js/dist/zone-patch-cordova` into `/src/polyfills.ts`.
This is what my `/src/polyfills.ts` looks like:
```
import 'zone.js/dist/zone'; // Included with Angular CLI.
import 'zone.js/dist/zone-patch-cordova';
```

**Comment by ahmad-alkhatib** [comment] 2020-06-21 18:41
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

You saved someone's else life here as well, Thanks man I waste a lot of time on this.

**Comment by skapeyi** [comment] 2020-07-23 19:57
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

Where do I put this?

**Comment by deborahjames** [comment] 2020-07-24 13:09
@tripodsgames  Thanks!!! 

Adding a few more lines - FileReader issue in android SOLVED

export function getFileReader(): FileReader {
  const fileReader = new FileReader();
  const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
  return zoneOriginalInstance || fileReader;
}


onSelectFile(event) {
    if (event.target.files && event.target.files[0]) {
      let newInstance = getFileReader();
      newInstance.readAsDataURL(event.target.files[0]); 
      newInstance.onload = (imgsrc) => {               
        let url = (imgsrc.target as FileReader).result; 
        console.log(url)
      }
    }
  }

**Comment by moridianmess** [comment] 2020-08-11 10:05
If you have plugins that rely on FileReader working correctly, using snippets from the getFileReader() code mentioned above, I have a solution

Add to app.module.ts:
```
export class FileReaderA extends window.FileReader {
	constructor() {
		super();
		const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
		return zoneOriginalInstance || this;
	}
}

window.FileReader = FileReaderA;
```

or add the above code to another file and import the file, not the class.

This is a hack, ideally it would be nice to be able to control the order in which scripts are imported. As the fix I've always used in a cordova based project is to change the order of polyfills.js and cordova.js in the index.html file.

**Comment by mtozzi** [comment] 2020-10-02 14:28
> private getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

Worked for me after days searching for a solution! Tks @tripodsgames !

**Comment by rajanwalt** [comment] 2020-10-24 14:07
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

It's working to me. Thanks a lot!

**Comment by rohitsethi007** [comment] 2020-11-09 14:46
> If you have plugins that rely on FileReader working correctly, using snippets from the getFileReader() code mentioned above, I have a solution
> 
> Add to app.module.ts:
> 
> ```
> export class FileReaderA extends window.FileReader {
> 	constructor() {
> 		super();
> 		const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
> 		return zoneOriginalInstance || this;
> 	}
> }
> 
> window.FileReader = FileReaderA;
> ```
> 
> or add the above code to another file and import the file, not the class.
> 
> This is a hack but it means that when calling `new FileReader()` all the events work. Ideally it would be nice to be able to control the order in which scripts are imported. As the fix I've always used in a cordova based project is to change the order of polyfills.js and cordova.js in the index.html file.

Thanks to you and @tripodsgames the fix saved me, took me 4 days to finally come across this solution and it works!

**Comment by nicolas-gameffecive** [comment] 2020-12-06 11:41
Thanks @tripodsgames 
Your solution saved my day

**Comment by davidst2017** [comment] 2021-01-01 14:47
BTW if you the change detection takes to long call  detectChanges() from ChangeDetecotrRef 

FYI import ChangeDetectorRef from "@angular/core"

**Comment by patriciopage** [comment] 2021-01-24 16:41
> You can try this.
> 
> ```
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

Thanks @tripodsgames , this is IT.

**Comment by Bforsyth1234** [comment] 2021-04-18 13:59
@tripodsgames Thank you!!!!

Dear google, please rank this higher in search results..... k thanks.

**Comment by fromage9747** [comment] 2021-04-24 08:23
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }

Thank you so much!  I had been fighting with this issue for days.  This resolved it!  Thank you thank you thank you!

**Comment by markbeij** [comment] 2021-07-15 09:29
> If you have plugins that rely on FileReader working correctly, using snippets from the getFileReader() code mentioned above, I have a solution
> 
> Add to app.module.ts:
> 
> ```
> export class FileReaderA extends window.FileReader {
> 	constructor() {
> 		super();
> 		const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
> 		return zoneOriginalInstance || this;
> 	}
> }
> 
> window.FileReader = FileReaderA;
> ```
> 
> or add the above code to another file and import the file, not the class.
> 
> This is a hack but it means that when calling `new FileReader()` all the events work. Ideally it would be nice to be able to control the order in which scripts are imported. As the fix I've always used in a cordova based project is to change the order of polyfills.js and cordova.js in the index.html file.

Thank you very much, worked for me!

**Comment by PhilippKorn** [comment] 2021-09-09 19:29
> You can try this.
> 
> ```ts
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

im a nooby, where to I have to put that code? Into the FileReader file or my ts file?

**Comment by moridianmess** [comment] 2021-09-09 19:48
> > You can try this.
> > ```ts
> > export function getFileReader(): FileReader {
> >     const fileReader = new FileReader();
> >     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
> >     return zoneOriginalInstance || fileReader;
> > }
> > ...
> > let newInstance = getFileReader();
> > ```
> 
> im a nooby, where to I have to put that code? Into the FileReader file or my ts file?

Using that method you need to use that function instead of using FileReader normally. If you use the method I [suggested](https://github.com/ionic-team/capacitor/issues/1564#issuecomment-671854779)  it means you can use it normally.

**Comment by luqmanyusof** [comment] 2021-12-01 06:35
I endup using "Capacitor/Filesystem" library to read the file that was written by using "@ionic-native/file/ngx".

**Comment by mherbert71** [comment] 2022-01-06 21:18
> If you have plugins that rely on FileReader working correctly, using snippets from the getFileReader() code mentioned above, I have a solution
> 
> Add to app.module.ts:
> 
> ```
> export class FileReaderA extends window.FileReader {
> 	constructor() {
> 		super();
> 		const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
> 		return zoneOriginalInstance || this;
> 	}
> }
> 
> window.FileReader = FileReaderA;
> ```
> 
> or add the above code to another file and import the file, not the class.
> 
> This is a hack but it means that when calling `new FileReader()` all the events work. Ideally it would be nice to be able to control the order in which scripts are imported. As the fix I've always used in a cordova based project is to change the order of polyfills.js and cordova.js in the index.html file.

this is the way...  great solution, thanks!

**Comment by andyyapwl** [comment] 2022-04-03 15:56
> If you have plugins that rely on FileReader working correctly, using snippets from the getFileReader() code mentioned above, I have a solution
> 
> Add to app.module.ts:
> 
> ```
> export class FileReaderA extends window.FileReader {
> 	constructor() {
> 		super();
> 		const zoneOriginalInstance = (this as any)['__zone_symbol__originalInstance'];
> 		return zoneOriginalInstance || this;
> 	}
> }
> 
> window.FileReader = FileReaderA;
> ```
> 
> or add the above code to another file and import the file, not the class.
> 
> This is a hack but it means that when calling `new FileReader()` all the events work. Ideally it would be nice to be able to control the order in which scripts are imported. As the fix I've always used in a cordova based project is to change the order of polyfills.js and cordova.js in the index.html file.

Kudos to you and @tripodsgames the fix saved me, took me many many days and energy to trace and the amazing patching really proven to be working!

**Comment by lalithumation** [comment] 2022-04-12 11:35
Can Any one help m when i and Passing data to File instance the data get changes in IOS and Android

in Android:-
lastModified: 1649763166169
lastModifiedDate: Tue Apr 12 2022 17:02:46 GMT+0530 (India Standard Time) {}
name: "test"
size: 118514
type: "image/jpeg"
webkitRelativePath: ""

in IOS :-
end: 0
lastModified: null
lastModifiedDate: null
localURL: "test"
name: [Uint8Array] (1)
size: 0
start: 0
type: {type: "image/jpeg"}

i want same as android in IOS

**Comment by Umer281** [comment] 2022-06-27 11:22
@tripodsgames thanks it is working

**Comment by mariusmoessmer** [comment] 2022-07-01 09:26
The above provided solution regarding the __zone_symbol__originalInstance - filereader works but has problems with changedetection in angular since the onload method of the filereader gets executed outside angular-zone.

We have overcome this issue by implementing a new filereader that decorates the __zone_symbol__originalInstance - filereader and executes the onload-method within the ngZone.

Therefore, we extend the above provided solution by following code:

`export class RealFileReader extends window.FileReader implements FileReader {
	constructor() {
		super();
		const zoneOriginalInstance =
			// eslint-disable-next-line @typescript-eslint/naming-convention
			(this as any as { __zone_symbol__originalInstance?: FileReader | undefined } & FileReader).__zone_symbol__originalInstance;

		return new DecoratedFileReader(zoneOriginalInstance || this, window.globalInjector.get(NgZone));
	}
}

window.FileReader = RealFileReader;

export function appInit(injector: Injector) {
	// eslint-disable-next-line arrow-body-style
	(window as any).globalInjector = injector;
	return (): Promise<any> => Promise.resolve();
}`

`import { NgZone } from '@angular/core';


/**
 * decorates a real filereader and executes all functions like onload within NgZone
 */
export class DecoratedFileReader implements FileReader {

	/**
	 *
	 */
	constructor(private realFileReader: FileReader, private ngZone: NgZone) {
	}

	// eslint-disable-next-line @typescript-eslint/naming-convention
	public get DONE(): number {
		return this.realFileReader.DONE;
	}
	// eslint-disable-next-line @typescript-eslint/naming-convention
	public get EMPTY(): number {
		return this.realFileReader.EMPTY;
	}
	// eslint-disable-next-line @typescript-eslint/naming-convention
	public get LOADING(): number {
		return this.realFileReader.LOADING;
	}

	public get error(): DOMException | null {
		return this.realFileReader.error;
	}

	public get readyState(): number {
		return this.realFileReader.readyState;
	}

	public get result(): string | ArrayBuffer | null {
		return this.realFileReader.result;
	}

	public get onabort(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onabort;
	}

	public set onabort(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onabort = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onabort = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}

	// eslint-disable-next-line @typescript-eslint/member-ordering
	public get onerror(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onerror;
	}

	public set onerror(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onerror = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onerror = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}

	// eslint-disable-next-line @typescript-eslint/member-ordering
	public get onload(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onload;
	}

	public set onload(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onload = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onload = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}

	// eslint-disable-next-line @typescript-eslint/member-ordering
	public get onloadend(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onloadend;
	}

	public set onloadend(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onloadend = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onloadend = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}

	// eslint-disable-next-line @typescript-eslint/member-ordering
	public get onloadstart(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onloadstart;
	}

	public set onloadstart(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onloadstart = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onloadstart = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}
	// eslint-disable-next-line @typescript-eslint/member-ordering
	public get onprogress(): ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null {
		return this.realFileReader.onprogress;
	}

	public set onprogress(value: ((this: FileReader, ev: ProgressEvent<FileReader>) => any) | null) {
		if (value == null) {
			this.realFileReader.onprogress = value;
		} else {
			// eslint-disable-next-line no-unused-vars
			this.realFileReader.onprogress = ev => {
				this.ngZone.run(() => value.call(this.realFileReader, ev));
			};
		}
	}

	abort(): void {
		this.realFileReader.abort();
	}
	readAsArrayBuffer(blob: Blob): void {
		this.realFileReader.readAsArrayBuffer(blob);
	}
	readAsBinaryString(blob: Blob): void {
		this.realFileReader.readAsBinaryString(blob);
	}
	readAsDataURL(blob: Blob): void {
		this.realFileReader.readAsDataURL(blob);
	}
	readAsText(blob: Blob, encoding?: string): void {
		this.realFileReader.readAsText(blob, encoding);
	}

	addEventListener<K extends keyof FileReaderEventMap>(
		type: K,
		listener: (this: FileReader, ev: FileReaderEventMap[K]) => any, options?: boolean | AddEventListenerOptions
	): void;
	addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
	addEventListener(type: any, listener: any, options?: any): void {
		return this.realFileReader.addEventListener(type, listener, options);
	}

	removeEventListener<K extends keyof FileReaderEventMap>(
		type: K,
		listener: (this: FileReader, ev: FileReaderEventMap[K]) => any, options?: boolean | EventListenerOptions
	): void;
	removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
	removeEventListener(type: any, listener: any, options?: any): void {
		return this.realFileReader.removeEventListener(type, listener, options);
	}

	dispatchEvent(event: Event): boolean {
		return this.ngZone.run(() => this.realFileReader.dispatchEvent(event));
	}
}
`

**Comment by harinderratton** [comment] 2022-07-26 07:03
> ```ts
> export function getFileReader(): FileReader {
>     const fileReader = new FileReader();
>     const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
>     return zoneOriginalInstance || fileReader;
> }
> ...
> let newInstance = getFileReader();
> ```

worked like a charm
