### ISSUE TITLE
bug:  lint with error

### ISSUE THREAD

**Issue by Brli** [ionic-team/capacitor#6296] opened 2023-02-14 08:00 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[error] Xcode is not installed
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

gradle lint returns

```
> Task :capacitor-android:lintDebug FAILED
Lint found 7 errors, 0 warnings (8 errors filtered by baseline lint-baseline.xml). First failure:

/home/user/.gradle/caches/transforms-3/1e7439d134cc68f2a6b6424032304fec/transformed/fragment-1.4.1/jars/lint.jar: Error: Library lint checks out of date;

The full lint text report is located at:
  /home/user/project/node_modules/@capacitor/android/capacitor/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-android:lintDebug'.
>                 Lint found errors in the project; aborting build.

                  Fix the issues identified by lint, or create a baseline to see only new errors:
                  ```
                  android {
                      lint {
                          baseline = file("lint-baseline.xml")
                      }
                  }
                  ```

                  For more details, see https://developer.android.com/studio/write/lint#snapshot

                  Lint found 7 errors, 0 warnings (8 errors filtered by baseline lint-baseline.xml). First failure:

  /home/user/.gradle/caches/transforms-3/1e7439d134cc68f2a6b6424032304fec/transformed/fragment-1.4.1/jars/lint.jar: Error: Library lint checks out of date;

  The full lint text report is located at:
    /home/user/project/node_modules/@capacitor/android/capacitor/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

### Expected Behavior

pass without error, or, at least, errors in my own project.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context

The full lint-results-debug.txt is as follows:

```
/home/user/project/node_modules/@capacitor/android/capacitor/lint-baseline.xml: Information: 4 errors/warnings were listed in the baseline file (lint-baseline.xml) but not found in the project; perhaps they have been fixed? Another possible explanation is that lint recently stopped analyzing (and including results from) dependent projects by default. You can turn this back on with android.lintOptions.checkDependencies=true. Unmatched issue types: DefaultLocale, SetJavaScriptEnabled, StaticFieldLeak (2) [LintBaseline]
/home/user/project/node_modules/@capacitor/android/capacitor/lint-baseline.xml: Information: 8 errors were filtered out because they are listed in the baseline file, lint-baseline.xml
 [LintBaseline]
/home/user/.gradle/caches/transforms-3/1e7439d134cc68f2a6b6424032304fec/transformed/fragment-1.4.1/jars/lint.jar: Error: Library lint checks out of date;
these checks will be skipped!

Lint found an issue registry (androidx.fragment.lint.FragmentIssueRegistry)
which was compiled against an older version of lint
than this one. This is usually fine, but not in this
case; some basic verification shows that the lint
check jar references (for example) the following API
which is no longer valid in this version of lint:
org.jetbrains.uast.kotlin.KotlinUClass: org.jetbrains.kotlin.psi.KtClassOrObject getKtClass()
(Referenced from androidx/fragment/lint/OnCreateDialogIncorrectCallbackDetector$UastHandler.class)

Therefore, this lint check library is not included
in analysis. This affects the following lint checks:
FragmentTagUsage
FragmentAddMenuProvider
FragmentBackPressedCallback
FragmentLiveDataObserve
UseRequireInsteadOfGet
UseGetLayoutInflater
DialogFragmentCallbacksDetector
UnsafeRepeatOnLifecycleDetector
DetachAndAttachSameFragment

Recompile the checks against the latest version, or if
this is a check bundled with a third-party library, see
if there is a more recent version available.

Version of Lint API this lint check is using is 11.
The Lint API version currently running is 13 (7.3+). [ObsoleteLintCustomCheck]

   Explanation for issues of type "ObsoleteLintCustomCheck":
   Lint can be extended with "custom checks": additional checks implemented by
   developers and libraries to for example enforce specific API usages
   required by a library or a company coding style guideline.

   The Lint APIs are not yet stable, so these checks may either cause a
   performance degradation, or stop working, or provide wrong results.

   This warning flags custom lint checks that are found to be using obsolete
   APIs and will need to be updated to run in the current lint environment.

   It may also flag issues found to be using a newer version of the API,
   meaning that you need to use a newer version of lint (or Android Studio or
   Gradle plugin etc) to work with these checks.

/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/util/AssetUtil.java:239: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        resId = res.getIdentifier(resName, "mipmap", pkgName);
                    ~~~~~~~~~~~~~
/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/util/AssetUtil.java:242: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
            resId = res.getIdentifier(resName, "drawable", pkgName);
                        ~~~~~~~~~~~~~
/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/util/AssetUtil.java:246: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
            resId = res.getIdentifier(resName, "raw", pkgName);
                        ~~~~~~~~~~~~~
/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/util/AssetUtil.java:342: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        return context.getResources().getIdentifier(resourceName, dir, context.getPackageName());
                                      ~~~~~~~~~~~~~
/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java:25: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        getApplication().setTheme(getResources().getIdentifier("AppTheme_NoActionBar", "style", getPackageName()));
                                                 ~~~~~~~~~~~~~
/home/user/project/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java:26: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        setTheme(getResources().getIdentifier("AppTheme_NoActionBar", "style", getPackageName()));
                                ~~~~~~~~~~~~~

   Explanation for issues of type "DiscouragedApi":
   Discouraged APIs are allowed and are not deprecated, but they may be unfit
   for common use (e.g. due to slow performance or subtle behavior).

7 errors, 0 warnings (8 errors filtered by baseline lint-baseline.xml)
```

**Comment by Ionitron** [comment] 2023-02-22 18:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-10 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-10 00:06 UTC
Labels: platform: android, needs reply, needs reproduction

**Comment by saschpe** [comment] 2023-04-03 10:50
That's still an issue, even with 4.7.3

**Comment by ptmkenny** [comment] 2023-04-26 10:07
Getting this same error in Capacitor 5 as shown here: https://github.com/RaphaelWoude/capacitor-native-settings/actions/runs/4739878824/jobs/8415109453?pr=32

**Comment by ejohanson-vi3** [comment] 2023-05-01 19:19
Here are the steps to reproduce this starting from an empty installation of Node.JS:

1.  npm install -g @ionic/cli
2.  ionic start TestProject blank --type=vue
3. cd ./TestProject
4. npm add @capacitor/android
5. ionic build
6. npx cap add android
7. cd ./android
8. Edit the file variables.gradle
9. Change the value of compileSdkVersion from 32 to 33
10. ./gradlew build

_**You will get the error during the build:**_
> Task :capacitor-android:lintDebug FAILED
Lint found 6 errors, 0 warnings (8 errors filtered by baseline lint-baseline.xml). First failure:

TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\plugin\util\AssetUtil.java:239: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        resId = res.getIdentifier(resName, "mipmap", pkgName);

_**There is a reference to a "full lint text report", which contains the following:**_
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\plugin\util\AssetUtil.java:239: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        resId = res.getIdentifier(resName, "mipmap", pkgName);
                    ~~~~~~~~~~~~~
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\plugin\util\AssetUtil.java:242: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
            resId = res.getIdentifier(resName, "drawable", pkgName);
                        ~~~~~~~~~~~~~
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\plugin\util\AssetUtil.java:246: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
            resId = res.getIdentifier(resName, "raw", pkgName);
                        ~~~~~~~~~~~~~
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\plugin\util\AssetUtil.java:342: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        return context.getResources().getIdentifier(resourceName, dir, context.getPackageName());
                                      ~~~~~~~~~~~~~
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\BridgeActivity.java:25: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        getApplication().setTheme(getResources().getIdentifier("AppTheme_NoActionBar", "style", getPackageName()));
                                                 ~~~~~~~~~~~~~
TestProject\node_modules\@capacitor\android\capacitor\src\main\java\com\getcapacitor\BridgeActivity.java:26: Error: Use of this function is discouraged because resource reflection makes it harder to perform build optimizations and compile-time verification of code. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)). [DiscouragedApi]
        setTheme(getResources().getIdentifier("AppTheme_NoActionBar", "style", getPackageName()));
                                ~~~~~~~~~~~~~

   Explanation for issues of type "DiscouragedApi":
   Discouraged APIs are allowed and are not deprecated, but they may be unfit
   for common use (e.g. due to slow performance or subtle behavior).

6 errors, 0 warnings (8 errors filtered by baseline lint-baseline.xml)

**Comment by ejohanson-vi3** [comment] 2023-05-01 20:22
Ok this is a production grade app that is released to the public, so I'd prefer not to use beta tooling.  Is there a target release date for Capacitor 5?
