### ISSUE TITLE
bug: no node_modules/@capacitor/cli/assets folder

### ISSUE THREAD

**Issue by ulf1** [ionic-team/capacitor#6193] opened 2022-12-25 12:30 UTC
### Capacitor Version

```
    Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[error] gradlew file is missing in android
        app directory is missing in android
```

### Platform(s)
- MacOS

### Current Behavior

```
ionic cap add android
[capacitor] ✖ Adding native android project in android - failed!
[capacitor] ✖ add - failed!
[capacitor] [error] Error: ENOENT: no such file or directory, stat ... node_modules/@capacitor/cli/assets/android-template.tar.gz

ls node_modules/@capacitor/cli/assets
No such file or directory
```

### Expected Behavior
- no error

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by IT-MikeS** [comment] 2023-01-03 17:46
Please provide a minimal code reproduction of the issue. This allows us to better diagnose issues by avoiding configuration differences.

**Comment by Ionitron** [comment] 2023-01-03 17:47
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-19 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-19 00:05 UTC
Labels: needs reply, needs reproduction
