### ISSUE TITLE
bug: iPhone simulator occurred blank screen with javascript error

### ISSUE THREAD

**Issue by j-shin** [ionic-team/capacitor#6289] opened 2023-02-10 07:09 UTC
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3
```

### Platform(s)
iOS simulator, iPhone14, iPhone SE, iPad mini6th, iPad

### Current Behavior
Only iPhone simulator blank screen problem
But i can not see any error log from iPhone simulator

I don't know but it is not occurred iPad simulator
iPad simulator is no problem

### Expected Behavior
Don't occur blank-screen issues

### Other Technical Details
`npm --version` output: 8.3.1

`node --version` output: v16.14.0

`pod --version` output (iOS issues only): 1.11.3

**Comment by crhayes** [comment] 2023-02-20 15:57
@j-shin IMO there's not enough detail in here to help debug your issue. I think you need to include a reproducible example.

Does this happen on multiple iPhone simulators or only one? Specific OS and model version?

Have you tried [resetting the simulator](https://stackoverflow.com/questions/2763733/how-to-reset-iphone-simulator)?

**Comment by Ionitron** [comment] 2023-02-22 19:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-10 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-10 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction
