### ISSUE TITLE
bug: Black Screen when using Live Reload

### ISSUE THREAD

**Issue by allidoisace** [ionic-team/capacitor#4921] opened 2021-08-12 20:15 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/electron: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/core 2.4.7
  @capacitor/cli 2.4.6
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

  Found 4 Capacitor plugins for ios:
    @capacitor-community/bluetooth-le (0.4.0)
    cordova-plugin-file-opener2 (3.0.5)
    cordova-plugin-wifiwizard2 (3.1.1)
    es6-promise-plugin (4.2.2)
[success] iOS looking great! 👌
```

### Platform(s)

- iOS

### Current Behavior

When running with live reload with an external server, sometimes the screen is just black on the iOS device. The device is an iPad  attached to the macbook and also on the same network. The external ip the capacitor config is using works fine on the macbook, but the iOS app cannot access it.

### Expected Behavior

iOS App doesn't show a black screen.

### Code Reproduction

```
ionic cap run ios -l --external -p 3000
```

### Other Technical Details

`npm --version` output: `7.20.3`

`node --version` output: `v16.6.1`

`pod --version` output (iOS issues only): `1.10.2`

### Additional Context

I have only seen a blog post that was a cry for help and no answers and there is no stacktrace produced.

**Comment by Ionitron** [comment] 2021-08-13 06:34
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-08-29 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-08-29 00:03 UTC
Labels: platform: ios, needs reply, needs reproduction
