### ISSUE TITLE
bug: Status bar doesn't change style when automatically changing day/night theme in iOS

### ISSUE THREAD

**Issue by Brullworfel** [ionic-team/capacitor#6409] opened 2023-03-18 07:05 UTC
## Bug Report

If automatic change of the theme of day/night according to the schedule is enabled in iOS, and the application was launched a long time ago, then after changing the theme and launching the application with session restoration, the status bar in the application does not respond to the automatic change of theme and becomes unreadable.

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0
```

### Platform(s)

iOS 16.3.1 on iPhone SE 2020

### Current Behavior

1. Activate the automatic change of the day night theme in the system settings;
2. Launch the application;
3. Minimize the app (switch to another one so your app stays running in the background);
4. Go about your business for a long time so that the application is automatically unloaded from the device's memory;
5. Do not return to the app until the night/day theme is automatically changed;
6. Go back to your application;
7. The application theme will be changed. But if you have not returned to the application for a long time, then you will see signs of restoring the application session (the web application inside the Capacitor will be reloaded) and the statusbar theme will remain the same as before and it will become unreadable.

### Expected Behavior

The statusbar theme changes when the system day/night theme changes automatically, even if the application was minimized at the time of the change for a long time.

### Other Technical Details

`npm --version` output: 8.1.2

`node --version` output: v16.13.1

`pod --version` output (iOS issues only): 1.12.0

**Comment by Ionitron** [comment] 2023-03-20 08:35
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-04-05 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-04-05 00:05 UTC
Labels: platform: ios, needs reply, needs reproduction
