### ISSUE TITLE
bug: Resource linking issue when adding Background location plugin (capacitor-background-geolocation)

### ISSUE THREAD

**Issue by raiprashantneo** [ionic-team/capacitor#4349] opened 2021-03-16 11:34 UTC
![image](https://user-images.githubusercontent.com/79777306/111302519-82e2d280-8679-11eb-960c-a46448d52b9d.png)
I have wasted a day on this. 

![image](https://user-images.githubusercontent.com/79777306/111302571-95f5a280-8679-11eb-814b-f0730d9dab49.png)

This is string.xml 
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">Enso mobile</string>
    <string name="title_activity_main">Enso mobile</string>
    <string name="package_name">com.neocepts.enso</string>
    <string name="custom_url_scheme">com.neocepts.enso</string>
     <string name="mauron85_bgloc_account_name">@string/app_name</string>
    <string name="mauron85_bgloc_account_type">com.neocepts.enso.account</string>
    <string name="mauron85_bgloc_content_authority">com.neocepts.enso</string>
</resources>

After build this response is coming when building apk 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\aaa neo staff\Enso_Mobile_App\android\capacitor-cordova-android-plugins\src\main\AndroidManifest.xml:20:1-200: AAPT: error: resource string/mauron85_bgloc_content_authority (aka capacitor.android.plugins:string/mauron85_bgloc_content_authority) not found.

**Comment by raiprashantneo** [comment] 2021-03-16 11:39
Can anyone please help me ?

**Comment by Ionitron** [comment] 2023-03-06 16:37
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-22 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-22 00:04 UTC
Labels: needs reply, needs reproduction
