### ISSUE TITLE
bug: mailto links not working 

### ISSUE THREAD

**Issue by idesignpixels** [ionic-team/capacitor#4500] opened 2021-04-27 14:57 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/ios 2.4.6
  @capacitor/electron not installed
```

### Platform(s)
Android/iOS

### Current Behavior
mailto links using both Plugins.Browser.open and Plugins.App.openUrl will not open:
Log using Browser plugin:
```
⚡️  To Native ->  Browser open 106494072
ERROR MESSAGE:  {"message":"Invalid URL","errorMessage":""}
```
Log using App plugin (email replaced):
```
⚡️  To Native ->  App openUrl 113642009
2021-04-27 15:27:10.317324+0100 App[59762:28364405] [default] Failed to open URL mailto:test@test.com: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=229, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}
⚡️  TO JS {"completed":false}
```

### Expected Behavior
mailto: links should open the default mail app with a new message.

### Code Reproduction

```
if (Capacitor.isNative) {
    window.open = async url => Browser.open({ url });
  }
```
And/or
```
if (Capacitor.isNative) {
    window.open = async url => App.openUrl({ url });
  }
```

**Comment by Ionitron** [comment] 2021-04-27 14:59
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-05-18 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-05-18 00:04 UTC
Labels: needs reply, needs reproduction, platform: android, platform: ios

**Comment by ipehimanshu** [comment] 2021-06-22 08:05
yes true i face same issue in capacitor 3, any solution ?

**Comment by sanderschnydrig** [comment] 2021-07-07 07:40
Same here, I have not found any solution to make mailto links work at all yet
