### ISSUE TITLE
bug: Keyboard.hide() requires afterScreenUpdates:YES

### ISSUE THREAD

**Issue by B30L** [ionic-team/capacitor#3013] opened 2020-05-29 15:51 UTC
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:
  @capacitor/cli: 2.1.1
  @capacitor/core: 2.1.1
  @capacitor/android: 2.1.1
  @capacitor/electron: 2.1.1
  @capacitor/ios: 2.1.1

Installed Dependencies:
  @capacitor/electron not installed
  @capacitor/cli 2.1.1
  @capacitor/core 2.1.1
  @capacitor/ios 2.1.1
  @capacitor/android 2.1.1
[success] Android looking great! 👌
  Found 6 Capacitor plugins for ios:
    cordova-plugin-device (2.0.3)
    cordova-plugin-email-composer (0.9.2)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-network-information (2.0.1)
    cordova-plugin-stripe (1.5.3)
    phonegap-plugin-barcodescanner (8.1.0)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
Calling Keyboard.hide() hides the keyboard after ion-searchbar input. Clicking an item in the list of search results triggers the keyboard to open again.

## Expected Behavior
The keyboard should hide after input. Clicking a list item in the search results should take the user to the next view without reopening the keyboard.

## Sample Code or Sample Application Repo

`<ion-searchbar color="light" debounce="700" placeholder="Enter a Business Name" [(ngModel)]="searchTerm" (ionChange)="getBusinessSearch()" (ionFocus)="removeFab()" (ionClear)="userClear()"></ion-searchbar>`

Keyboard.hide() is called after the ionChange event

![ezgif-3-0fb51669a6d2](https://user-images.githubusercontent.com/49598825/83279006-4cd76f00-a189-11ea-8bb9-ae8b07633bdb.gif)

## Reproduction Steps

https://github.com/B30L/keyboard

## Other Technical Details
`npm --version` output:
6.9.0
`node --version` output:
v10.15.2
`pod --version` output (iOS issues only):
1.7.5
## Other Information
Xcode logs:
 To Native ->  Keyboard hide 93961487
⚡️  TO JS {}
2020-05-29 08:22:10.282138-0700 App[80478:1635968] [Snapshotting] Snapshotting a view (0x7fd3d7d3acb0, UIInputSetContainerView) that has not been rendered at least once requires afterScreenUpdates:YES.

**Comment by jcesarmobile** [comment] 2020-05-29 16:17
can you provide a sample app?

**Comment by werewolfe** [comment] 2020-05-29 17:27
Thanks. I was able to reproduce it in this repo:
https://github.com/B30L/keyboard

**Comment by werewolfe** [comment] 2020-05-29 17:29
> can you provide a sample app?
Thanks. I was able to reproduce it in this repo:
https://github.com/B30L/keyboard

**Comment by B30L** [comment] 2020-05-29 17:41
I was able to reproduce it in this repo:
https://github.com/B30L/keyboard

**Comment by B30L** [comment] 2020-05-29 23:08
I was able to work around the issue by moving the (click) handler in <ion-item> to an <ion-button> element within the item. So it seems to be an issue with how click events are handled within an <ion-item> element after calling Keyboard.hide().

**Comment by jcesarmobile** [comment] 2020-06-01 11:30
I can't reproduce on the sample app and by the comment it doesn't look like a Capacitor bug to me, so closing

**Closed by jcesarmobile** 2020-06-01 11:30 UTC

**Comment by mifo111** [comment] 2020-10-17 19:03
I'm having the same problem. Keyboard shows again after .hide() call even on <ion-button> click-event. 
I could reproduce the issue with 
[https://github.com/B30L/keyboard]
keyboard/src/app/tab1/

**Comment by mifo111** [comment] 2020-10-18 06:08
> I was able to work around the issue by moving the (click) handler in `<ion-item>` to an `<ion-button>` element within the item. So it seems to be an issue with how click events are handled within an `<ion-item>` element after calling Keyboard.hide().

**Comment by mifo111** [comment] 2020-10-18 06:20
> I was able to work around the issue by moving the (click) handler in `<ion-item>` to an `<ion-button>` element within the item. So it seems to be an issue with how click events are handled within an `<ion-item>` element after calling Keyboard.hide().

This is not working for me. Can you please post the coding? Thank you

**Comment by werewolfe** [comment] 2020-10-18 07:05
This did **not** work...
```
<ion-item (click)="buttonClick()">
  <ion-label>
    Button Item
  </ion-label>
</ion-item>
```
This **did** work...
```
<ion-item>
  <ion-label>
    Button Item
  </ion-label>
  <ion-button slot="end" (click)="buttonClick()">My Button</ion-button>
</ion-item>
```

However, the docs currently show and additional "button" reference in the item if it is acting as a button:
I have not tried this...
```
<!-- Item as a Button -->
<ion-item button (click)="buttonClick()">
  <ion-label>
    Button Item
  </ion-label>
</ion-item>
```
Hope it helps.

**Comment by mifo111** [comment] 2020-10-18 11:40
> This did **not** work...
> 
> ```
> <ion-item (click)="buttonClick()">
>   <ion-label>
>     Button Item
>   </ion-label>
> </ion-item>
> ```
> 
> This **did** work...
> 
> ```
> <ion-item>
>   <ion-label>
>     Button Item
>   </ion-label>
>   <ion-button slot="end" (click)="buttonClick()">My Button</ion-button>
> </ion-item>
> ```
> 
> However, the docs currently show and additional "button" reference in the item if it is acting as a button:
> I have not tried this...
> 
> ```
> 
> <ion-item button (click)="buttonClick()">
>   <ion-label>
>     Button Item
>   </ion-label>
> </ion-item>
> ```
> 
> Hope it helps.

Thank you for the answer. This does not help in my case. Even click events on ion-buttons within ion-toolbar make the Keyboard appear again after hidding it before with .hide(). Is it possible to re-open the issue?
