### ISSUE TITLE
bug: Push Notification events lost after WebView crash

### ISSUE THREAD

**Issue by spasma** [ionic-team/capacitor#6153] opened 2022-12-08 08:38 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0
  @capacitor/android: 4.5.0

```

### Platform(s)
- iOS

### Current Behavior
I debugged this for a long time, I think I now know what is happening. We're having this problem for a long time, but it was hard to reproduce.

When the WebView is terminated and reloaded (by https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/WebViewDelegationHandler.swift#L160, which apparently happens a lot in our env), the events set by the Push Notification are not connected to the WebView anymore. 

Therefore, you still receive push notifications, but pushNotificationActionPerformed will not be fired. When this happens, you end up on the home screen of the app.

### Expected Behavior
The expected behavior is that after reload, the push notification events will be reattached to the WebView.

### Code Reproduction
Any app with the push notifications, let the WebView crash (or terminate by OS memory disposal of iOS, wait some time). And reopen the app.

**Comment by Ionitron** [comment] 2022-12-08 10:36
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by spasma** [comment] 2022-12-08 12:07
I tried to create a code reproduction, but I cannot force the WebView to crash (and trigger webViewWebContentProcessDidTerminate). 

It happens when the app is was to the background and iOS kills the app due to memory usage (if you use any other apps for example). 

This behavior is changed with iOS 16, where iOS kills the processes quite fast. I think the process of the WebView is killed, while the native App container is still alive.

**Comment by jcesarmobile** [comment] 2022-12-08 13:04
Please, provide a sample app where you use the push notifications, then I'll run it and try to get the webViewWebContentProcessDidTerminate

**Comment by Ionitron** [comment] 2022-12-24 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-24 00:04 UTC
Labels: platform: ios, needs reply, needs reproduction
