### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by quavo19** [ionic-team/capacitor#6660] opened 2023-06-19 10:37 UTC
### Capacitor Version

```
 Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/core: 5.0.5
  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

IOS and Android

### Current Behavior

Does not show any UI

### Expected Behavior

to show the app UI

### Other Technical Details

`npm --version` output: 9.7.1

`node --version` output: v18.15.0

### Additional Context

After running yarn build, I proceeded to utilize Capacitor to generate the iOS and Android folders. However, when I opened the project in Android Studio, a popup appeared indicating that the UI is not responding.

I suspect that the issue may be related to my configuration, as there is limited documentation available specifically for integrating TypeScript. I would greatly appreciate any assistance in resolving this problem or any insights regarding the correct configuration process.

Additionally, if anyone has come across documentation or resources pertaining to using the Element Open Source SDK with TypeScript, I would be grateful if you could share them

**Comment by Ionitron** [comment] 2023-06-20 08:19
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-07-06 00:07
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-07-06 00:07 UTC
Labels: platform: android, platform: ios, needs reply, needs reproduction
