### ISSUE TITLE
Error when ionContent.scrollToBottom() invoked in keyboardDidShow handler

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#1331] opened 2019-03-18 15:44 UTC
Description of the problem:
Getting the below in the console:
```
TypeError: null is not an object (evaluating 'this.scrollEl.scrollHeight') in console when invoke ionContent.scrollToBottom() in  window.addEventListener('keyboardDidShow' handler
```

I'm getting this error when added a workaround for this https://github.com/ionic-team/capacitor/issues/577 (the bug is closed but I'm still having an issue when the keyboard is opened it covers the bottom of my form so I have implemented a workaround to scroll to the bottom of the ion-content. This is reproducible on iOS. On Android everything works fine and the content is pulled up as expected).

Affected platform
- [x] Android
- [x] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:
Alexs-MacBook-Pro:bossdesk.mobile2 alexryltsov$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (6 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/alexryltsov/Library/Android/sdk/)
   NodeJS            : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

Capacitor version:
Alexs-MacBook-Pro:bossdesk.mobile2 alexryltsov$ npx cap --version
1.0.0-beta.19

node version:
See above

npm version:
See above

CocoaPods version:
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods.rb

Steps to reproduce:
In one of the components I added the below code
```

    window.addEventListener('keyboardDidShow', () => {
      const routerUrl = this.router.url;
      if (routerUrl === '/tickets/detail/tabs/tab2') {
        this.scrollToBottomFn();
      }
    });
```

This is required as a workaround when the keyboard is opened and covers the bottom of my form

Link to sample project:

**Comment by jcesarmobile** [comment] 2019-03-18 15:53
Can you provide a sample project where the actual problem can be reproduced (the one about your form being behind the keyboard)

**Comment by ryaa** [comment] 2019-03-21 05:51
@jcesarmobile Here is the repo with the project to reproduce the problem on iOS (note that it works fine on Android) - see https://github.com/ryaa/focus-input-control-opens-keyboard-which-covers-it
To reproduce please:
1) build and install on iOS and then run
2) click TEST button
3) scroll to the bottom to see Notes textarea
4) tap on it (to start entering smth)
Note that the keyboard opened will cover the text area and the user needs to scroll to make it into the view

Please note that I tried different resize options for Keyboard config in capacitor.config.json. None of them fixed the problem for me. The current setting is as below
```
  "plugins": {
    "Keyboard": {
      "resize": "native",
      "style": "dark"
    }
  }
```

Here is the video showing the problem on iOS - [capacitor-keyboard_covers_notes_textarea iOS.mov.zip](https://github.com/ionic-team/capacitor/files/2990931/capacitor-keyboard_covers_notes_textarea.iOS.mov.zip)

Here is how it works on Android - see 
[capacitor-keyboard_covers_notes_textarea ANDROID.mp4.zip](https://github.com/ionic-team/capacitor/files/2990943/capacitor-keyboard_covers_notes_textarea.ANDROID.mp4.zip). I assume that this is the correct behaviour.

**Comment by jcesarmobile** [comment] 2019-03-21 14:00
Looks like an Ionic bug as it works fine with `ion-input` but not with `ion-textarea`.
This is not really a Capacitor bug, Capacitor just resizes the webview, but it's up to the developer or framework to reposition the fields as Ionic is doing for `ion-input`.

I didn't have problems to scroll the ion-content when the keyboard appears, I've sent a PR to your sample project.
https://github.com/ryaa/focus-input-control-opens-keyboard-which-covers-it/pull/1

Will report the problem with `ion-textarea` and link it to this issue

**Comment by jcesarmobile** [comment] 2019-03-21 14:37
Reported the ionic issue, closing this one
https://github.com/ionic-team/ionic/issues/17847

**Closed by jcesarmobile** 2019-03-21 14:37 UTC
Labels: needs-reply
