### ISSUE TITLE
bug: HttpResponseType blob returns a string

### ISSUE THREAD

**Issue by maxarndt** [ionic-team/capacitor#6241] opened 2023-01-22 10:32 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

* android
* iOS
* web

### Current Behavior

https://github.com/ionic-team/capacitor/blob/6c2726dc0817c9e57c8b7909e4a69a9b376c425d/core/src/core-plugins.ts#L373-L376

Setting `responseType` to `blob` does return a base64 encoded string. 

### Expected Behavior

Setting `responseType` to `blob` should return an object which is an instance of `Blob`.
The coresponding interface already allows this:
https://github.com/ionic-team/capacitor/blob/6c2726dc0817c9e57c8b7909e4a69a9b376c425d/core/src/core-plugins.ts#L207-L208

### Other Technical Details

`npm --version` output: 8.19.1

`node --version` output: v16.13.1

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

Of course this would be somehow breaking. But IMHO the current implementation is super misleading. Especially when people migrate over from [cordova-plugin-advanced-http](https://github.com/silkimen/cordova-plugin-advanced-http#sendrequest) this causes lots of confusion. Over there you have the same `responseType` option which takes `blob` and returns an instance of type `Blob` on the `data` property of the response object.

**Comment by Ionitron** [comment] 2023-01-23 09:20
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by maxarndt** [comment] 2023-01-23 17:08
@jcesarmobile what do you want to see in a Code Reproduction for this particular issue? Would like to know before I waste your time or mine.

**Comment by Ionitron** [comment] 2023-03-04 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-04 00:05 UTC
Labels: platform: android, platform: ios, needs reply, platform: web, needs reproduction

**Comment by pulsejet** [comment] 2023-03-04 00:39
This is still an issue. Blob should not return a string.

**Comment by maxarndt** [comment] 2023-03-04 07:41
@jcesarmobile ignoring my question does not help to resolve such issues.
