### ISSUE TITLE
feat: @capacitor/filesystem support Blob type for writing

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/capacitor#5207] opened 2021-11-04 13:09 UTC
### Description
'@ionic-native/file/ngx' allows me to write BLOB into a file. @capacitor/filesystem seems to only allow string to be written.
Please add ability to write BLOB into a file.

### Additional Context
I wrote an [Issue](https://github.com/ionic-team/capacitor/issues/5206) where I encountered the problem.

**Comment by Ionitron** [comment] 2021-11-04 13:46
Issue detected as duplicate of https://github.com/ionic-team/capacitor/issues/984

**Closed by Ionitron** 2021-11-04 13:46 UTC
