### ISSUE TITLE
feat: Adding versionName props into capacitor.config.json

### ISSUE THREAD

**Issue by darron1217** [ionic-team/capacitor#3295] opened 2020-07-18 07:53 UTC
## Feature Request
From : https://github.com/ionic-team/capacitor/issues/840

It would be come in handy if capacitor can pickup the build and version from capacitor.config.json
```
{
  "appId": "com.testapp",
  "appName": "Test App",
  "androidBuild": "6",
  "androidVersion": "1.0",
  "iosVersion": "1.1"
}
```
And it would be more handy if capacitor can `bump version` while building app.

### Platform(s)
Android, iOS

**Comment by dwieeb** [comment] 2020-07-20 23:22
I think this is a duplicate of https://github.com/ionic-team/capacitor/issues/2848, but let me know if it's not.

**Closed by dwieeb** 2020-07-20 23:22 UTC
Labels: platform: android, platform: ios

**Comment by darron1217** [comment] 2020-07-21 00:08
@dwieeb It's different issue

My suggest is to add `androidBuild`, `androidVersion`, `iosVersion` props

**Comment by dwieeb** [comment] 2020-07-21 01:19
If we were going to add tooling around app versions, we would try to keep the versions between the platforms consistent. If you want to manage versions independently, there's nothing stopping you from doing so in the native projects. The versions can be edited with Xcode/Android Studio.
