### ISSUE TITLE
bug: Storage not save data after closing the app 

### ISSUE THREAD

**Issue by skiod** [ionic-team/capacitor#4249] opened 2021-02-25 11:56 UTC
## Bug Report
I'm building an app offline 100%
i tried  [Storage api](https://capacitorjs.com/docs/apis/storage)
but it looks like when i close the app data disappears?? 

### Capacitor Version
Latest Dependencies:

```
  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/electron not installed
```

### Platform(s)

android

### Expected Behavior
saved data even the app is closes or removed from the background

### Code Reproduction
```
//GET
 const ret = await Storage.get({ key: 'data' });


//ADD
ADD_TRANSACTION (transaction){
      console.log('ADD_TRANSACTION TRIGGRED')
      Storage.set({
        key: 'data',
        value: JSON.stringify({transactions : state.data.transactions , 
                               language : state.data.language,
                                currency : state.data.currency  })
      });
    },
```

**Comment by Ionitron** [comment] 2021-02-25 12:25
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-03-28 00:07
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-03-28 00:07 UTC
Labels: needs reply, needs reproduction, platform: android
