### ISSUE TITLE
bug: Webpage not available net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by cpro90** [ionic-team/capacitor#4743] opened 2021-06-18 18:57 UTC
### Used Packages
    "@angular/animations": "^12.0.5",
    "@angular/common": "^12.0.5",
    "@angular/core": "^12.0.5",
    "@angular/forms": "^12.0.5",
    "@angular/platform-browser": "^12.0.5",
    "@angular/platform-browser-dynamic": "^12.0.5",
    "@angular/router": "^12.0.5",
    "@angular/service-worker": "~12.0.5",
    "@byteowls/capacitor-filesharer": "^2.0.0",
    "@capacitor/android": "^3.0.1",
    "@capacitor/app": "^1.0.1",
    "@capacitor/camera": "^1.0.1",
    "@capacitor/cli": "^3.0.1",
    "@capacitor/core": "^3.0.1",
    "@capacitor/ios": "^3.0.1",
    "@capacitor/keyboard": "^1.0.1",
    "@capacitor/push-notifications": "^1.0.1",
    "@capacitor/share": "^1.0.1",
    "@ionic-native/core": "^5.33.1",
    "@ionic-native/file": "^5.33.1",
    "@ionic-native/media": "^5.33.1",
    "@ionic-native/media-capture": "^5.33.1",
    "@ionic-native/splash-screen": "^5.33.1",
    "@ionic-native/status-bar": "^5.33.1",
    "@ionic/angular": "^5.6.9",
    "@ionic/pwa-elements": "^3.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-media": "^5.0.3",
    "cordova-plugin-media-capture": "^3.0.3",
    "firebase": "^7.24.0",
    "hammerjs": "^2.0.8",
    "ionic4-tooltips": "^2.0.2",
    "js-sha512": "^0.8.0",
    "linkifyjs": "^2.1.9",
    "moment": "^2.29.1",
    "ngx-image-cropper": "^3.3.5",
    "ngx-ionic-image-viewer": "^0.7.4",
    "ngx-socket-io": "^3.3.1",
    "ngx-toastr": "^13.2.1",
    "rxjs": "~6.5.5",
    "send-intent": "^1.1.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"

### Platform(s)
Some Android only (iOS works as expected)

### Current Behavior
I deployed an app via Google Play that was built with "ionic build --prod" and synced with "npx cap sync android". It runs on all my test devices (Huawei P8 lite, Samsung A52, Xiaomi Redmi Note 9, Galaxy Tab 10.1 - Android 9 to 11). But some customers report me a white screen with:

Webpage not available
The webpage at http://localhost/ could not be loaded because:

net::ERR_HTTP_RESPONSE_CODE_FAILURE

This affects nearly 50% of my customers phones, but not my own devices. I tried to enable 
`android:usesCleartextTraffic="true"`
not working. I changed 
`<base href="./">`
not working either.
Even this error code is nearly not known to the community. I updated all packages, migrated to newest angular / ionic / capacitor / cordova, still working on my phones, still failing on customers phones.

Since I cannot read out the customers phones, I sent one of them a signed APK directly and it seemed to work. How can it be, that the same APK, provided via Google, causes Capacitor to fail with this error code?

Best,
Chris

![6abc9020-3ff0-4022-8dc8-21be869faabb](https://user-images.githubusercontent.com/35732217/122605204-6b9bf280-d077-11eb-9ffe-3f0eea0af00f.jpg)

**Comment by Ionitron** [comment] 2021-06-21 09:23
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by cpro90** [comment] 2021-06-22 10:12
There is unfortunately no chance of code reproduction, the code does not occur on my test device, neither on the customer's phones with direct contact.

I will try to meet with a customer, but this will take some time. Approximately this error occurs on 10% of the android apps that were downloaded via Google Play - and only via Google Play. If I send the exact APK that is rolled out via Google Play directly to the customer and they install it, it is working perfectly.

**Comment by jcesarmobile** [comment] 2021-08-09 17:24
I can't reproduce and no code reproduction can be provided, so closing, sorry.

**Closed by jcesarmobile** 2021-08-09 17:24 UTC
Labels: platform: android, needs reproduction
