### ISSUE TITLE
Compatibility support below API 23 (Android 6.0)

### ISSUE THREAD

**Issue by taufikterdidik** [ionic-team/capacitor#1340] opened 2019-03-21 02:46 UTC
I try to migrate (rebuild) my app from cordova to capacitor. It says the compatibility API 21 or greater. But when I try to use Plugins, it's not compatible. ex:
`import { Component } from '@angular/core';`
`import { WpService } from '../api/wp.service';`
`import { Plugins } from '@capacitor/core';`
`const { Device } = Plugins;`
When I add line 4, It show error "Proxy is not defined...". This code only work on API 24 (Android 7.0) or above.
I hope capacitor is more compatible for older API, atleast API 22 (Android Lolipop 5.1) because it still have many user/distribution.
Now I back to use cordova until capacitor is stable enough.

Note: I have to uncomment imports on polyfills.ts too because it white/blankscreen on older API.

(sorry for my language)

**Comment by jcesarmobile** [comment] 2019-03-21 09:38
This is a duplicate of https://github.com/ionic-team/capacitor/issues/456

It doesn’t really depend on the android version but on the system webview version on android 5/6 devices, if it’s old it doesn’t support Proxy, which is used on plugins

**Closed by jcesarmobile** 2019-03-21 09:38 UTC
