### ISSUE TITLE
bug: ios http request throws error 

### ISSUE THREAD

**Issue by colenso** [ionic-team/capacitor#6070] opened 2022-11-11 08:35 UTC
### Capacitor Version
  @capacitor/cli: 4.3.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

### Platform(s)
iOS

### Current Behavior
I followed https://capacitorjs.com/docs/apis/http#configuration and enabled CapacitorHttp in the config and when I built and ran the app Xcode halts at an error thrown:
```
Could not cast value of type 'NSNull' (0x1b7cc9c88) to 'NSString' (0x1b7cc7fc8).
```

### Expected Behavior
This error should not be thrown.

### Other Technical Details

`npm --version` output: 6.14.16

`node --version` output: v14.19.0

`pod --version` output (iOS issues only): 1.11.2

Let me know if I can help with any more info

**Comment by Ionitron** [comment] 2022-11-14 10:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-30 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-30 00:06 UTC
Labels: platform: ios, needs reply, needs reproduction

**Comment by Cyral** [comment] 2022-12-15 17:47
This happens if any of the headers for fetch() are set to null/undefined. They end up in the capacitor plugin as NSNull rather than an NSString. Null or undefined headers are valid for fetch and are simply removed by the runtime, I suggest that capacitor does the same for this plugin.
